--VERSIONES
	--	v1.0	20251201	Inicial
	--	v2.0	20251215	Se filtro solo el periodo actual y se añade vision total para Empleados con CENTRAL0010

Alter STRUCTURED PRIVILEGE REP_1_18_EXT
--ALTER STRUCTURED PRIVILEGE REP_1_18_EXT
FOR SELECT
ON EXT.CSA_ESTRUCTURA_COMERCIAL_SVW

WHERE (POSITIONSEQ) IN ( 
	SELECT distinct PARD.DESCENDANTPOSITIONSEQ
	FROM TCMP.CSA_PADIMENSION PAD
	INNER JOIN CSA_PERIODDIMENSION PER ON PERIODTYPE='month' AND 
										PAD.PERIODSEQ = PER.PERIODSEQ AND
										current_timestamp >= startdate AND current_timestamp < enddate
	INNER JOIN CSA_PAREPORTINGDIMENSION PARD ON PER.PERIODSEQ = PARD.PERIODSEQ AND 
												PAD.PARTICIPANTSEQ = PARD.ANCESTORPARTICIPANTSEQ AND
												PAD.POSITIONSEQ = PARD.ANCESTORPOSITIONSEQ AND 
												(
													(PAD.POSITIONGENERICNUMBER2 <> 73 AND PAD.POSITIONGENERICNUMBER2 BETWEEN 50 AND 82 AND PARD.RELATIVEDISTANCE = 0)
												OR 
													PAD.POSITIONGENERICNUMBER2 IS NULL
												OR NOT 
													(PAD.POSITIONGENERICNUMBER2 <> 73 AND PAD.POSITIONGENERICNUMBER2 BETWEEN 50 AND 82)
												)
	WHERE PAD.ISPAYEE=1 AND -- se aplican mismos filtros que en ORACLE
		  ( 
			( --INICIO PAD USERS + Visibility
		  		( 
					PAD.USERID=SESSION_CONTEXT('APPLICATIONUSER')
					OR  -- Visibilidad por posicion definida por configuracion en EA
					PAD.POSITIONSEQ IN ( SELECT VALUE 
										FROM CSA_DATASECURITY DS
										WHERE DS.USERID = SESSION_CONTEXT('APPLICATIONUSER') AND 
										  DS.REMOVEDATE = TO_DATE('22000101','YYYYMMDD') AND
										  DS.SECURITYTYPE = 'POS'  )
					OR  -- visibilidad de oficinas por posiciones con tipo de relaci�n "Empleados" 
					PAD.POSITIONSEQ IN ( SELECT POSREL.PARENTPOSITIONSEQ
										FROM TCMP.CS_POSITIONRELATION POSREL
										INNER JOIN TCMP.CS_POSITIONRELATIONTYPE RELTYP ON RELTYP.DATATYPESEQ = POSREL.POSITIONRELATIONTYPESEQ AND
											RELTYP.REMOVEDATE = TO_DATE('22000101','YYYYMMDD') AND
											RELTYP.NAME = 'Empleados'
										INNER JOIN TCMP.CS_POSITION POSCHI ON POSCHI.RULEELEMENTOWNERSEQ = POSREL.CHILDPOSITIONSEQ AND
											POSCHI.REMOVEDATE = TO_DATE('22000101','YYYYMMDD') AND
											POSCHI.ISLAST = 1
										INNER JOIN TCMP.CS_PARTICIPANT PARCHI ON POSCHI.PAYEESEQ = PARCHI.PAYEESEQ AND
											PARCHI.REMOVEDATE = TO_DATE('22000101','YYYYMMDD') AND
											PARCHI.ISLAST = 1
										WHERE POSREL.REMOVEDATE = TO_DATE('22000101','YYYYMMDD') AND
											POSREL.ISLAST = 1 AND
											PARCHI.USERID = SESSION_CONTEXT('APPLICATIONUSER') -- 'O2RC'
								)
		  		) AND -- Visibilidad de datos en informes solo aplica a mediadores
		  		1 = (	SELECT VALUE 
								FROM TCMP.CS_FIXEDVALUE
								WHERE NAME = 'FV-VisibilidadReporting' AND REMOVEDATE = TO_DATE('22000101','YYYYMMDD')
							UNION ALL
								SELECT 1 FROM DUMMY 
								WHERE NOT EXISTS ( SELECT 1 FROM TCMP.CS_FIXEDVALUE WHERE NAME = 'FV-VisibilidadReporting' AND REMOVEDATE = TO_DATE('22000101','YYYYMMDD'))
							LIMIT 1
					)			
			)
		  OR -- Visibilidad de Administradores por configuracion en EA
			EXISTS (	SELECT 1 
						FROM CSA_DATASECURITY 
						WHERE (USERID = SESSION_CONTEXT('APPLICATIONUSER') 
								AND SECURITYTYPE = 'ALL' 
								AND REMOVEDATE = TO_DATE('22000101','YYYYMMDD')) 
							OR (SESSION_CONTEXT('APPLICATIONUSER') LIKE 'WEBIDE_PS%')
						)
		  OR -- Visibilidad TOTAL de empleados de OFICINA CENTRAL0010
			EXISTS (	SELECT distinct 1 
							FROM TCMP.CS_POSITIONRELATION POSREL
							INNER JOIN TCMP.CS_POSITIONRELATIONTYPE RELTYP ON RELTYP.DATATYPESEQ = POSREL.POSITIONRELATIONTYPESEQ AND
								RELTYP.REMOVEDATE = TO_DATE('22000101','YYYYMMDD') AND
								RELTYP.NAME = 'Empleados'
							INNER JOIN TCMP.CS_POSITION POSPAR ON POSPAR.RULEELEMENTOWNERSEQ = POSREL.PARENTPOSITIONSEQ AND
								POSPAR.REMOVEDATE = TO_DATE('22000101','YYYYMMDD') AND
								POSPAR.ISLAST = 1
							INNER JOIN TCMP.CS_POSITION POSCHI ON POSCHI.RULEELEMENTOWNERSEQ = POSREL.CHILDPOSITIONSEQ AND
								POSCHI.REMOVEDATE = TO_DATE('22000101','YYYYMMDD') AND
								POSCHI.ISLAST = 1
							INNER JOIN TCMP.CS_PARTICIPANT PARCHI ON POSCHI.PAYEESEQ = PARCHI.PAYEESEQ AND
								PARCHI.REMOVEDATE = TO_DATE('22000101','YYYYMMDD') AND
								PARCHI.ISLAST = 1
							WHERE POSREL.REMOVEDATE = TO_DATE('22000101','YYYYMMDD') AND
								POSREL.ISLAST = 1  AND POSPAR.NAME = 'CENTRAL0010'  AND
								PARCHI.USERID = SESSION_CONTEXT('APPLICATIONUSER')
					)
		  )
);
