CREATE LIBRARY "EXT"."LIB_CONSTANTES" LANGUAGE SQLSCRIPT AS
BEGIN
  PUBLIC VARIABLE v_eot               CONSTANT DATE := TO_DATE('22000101','yyyymmdd');
  PUBLIC VARIABLE  CONST_SI    CONSTANT VARCHAR2(2) := 'SI';
  PUBLIC VARIABLE  CONST_NO    CONSTANT VARCHAR2(2) := 'NO';
  PUBLIC VARIABLE   CONST_S    CONSTANT VARCHAR2(1) := 'S';
  PUBLIC VARIABLE   CONST_N    CONSTANT VARCHAR2(1) := 'N';
  PUBLIC VARIABLE   CONST_S_1    CONSTANT VARCHAR2(1) := '1';
  PUBLIC VARIABLE   CONST_N_0    CONSTANT VARCHAR2(1) := '0';
  PUBLIC VARIABLE   CONST_RAMA_RRTT  CONSTANT VARCHAR2(4) := 'RRTT';
  PUBLIC VARIABLE   CONST_RAMA_RRGG  CONSTANT VARCHAR2(4) := 'RRGG';
  PUBLIC VARIABLE   CONST_RAMA_RRPP  CONSTANT VARCHAR2(4) := 'RRPP';
  PUBLIC VARIABLE   CONST_PRINT_OUTPUT       CONSTANT BOOLEAN := FALSE;
  PUBLIC VARIABLE   CONST_MAX_EDAD   CONSTANT NUMBER(2) := 70;
  PUBLIC VARIABLE   CONST_MAYOR_EDAD CONSTANT NUMBER(2) := 18;
  PUBLIC VARIABLE   CONST_PERIODO_EXT_RRGGRRPP CONSTANT NUMBER(2) := 12;
  PUBLIC VARIABLE   CONST_CIA_OC CONSTANT VARCHAR2(2) := '01';
  PUBLIC VARIABLE   CONST_CIA_ET CONSTANT VARCHAR2(2) := '03';
  PUBLIC VARIABLE CONST_OCASO  CONSTANT VARCHAR2(5) := 'OCASO';
  PUBLIC VARIABLE CONST_ETERNA CONSTANT VARCHAR2(6) := 'ETERNA';
  PUBLIC VARIABLE   CONST_EMI_DIARIO_RRTT_ETERNA CONSTANT VARCHAR2(20) := '1625';
  PUBLIC VARIABLE   CONST_EMI_DIARIO_RRTT_OCASO  CONSTANT VARCHAR2(20) := '1624';
  PUBLIC VARIABLE   CONST_EMI_DIARIO_RRGGRRPP_ET CONSTANT VARCHAR2(20) := '1627';
  PUBLIC VARIABLE   CONST_EMI_DIARIO_RRGGRRPP_OC  CONSTANT VARCHAR2(20) := '1626';
  PUBLIC VARIABLE   CONST_EMI_DIARIO_SOLNET_OCASO CONSTANT VARCHAR2(20) := 'SOL1626';
  PUBLIC VARIABLE   CONST_CARTERA_RRTT_ETERNA CONSTANT VARCHAR2(20) := '1629';
  PUBLIC VARIABLE   CONST_CARTERA_RRTT_OCASO  CONSTANT VARCHAR2(20) := '1628';
  PUBLIC VARIABLE   CONST_CARTERA_RRGGRRPP_ETERNA CONSTANT VARCHAR2(20) := '1631';
  PUBLIC VARIABLE   CONST_CARTERA_RRGGRRPP_OCASO  CONSTANT VARCHAR2(20) := '1630';
  PUBLIC VARIABLE   CONST_MINICARTERA_OCASO CONSTANT VARCHAR2(20) := 'OBCAFTP163702P';
  PUBLIC VARIABLE   CONST_CARTERA_SOLNET_OCASO CONSTANT VARCHAR2(20) := 'SOL1630';
  PUBLIC VARIABLE   CONST_COBROS_RRTT_OCASO CONSTANT VARCHAR2(20) := '1632';
  PUBLIC VARIABLE   CONST_COBROS_RRTT_ETERNA CONSTANT VARCHAR2(20) := '1633';
  PUBLIC VARIABLE   CONST_COBROS_RRGGRRPP_ETERNA CONSTANT VARCHAR2(20) := '1654';
  PUBLIC VARIABLE   CONST_COBROS_RRGGRRPP_OCASO  CONSTANT VARCHAR2(20) := '1653';
  PUBLIC VARIABLE   CONST_COBROS_SOLNET_OCASO CONSTANT VARCHAR2(20) := 'SOL1653';
  PUBLIC VARIABLE   CONST_COBROS_RRTT_OCASO_SERCO  CONSTANT VARCHAR2(20)  := 'OF1951';
  PUBLIC VARIABLE   CONST_COBROS_RRTT_ETERNA_SERCO  CONSTANT VARCHAR2(20) := 'AF1952';
  PUBLIC VARIABLE   CONST_COBROS_RRGG_OCASO_SERCO  CONSTANT VARCHAR2(20)  := 'R1951';
  PUBLIC VARIABLE   CONST_COBROS_RRGG_ETERNA_SERCO  CONSTANT VARCHAR2(20) := 'R1952';
  PUBLIC VARIABLE   CONST_COBROS_SOLNET_SERCO  CONSTANT VARCHAR2(20) := 'SOL1951';
  PUBLIC VARIABLE   CONST_RECIBO_COBRADO CONSTANT VARCHAR2(6) := 'C';
  PUBLIC VARIABLE   CONST_RECIBO_EMITIDO CONSTANT VARCHAR2(6) := 'E';
  PUBLIC VARIABLE   CONST_RECIBO_PENDIENTE CONSTANT VARCHAR2(6) := 'P';
  PUBLIC VARIABLE   CONST_RECIBO_ANULADO CONSTANT VARCHAR2(6) := 'A';
  PUBLIC VARIABLE   CONST_RECIBO_ANULADO_D CONSTANT VARCHAR2(6) := 'D';
  PUBLIC VARIABLE   CONST_RECIBO_EXTORNO CONSTANT VARCHAR2(6) := 'EXT';
  PUBLIC VARIABLE CONST_RECIBO_COBRADO_SINFIRMAR CONSTANT VARCHAR2(6) := 'N';
  PUBLIC VARIABLE CONST_RECIBO_EMITIDO_SINFIRMAR CONSTANT VARCHAR2(6) := 'S';
  PUBLIC VARIABLE CONST_RECIBO_PENDIENTE_SINFIRMAR CONSTANT VARCHAR2(6) := 'M';
  PUBLIC VARIABLE CONST_TIPO_RECIBO_AD CONSTANT VARCHAR2(2) := 'AD';
  PUBLIC VARIABLE   CONST_TIPO_MOV_ALTAPOLI  CONSTANT VARCHAR2(8) := 'ALTAPOLI';
  PUBLIC VARIABLE   CONST_TIPO_MOV_SUPLEFPN  CONSTANT VARCHAR2(8) := 'SUPLEFPN';
  PUBLIC VARIABLE   CONST_TIPO_MOV_SUPLEFPS  CONSTANT VARCHAR2(8) := 'SUPLEFPS';
  PUBLIC VARIABLE   CONST_TIPO_MOV_SUPGENER  CONSTANT VARCHAR2(8) := 'SUPGENER';
  PUBLIC VARIABLE   CONST_TIPO_MOV_SUPDEAUT  CONSTANT VARCHAR2(8) := 'SUPDEAUT';
  PUBLIC VARIABLE   CONST_TIPO_MOV_SUPINASE  CONSTANT VARCHAR2(8) := 'SUPINASE';
  PUBLIC VARIABLE   CONST_TIPO_MOV_SUPDIASE  CONSTANT VARCHAR2(8) := 'SUPDIASE';
  PUBLIC VARIABLE   CONST_TIPO_MOV_SUPTRASP  CONSTANT VARCHAR2(8) := 'SUPTRASP';
  PUBLIC VARIABLE   CONST_TIPO_MOV_SUPINGAR  CONSTANT VARCHAR2(8) := 'SUPINGAR';
  PUBLIC VARIABLE   CONST_TIPO_MOV_SUPDIGAR  CONSTANT VARCHAR2(8) := 'SUPDIGAR';
  PUBLIC VARIABLE   CONST_TIPO_MOV_SUPAUCAP  CONSTANT VARCHAR2(8) := 'SUPAUCAP';
  PUBLIC VARIABLE   CONST_TIPO_MOV_SUPDICAP  CONSTANT VARCHAR2(8) := 'SUPDICAP';
  PUBLIC VARIABLE   CONST_TIPO_MOV_REHABILI  CONSTANT VARCHAR2(8) := 'REHABILI';
  PUBLIC VARIABLE   CONST_SUBTIPO_MOV_A_GARAN CONSTANT VARCHAR2(25) := 'SUPINGAR';
  PUBLIC VARIABLE   CONST_SUBTIPO_MOV_A_ASEG  CONSTANT VARCHAR2(25) := 'SUPINASE';
  PUBLIC VARIABLE   CONST_SUBTIPO_MOV_INC_CAP CONSTANT VARCHAR2(25) := 'SUPAUCAP';
  PUBLIC VARIABLE   CONST_SUBTIPO_MOV_DEC_CAP CONSTANT VARCHAR2(25) := 'SUPDICAP';
  PUBLIC VARIABLE   CONST_SUBTIPO_MOV_B_ASEG  CONSTANT VARCHAR2(25) := 'SUPDIASE';
  PUBLIC VARIABLE   CONST_SUBTIPO_MOV_B_GARAN CONSTANT VARCHAR2(25) := 'SUPDIGAR';
  PUBLIC VARIABLE   CONST_MOTIVO_ALTA_RC    CONSTANT VARCHAR2(2) := 'RC';
  PUBLIC VARIABLE   CONST_MOTIVO_ALTA_RO    CONSTANT VARCHAR2(2) := 'RO';
  PUBLIC VARIABLE   CONST_MOTIVO_ALTA_NP    CONSTANT VARCHAR2(2) := 'NP';
  PUBLIC VARIABLE   CONST_MOTIVO_ALTA_CO    CONSTANT VARCHAR2(2) := 'CO';
  PUBLIC VARIABLE   CONST_MOTIVO_ALTA_RE    CONSTANT VARCHAR2(2) := 'RE';
  PUBLIC VARIABLE   CONST_MOTIVO_ALTA_DE    CONSTANT VARCHAR2(2) := 'DE';
  PUBLIC VARIABLE   CONST_MOTIVO_ALTA_SU    CONSTANT VARCHAR2(2) := 'SU';
  PUBLIC VARIABLE   CONST_MOTIVO_ALTA_TP    CONSTANT VARCHAR2(2) := 'TP';
  PUBLIC VARIABLE   CONST_MOTIVO_ALTA_TS    CONSTANT VARCHAR2(2) := 'TS';
  PUBLIC VARIABLE   CONST_MOTIVO_ALTA_DT    CONSTANT VARCHAR2(2) := 'DT';
  PUBLIC VARIABLE   CONST_MOTIVO_ALTA_AC    CONSTANT VARCHAR2(2) := 'AC';
  PUBLIC VARIABLE   CONST_MOTIVO_BAJA_BB    CONSTANT VARCHAR2(2) := 'BB';
  PUBLIC VARIABLE   CONST_MOTIVO_ALTA_RH    CONSTANT VARCHAR2(2) := 'RH';
  PUBLIC VARIABLE   CONST_BAJA_SUSTITUCION  CONSTANT VARCHAR2(2) := '56';
  PUBLIC VARIABLE   CONST_BAJA_ERROR        CONSTANT VARCHAR2(2) := '57';
  PUBLIC VARIABLE   CONST_BAJA_RESCISION    CONSTANT VARCHAR2(2) := '58';
  PUBLIC VARIABLE   CONST_BAJA_VTO          CONSTANT VARCHAR2(2) := '59';
  PUBLIC VARIABLE   CONST_BAJA_RESCATE      CONSTANT VARCHAR2(2) := '60';
  PUBLIC VARIABLE   CONST_BAJA_YA_FUE_BAJA  CONSTANT VARCHAR2(2) := '62';
  PUBLIC VARIABLE   CONST_RECIBOS_ESPECIFICOS_71 CONSTANT VARCHAR2(2) := '71';
  PUBLIC VARIABLE   CONST_RECIBOS_ESPECIFICOS_66 CONSTANT VARCHAR2(2) := '66';
  PUBLIC VARIABLE   CONST_RECIBOS_ESPECIFICOS_65 CONSTANT VARCHAR2(2) := '65';
  PUBLIC VARIABLE   CONST_RECIBOS_ESPECIFICOS_55 CONSTANT VARCHAR2(2) := '55';
  PUBLIC VARIABLE	CONST_RECIBOS_ESPECIFICOS_43 CONSTANT VARCHAR2(2) := '43';
  PUBLIC VARIABLE   CONST_RECIBOS_ESPECIFICOS_10 CONSTANT VARCHAR2(2) := '10';
  PUBLIC VARIABLE   CONST_RECIBOS_ESPECIFICOS_20 CONSTANT VARCHAR2(2) := '20';
  PUBLIC VARIABLE   CONST_RECIBOS_ESPECIFICOS_16 CONSTANT VARCHAR2(2) := '16';
  PUBLIC VARIABLE   CONST_RECIBOS_ESPECIFICOS_72 CONSTANT VARCHAR2(2) := '72';
  PUBLIC VARIABLE   CONST_RECIBOS_ESPECIFICOS_11 CONSTANT VARCHAR2(2) := '11';
  PUBLIC VARIABLE CONST_RECIBOS_ESPECIFICOS_0 CONSTANT VARCHAR2(2):= '0';
  PUBLIC VARIABLE   CONST_RECIBOS_CARTERA_72 CONSTANT VARCHAR2(2) := '72';
  PUBLIC VARIABLE   CONST_RECIBOS_CARTERA_81 CONSTANT VARCHAR2(2) := '81';
  PUBLIC VARIABLE   CONST_UNIDAD_POLIZA CONSTANT             NUMBER(15,2) := 0.25;
  PUBLIC VARIABLE   CONST_UNIDAD_POLIZA_CRUZADA  CONSTANT    NUMBER(15,2) := 0.35;
  PUBLIC VARIABLE   CONST_UNIDAD_POLIZA_CORRECTOR CONSTANT   NUMBER(15,2) := 0.5;
  PUBLIC VARIABLE   CONST_UNIDAD_POLIZA_JUN_2020 CONSTANT    NUMBER(15,2) := 0.3;
  PUBLIC VARIABLE   CONST_UNIDAD_POLIZA_FIJO_0 CONSTANT NUMBER := 0;
  PUBLIC VARIABLE   CONST_UNIDAD_POLIZA_FIJO_1 CONSTANT NUMBER := 1;
  PUBLIC VARIABLE   CONST_CAMPANIA_CRUZADA CONSTANT VARCHAR2(255) := 'CRUZADA';
  PUBLIC VARIABLE   CONST_CAMPANIA_DUATHLON CONSTANT VARCHAR2(255) := 'DUATHLON';
  PUBLIC VARIABLE   CONST_CAMPANIA_DUATHLON_N1 CONSTANT VARCHAR2(255) := 'DUATHLON_N1';
  PUBLIC VARIABLE   CONST_365_DIAS CONSTANT NUMBER(3) := 365;
  PUBLIC VARIABLE   CONST_BONIFICACION_CRUZADA      CONSTANT    NUMBER(15,2) := 0.75;
  PUBLIC VARIABLE   CONST_BONIFICACION_DUATHLON     CONSTANT    NUMBER(15,2) := 0.25;
  PUBLIC VARIABLE   CONST_PORCENTAJE_BONIFICA_10    CONSTANT    NUMBER(15,2) := 0.1;
  PUBLIC VARIABLE   CONST_BONIFICACION_POLIZA_10    CONSTANT    NUMBER       := 1;
  PUBLIC VARIABLE   CONST_BONIFICACION_POLIZA       CONSTANT    NUMBER(15,2) := 0.5;
  PUBLIC VARIABLE   CONST_TIPO_EURO     CONSTANT VARCHAR2(255) := 'Euro';
  PUBLIC VARIABLE   CONST_TIPO_QUANTITY   CONSTANT VARCHAR2(255) := 'Quantity';
  PUBLIC VARIABLE   CONST_TIPO_PERCENTAGE   CONSTANT VARCHAR2(255) := 'Percentage';
  PUBLIC VARIABLE   CONST_TIPO_ESP      CONSTANT VARCHAR2(255) := 'ESP';
  PUBLIC VARIABLE   CONST_TIPO_INTEGER    CONSTANT VARCHAR2(255) := 'Integer';
  PUBLIC VARIABLE   CONST_TIPO_ACT_PCOMIS_POLIZA CONSTANT VARCHAR2(10) := 'P';
  PUBLIC VARIABLE   CONST_TIPO_ACT_PCOMIS_RECIBO CONSTANT VARCHAR2(10) := 'R';
  PUBLIC VARIABLE   CONST_TIPO_ACT_PCOMIS_TODOS  CONSTANT VARCHAR2(10) := 'T';
  PUBLIC VARIABLE   CONST_DELIMITADOR_NB_FICH  CONSTANT VARCHAR2(1) := '_';
  PUBLIC VARIABLE   CONST_POSITION_FECHA            CONSTANT NUMBER(1) := 4;
  PUBLIC VARIABLE   CONST_POSITION_HORA             CONSTANT NUMBER(1) := 5;
  PUBLIC VARIABLE   CONST_POSITION_COMPANIA         CONSTANT NUMBER(1) := 6;
  PUBLIC VARIABLE   CONST_POSITION_TIPO_FICHERO     CONSTANT NUMBER(1) := 7;
  PUBLIC VARIABLE   CONST_POSITION_JOB_ID           CONSTANT NUMBER(1) := 8;
  PUBLIC VARIABLE   CONST_FICHERO_TEXTO             CONSTANT VARCHAR2(4) := '.txt';
  PUBLIC VARIABLE   CONST_AGENCIA                   CONSTANT VARCHAR2(6) := '999999';
  PUBLIC VARIABLE   CONST_SUBLINE_RRGGRRPP          CONSTANT VARCHAR2(4) := '0000';
  PUBLIC VARIABLE   CONST_RP_NEG_CON_AGENTE CONSTANT VARCHAR2(1) := '7';
  PUBLIC VARIABLE   CONST_RP_NEG_SIN_AGENTE CONSTANT VARCHAR2(1) := '8';
  PUBLIC VARIABLE   CONST_RP_POS_CON_AGENTE CONSTANT VARCHAR2(1) := '5';
  PUBLIC VARIABLE   CONST_RP_POS_SIN_AGENTE CONSTANT VARCHAR2(1) := '6';
  PUBLIC VARIABLE   CONST_RR_NEG_CON_AGENTE CONSTANT VARCHAR2(1) := '7';
  PUBLIC VARIABLE   CONST_RR_NEG_SIN_AGENTE CONSTANT VARCHAR2(1) := '8';
  PUBLIC VARIABLE   CONST_RR_POS_CON_AGENTE CONSTANT VARCHAR2(1) := '3';
  PUBLIC VARIABLE   CONST_RR_POS_SIN_AGENTE CONSTANT VARCHAR2(1) := '4';
  PUBLIC VARIABLE   COSNT_RECU_POLIZA CONSTANT VARCHAR2(2) := 'RP';
  PUBLIC VARIABLE   CONST_RECU_RECIBO CONSTANT VARCHAR2(2) := 'RR';
  PUBLIC VARIABLE   CONST_MODALIDAD_D    CONSTANT VARCHAR2(1)  := 'D';
  PUBLIC VARIABLE   CONST_OFICINA_SECI   CONSTANT VARCHAR2(10) := '946';
  PUBLIC VARIABLE CONST_CORTE_INGLES CONSTANT  VARCHAR(10):= '0946';
  PUBLIC VARIABLE   CONST_PRODUCTO_50114 CONSTANT VARCHAR2(10) := '50114';
  PUBLIC VARIABLE CONST_PRODUCTO_21021   CONSTANT VARCHAR2(5) := '21021';
  PUBLIC VARIABLE CONST_PRODUCTO_21030   CONSTANT VARCHAR2(5) := '21030';
  PUBLIC VARIABLE   CONST_MOVILIDAD_MOV CONSTANT VARCHAR2(255) := 'MOV';
  PUBLIC VARIABLE   CONST_NO_ENCONTRADO CONSTANT VARCHAR2(20) := 'NO_ENCONTRADO';
  PUBLIC VARIABLE   CONST_TIPO_AGENTE_AGENCIA CONSTANT NUMBER := 100;
  PUBLIC VARIABLE   CONST_PERMANENCIA_ANU_2ANIO CONSTANT VARCHAR2(1) := 'A';
  PUBLIC VARIABLE   CONST_PERMANENCIA_ANU_MAS2ANIO CONSTANT VARCHAR2(1) := 'B';
  PUBLIC VARIABLE   CONST_PRIMER_ANIO CONSTANT NUMBER := 1;
  PUBLIC VARIABLE   CONST_SEGUNDO_ANIO CONSTANT NUMBER := 2;
  PUBLIC VARIABLE   CONST_TERCER_ANIO CONSTANT NUMBER := 3;
  PUBLIC VARIABLE CONST_COD_SUPLEMENTO_DEFECTO CONSTANT INTEGER := 0;
  PUBLIC VARIABLE CONST_COD_SUPLEMENTO_DESDOBLES CONSTANT INTEGER := 666;
  PUBLIC VARIABLE CONST_COD_SUPLEMENTO_100 CONSTANT INTEGER := 100;
  PUBLIC VARIABLE CONST_COD_RECIBO_ANUL_RRGGPP CONSTANT VARCHAR2(13) := 'C_ANUL_RRGGPP';
  PUBLIC VARIABLE CONST_COD_RECIBO_ANUL_RRTT CONSTANT VARCHAR2(13) := 'C_ANUL_RRTT';
  PUBLIC VARIABLE CONST_COD_RECIBO_ANUL_SERCO CONSTANT VARCHAR(13) := 'C_ANUL_SERCO';
  PUBLIC VARIABLE CONST_COD_RECIBO_INI CONSTANT VARCHAR2(13) := 'C_INI';
  PUBLIC VARIABLE CONST_COD_RECIBO_SERCO CONSTANT VARCHAR2(13) := 'C_SERCO';
  PUBLIC VARIABLE CONST_PRESTAGE_STATUS_LOAD        CONSTANT INTEGER := 0;
  PUBLIC VARIABLE CONST_STAGE_STATUS_OK         CONSTANT INTEGER := 1;
  PUBLIC VARIABLE CONST_STAGE_STATUS_ERROR        CONSTANT INTEGER := 3;
  PUBLIC VARIABLE CONST_POPULATE_STATUS_OK        CONSTANT INTEGER := 2;
  PUBLIC VARIABLE CONST_POPULATE_STATUS_ERROR       CONSTANT INTEGER := 4;
  PUBLIC VARIABLE CONST_CALCULO_STATUS_OK         CONSTANT INTEGER := 6;
  PUBLIC VARIABLE CONST_CALCULO_STATUS_ERROR        CONSTANT INTEGER := 7;
  PUBLIC VARIABLE CONST_GENERA_TRX_STATUS_OK        CONSTANT INTEGER := 9;
  PUBLIC VARIABLE CONST_GENERA_TRX_STATUS_ERROR     CONSTANT INTEGER := 5;
  PUBLIC VARIABLE CONST_OUT_BATCH_CONTROL_LOAD      CONSTANT INTEGER := 1;
  PUBLIC VARIABLE CONST_OUT_BATCH_CONTROL_OK        CONSTANT INTEGER := 2;
  PUBLIC VARIABLE CONST_OUT_BATCH_CONTROL_ERROR     CONSTANT INTEGER := 3;
  PUBLIC VARIABLE CONST_BORRADO_STATUS_OK         CONSTANT INTEGER := -1;
  PUBLIC VARIABLE CONST_BORRADO_STATUS_ERROR        CONSTANT INTEGER := -3;
  PUBLIC VARIABLE CONST_TIPO_REC_ANUL_K5          CONSTANT VARCHAR(2) := 'K5';
  PUBLIC VARIABLE CONST_TIPO_REC_AC           CONSTANT VARCHAR(2) := 'AC';
  PUBLIC VARIABLE CONST_TIPO_REC_GD           CONSTANT VARCHAR(2) := 'GD';
  PUBLIC VARIABLE CONST_TIPO_REC_5            CONSTANT VARCHAR(2) := '5';
  PUBLIC VARIABLE CONST_TIPO_REC_6            CONSTANT VARCHAR(2) := '6';
  PUBLIC VARIABLE CONST_OFICINA_GESTORA_900       CONSTANT VARCHAR(3) := '900';
  PUBLIC VARIABLE CONST_OFICINA_GESTORA_0900        CONSTANT VARCHAR(4) := '0900';
  PUBLIC VARIABLE   CONST_CALENDAR_NAME           CONSTANT VARCHAR(21):= 'Main Monthly Calendar';
  PUBLIC VARIABLE CONST_DE_AGENTE_REGISTRADO        CONSTANT INTEGER := 0;
  PUBLIC VARIABLE CONST_DE_AGENTE_INSERTADO_STAGE     CONSTANT INTEGER := 1;
  PUBLIC VARIABLE CONST_DE_AGENTE_INSERTADO_BATCH     CONSTANT INTEGER := 2;
  PUBLIC VARIABLE CONST_DE_AGENTE_EMAIL_ENVIADO     CONSTANT INTEGER := 3;
  PUBLIC FUNCTION getTenantID() RETURNS o_TI VARCHAR(4)
  AS
  BEGIN
    SELECT DISTINCT TENANTID
    INTO o_TI
    FROM TCMP.CS_CALENDAR;
  END;
  PUBLIC FUNCTION GET_PERMISOS_LOG () RETURNS o_permisos VARCHAR(4)LANGUAGE SQLSCRIPT AS
  BEGIN 
      DECLARE v_eot DATE :=TO_DATE('22000101','yyyymmdd');
  
    SELECT STRING_AGG(CGC.GENERICBOOLEAN1 ORDER BY CGC.CLASSIFIERSEQ ASC) INTO o_permisos
      FROM TCMP.CS_CLASSIFIER CLAS
      INNER JOIN TCMP.CS_GENERICCLASSIFIERTYPE GCT ON GCT.GENERICCLASSIFIERTYPESEQ = CLAS.SELECTORID
        AND GCT.NAME = 'Parametros Log'
      INNER JOIN TCMP.CS_GENERICCLASSIFIER CGC ON CLAS.CLASSIFIERSEQ = CGC.CLASSIFIERSEQ
        AND CGC.REMOVEDATE = v_eot 
        AND CGC.EFFECTIVEENDDATE > CURRENT_DATE
        AND CGC.EFFECTIVESTARTDATE <= CURRENT_DATE
      WHERE CLAS.REMOVEDATE = v_eot
        AND CLAS.EFFECTIVEENDDATE > CURRENT_DATE
        AND CLAS.EFFECTIVESTARTDATE <= CURRENT_DATE
;
  END;
  PUBLIC PROCEDURE WRITE_LOG (IN i_array_permmisos VARCHAR2(4), IN i_object VARCHAR2(400), IN i_txt VARCHAR2(4000), INOUT io_valor INT, IN i_idproceso BIGINT,IN i_loglevel VARCHAR(20) ) LANGUAGE SQLSCRIPT 
  AS
  BEGIN
    
    BEGIN AUTONOMOUS TRANSACTION
    
      IF( SUBSTR(i_array_permmisos,1,1) = 1 AND i_loglevel = 'debug' )THEN
        INSERT INTO "EXT"."CSE_LOG" (DATETIME, OBJECT, TEXT, VALUE, ID_PROCESO,LEVEL)
        VALUES (CURRENT_TIMESTAMP, i_object, i_txt, io_valor, i_idproceso,i_loglevel);
      
        io_valor:= io_valor + 1;
      
      END IF;
      
      IF( SUBSTR(i_array_permmisos,2,1) = 1 AND i_loglevel = 'info' )THEN
        INSERT INTO "EXT"."CSE_LOG" (DATETIME, OBJECT, TEXT, VALUE, ID_PROCESO,LEVEL)
        VALUES (CURRENT_TIMESTAMP, i_object, i_txt, io_valor, i_idproceso,i_loglevel);
      
        io_valor:= io_valor + 1;
      
      END IF;
      
      IF( SUBSTR(i_array_permmisos,3,1) = 1 AND i_loglevel = 'warning' )THEN
        INSERT INTO "EXT"."CSE_LOG" (DATETIME, OBJECT, TEXT, VALUE, ID_PROCESO,LEVEL)
        VALUES (CURRENT_TIMESTAMP, i_object, i_txt, io_valor, i_idproceso,i_loglevel);
      
        io_valor:= io_valor + 1;
      
      END IF;
      
      IF( SUBSTR(i_array_permmisos,4,1) = 1 AND i_loglevel = 'error' )THEN
        INSERT INTO "EXT"."CSE_LOG" (DATETIME, OBJECT, TEXT, VALUE, ID_PROCESO,LEVEL)
        VALUES (CURRENT_TIMESTAMP, i_object, i_txt, io_valor, i_idproceso,i_loglevel);
      
        io_valor:= io_valor + 1;
      
      END IF;
    
    END;
    
  END;
END