CREATE OR REPLACE PROCEDURE EXT.SP_CREAR_TABLAS (IN i_PeriodSeq BIGINT, IN i_lista_informes VARCHAR(5000), IN i_id_proceso BIGINT, IN i_log_count INTEGER)
LANGUAGE SQLSCRIPT 
SQL SECURITY INVOKER 
DEFAULT SCHEMA EXT AS

/*---------------------------------------------------------------------
    | Author: Rubén Martínez 
    | Company: Inycom
    | Initial Version Date: 16-Mayo-2025
    |----------------------------------------------------------------------
    | Procedure Purpose: Procedimiento para la recarga de tablas de informes. 
    | El procedimiento funciona desde un interfaz de salida de xDL, pasando la fecha en formato YYYYMMDD y el listado de informes a ejecutar
    |
	|
	| Version: 	0.1		RMF 20250516		Initial Version.
	|          	0.2  	MLR 20250521		Completado el esqueleto
	| 		   	0.3  	BRG/DTB 20250522	Tablas temporales adaptadas a variables tabla
	|		   	0.4  	BRG/DTB 20250523	Creada primera version de la tabla OUT_PERC_AGENTES_REP	
	|
    -----------------------------------------------------------------------
*/

BEGIN

	USING SQLSCRIPT_STRING AS LIBRARY;
	
	--	VARIABLES DE USO GENERAL
	DECLARE proc_name VARCHAR2(50) := ::CURRENT_OBJECT_SCHEMA ||'.'|| ::CURRENT_OBJECT_NAME;
	DECLARE v_version VARCHAR2(10) := '0.4';
	DECLARE v_num_rows INTEGER := 0;
	DECLARE v_idtenant VARCHAR(50) := EXT.LIB_GLOBAL:getTenantID();
	DECLARE v_permisos_log VARCHAR(50) := EXT.LIB_GLOBAL:GET_PERMISOS_LOG();
	DECLARE v_eot DATE := EXT.LIB_CONSTANTES:v_eot;
	DECLARE v_tablas_a_cargar VARCHAR(20) := '';
	DECLARE v_periodo_posteado INTEGER := 0;
	DECLARE v_periodo_finalizado INTEGER := 0;
	DECLARE v_period_name VARCHAR(100);
	DECLARE v_period_startdate DATE;
	DECLARE v_period_enddate DATE;
	DECLARE v_carga INTEGER := 0;
	DECLARE v_stop NUMBER(1);
	DECLARE v_FV_EstadoTrx number(1);
	DECLARE v_startdate_cartera DATE;
	
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
		BEGIN
		
			ROLLBACK;
			
			CALL EXT.LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name , 'Error en procedimiento principal ' || proc_name || ' - SQL_ERROR_MESSAGE: ' || IFNULL(::SQL_ERROR_MESSAGE,'')
																									|| '. SQL_ERROR_CODE: ' || ::SQL_ERROR_CODE, i_log_count, i_id_proceso, 'error');

			v_num_rows := 0;
		
			RESIGNAL;
		
		END;
	
	BEGIN
	
		CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'Version: ' || v_version || ' - Procedure starting ...', i_log_count, i_id_proceso, 'info');
		CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'Parámetros de entrada -> i_periodSeq: ' || i_PeriodSeq || ' | i_listado_informes: ' || i_lista_informes, i_log_count, i_id_proceso, 'info');

		-- Revisamos si se debe detener el proceso
		call EXT.LIB_CREAR_TABLAS:w_stop(:v_stop);
		IF v_stop = 0 THEN
			CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'CONTROL PARA NO EJECUTAR EL PROCESO. REVISAR CLASIFICACION!!!!!!!' , i_log_count, i_id_proceso, 'warning');    	
			RETURN;
		END IF;
		
		-- Obtener Periodo
		SELECT per.NAME, per.STARTDATE, per.ENDDATE INTO v_period_name, v_period_startdate, v_period_enddate
		FROM TCMP.cs_period per
		WHERE per.periodseq = :i_PeriodSeq AND
				per.removedate = :v_eot;

		CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'Periodo -> NAME: ' || :v_period_name || ' | STARTDATE: ' || :v_period_startdate || ' | ENDDATE: ' || v_period_enddate, i_log_count, i_id_proceso, 'info');
		
		-- Obtener clasificador de Tablas a Cargar
		SELECT GC.GENERICATTRIBUTE1 INTO v_tablas_a_cargar
		FROM CS_CLASSIFIER c 
		INNER JOIN CS_GENERICCLASSIFIER gc ON C.CLASSIFIERSEQ = GC.CLASSIFIERSEQ AND gc.REMOVEDATE = :v_eot  AND	gc.ISLAST = 1
		INNER JOIN CS_CATEGORY_CLASSIFIERS ccc ON ccc.CLASSIFIERSEQ = c.CLASSIFIERSEQ AND CCC.REMOVEDATE = :v_eot AND CCC.ISLAST = 1 AND CCC.MODELSEQ = 0
		INNER JOIN CS_CATEGORYTREE ct ON CCC.CATEGORYTREESEQ = CT.CATEGORYTREESEQ AND ct.REMOVEDATE =  :v_eot AND ct.ISLAST = 1
		WHERE CT.NAME = 'Permisos' AND c.classifierid = 'RECARGA' AND c.REMOVEDATE = :v_eot AND c.ISLAST = 1;	

		IF v_tablas_a_cargar = 'AUTO' THEN
			CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'Se recargan las tablas de informes por defecto dependiendo de si el periodo esta posteado o finalizado: '|| v_tablas_a_cargar , i_log_count, i_id_proceso, 'info');    	
			
			SELECT COUNT(DISTINCT PAY.POSTPIPELINERUNSEQ) INTO v_periodo_posteado
			FROM TCMP.CS_PAYMENT PAY
			INNER JOIN TCMP.CS_PLRUN PL ON PAY.TRIALPIPELINERUNSEQ = PL.PIPELINERUNSEQ AND PL.MODELSEQ = 0
			WHERE PAY.POSTPIPELINERUNSEQ IS NOT NULL AND PAY.PERIODSEQ = :i_PeriodSeq;
		
			SELECT COUNT(1) INTO v_periodo_finalizado
			FROM TCMP.CS_BALANCE BAL
			INNER JOIN TCMP.CS_PLRUN PL ON BAL.TRIALPIPELINERUNSEQ = PL.PIPELINERUNSEQ AND PL.MODELSEQ = 0
			WHERE BAL.PERIODSEQ = :i_PeriodSeq;
		
			-- PARA CARGAR LAS TABLAS DE CIERRE BASTA CON PONER LA VARIABLE v_periodo_posteado = 0 
			-- v_periodo_posteado := 0;
			-- PARA CARGAR LAS TABLAS DE LIQUIDACION COMPLEMENTARIA HAY QUE PONER LA VARIABLE v_periodo_posteado = 1 Y LA VARIABLE v_periodo_finalizado = 0
			-- v_periodo_posteado := 2;
			-- v_periodo_finalizado := 0;
			-- PARA CARGAR LAS TABLAS DE BALANCE HAY QUE PONER LA VARIABLE v_periodo_posteado = 1 Y LA VARIABLE v_periodo_finalizado = 1
			-- v_periodo_posteado := 1;
			-- v_periodo_finalizado := 1;

		ELSE
			CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'Se recargan las tablas de informes dependiendo de los clasificadores POST y FINALIZE: '|| v_tablas_a_cargar , i_log_count, i_id_proceso, 'info');    	

			SELECT GC.GENERICBOOLEAN1 INTO v_periodo_posteado
			FROM CS_CLASSIFIER c 
			INNER JOIN CS_GENERICCLASSIFIER gc ON C.CLASSIFIERSEQ = GC.CLASSIFIERSEQ AND gc.REMOVEDATE = v_eot AND gc.islast = 1
			INNER JOIN CS_CATEGORY_CLASSIFIERS ccc ON  ccc.CLASSIFIERSEQ = c.CLASSIFIERSEQ AND CCC.REMOVEDATE = v_eot AND CCC.ISLAST = 1 AND CCC.MODELSEQ = 0
			INNER JOIN CS_CATEGORYTREE ct ON CCC.CATEGORYTREESEQ = CT.CATEGORYTREESEQ AND ct.REMOVEDATE = v_eot AND ct.ISLAST = 1
			WHERE CT.NAME = 'Permisos' AND c.classifierid = 'POST' AND c.REMOVEDATE = v_eot AND c.ISLAST = 1;
		
			SELECT GC.GENERICBOOLEAN1 INTO v_periodo_finalizado
			FROM CS_CLASSIFIER c 
			INNER JOIN CS_GENERICCLASSIFIER gc ON C.CLASSIFIERSEQ = GC.CLASSIFIERSEQ AND gc.REMOVEDATE = v_eot AND gc.islast = 1
			INNER JOIN CS_CATEGORY_CLASSIFIERS ccc ON ccc.CLASSIFIERSEQ = c.CLASSIFIERSEQ AND CCC.REMOVEDATE = v_eot AND CCC.ISLAST = 1 AND CCC.MODELSEQ = 0
			INNER JOIN CS_CATEGORYTREE ct ON CCC.CATEGORYTREESEQ = CT.CATEGORYTREESEQ AND ct.REMOVEDATE = v_eot AND ct.ISLAST = 1
			WHERE CT.NAME ='Permisos' AND c.classifierid = 'FINALIZE' AND c.REMOVEDATE = v_eot AND c.ISLAST = 1;

		END IF;        

		CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'Carga variable v_periodo_posteado: '|| v_periodo_posteado , i_log_count, i_id_proceso, 'info');
		CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'Carga variable v_periodo_finalizado: '|| v_periodo_finalizado , i_log_count, i_id_proceso, 'info');    	

		IF v_periodo_finalizado = 1 AND v_periodo_posteado = 0 THEN
			CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'PERIODO FINALIZADO SIN PAGOS POSTEADOS. POSIBLE ERROR EN LOS DATOS. REVISAR!!!!!!!' , i_log_count, i_id_proceso, 'warning');    	

			-- RAISE_APPLICATION_ERROR(-20000, 'Finalizacion Forzada.');
			SIGNAL SQL_ERROR_CODE 10001 SET MESSAGE_TEXT = 'PERIODO FINALIZADO SIN PAGOS POSTEADOS. POSIBLE ERROR EN LOS DATOS.';
			RETURN;
		END IF;

		--ALM 20210924; Proyecto Licencias Payee. Consultamos el parametro para saber si estamos en paralelo o ya en Produccion.
		SELECT MAX(VALUE) INTO v_FV_EstadoTrx
		FROM TCMP.CS_FIXEDVALUE
		WHERE NAME = 'FV-CONF-Estado-Transaccion'
			AND REMOVEDATE = :v_eot
			AND MODELSEQ = 0
			AND EFFECTIVESTARTDATE <= :v_period_startdate
			AND EFFECTIVEENDDATE > :v_period_startdate;
		
		CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'Carga variable v_FV_EstadoTrx: '|| v_FV_EstadoTrx , i_log_count, i_id_proceso, 'info');

		-- LOGICA CREAR_TABLAS 
		-- Variables proceso anterior - No migradas:
			-- v_Licencias - no se aplica 
			-- v_recarga_temp - se recargan siempre
    -------------------------------------------------------------------------------------------------------------------------------------
    -- INICIO TABLAS EXTRACCIONES (TEMPORALES)
	-- uso de variables de tabla si es posible
		---------------------------------------------------------------------------------------------------------------------------------
		-- BRG 20250522: Tabla temporal TEMP_TABLA_IRPF_REP pasa a ser TBL_TABLA_IRPF

		TBL_TABLA_IRPF = SELECT C.CLASSIFIERID,SUBSTR(C.NAME,1,1),GC.GENERICNUMBER1
			FROM CS_GENERICCLASSIFIERTYPE GCT
			INNER JOIN CS_CLASSIFIER C ON GCT.GENERICCLASSIFIERTYPESEQ = C.SELECTORID
				AND C.TENANTID = :v_idtenant 
				AND C.REMOVEDATE = :v_eot
			INNER JOIN TCMP.CSA_PERIODDIMENSION PD ON C.EFFECTIVESTARTDATE < PD.ENDDATE AND C.EFFECTIVEENDDATE >= PD.ENDDATE
				AND PD.TENANTID = :v_idtenant
			INNER JOIN CS_GENERICCLASSIFIER GC ON C.CLASSIFIERSEQ = GC.CLASSIFIERSEQ
				AND GC.EFFECTIVESTARTDATE < PD.ENDDATE AND GC.EFFECTIVEENDDATE >= PD.ENDDATE
				AND GC.TENANTID = :v_idtenant
				AND GC.REMOVEDATE = :v_eot
			INNER JOIN CS_CATEGORY_CLASSIFIERS CC ON C.CLASSIFIERSEQ = CC.CLASSIFIERSEQ 
				AND CC.EFFECTIVESTARTDATE < PD.ENDDATE AND CC.EFFECTIVEENDDATE >= PD.ENDDATE
				AND CC.TENANTID = :v_idtenant
				AND CC.REMOVEDATE = :v_eot
				-- ALM 20191008: Anadimos condicion para no coger posibles resultados de los MODELS
				AND MODELSEQ = 0
			INNER JOIN CS_CATEGORYTREE CT ON CC.CATEGORYTREESEQ = CT.CATEGORYTREESEQ
				AND CT.EFFECTIVESTARTDATE < PD.ENDDATE AND CT.EFFECTIVEENDDATE >= PD.ENDDATE
				AND CT.TENANTID = :v_idtenant
				AND CT.REMOVEDATE = :v_eot
				AND CT.NAME = 'Tipo IRPF'    
			WHERE GCT.TENANTID = :v_idtenant
				AND GCT.NAME = 'Tipo IRPF'
				AND PD.PERIODSEQ = :i_PeriodSeq;
		
		v_num_rows := RECORD_COUNT(:TBL_TABLA_IRPF);

		CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'TBL_TABLA_IRPF creada. Filas: ' || v_num_rows, i_log_count, i_id_proceso, 'debug');

		-- Revisamos si se debe detener el proceso
		call EXT.LIB_CREAR_TABLAS:w_stop(:v_stop);
		IF v_stop = 0 THEN
			CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'CONTROL PARA NO EJECUTAR EL PROCESO. REVISAR CLASIFICACION!!!!!!!' , i_log_count, i_id_proceso, 'warning');    	
			RETURN;
		END IF;
	
		---------------------------------------------------------------------------------------------------------------------------------
		-- DTB 20250522: Tabla temporal INYC_TABLA_PERCEPCIONES pasa a ser TBL_TABLA_PERCEPCIONES

		TBL_TABLA_PERCEPCIONES = SELECT DISTINCT GC.GENERICATTRIBUTE4 AS DEPOSITO,GC.GENERICATTRIBUTE1 AS DESCRIPCION, GC.GENERICATTRIBUTE2 AS EARNINGCODE,GC.GENERICATTRIBUTE3 AS EARNINGGROUP
			FROM CS_GENERICCLASSIFIERTYPE GCT
			INNER JOIN CS_CLASSIFIER C ON GCT.GENERICCLASSIFIERTYPESEQ = C.SELECTORID
				AND C.TENANTID = :v_idtenant
				AND C.REMOVEDATE = :v_eot
			INNER JOIN TCMP.CSA_PERIODDIMENSION PD ON C.EFFECTIVESTARTDATE < PD.ENDDATE AND C.EFFECTIVEENDDATE >= PD.ENDDATE
				AND PD.TENANTID = :v_idtenant
			INNER JOIN CS_GENERICCLASSIFIER GC ON C.CLASSIFIERSEQ = GC.CLASSIFIERSEQ
				AND GC.EFFECTIVESTARTDATE < PD.ENDDATE AND GC.EFFECTIVEENDDATE >= PD.ENDDATE
				AND GC.TENANTID = :v_idtenant
				AND GC.REMOVEDATE = :v_eot
			INNER JOIN CS_CATEGORY_CLASSIFIERS CC ON C.CLASSIFIERSEQ = CC.CLASSIFIERSEQ 
				AND CC.EFFECTIVESTARTDATE < PD.ENDDATE AND CC.EFFECTIVEENDDATE >= PD.ENDDATE
				AND CC.TENANTID = :v_idtenant
				AND CC.REMOVEDATE = :v_eot
				--ALM 20191008: Anadimos condicion para no coger posibles resultados de los MODELS
				AND MODELSEQ = 0
			INNER JOIN CS_CATEGORYTREE CT ON CC.CATEGORYTREESEQ = CT.CATEGORYTREESEQ
				AND CT.EFFECTIVESTARTDATE < PD.ENDDATE AND CT.EFFECTIVEENDDATE >= PD.ENDDATE
				AND CT.TENANTID = :v_idtenant
				AND CT.REMOVEDATE = :v_eot
				AND CT.NAME = 'Percepciones'    
			WHERE GCT.TENANTID = 'G203'
				AND GCT.NAME LIKE 'Percepci%n'
				AND PD.PERIODSEQ = :i_PeriodSeq;


		v_num_rows := RECORD_COUNT(:TBL_TABLA_PERCEPCIONES);

		CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'TBL_TABLA_PERCEPCIONES creada. Filas: ' || v_num_rows, i_log_count, i_id_proceso, 'debug');

		-- Revisamos si se debe detener el proceso
		call EXT.LIB_CREAR_TABLAS:w_stop(:v_stop);
		IF v_stop = 0 THEN
			CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'CONTROL PARA NO EJECUTAR EL PROCESO. REVISAR CLASIFICACION!!!!!!!' , i_log_count, i_id_proceso, 'warning');    	
			RETURN;
		END IF;
		---------------------------------------------------------------------------------------------------------------------------------
		-- BRG 20250522: Modificacion de EXT.TEST_CARTERA_DDEE
		-- ALM 20220330: Solo hacemos esta modificacion si se ejecuta un periodo antes de la LC y los balances.
		IF v_periodo_posteado = 0 THEN

			CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'Inicio modificacion EXT.TEST_CARTERA_DDEE si ya no es derechos economicos.', i_log_count, i_id_proceso, 'debug');


			-- BRG 20250522: Creamos variable v_startdate_cartera para optimizar
			SELECT STARTDATE INTO v_startdate_cartera
			FROM CSA_PERIODDIMENSION 
			WHERE TENANTID = :v_idtenant
				AND PERIODSEQ = :i_PeriodSeq;

			-- BRG 20250522: Variable tabla TBL_POSITIONS_CARTERA para optimizar
			TBL_POSITIONS_CARTERA = SELECT P.NAME
				FROM TCMP.CSA_PERIODDIMENSION PD
				INNER JOIN TCMP.CS_POSITION P ON P.EFFECTIVESTARTDATE <= PD.STARTDATE
					AND P.EFFECTIVEENDDATE > PD.STARTDATE
					AND P.REMOVEDATE = :v_eot
					AND P.TENANTID = :v_idtenant
					AND P.GENERICNUMBER2 IN (6,12) 
				WHERE PD.TENANTID = :v_idtenant
					AND PD.PERIODSEQ = :i_PeriodSeq;

			-- MCR 20220329: En el caso de que a un agente DDEE le cambien de tipologia, se borraba de la tabla. Cambiamos el estado para que no se tenga en cuenta pero no se borren los datos. 
            -- ATV 20240710: Anyadimos el tipo 6 (que ahora es DDEE) para que no ponga el estado X.
			UPDATE EXT.TEST_CARTERA_DDEE
			SET ESTADO = 'X'
			WHERE COMPENSATIONDATE = :v_startdate_cartera
				AND POSITIONNAME NOT IN (SELECT NAME FROM :TBL_POSITIONS_CARTERA)
				AND ESTADO = 'C'
				--ALM 20220331: Control manual para no tener en cuenta agentes concretos:
				AND (COMPENSATIONDATE <> TO_DATE('20220301','YYYYMMDD') OR COD_AGENTE <> '0316003359'); --Pedido por David para 2022-03

			v_num_rows := ::ROWCOUNT;

			CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'Fin modificacion EXT.TEST_CARTERA_DDEE si ya no es derechos economicos. Filas: ' || v_num_rows, i_log_count, i_id_proceso, 'debug');
		
		END IF;
		
		-- Revisamos si se debe detener el proceso
		call EXT.LIB_CREAR_TABLAS:w_stop(:v_stop);
		IF v_stop = 0 THEN
			CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'CONTROL PARA NO EJECUTAR EL PROCESO. REVISAR CLASIFICACION!!!!!!!' , i_log_count, i_id_proceso, 'warning');    	
			RETURN;
		END IF;
		-------------------------------------------------------------------------------------------------------------------------------------		
		-- DTB 20250522: Modificación de CONF_PARAMETROS_FILE
		-- SE HA DE MODIFICAR ESTA TABLA?????????
		-- UPDATE EXT.CONF_PARAMETROS_FILE SET VALOR = :v_carga WHERE NOMBRE = 'CARGA_TABLAS_TEMP'
		
		
		---------------------------------------------------------------------------------------------------------------------------------
		-- DTB 20250522: Tabla temporal INYC_TXN_MES_TEMP pasa a ser TBL_TXN_MES      
        TBL_TXN_MES = 
            SELECT ST.TENANTID, ST.SALESTRANSACTIONSEQ, ST.SALESORDERSEQ, ST.LINENUMBER, ST.SUBLINENUMBER, ST.EVENTTYPESEQ, ST.PIPELINERUNSEQ, ST.ORIGINTYPEID,
                ST.COMPENSATIONDATE, ST.BILLTOADDRESSSEQ, ST.SHIPTOADDRESSSEQ, ST.OTHERTOADDRESSSEQ, ST.ISRUNNABLE, ST.BUSINESSUNITMAP, ST.ACCOUNTINGDATE,
                ST.PRODUCTID, ST.PRODUCTNAME, ST.PRODUCTDESCRIPTION, ST.NUMBEROFUNITS, ST.UNITVALUE, ST.UNITTYPEFORUNITVALUE, ST.PREADJUSTEDVALUE,
                ST.UNITTYPEFORPREADJUSTEDVALUE, ST.VALUE, ST.UNITTYPEFORVALUE, ST.NATIVECURRENCY, ST.NATIVECURRENCYAMOUNT, ST.DISCOUNTPERCENT, ST.DISCOUNTTYPE,
                ST.PAYMENTTERMS, ST.PONUMBER, ST.CHANNEL, ST.ALTERNATEORDERNUMBER, ST.DATASOURCE, ST.REASONSEQ, ST.COMMENTS, ST.GENERICATTRIBUTE1,
                ST.GENERICATTRIBUTE2, ST.GENERICATTRIBUTE3, ST.GENERICATTRIBUTE4, ST.GENERICATTRIBUTE5, ST.GENERICATTRIBUTE6, ST.GENERICATTRIBUTE7,
                ST.GENERICATTRIBUTE8, ST.GENERICATTRIBUTE9, ST.GENERICATTRIBUTE10, ST.GENERICATTRIBUTE11, ST.GENERICATTRIBUTE12, ST.GENERICATTRIBUTE13,
                ST.GENERICATTRIBUTE14, ST.GENERICATTRIBUTE15, ST.GENERICATTRIBUTE16, ST.GENERICATTRIBUTE17, ST.GENERICATTRIBUTE18, ST.GENERICATTRIBUTE19,
                ST.GENERICATTRIBUTE20, ST.GENERICATTRIBUTE21, ST.GENERICATTRIBUTE22, ST.GENERICATTRIBUTE23, ST.GENERICATTRIBUTE24, ST.GENERICATTRIBUTE25,
                ST.GENERICATTRIBUTE26, ST.GENERICATTRIBUTE27, ST.GENERICATTRIBUTE28, ST.GENERICATTRIBUTE29, ST.GENERICATTRIBUTE30, ST.GENERICATTRIBUTE31,
                ST.GENERICATTRIBUTE32, ST.GENERICNUMBER1, ST.UNITTYPEFORGENERICNUMBER1, ST.GENERICNUMBER2, ST.UNITTYPEFORGENERICNUMBER2, ST.GENERICNUMBER3,
                ST.UNITTYPEFORGENERICNUMBER3, ST.GENERICNUMBER4, ST.UNITTYPEFORGENERICNUMBER4, ST.GENERICNUMBER5, ST.UNITTYPEFORGENERICNUMBER5, ST.GENERICNUMBER6,
                ST.UNITTYPEFORGENERICNUMBER6, ST.GENERICDATE1, ST.GENERICDATE2, ST.GENERICDATE3, ST.GENERICDATE4, ST.GENERICDATE5, ST.GENERICDATE6,
                ST.GENERICBOOLEAN1, ST.GENERICBOOLEAN2, ST.GENERICBOOLEAN3, ST.GENERICBOOLEAN4, ST.GENERICBOOLEAN5, ST.GENERICBOOLEAN6, ST.PROCESSINGUNITSEQ,
                ST.MODIFICATIONDATE, ST.UNITTYPEFORLINENUMBER, ST.UNITTYPEFORSUBLINENUMBER, ST.UNITTYPEFORNUMBEROFUNITS, ST.UNITTYPEFORDISCOUNTPERCENT,
                ST.UNITTYPEFORNATIVECURRENCYAMT, ST.MODELSEQ,
                CASE WHEN ET.EVENTTYPEID IN ('66','81') AND ST.GENERICATTRIBUTE3 IN ('3','4','5','6','7','8') THEN 'Recuperacion' 
                    --WHEN ET.EVENTTYPEID LIKE 'AS%' THEN 'Tramitacion'
                    --ALM 20180921: Cambiamos la tipologia de las transacciones generadas por Javier para la Venta Simultanea 1+1
                    --              Son transacciones tipo 71 y llevan en el campo Tipo de Campania (GA21) el codigo 'VS11' 
                    WHEN ET.EVENTTYPEID = '71' AND ST.GENERICATTRIBUTE21 = 'VS11' THEN 'Bonif Venta Simultanea'
                    --ATV 20241231 Anyadimos modificacion para polizas sin firmar
                    WHEN ST.GENERICATTRIBUTE6 IN ('S','N') THEN ET.DESCRIPTION || ' - No firmadas Cond. Part'
                    ELSE ET.DESCRIPTION
				END AS EVENTO,
                PROD.GENERICATTRIBUTE5 AS PRODUCTO, PROD.GENERICBOOLEAN1 AS GARANTIA,
                TA.GENERICDATE1 AS FEC_VTO_REC, TA.GENERICNUMBER2 AS KM, TA.GENERICBOOLEAN2 AS RECIBO
            FROM TCMP.CS_SALESTRANSACTION ST
            INNER JOIN TCMP.CS_TRANSACTIONASSIGNMENT TA ON ST.SALESTRANSACTIONSEQ = TA.SALESTRANSACTIONSEQ
                AND TA.TENANTID = :v_idtenant
                --ALM 20211025: Anadimos condicion para mejorar el rendimeinto de la consulta
                AND TA.PROCESSINGUNITSEQ = 38280596832649217
            INNER JOIN TCMP.CSA_PERIODDIMENSION PD ON ST.COMPENSATIONDATE >= PD.STARTDATE AND ST.COMPENSATIONDATE < PD.ENDDATE
                AND PD.TENANTID = :v_idtenant
            LEFT OUTER JOIN TCMP.CS_EVENTTYPE ET ON ST.EVENTTYPESEQ = ET.DATATYPESEQ
                AND ET.REMOVEDATE = :v_eot 
                AND ET.TENANTID = :v_idtenant
            LEFT OUTER JOIN TCMP.CS_CLASSIFIER CL ON ST.PRODUCTID = CL.CLASSIFIERID 
                AND CL.REMOVEDATE = :v_eot  
                AND CL.EFFECTIVESTARTDATE <= ST.COMPENSATIONDATE AND CL.EFFECTIVEENDDATE > ST.COMPENSATIONDATE
                AND CL.TENANTID = :v_idtenant
            LEFT OUTER JOIN TCMP.CS_PRODUCT PROD ON CL.CLASSIFIERSEQ = PROD.CLASSIFIERSEQ 
                AND PROD.REMOVEDATE = :v_eot  
                AND PROD.EFFECTIVESTARTDATE <= ST.COMPENSATIONDATE AND PROD.EFFECTIVEENDDATE > ST.COMPENSATIONDATE
                AND PROD.TENANTID = :v_idtenant
            WHERE ST.TENANTID = :v_idtenant AND PD.PERIODSEQ = :i_PeriodSeq
                --ALM 20191008: Anadimos condicion para no coger posibles resultados de los MODELS
                AND ST.MODELSEQ = 0
                --ALM 20211025: Anadimos condicion para mejorar el rendimeinto de la consulta
                AND ST.PROCESSINGUNITSEQ = 38280596832649217;
        
		v_num_rows := RECORD_COUNT(:TBL_TXN_MES);

		CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'TBL_TXN_MES creada. Filas: ' || v_num_rows, i_log_count, i_id_proceso, 'debug');

		-- Revisamos si se debe detener el proceso
		call EXT.LIB_CREAR_TABLAS:w_stop(:v_stop);
		IF v_stop = 0 THEN
			CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'CONTROL PARA NO EJECUTAR EL PROCESO. REVISAR CLASIFICACION!!!!!!!' , i_log_count, i_id_proceso, 'warning');    	
			RETURN;
		END IF;

		---------------------------------------------------------------------------------------------------------------------------------
		-- BRG 20250522: Tabla temporal INYC_CREDITOS_MES_TEMP pasa a ser TBL_CREDITOS_MES
		TBL_CREDITOS_MES = SELECT C.TENANTID, C.CREDITSEQ, C.PAYEESEQ, C.POSITIONSEQ, C.SALESORDERSEQ, C.SALESTRANSACTIONSEQ, C.PERIODSEQ, C.CREDITTYPESEQ, C.NAME, C.PIPELINERUNSEQ,
                C.ORIGINTYPEID, C.COMPENSATIONDATE, C.PIPELINERUNDATE, C.BUSINESSUNITMAP, C.PREADJUSTEDVALUE, C.UNITTYPEFORPREADJUSTEDVALUE, C.VALUE,
                C.UNITTYPEFORVALUE, C.RELEASEDATE, C.RULESEQ, C.ISHELD, C.ISROLLABLE, C.ROLLDATE, C.REASONSEQ, C.COMMENTS, C.GENERICATTRIBUTE1, C.GENERICATTRIBUTE2,
                C.GENERICATTRIBUTE3, C.GENERICATTRIBUTE4, C.GENERICATTRIBUTE5, C.GENERICATTRIBUTE6, C.GENERICATTRIBUTE7, C.GENERICATTRIBUTE8, C.GENERICATTRIBUTE9,
                C.GENERICATTRIBUTE10, C.GENERICATTRIBUTE11, C.GENERICATTRIBUTE12, C.GENERICATTRIBUTE13, C.GENERICATTRIBUTE14, C.GENERICATTRIBUTE15,
                C.GENERICATTRIBUTE16, C.GENERICNUMBER1, C.UNITTYPEFORGENERICNUMBER1, C.GENERICNUMBER2, C.UNITTYPEFORGENERICNUMBER2, C.GENERICNUMBER3,
                C.UNITTYPEFORGENERICNUMBER3, C.GENERICNUMBER4, C.UNITTYPEFORGENERICNUMBER4, C.GENERICNUMBER5, C.UNITTYPEFORGENERICNUMBER5, C.GENERICNUMBER6,
                C.UNITTYPEFORGENERICNUMBER6, C.GENERICDATE1, C.GENERICDATE2, C.GENERICDATE3, C.GENERICDATE4, C.GENERICDATE5, C.GENERICDATE6, C.GENERICBOOLEAN1,
                C.GENERICBOOLEAN2, C.GENERICBOOLEAN3, C.GENERICBOOLEAN4, C.GENERICBOOLEAN5, C.GENERICBOOLEAN6, C.PROCESSINGUNITSEQ
            FROM TCMP.CS_CREDIT C
            --ALM 20191008: Anadimos condicion para no coger posibles resultados de los MODELS
            INNER JOIN TCMP.CS_PLRUN PL ON C.PIPELINERUNSEQ = PL.PIPELINERUNSEQ AND PL.MODELSEQ = 0
            WHERE C.TENANTID = :v_idtenant AND C.PERIODSEQ = :i_PeriodSeq
				--ALM 20211025: Anadimos condicion para mejorar el rendimeinto de la consulta
                AND C.PROCESSINGUNITSEQ = 38280596832649217;
		
		v_num_rows := RECORD_COUNT(:TBL_CREDITOS_MES);

		CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'TBL_CREDITOS_MES creada. Filas: ' || v_num_rows, i_log_count, i_id_proceso, 'debug');

		-- Revisamos si se debe detener el proceso
		call EXT.LIB_CREAR_TABLAS:w_stop(:v_stop);
		IF v_stop = 0 THEN
			CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'CONTROL PARA NO EJECUTAR EL PROCESO. REVISAR CLASIFICACION!!!!!!!' , i_log_count, i_id_proceso, 'warning');    	
			RETURN;
		END IF;

		-------------------------------------------------------------------------------------------------------------------------------------
		--DTB 20250522: Tabla temporal INYC_MEDIDAS_MES_TEMP pasa a ser TBL_MEDIDAS_MES
        TBL_MEDIDAS_MES =
            SELECT M.TENANTID, M.MEASUREMENTSEQ, M.NAME, M.PAYEESEQ, M.POSITIONSEQ, M.PERIODSEQ, M.PIPELINERUNSEQ, M.PIPELINERUNDATE, M.PLANSEQ, M.RULESEQ, M.VALUE,
                M.UNITTYPEFORVALUE, M.NUMBEROFCREDITS, M.BUSINESSUNITMAP, M.GENERICATTRIBUTE1, M.GENERICATTRIBUTE2, M.GENERICATTRIBUTE3, M.GENERICATTRIBUTE4,
                M.GENERICATTRIBUTE5, M.GENERICATTRIBUTE6, M.GENERICATTRIBUTE7, M.GENERICATTRIBUTE8, M.GENERICATTRIBUTE9, M.GENERICATTRIBUTE10, M.GENERICATTRIBUTE11,
                M.GENERICATTRIBUTE12, M.GENERICATTRIBUTE13, M.GENERICATTRIBUTE14, M.GENERICATTRIBUTE15, M.GENERICATTRIBUTE16, M.GENERICNUMBER1,
                M.UNITTYPEFORGENERICNUMBER1, M.GENERICNUMBER2, M.UNITTYPEFORGENERICNUMBER2, M.GENERICNUMBER3, M.UNITTYPEFORGENERICNUMBER3, M.GENERICNUMBER4,
                M.UNITTYPEFORGENERICNUMBER4, M.GENERICNUMBER5, M.UNITTYPEFORGENERICNUMBER5, M.GENERICNUMBER6, M.UNITTYPEFORGENERICNUMBER6, M.GENERICDATE1,
                M.GENERICDATE2, M.GENERICDATE3, M.GENERICDATE4, M.GENERICDATE5, M.GENERICDATE6, M.GENERICBOOLEAN1, M.GENERICBOOLEAN2, M.GENERICBOOLEAN3,
                M.GENERICBOOLEAN4, M.GENERICBOOLEAN5, M.GENERICBOOLEAN6, M.PROCESSINGUNITSEQ, M.UNITTYPEFORNUMBEROFCREDITS 
            FROM TCMP.CS_MEASUREMENT M
            --ALM 20191008: Anadimos condicion para no coger posibles resultados de los MODELS
            INNER JOIN TCMP.CS_PLRUN PL ON M.PIPELINERUNSEQ = PL.PIPELINERUNSEQ AND PL.MODELSEQ = 0
            WHERE M.TENANTID = :v_idtenant AND M.PERIODSEQ = :i_PeriodSeq
                --ALM 20211025: Anadimos condicion para mejorar el rendimeinto de la consulta
                AND M.PROCESSINGUNITSEQ = 38280596832649217;

		v_num_rows := RECORD_COUNT(:TBL_MEDIDAS_MES);

		CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'TBL_MEDIDAS_MES creada. Filas: ' || v_num_rows, i_log_count, i_id_proceso, 'debug');

		-- Revisamos si se debe detener el proceso
		call EXT.LIB_CREAR_TABLAS:w_stop(:v_stop);
		IF v_stop = 0 THEN
			CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'CONTROL PARA NO EJECUTAR EL PROCESO. REVISAR CLASIFICACION!!!!!!!' , i_log_count, i_id_proceso, 'warning');    	
			RETURN;
		END IF;

		---------------------------------------------------------------------------------------------------------------------------------
		-- BRG 20250522: Tabla temporal INYC_PAGOS_MES_TEMP pasa a ser TBL_PAGOS_MES
		TBL_PAGOS_MES = SELECT P.TENANTID, P.PAYMENTSEQ, P.PAYEESEQ, P.POSITIONSEQ, P.PERIODSEQ, P.EARNINGGROUPID, P.EARNINGCODEID, P.TRIALPIPELINERUNSEQ, P.TRIALPIPELINERUNDATE, P.POSTPIPELINERUNSEQ,
                P.POSTPIPELINERUNDATE, P.BUSINESSUNITMAP, P.VALUE, P.UNITTYPEFORVALUE, P.REASONSEQ, P.PROCESSINGUNITSEQ,
                P.GENERICATTRIBUTE1, P.GENERICATTRIBUTE2, P.GENERICATTRIBUTE3, P.GENERICATTRIBUTE4, P.GENERICATTRIBUTE5, P.GENERICATTRIBUTE6, P.GENERICATTRIBUTE7, P.GENERICATTRIBUTE8,
                P.GENERICATTRIBUTE9, P.GENERICATTRIBUTE10, P.GENERICATTRIBUTE11, P.GENERICATTRIBUTE12, P.GENERICATTRIBUTE13, P.GENERICATTRIBUTE14, P.GENERICATTRIBUTE15, P.GENERICATTRIBUTE16,
                P.GENERICNUMBER1, P.GENERICNUMBER2, P.GENERICNUMBER3, P.GENERICNUMBER4, P.GENERICNUMBER5, P.GENERICNUMBER6,
                P.UNITTYPEFORGENERICNUMBER1, P.UNITTYPEFORGENERICNUMBER2, P.UNITTYPEFORGENERICNUMBER3, P.UNITTYPEFORGENERICNUMBER4, P.UNITTYPEFORGENERICNUMBER5, P.UNITTYPEFORGENERICNUMBER6,
                P.GENERICDATE1, P.GENERICDATE2, P.GENERICDATE3, P.GENERICDATE4, P.GENERICDATE5, P.GENERICDATE6,
                P.GENERICBOOLEAN1, P.GENERICBOOLEAN2, P.GENERICBOOLEAN3, P.GENERICBOOLEAN4, P.GENERICBOOLEAN5, P.GENERICBOOLEAN6 
            FROM TCMP.CS_PAYMENT P
            --ALM 20191008: Anadimos condicion para no coger posibles resultados de los MODELS
            INNER JOIN TCMP.CS_PLRUN PL ON P.TRIALPIPELINERUNSEQ = PL.PIPELINERUNSEQ AND PL.MODELSEQ = 0
            WHERE P.TENANTID = :v_idtenant AND P.PERIODSEQ = :i_PeriodSeq
                --ALM 20211025: Anadimos condicion para mejorar el rendimeinto de la consulta
                AND P.PROCESSINGUNITSEQ = 38280596832649217;
		
		v_num_rows := RECORD_COUNT(:TBL_PAGOS_MES);

		CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'TBL_PAGOS_MES creada. Filas: ' || v_num_rows, i_log_count, i_id_proceso, 'debug');

		-- Revisamos si se debe detener el proceso
		call EXT.LIB_CREAR_TABLAS:w_stop(:v_stop);
		IF v_stop = 0 THEN
			CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'CONTROL PARA NO EJECUTAR EL PROCESO. REVISAR CLASIFICACION!!!!!!!' , i_log_count, i_id_proceso, 'warning');    	
			RETURN;
		END IF;

		---------------------------------------------------------------------------------------------------------------------------------
		-- BRG 20250522: Tabla temporal INYC_OFICINAS_MES_TEMP pasa a ser TBL_OFICINAS_MES
		TBL_OFICINAS_MES = SELECT PAD.TENANTID, PAD.PERIODSEQ, PAD.POSITIONSEQ, PAD.PARTICIPANTSEQ, PAD.PARTICIPANTID, PAD.USERID, PAD.PREFIX, PAD.FIRSTNAME, PAD.MIDDLENAME, 
                PAD.LASTNAME, PAD.SUFFIX, PAD.FULLNAME, PAD.TAXID, PAD.SALARY, PAD.UTSFORSALARY, PAD.HIREDATE, PAD.TERMINATIONDATE, PAD.BUSINESSUNITMAP,
                PAD.POSITIONNAME, PAD.POSITIONDESCRIPTION, PAD.TITLENAME, PAD.TITLEDESCRIPTION, PAD.TARGETCOMPENSATION, PAD.UTSFORTARGETCOMPENSATION, PAD.PLANNAME,
                PAD.PLANSEQ, PAD.PROCESSINGUNITNAME, PAD.PROCESSINGUNITSEQ, PAD.POSITIONGENERICATTRIBUTE1, PAD.POSITIONGENERICATTRIBUTE2,
                PAD.POSITIONGENERICATTRIBUTE3, PAD.POSITIONGENERICATTRIBUTE4, PAD.POSITIONGENERICATTRIBUTE5, PAD.POSITIONGENERICATTRIBUTE6,
                PAD.POSITIONGENERICATTRIBUTE7, PAD.POSITIONGENERICATTRIBUTE8, PAD.POSITIONGENERICATTRIBUTE9, PAD.POSITIONGENERICATTRIBUTE10,
                PAD.POSITIONGENERICATTRIBUTE11, PAD.POSITIONGENERICATTRIBUTE12, PAD.POSITIONGENERICATTRIBUTE13, PAD.POSITIONGENERICATTRIBUTE14,
                PAD.POSITIONGENERICATTRIBUTE15, PAD.POSITIONGENERICATTRIBUTE16, PAD.POSITIONGENERICNUMBER1, PAD.UTSFORPOSITIONGN1, PAD.POSITIONGENERICNUMBER2,
                PAD.UTSFORPOSITIONGN2, PAD.POSITIONGENERICNUMBER3, PAD.UTSFORPOSITIONGN3, PAD.POSITIONGENERICNUMBER4, PAD.UTSFORPOSITIONGN4,
                PAD.POSITIONGENERICNUMBER5, PAD.UTSFORPOSITIONGN5, PAD.POSITIONGENERICNUMBER6, PAD.UTSFORPOSITIONGN6, PAD.POSITIONGENERICDATE1,
                PAD.POSITIONGENERICDATE2, PAD.POSITIONGENERICDATE3, PAD.POSITIONGENERICDATE4, PAD.POSITIONGENERICDATE5, PAD.POSITIONGENERICDATE6,
                PAD.POSITIONGENERICBOOLEAN1, PAD.POSITIONGENERICBOOLEAN2, PAD.POSITIONGENERICBOOLEAN3, PAD.POSITIONGENERICBOOLEAN4, PAD.POSITIONGENERICBOOLEAN5,
                PAD.POSITIONGENERICBOOLEAN6, PAD.PARTICIPANTGENERICATTRIBUTE1, PAD.PARTICIPANTGENERICATTRIBUTE2, PAD.PARTICIPANTGENERICATTRIBUTE3,
                PAD.PARTICIPANTGENERICATTRIBUTE4, PAD.PARTICIPANTGENERICATTRIBUTE5, PAD.PARTICIPANTGENERICATTRIBUTE6, PAD.PARTICIPANTGENERICATTRIBUTE7,
                PAD.PARTICIPANTGENERICATTRIBUTE8, PAD.PARTICIPANTGENERICATTRIBUTE9, PAD.PARTICIPANTGENERICATTRIBUTE10, PAD.PARTICIPANTGENERICATTRIBUTE11,
                PAD.PARTICIPANTGENERICATTRIBUTE12, PAD.PARTICIPANTGENERICATTRIBUTE13, PAD.PARTICIPANTGENERICATTRIBUTE14, PAD.PARTICIPANTGENERICATTRIBUTE15,
                PAD.PARTICIPANTGENERICATTRIBUTE16, PAD.PARTICIPANTGENERICNUMBER1, PAD.UTSFORPARTICIPANTGN1, PAD.PARTICIPANTGENERICNUMBER2,
                PAD.UTSFORPARTICIPANTGN2, PAD.PARTICIPANTGENERICNUMBER3, PAD.UTSFORPARTICIPANTGN3, PAD.PARTICIPANTGENERICNUMBER4, PAD.UTSFORPARTICIPANTGN4,
                PAD.PARTICIPANTGENERICNUMBER5, PAD.UTSFORPARTICIPANTGN5, PAD.PARTICIPANTGENERICNUMBER6, PAD.UTSFORPARTICIPANTGN6, PAD.PARTICIPANTGENERICDATE1,
                PAD.PARTICIPANTGENERICDATE2, PAD.PARTICIPANTGENERICDATE3, PAD.PARTICIPANTGENERICDATE4, PAD.PARTICIPANTGENERICDATE5, PAD.PARTICIPANTGENERICDATE6, 
                PAD.PARTICIPANTGENERICBOOLEAN1, PAD.PARTICIPANTGENERICBOOLEAN2, PAD.PARTICIPANTGENERICBOOLEAN3, PAD.PARTICIPANTGENERICBOOLEAN4,
                PAD.PARTICIPANTGENERICBOOLEAN5, PAD.PARTICIPANTGENERICBOOLEAN6, PAD.TITLEGENERICATTRIBUTE1, PAD.TITLEGENERICATTRIBUTE2, PAD.TITLEGENERICATTRIBUTE3,
                PAD.TITLEGENERICATTRIBUTE4, PAD.TITLEGENERICATTRIBUTE5, PAD.TITLEGENERICATTRIBUTE6, PAD.TITLEGENERICATTRIBUTE7, PAD.TITLEGENERICATTRIBUTE8,
                PAD.TITLEGENERICATTRIBUTE9, PAD.TITLEGENERICATTRIBUTE10, PAD.TITLEGENERICATTRIBUTE11, PAD.TITLEGENERICATTRIBUTE12, PAD.TITLEGENERICATTRIBUTE13,
                PAD.TITLEGENERICATTRIBUTE14, PAD.TITLEGENERICATTRIBUTE15, PAD.TITLEGENERICATTRIBUTE16, PAD.TITLEGENERICNUMBER1, PAD.UTSFORTITLEGN1,
                PAD.TITLEGENERICNUMBER2, PAD.UTSFORTITLEGN2, PAD.TITLEGENERICNUMBER3, PAD.UTSFORTITLEGN3, PAD.TITLEGENERICNUMBER4, PAD.UTSFORTITLEGN4,
                PAD.TITLEGENERICNUMBER5, PAD.UTSFORTITLEGN5, PAD.TITLEGENERICNUMBER6, PAD.UTSFORTITLEGN6, PAD.TITLEGENERICDATE1, PAD.TITLEGENERICDATE2,
                PAD.TITLEGENERICDATE3, PAD.TITLEGENERICDATE4, PAD.TITLEGENERICDATE5, PAD.TITLEGENERICDATE6, PAD.TITLEGENERICBOOLEAN1, PAD.TITLEGENERICBOOLEAN2,
                PAD.TITLEGENERICBOOLEAN3, PAD.TITLEGENERICBOOLEAN4, PAD.TITLEGENERICBOOLEAN5, PAD.TITLEGENERICBOOLEAN6, PAD.MANAGERSEQ, PAD.MANAGERFULLNAME,
                PAD.FULLNAMELEVEL_1, PAD.FULLNAMELEVEL_2, PAD.FULLNAMELEVEL_3, PAD.FULLNAMELEVEL_4, PAD.FULLNAMELEVEL_5, PAD.FULLNAMELEVEL_6, PAD.FULLNAMELEVEL_7,
                PAD.FULLNAMELEVEL_8, PAD.ISPAYEE, PAD.BOUSERID, PAD.ETLHISTORYKEY, PAD.ISRELEASEDFORRPT
            FROM TCMP.CSA_PADIMENSION PAD
            WHERE PAD.TENANTID = :v_idtenant AND PAD.ISPAYEE = 1 AND PAD.POSITIONGENERICNUMBER2 IS NULL 
                AND PAD.PERIODSEQ = :i_PeriodSeq;
		
		v_num_rows := RECORD_COUNT(:TBL_OFICINAS_MES);

		CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'TBL_OFICINAS_MES creada. Filas: ' || v_num_rows, i_log_count, i_id_proceso, 'debug');

		-- Revisamos si se debe detener el proceso
		call EXT.LIB_CREAR_TABLAS:w_stop(:v_stop);
		IF v_stop = 0 THEN
			CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'CONTROL PARA NO EJECUTAR EL PROCESO. REVISAR CLASIFICACION!!!!!!!' , i_log_count, i_id_proceso, 'warning');    	
			RETURN;
		END IF;

		---------------------------------------------------------------------------------------------------------------------------------
		-- BRG 20250522: Tabla temporal INYC_AGENTES_MES_TEMP pasa a ser TBL_AGENTES_MES
		TBL_AGENTES_MES = SELECT PAD.TENANTID, PAD.PERIODSEQ, PAD.POSITIONSEQ, PAD.PARTICIPANTSEQ, PAD.PARTICIPANTID, PAD.USERID, PAD.PREFIX, PAD.FIRSTNAME, PAD.MIDDLENAME, 
                PAD.LASTNAME, PAD.SUFFIX, PAD.FULLNAME, PAD.TAXID, PAD.SALARY, PAD.UTSFORSALARY, PAD.HIREDATE, PAD.TERMINATIONDATE, PAD.BUSINESSUNITMAP,
                PAD.POSITIONNAME, PAD.POSITIONDESCRIPTION, PAD.TITLENAME, PAD.TITLEDESCRIPTION, PAD.TARGETCOMPENSATION, PAD.UTSFORTARGETCOMPENSATION, PAD.PLANNAME,
                PAD.PLANSEQ, PAD.PROCESSINGUNITNAME, PAD.PROCESSINGUNITSEQ, PAD.POSITIONGENERICATTRIBUTE1, PAD.POSITIONGENERICATTRIBUTE2,
                PAD.POSITIONGENERICATTRIBUTE3, PAD.POSITIONGENERICATTRIBUTE4, PAD.POSITIONGENERICATTRIBUTE5, PAD.POSITIONGENERICATTRIBUTE6,
                PAD.POSITIONGENERICATTRIBUTE7, PAD.POSITIONGENERICATTRIBUTE8, PAD.POSITIONGENERICATTRIBUTE9, PAD.POSITIONGENERICATTRIBUTE10,
                PAD.POSITIONGENERICATTRIBUTE11, PAD.POSITIONGENERICATTRIBUTE12, PAD.POSITIONGENERICATTRIBUTE13, PAD.POSITIONGENERICATTRIBUTE14,
                PAD.POSITIONGENERICATTRIBUTE15, PAD.POSITIONGENERICATTRIBUTE16, PAD.POSITIONGENERICNUMBER1, PAD.UTSFORPOSITIONGN1, PAD.POSITIONGENERICNUMBER2,
                PAD.UTSFORPOSITIONGN2, PAD.POSITIONGENERICNUMBER3, PAD.UTSFORPOSITIONGN3, PAD.POSITIONGENERICNUMBER4, PAD.UTSFORPOSITIONGN4,
                PAD.POSITIONGENERICNUMBER5, PAD.UTSFORPOSITIONGN5, PAD.POSITIONGENERICNUMBER6, PAD.UTSFORPOSITIONGN6, PAD.POSITIONGENERICDATE1,
                PAD.POSITIONGENERICDATE2, PAD.POSITIONGENERICDATE3, PAD.POSITIONGENERICDATE4, PAD.POSITIONGENERICDATE5, PAD.POSITIONGENERICDATE6,
                PAD.POSITIONGENERICBOOLEAN1, PAD.POSITIONGENERICBOOLEAN2, PAD.POSITIONGENERICBOOLEAN3, PAD.POSITIONGENERICBOOLEAN4, PAD.POSITIONGENERICBOOLEAN5,
                PAD.POSITIONGENERICBOOLEAN6, PAD.PARTICIPANTGENERICATTRIBUTE1, PAD.PARTICIPANTGENERICATTRIBUTE2, PAD.PARTICIPANTGENERICATTRIBUTE3,
                PAD.PARTICIPANTGENERICATTRIBUTE4, PAD.PARTICIPANTGENERICATTRIBUTE5, PAD.PARTICIPANTGENERICATTRIBUTE6, PAD.PARTICIPANTGENERICATTRIBUTE7,
                PAD.PARTICIPANTGENERICATTRIBUTE8, PAD.PARTICIPANTGENERICATTRIBUTE9, PAD.PARTICIPANTGENERICATTRIBUTE10, PAD.PARTICIPANTGENERICATTRIBUTE11,
                PAD.PARTICIPANTGENERICATTRIBUTE12, PAD.PARTICIPANTGENERICATTRIBUTE13, PAD.PARTICIPANTGENERICATTRIBUTE14, PAD.PARTICIPANTGENERICATTRIBUTE15,
                PAD.PARTICIPANTGENERICATTRIBUTE16, PAD.PARTICIPANTGENERICNUMBER1, PAD.UTSFORPARTICIPANTGN1, PAD.PARTICIPANTGENERICNUMBER2,
                PAD.UTSFORPARTICIPANTGN2, PAD.PARTICIPANTGENERICNUMBER3, PAD.UTSFORPARTICIPANTGN3, PAD.PARTICIPANTGENERICNUMBER4, PAD.UTSFORPARTICIPANTGN4,
                PAD.PARTICIPANTGENERICNUMBER5, PAD.UTSFORPARTICIPANTGN5, PAD.PARTICIPANTGENERICNUMBER6, PAD.UTSFORPARTICIPANTGN6, PAD.PARTICIPANTGENERICDATE1,
                PAD.PARTICIPANTGENERICDATE2, PAD.PARTICIPANTGENERICDATE3, PAD.PARTICIPANTGENERICDATE4, PAD.PARTICIPANTGENERICDATE5, PAD.PARTICIPANTGENERICDATE6, 
                PAD.PARTICIPANTGENERICBOOLEAN1, PAD.PARTICIPANTGENERICBOOLEAN2, PAD.PARTICIPANTGENERICBOOLEAN3, PAD.PARTICIPANTGENERICBOOLEAN4,
                PAD.PARTICIPANTGENERICBOOLEAN5, PAD.PARTICIPANTGENERICBOOLEAN6, PAD.TITLEGENERICATTRIBUTE1, PAD.TITLEGENERICATTRIBUTE2, PAD.TITLEGENERICATTRIBUTE3,
                PAD.TITLEGENERICATTRIBUTE4, PAD.TITLEGENERICATTRIBUTE5, PAD.TITLEGENERICATTRIBUTE6, PAD.TITLEGENERICATTRIBUTE7, PAD.TITLEGENERICATTRIBUTE8,
                PAD.TITLEGENERICATTRIBUTE9, PAD.TITLEGENERICATTRIBUTE10, PAD.TITLEGENERICATTRIBUTE11, PAD.TITLEGENERICATTRIBUTE12, PAD.TITLEGENERICATTRIBUTE13,
                PAD.TITLEGENERICATTRIBUTE14, PAD.TITLEGENERICATTRIBUTE15, PAD.TITLEGENERICATTRIBUTE16, PAD.TITLEGENERICNUMBER1, PAD.UTSFORTITLEGN1,
                PAD.TITLEGENERICNUMBER2, PAD.UTSFORTITLEGN2, PAD.TITLEGENERICNUMBER3, PAD.UTSFORTITLEGN3, PAD.TITLEGENERICNUMBER4, PAD.UTSFORTITLEGN4,
                PAD.TITLEGENERICNUMBER5, PAD.UTSFORTITLEGN5, PAD.TITLEGENERICNUMBER6, PAD.UTSFORTITLEGN6, PAD.TITLEGENERICDATE1, PAD.TITLEGENERICDATE2,
                PAD.TITLEGENERICDATE3, PAD.TITLEGENERICDATE4, PAD.TITLEGENERICDATE5, PAD.TITLEGENERICDATE6, PAD.TITLEGENERICBOOLEAN1, PAD.TITLEGENERICBOOLEAN2,
                PAD.TITLEGENERICBOOLEAN3, PAD.TITLEGENERICBOOLEAN4, PAD.TITLEGENERICBOOLEAN5, PAD.TITLEGENERICBOOLEAN6, PAD.MANAGERSEQ, PAD.MANAGERFULLNAME,
                PAD.FULLNAMELEVEL_1, PAD.FULLNAMELEVEL_2, PAD.FULLNAMELEVEL_3, PAD.FULLNAMELEVEL_4, PAD.FULLNAMELEVEL_5, PAD.FULLNAMELEVEL_6, PAD.FULLNAMELEVEL_7,
                PAD.FULLNAMELEVEL_8, PAD.ISPAYEE, PAD.BOUSERID, PAD.ETLHISTORYKEY, PAD.ISRELEASEDFORRPT, PAD.MANAGERPARTICIPANTSEQ
            FROM TCMP.CSA_PADIMENSION PAD
            WHERE PAD.TENANTID = :v_idtenant AND PAD.ISPAYEE = 1
                --ALM 20170925: No filtrmaos por TerminationDate nula sino porque sea mayor que el periodo actual o nula 
                --AND PAD.TERMINATIONDATE IS NULL
                AND (PAD.TERMINATIONDATE IS NULL OR PAD.TERMINATIONDATE >= :v_period_enddate)
                --ALM 20170711: Quitamos las Position sin Plan, ya que no aportan calculos
                AND PAD.TITLENAME <> 'TTL SIN PLAN'
                AND PAD.PERIODSEQ = :i_PeriodSeq;
		
		v_num_rows := RECORD_COUNT(:TBL_AGENTES_MES);

		CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'TBL_AGENTES_MES creada. Filas: ' || v_num_rows, i_log_count, i_id_proceso, 'debug');

		-- Revisamos si se debe detener el proceso
		call EXT.LIB_CREAR_TABLAS:w_stop(:v_stop);
		IF v_stop = 0 THEN
			CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'CONTROL PARA NO EJECUTAR EL PROCESO. REVISAR CLASIFICACION!!!!!!!' , i_log_count, i_id_proceso, 'warning');    	
			RETURN;
		END IF;

		---------------------------------------------------------------------------------------------------------------------------------
		-- BRG 20250522: Tabla temporal INYC_AGENTES_PRIN_MES_TEMP pasa a ser TBL_AGENTES_PRIN_MES
		
		TBL_POSITION_RELATION_CR = SELECT PR.PARENTPOSITIONSEQ,PR.CHILDPOSITIONSEQ,PR.EFFECTIVESTARTDATE,PR.EFFECTIVEENDDATE 
			FROM TCMP.CS_POSITIONRELATION PR
			INNER JOIN TCMP.CS_POSITIONRELATIONTYPE PRT ON PR.POSITIONRELATIONTYPESEQ=PRT.DATATYPESEQ 
				AND PRT.REMOVEDATE = :v_eot
				AND PRT.NAME = 'Contract Rollup'
				AND PRT.TENANTID = :v_idtenant
			WHERE PR.REMOVEDATE = :v_eot
				AND PR.TENANTID = :v_idtenant;
		
		TBL_AGENTES_PRIN_MES = SELECT DISTINCT 
                --ALM 20161201: Anadimos los campos de la tabla de PERIODOS que se utilizan en los diferentes informes
                PD.YEAR,PD.QUARTER,
                PD.NAME AS PERIODO,
                PD.STARTDATE,
                PD.PERIODSEQ,
                CASE WHEN P.RULEELEMENTOWNERSEQ IS NULL THEN PAD_INS.POSITIONSEQ ELSE P.RULEELEMENTOWNERSEQ END AS POSITIONSEQ_PRIN,
                PAD_INS.POSITIONSEQ,
                PAD_INS.PARTICIPANTSEQ,
                PAD_INS.BOUSERID,
                --ALM 20160404: MODIFICACIoN PARA EL CAMBIO AL CoDIGO uNICO
                PAD_INS.POSITIONNAME AS POS_CALLIDUS,
                PAD_INS.POSITIONGENERICATTRIBUTE3 AS POSITIONNAME,
                PAD_INS.FIRSTNAME,
                PAD_INS.LASTNAME,
                PAD_INS.SUFFIX,
                PAD_INS.TAXID,
                --ALM 20170512: Anadimos todos los campos existentes del Participant y la Position
                PAD_INS.HIREDATE,
                PAD_INS.TERMINATIONDATE,
                PAD_INS.PARTICIPANTGENERICATTRIBUTE1 AS NIF,
                PAD_INS.PARTICIPANTGENERICATTRIBUTE2 AS TIPO_DOCUMENTO,
                PAD_INS.PARTICIPANTGENERICATTRIBUTE3 AS TIPO_PERSONA,
                PAD_INS.PARTICIPANTGENERICATTRIBUTE4 AS COD_DGS,
                PAD_INS.PARTICIPANTGENERICATTRIBUTE5 AS CIA_EMPLEADO,
                PAD_INS.PARTICIPANTGENERICATTRIBUTE6 AS TIPO_MEDIADOR_OCASO,
                PAD_INS.PARTICIPANTGENERICATTRIBUTE7 AS MUNICIPIO,
                PAD_INS.PARTICIPANTGENERICATTRIBUTE8 AS TIPO_VIA,
                PAD_INS.PARTICIPANTGENERICATTRIBUTE9 AS DOMICILIO,
                PAD_INS.PARTICIPANTGENERICATTRIBUTE10 AS NUMERO,
                PAD_INS.PARTICIPANTGENERICATTRIBUTE11 AS RESTO_DOMICILIO,   
                PAD_INS.PARTICIPANTGENERICATTRIBUTE12 AS SEXO,
                PAD_INS.PARTICIPANTGENERICATTRIBUTE13 AS ESTADO_CIVIL,
                PAD_INS.PARTICIPANTGENERICATTRIBUTE14 AS TELEFONO_FIJO,
                PAD_INS.PARTICIPANTGENERICATTRIBUTE15 AS TELEFONO_MOVIL,
                PAD_INS.PARTICIPANTGENERICATTRIBUTE16 AS IBAN,
                PAD_INS.PARTICIPANTGENERICNUMBER1 AS CP,
                PAD_INS.PARTICIPANTGENERICNUMBER2 AS COD_PROVINCIA,
                PAD_INS.PARTICIPANTGENERICNUMBER3 AS COD_MUNICIPIO,
                PAD_INS.PARTICIPANTGENERICNUMBER4 AS ID_EMPLEADO,
                PAD_INS.PARTICIPANTGENERICNUMBER5 AS IRPF_EMPLEADO,
                PAD_INS.PARTICIPANTGENERICNUMBER6 AS FAX,
                PAD_INS.PARTICIPANTGENERICDATE1 AS FEC_NACIMIENTO,
                PAD_INS.PARTICIPANTGENERICDATE2 AS FEC_REG_DGS,
                PAD_INS.PARTICIPANTGENERICDATE3 AS FEC_ENVIO_DGS,
                PAD_INS.PARTICIPANTGENERICDATE4 AS FEC_FIN_CIASE,
                PAD_INS.PARTICIPANTGENERICDATE5 AS FEC_EFECTO_SUPERRAPEL,
                PAD_INS.PARTICIPANTGENERICDATE6 AS FEC_REGULA_SUPERRAPEL,
                PAD_INS.PARTICIPANTGENERICBOOLEAN1 AS AUTOLIQUIDA,
                PAD_INS.PARTICIPANTGENERICBOOLEAN2 AS CORREDOR,
                PAD_INS.PARTICIPANTGENERICBOOLEAN3 AS PROPIEDAD,
                PAD_INS.PARTICIPANTGENERICBOOLEAN4 AS SUPERRAPEL,
                PAD_INS.PARTICIPANTGENERICBOOLEAN5 AS COMIS_ANUAL_RRPP,
                PAD_INS.PARTICIPANTGENERICBOOLEAN6 AS PAGO_POR_IBAN,
                --ALM 20160315: MODIFICACIoN PARA EL CAMBIO AL CoDIGO uNICO
                CASE WHEN P.NAME IS NULL THEN PAD_INS.POSITIONGENERICATTRIBUTE1 ELSE P.GENERICATTRIBUTE1 END AS TIPO_PRIN_AGENTE,
                CASE WHEN P.NAME IS NULL THEN PAD_INS.POSITIONGENERICATTRIBUTE2 ELSE P.GENERICATTRIBUTE2 END AS TIPO_AGENTE,
                CASE WHEN P.NAME IS NULL THEN PAD_INS.POSITIONGENERICATTRIBUTE3 ELSE P.GENERICATTRIBUTE3 END AS POS_PRIN,
                CASE WHEN P.NAME IS NULL THEN PAD_INS.POSITIONGENERICATTRIBUTE5 ELSE P.GENERICATTRIBUTE5 END AS CUADRO_INSP_OCASO,
                CASE WHEN P.NAME IS NULL THEN PAD_INS.POSITIONGENERICATTRIBUTE6 ELSE P.GENERICATTRIBUTE6 END AS CUADRO_RRGG_OCASO,
                CASE WHEN P.NAME IS NULL THEN PAD_INS.POSITIONGENERICATTRIBUTE7 ELSE P.GENERICATTRIBUTE7 END AS CUADRO_RRTT_OCASO,
                CASE WHEN P.NAME IS NULL THEN PAD_INS.POSITIONGENERICATTRIBUTE8 ELSE P.GENERICATTRIBUTE8 END AS CIA_POS,
                CASE WHEN P.NAME IS NULL THEN PAD_INS.POSITIONGENERICATTRIBUTE9 ELSE P.GENERICATTRIBUTE9 END AS PROMOCION,
                CASE WHEN P.NAME IS NULL THEN PAD_INS.POSITIONGENERICATTRIBUTE10 ELSE P.GENERICATTRIBUTE10 END AS CUADRO_INSP_ETERNA,
                CASE WHEN P.NAME IS NULL THEN PAD_INS.POSITIONGENERICATTRIBUTE11 ELSE P.GENERICATTRIBUTE11 END AS CUADRO_RRGG_ETERNA,
                CASE WHEN P.NAME IS NULL THEN PAD_INS.POSITIONGENERICATTRIBUTE12 ELSE P.GENERICATTRIBUTE12 END AS CUADRO_RRTT_ETERNA,
                CASE WHEN P.NAME IS NULL THEN PAD_INS.POSITIONGENERICATTRIBUTE13 ELSE P.GENERICATTRIBUTE13 END AS ANIO_CAPTACION,
                CASE WHEN P.NAME IS NULL THEN PAD_INS.POSITIONGENERICATTRIBUTE14 ELSE P.GENERICATTRIBUTE14 END AS INSP_CAPTACION,
                CASE WHEN P.NAME IS NULL THEN PAD_INS.POSITIONGENERICATTRIBUTE15 ELSE P.GENERICATTRIBUTE15 END AS NUM_MESES_PREPLAN,
                CASE WHEN P.NAME IS NULL THEN PAD_INS.POSITIONGENERICATTRIBUTE16 ELSE P.GENERICATTRIBUTE16 END AS ESCALADO,
                CASE WHEN P.NAME IS NULL THEN PAD_INS.POSITIONGENERICNUMBER1 ELSE P.GENERICNUMBER1 END AS ID_TIPO_PRIN_AGENTE,
                CASE WHEN P.NAME IS NULL THEN PAD_INS.POSITIONGENERICNUMBER2 ELSE P.GENERICNUMBER2 END AS ID_TIPO_AGENTE,
                CASE WHEN P.NAME IS NULL THEN PAD_INS.POSITIONGENERICNUMBER3 ELSE P.GENERICNUMBER3 END AS ID_CLASE_OFICINA,
                CASE WHEN P.NAME IS NULL THEN PAD_INS.POSITIONGENERICNUMBER4 ELSE P.GENERICNUMBER4 END AS ID_TIPO_OFICINA,
                CASE WHEN P.NAME IS NULL THEN PAD_INS.POSITIONGENERICNUMBER5 ELSE P.GENERICNUMBER5 END AS PORC_COMIS_CARTERA,
                CASE WHEN P.NAME IS NULL THEN PAD_INS.POSITIONGENERICNUMBER6 ELSE P.GENERICNUMBER6 END AS IMP_COMIS_CARTERA,
                CASE WHEN P.NAME IS NULL THEN PAD_INS.POSITIONGENERICDATE1 ELSE P.GENERICDATE1 END AS FEC_ALTA_POS,
                CASE WHEN P.NAME IS NULL THEN PAD_INS.POSITIONGENERICDATE2 ELSE P.GENERICDATE2 END AS FEC_BAJA_POS,
                CASE WHEN P.NAME IS NULL THEN PAD_INS.POSITIONGENERICDATE3 ELSE P.GENERICDATE3 END AS FEC_INI_CONS_PC,
                CASE WHEN P.NAME IS NULL THEN PAD_INS.POSITIONGENERICDATE4 ELSE P.GENERICDATE4 END AS FEC_FIN_CONS_PC,
                CASE WHEN P.NAME IS NULL THEN PAD_INS.POSITIONGENERICDATE5 ELSE P.GENERICDATE5 END AS FEC_INI_ASIS,
                CASE WHEN P.NAME IS NULL THEN PAD_INS.POSITIONGENERICDATE6 ELSE P.GENERICDATE6 END AS FEC_LIM_COMIS,
                CASE WHEN P.NAME IS NULL THEN PAD_INS.POSITIONGENERICBOOLEAN1 ELSE P.GENERICBOOLEAN1 END AS REDUCCION,
                CASE WHEN P.NAME IS NULL THEN PAD_INS.POSITIONGENERICBOOLEAN2 ELSE P.GENERICBOOLEAN2 END AS PRODUCTOR_OCASO,
                CASE WHEN P.NAME IS NULL THEN PAD_INS.POSITIONGENERICBOOLEAN3 ELSE P.GENERICBOOLEAN3 END AS CONSOLIDA,
                CASE WHEN P.NAME IS NULL THEN PAD_INS.POSITIONGENERICBOOLEAN4 ELSE P.GENERICBOOLEAN4 END AS INI_AGENTE_ASIS,
                CASE WHEN P.NAME IS NULL THEN PAD_INS.POSITIONGENERICBOOLEAN5 ELSE P.GENERICBOOLEAN5 END AS PRODUCTOR_ETERNA,
                --ALM 20180613: Anadimos campos para poder unir por Manager y incluir sus campos en la tabla INYC_JERARQUIA
                CASE WHEN P.NAME IS NULL THEN PAD_INS.MANAGERSEQ ELSE P.MANAGERSEQ END AS MANAGERSEQ_PRIN,
                PAD_INS.MANAGERSEQ AS MANAGERSEQ
            FROM :TBL_AGENTES_MES PAD_INS
            INNER JOIN TCMP.CSA_PERIODDIMENSION PD ON PAD_INS.PERIODSEQ = PD.PERIODSEQ
                AND PD.TENANTID = :v_idtenant
            LEFT OUTER JOIN :TBL_POSITION_RELATION_CR PR ON PAD_INS.POSITIONSEQ = PR.CHILDPOSITIONSEQ 
                AND PR.EFFECTIVESTARTDATE < PD.ENDDATE AND PR.EFFECTIVEENDDATE >= PD.ENDDATE
            LEFT OUTER JOIN TCMP.CS_POSITION P ON PR.PARENTPOSITIONSEQ = P.RULEELEMENTOWNERSEQ
                AND P.REMOVEDATE = :v_eot
                AND P.EFFECTIVESTARTDATE <= PD.STARTDATE AND P.EFFECTIVEENDDATE > PD.STARTDATE 
                AND P.TENANTID = :v_idtenant
            WHERE PD.PERIODSEQ = :i_PeriodSeq;

		v_num_rows := RECORD_COUNT(:TBL_AGENTES_PRIN_MES);

		CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'TBL_AGENTES_PRIN_MES creada. Filas: ' || v_num_rows, i_log_count, i_id_proceso, 'debug');

		-- Revisamos si se debe detener el proceso
		call EXT.LIB_CREAR_TABLAS:w_stop(:v_stop);
		IF v_stop = 0 THEN
			CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'CONTROL PARA NO EJECUTAR EL PROCESO. REVISAR CLASIFICACION!!!!!!!' , i_log_count, i_id_proceso, 'warning');    	
			RETURN;
		END IF;
		
	-------------------------------------------------------------------------------------------------------------------------------------
    -- INICIO TABLAS DE INFORMES
	------------------------------------------------------------------------------------------------------------------------------------
		-- BRG 20250522: Tabla INYC_JERARQUIA pasa a ser TEST_OUT_JERARQUIA_REP
		CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'Inicio Borrado TEST_OUT_JERARQUIA_REP', i_log_count, i_id_proceso, 'debug');

		DELETE FROM EXT.TEST_OUT_JERARQUIA_REP WHERE PERIODSEQ = :i_PeriodSeq;

		v_num_rows := ::ROWCOUNT;

		CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'Fin Borrado TEST_OUT_JERARQUIA_REP. Filas borradas: ' || v_num_rows, i_log_count, i_id_proceso, 'debug');

		CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'Inicio Carga TEST_OUT_JERARQUIA_REP', i_log_count, i_id_proceso, 'debug');

		INSERT INTO EXT.TEST_OUT_JERARQUIA_REP
			SELECT
				CASE 
                    WHEN PAD_PTO_VENTA.POSITIONGENERICNUMBER3 IN (5) 
                        THEN PAD_REG.POSITIONNAME
                    WHEN PAD_PTO_VENTA.POSITIONGENERICNUMBER3 IN (4,7) 
                        THEN PAD_SUC.POSITIONNAME
                    WHEN PAD_PTO_VENTA.POSITIONGENERICNUMBER3 IN (3,6,8,10) 
                        THEN PAD_OF.POSITIONNAME
                    ELSE PAD_PTO_VENTA.POSITIONNAME 
                    END AS COD_REGIONAL,
                CASE 
                    WHEN PAD_PTO_VENTA.POSITIONGENERICNUMBER3 IN (5) 
                        THEN PAD_REG.LASTNAME
                    WHEN PAD_PTO_VENTA.POSITIONGENERICNUMBER3 IN (4,7) 
                        THEN PAD_SUC.LASTNAME
                    WHEN PAD_PTO_VENTA.POSITIONGENERICNUMBER3 IN (3,6,8,10) 
                        THEN PAD_OF.LASTNAME
                    ELSE PAD_PTO_VENTA.LASTNAME
                    END AS REGIONAL,
				CASE 
                    WHEN PAD_PTO_VENTA.POSITIONGENERICNUMBER3 IN (5) 
						THEN PAD_SUC.POSITIONNAME
                    WHEN PAD_PTO_VENTA.POSITIONGENERICNUMBER3 IN (4,7) 
						THEN PAD_OF.POSITIONNAME
                    ELSE PAD_PTO_VENTA.POSITIONNAME 
					END AS COD_SUCURSAL,
				CASE 
					WHEN PAD_PTO_VENTA.POSITIONGENERICNUMBER3 IN (5) 
						THEN PAD_SUC.LASTNAME
                    WHEN PAD_PTO_VENTA.POSITIONGENERICNUMBER3 IN (4,7) 
						THEN PAD_OF.LASTNAME
                    ELSE PAD_PTO_VENTA.LASTNAME 
					END AS SUCURSAL,
				CASE 
					WHEN PAD_PTO_VENTA.POSITIONGENERICNUMBER3 IN (5) 
						THEN PAD_OF.POSITIONNAME  
                    ELSE PAD_PTO_VENTA.POSITIONNAME 
					END AS COD_OFICINA,
				CASE 
					WHEN PAD_PTO_VENTA.POSITIONGENERICNUMBER3 IN (5) 
						THEN PAD_OF.LASTNAME  
                    ELSE PAD_PTO_VENTA.LASTNAME 
					END AS OFICINA,
				PAD_INS.YEAR, PAD_INS.QUARTER, PAD_INS.PERIODO, PAD_INS.STARTDATE,
                PAD_INS.PERIODSEQ, PAD_INS.POSITIONSEQ_PRIN, PAD_INS.POSITIONSEQ, PAD_INS.PARTICIPANTSEQ, PAD_INS.BOUSERID,
                PAD_INS.POS_PRIN, PAD_INS.POS_CALLIDUS, PAD_INS.POSITIONNAME, PAD_INS.NIF,
                RTRIM(PAD_INS.FIRSTNAME) || ' ' || RTRIM(PAD_INS.LASTNAME) || ' ' || RTRIM(PAD_INS.SUFFIX) AS NOMBRE,
                PAD_INS.TIPO_PERSONA, PAD_INS.TAXID, PAD_INS.MUNICIPIO, PAD_INS.DOMICILIO,   
                PAD_INS.CP, PAD_INS.ID_EMPLEADO AS ID_EMPLEADO, 
				PAD_INS.IRPF_EMPLEADO, PAD_INS.CIA_EMPLEADO,
                PAD_INS.ID_TIPO_AGENTE, PAD_INS.TIPO_AGENTE, PAD_INS.CUADRO_INSP_OCASO, PAD_INS.CUADRO_INSP_ETERNA,
                PAD_INS.CUADRO_RRGG_OCASO, PAD_INS.CUADRO_RRTT_OCASO, PAD_INS.CUADRO_RRGG_ETERNA, PAD_INS.CUADRO_RRTT_ETERNA,
                PAD_INS.PROMOCION, PAD_INS.SUPERRAPEL, PAD_INS.ESCALADO, PAD_INS.FEC_BAJA_POS, PAD_INS.FEC_ALTA_POS,
                --ALM 20180613: Anadimos campos del Manager para el nuevo informe 1.12.1 Produccion Agentes por Meses
                MANAGER.POS_PRIN AS MANAGER_POS_PRIN, MANAGER.POS_CALLIDUS AS MANAGER_POS_CALLIDUS, MANAGER.POSITIONNAME AS MANAGER_POSITIONNAME, MANAGER.NIF AS MANAGER_NIF,
                RTRIM(MANAGER.FIRSTNAME) || ' ' || RTRIM(MANAGER.LASTNAME) || ' ' || RTRIM(MANAGER.SUFFIX) AS MANAGER_NOMBRE,
                MANAGER.ID_TIPO_AGENTE AS MANAGER_ID_TIPO_AGENTE, MANAGER.TIPO_AGENTE AS MANAGER_TIPO_AGENTE,
                MANAGER.CUADRO_INSP_OCASO AS MANAGER_CUADRO_INSP_OCASO, MANAGER.CUADRO_INSP_ETERNA AS MANAGER_CUADRO_INSP_ETERNA,
                MANAGER.FEC_BAJA_POS AS MANAGER_FEC_BAJA_POS, MANAGER.FEC_ALTA_POS AS MANAGER_FEC_ALTA_POS,
				(SELECT IFNULL(MAX(POS_ANT.EFFECTIVEENDDATE), MIN(POS_ACT.EFFECTIVESTARTDATE))
				FROM TCMP.CS_POSITION POS_ACT
				--ALM 20170510: Tenemos que tener en cuenta cualquier cambio de tipologia no solo el paso de agente a inspector
				LEFT JOIN TCMP.CS_POSITION POS_ANT ON POS_ACT.PAYEESEQ = POS_ANT.PAYEESEQ
					--ALM 20170519: Tenemos en cuenta todas las versiones anteriores porque puede que venga de una tipologia que no sea inspector
					AND POS_ACT.EFFECTIVESTARTDATE >= POS_ANT.EFFECTIVEENDDATE
					--ATV 20240228 Los cuadros A, D y N se reagrupan en el cuadro P, la modificacion se debe a que no se debe tener en cuenta que ha habido un cambio de categoria y asi puedan acumular
					AND (REPLACE(REPLACE(REPLACE(POS_ACT.GENERICATTRIBUTE5, 'A', 'P'), 'D', 'P'), 'N', 'P') <> REPLACE(REPLACE(REPLACE(POS_ANT.GENERICATTRIBUTE5, 'A', 'P'), 'D', 'P'), 'N', 'P') OR POS_ANT.GENERICATTRIBUTE5 IS NULL)
					AND POS_ANT.REMOVEDATE = :v_eot
				WHERE POS_ACT.REMOVEDATE = :v_eot
					--ALM 20170512: Filtramos las versiones de las posiciones con tipologia de agente con grupo/inspector/responsable
					AND POS_ACT.GENERICNUMBER2 >= 50
					AND POS_ACT.EFFECTIVESTARTDATE <= PAD_INS.STARTDATE
					AND POS_ACT.PAYEESEQ = PAD_INS.PARTICIPANTSEQ) AS FEC_ALTA_CAT_INS
            FROM :TBL_AGENTES_PRIN_MES PAD_INS
			LEFT OUTER JOIN :TBL_OFICINAS_MES PAD_PTO_VENTA ON PAD_INS.PERIODSEQ = PAD_PTO_VENTA.PERIODSEQ
                AND PAD_PTO_VENTA.POSITIONNAME = SUBSTR(PAD_INS.POS_PRIN,1,4)
			LEFT OUTER JOIN :TBL_OFICINAS_MES PAD_OF ON PAD_PTO_VENTA.PERIODSEQ = PAD_OF.PERIODSEQ
                AND PAD_OF.POSITIONSEQ = PAD_PTO_VENTA.MANAGERSEQ
			LEFT OUTER JOIN :TBL_OFICINAS_MES PAD_SUC ON PAD_INS.PERIODSEQ = PAD_SUC.PERIODSEQ
                AND PAD_SUC.POSITIONSEQ = PAD_OF.MANAGERSEQ
			LEFT OUTER JOIN :TBL_OFICINAS_MES PAD_REG ON PAD_INS.PERIODSEQ = PAD_REG.PERIODSEQ
                AND PAD_REG.POSITIONSEQ = PAD_SUC.MANAGERSEQ
			--ALM 20180613: Unimos por el Manager para poder extraer informacion de el para el nuevo informe 1.12.1 Produccion Agentes por Meses
            LEFT OUTER JOIN :TBL_AGENTES_PRIN_MES MANAGER ON PAD_INS.PERIODSEQ = MANAGER.PERIODSEQ 
                AND PAD_INS.MANAGERSEQ_PRIN = MANAGER.POSITIONSEQ_PRIN
			WHERE PAD_INS.POS_PRIN <> '0000000000';
		
		v_num_rows := ::ROWCOUNT;

		CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'Fin Carga TEST_OUT_JERARQUIA_REP. Filas: ' || v_num_rows, i_log_count, i_id_proceso, 'debug');

		-- Revisamos si se debe detener el proceso
		call EXT.LIB_CREAR_TABLAS:w_stop(:v_stop);
		IF v_stop = 0 THEN
			CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'CONTROL PARA NO EJECUTAR EL PROCESO. REVISAR CLASIFICACION!!!!!!!' , i_log_count, i_id_proceso, 'warning');    	
			RETURN;
		END IF;

		---------------------------------------------------------------------------------------------------------------------------------
		-- BRG 20250522: TABLAS PARA INFORME 1.11 PERCEPCION AGENTES
		-- BRG 20250522: Tabla INYC_PERC_AGENTES pasa a ser TEST_OUT_PERC_AGENTES_REP
		-- PENDIENTE!!: CREAR CLASIFICACIÓN PARA GENERAR LISTA DE INFORMES
		IF :i_lista_informes = 'PEAG' OR :i_lista_informes LIKE '%,PEAG,%' OR :i_lista_informes LIKE '%,PEAG'
			OR :i_lista_informes LIKE 'PEAG,%' OR :i_lista_informes = 'ALL' THEN

			CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'Inicio Borrado TEST_OUT_PERC_AGENTES_REP', i_log_count, i_id_proceso, 'debug');

			DELETE FROM EXT.TEST_OUT_PERC_AGENTES_REP WHERE PERIODSEQ = :i_PeriodSeq;

			v_num_rows := ::ROWCOUNT;

			CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'Fin Borrado TEST_OUT_PERC_AGENTES_REP. Filas borradas: ' || v_num_rows, i_log_count, i_id_proceso, 'debug');

			CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'Inicio Carga TEST_OUT_PERC_AGENTES_REP. Percepciones.', i_log_count, i_id_proceso, 'debug');

			INSERT INTO EXT.TEST_OUT_PERC_AGENTES_REP
				SELECT
					PAD_INS.YEAR,PAD_INS.QUARTER, PAD_INS.PERIODO, PAD_INS.STARTDATE, PAD_INS.PERIODSEQ,
					PAD_INS.NIF,
					PERC.DESCRIPCION AS PERCEPCION, D.VALUE AS IMP_PERCEPCION,
					(SELECT EXTRACT(MONTH FROM PD.STARTDATE) FROM TCMP.CS_PERIOD PD WHERE PD.PERIODSEQ = D.PERIODSEQ) AS MES_PERCEPCION,
					0 AS BALANCE, D.EARNINGCODEID, D.EARNINGGROUPID,
					PAD_INS.POSITIONSEQ_PRIN, PAD_INS.POSITIONSEQ, PAD_INS.PARTICIPANTSEQ,
					PAD_INS.POS_PRIN, PAD_INS.POS_CALLIDUS, PAD_INS.POSITIONNAME
				FROM :TBL_AGENTES_PRIN_MES PAD_INS
				INNER JOIN TCMP.CS_DEPOSIT D ON PAD_INS.POSITIONSEQ = D.POSITIONSEQ
					AND PAD_INS.PARTICIPANTSEQ = D.PAYEESEQ
					AND D.PERIODSEQ IN (
						SELECT P.PERIODSEQ
						FROM TCMP.CS_PERIOD P
						INNER JOIN TCMP.CS_PERIODTYPE PT ON P.PERIODTYPESEQ = PT.PERIODTYPESEQ
							AND PT.REMOVEDATE = :v_eot
							-- BRG 20250522: Filtramos por el tipo de periodo para quedarnos solo los meses
							AND PT.NAME = 'month'
							AND PT.TENANTID = :v_idtenant
						WHERE P.REMOVEDATE = :v_eot
							AND SUBSTR(P.NAME,-4) = SUBSTR(PAD_INS.PERIODO,-4)
							AND P.STARTDATE <= PAD_INS.STARTDATE
							AND P.TENANTID = :v_idtenant)
					AND D.TENANTID = :v_idtenant
					--ALM 20211025: Anadimos condicion para mejorar el rendimeinto de la consulta
					AND D.PROCESSINGUNITSEQ = 38280596832649217
					AND SUBSTR(D.EARNINGGROUPID,7,2) = '01'
					--ALM 20170309: A peticion de Alfonso filtramos por los depositos del S4
					AND SUBSTR(D.EARNINGGROUPID,4,2) = 'S4'
					--ALM 20170309: A peticion de Alfonso excluimos el concepto de pago 801 porque van despues del calculo del IRPF
					AND SUBSTR(D.EARNINGCODEID,1,3) <> '801'
				--ALM 20191008: Anadimos condicion para no coger posibles resultados de los MODELS
				INNER JOIN TCMP.CS_PLRUN PL ON D.PIPELINERUNSEQ = PL.PIPELINERUNSEQ AND PL.MODELSEQ = 0
				INNER JOIN :TBL_TABLA_PERCEPCIONES PERC ON D.NAME = PERC.DEPOSITO
					AND SUBSTR(D.EARNINGCODEID,1,3) = PERC.EARNINGCODE
					AND D.EARNINGGROUPID = PERC.EARNINGGROUP
				INNER JOIN EXT.CONF_AGENTES_REP AG ON PAD_INS.ID_TIPO_AGENTE = AG.ID_TIPO_AGENTE
					AND AG.COD_INFORME = 112
					AND AG.F_INICIO <= PAD_INS.STARTDATE AND  AG.F_FIN > PAD_INS.STARTDATE;
		
			v_num_rows := ::ROWCOUNT;

			CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'Fin Carga TEST_OUT_PERC_AGENTES_REP. Percepciones. Filas: ' || v_num_rows, i_log_count, i_id_proceso, 'debug');

			CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'Inicio Carga TEST_OUT_PERC_AGENTES_REP. Percepciones DDEE.', i_log_count, i_id_proceso, 'debug');

			INSERT INTO EXT.TEST_OUT_PERC_AGENTES_REP
				SELECT
					PAD_INS.YEAR,PAD_INS.QUARTER,PAD_INS.PERIODO,PAD_INS.STARTDATE,PAD_INS.PERIODSEQ,
					PAD_INS.NIF,
					'Comision DDEE' as PERCEPCION,
					SUM(CAR_LP.IMPORTE) AS IMP_PERCEPCION,
					EXTRACT(MONTH FROM PAD_INS.STARTDATE) AS MES_PERCEPCION,
					0 AS BALANCE,
					CAR_LP.EARNINGCODEID,CAR_LP.EARNINGGROUPID,
					PAD_INS.POSITIONSEQ_PRIN,PAD_INS.POSITIONSEQ,PAD_INS.PARTICIPANTSEQ,
					PAD_INS.POS_PRIN,PAD_INS.POS_CALLIDUS,PAD_INS.POSITIONNAME
				FROM :TBL_AGENTES_PRIN_MES PAD_INS
				INNER JOIN EXT.TEST_CARTERA_DDEE CAR_LP ON PAD_INS.POS_CALLIDUS = CAR_LP.POSITIONNAME AND PAD_INS.STARTDATE = CAR_LP.COMPENSATIONDATE
					AND (v_FV_EstadoTrx = 0 OR (v_FV_EstadoTrx = 1 AND CAR_LP.ESTADO = 'C'))
					--JGE 20230816 Solamente tiene que salir los 01 Ocaso
					AND SUBSTR(CAR_LP.EARNINGGROUPID,7,2) = '01'
					AND SUBSTR(CAR_LP.EARNINGGROUPID,4,2) = 'S4'
					AND SUBSTR(CAR_LP.EARNINGCODEID,1,3) <> '801'
					--ATV 20241218 No incluimos los registros con importe 0. Cambio debido a problemas en factura
					AND CAR_LP.IMPORTE <> 0
				GROUP BY
					PAD_INS.YEAR,PAD_INS.QUARTER,PAD_INS.PERIODO,PAD_INS.STARTDATE,PAD_INS.PERIODSEQ,
					PAD_INS.NIF,CAR_LP.EARNINGCODEID,CAR_LP.EARNINGGROUPID,
					PAD_INS.POSITIONSEQ_PRIN,PAD_INS.POSITIONSEQ,PAD_INS.PARTICIPANTSEQ,
					PAD_INS.POS_PRIN,PAD_INS.POS_CALLIDUS,PAD_INS.POSITIONNAME;

			v_num_rows := ::ROWCOUNT;

			CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'Fin Carga TEST_OUT_PERC_AGENTES_REP. Percepciones DDEE. Filas: ' || v_num_rows, i_log_count, i_id_proceso, 'debug');

			CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'Inicio Carga TEST_OUT_PERC_AGENTES_REP. Balances.', i_log_count, i_id_proceso, 'debug');

			INSERT INTO EXT.TEST_OUT_PERC_AGENTES_REP
				SELECT 
					PAD_INS.YEAR,PAD_INS.QUARTER, PAD_INS.PERIODO, PAD_INS.STARTDATE,PAD_INS.PERIODSEQ,
					PAD_INS.NIF,
					'Balance ' || (SELECT PER.NAME FROM TCMP.CS_PERIOD PER WHERE PER.REMOVEDATE = v_eot 
						AND PER.PERIODSEQ = B.PERIODSEQ) ||' - ' || INITCAP(EC.DESCRIPTION) AS PERCEPCION,
					B.VALUE AS IMP_PERCEPCION,
					EXTRACT(MONTH FROM PAD_INS.STARTDATE) AS MES_PERCEPCION,                
					1 AS BALANCE,B.EARNINGCODEID,B.EARNINGGROUPID,
					PAD_INS.POSITIONSEQ_PRIN,PAD_INS.POSITIONSEQ,PAD_INS.PARTICIPANTSEQ,
					PAD_INS.POS_PRIN,PAD_INS.POS_CALLIDUS,PAD_INS.POSITIONNAME
				FROM :TBL_AGENTES_PRIN_MES PAD_INS
				INNER JOIN TCMP.CS_BALANCE B ON PAD_INS.POSITIONSEQ = B.POSITIONSEQ
					AND PAD_INS.PARTICIPANTSEQ = B.PAYEESEQ
					AND B.POSTPIPELINERUNDATE < (SELECT PER.ENDDATE FROM TCMP.CS_PERIOD PER WHERE PER.REMOVEDATE = v_eot 
						AND PER.PERIODSEQ = PAD_INS.PERIODSEQ)
					AND B.POSTPIPELINERUNDATE > (SELECT PER.STARTDATE FROM TCMP.CS_PERIOD PER WHERE PER.REMOVEDATE = v_eot 
						AND PER.PERIODSEQ = PAD_INS.PERIODSEQ)
					AND B.TENANTID = :v_idtenant
					--ALM 20211025: Anadimos condicion para mejorar el rendimeinto de la consulta
					AND B.PROCESSINGUNITSEQ = 38280596832649217
					--AND D.VALUE <> 0
					AND SUBSTR(B.EARNINGGROUPID,7,2) = '01'
					--ALM 20170309: A peticion de Alfonso filtramos por los depositos del S4
					AND SUBSTR(B.EARNINGGROUPID,4,2) = 'S4'
					--ALM 20170309: A peticion de Alfonso excluimos el concepto de pago 801 porque van despues del calculo del IRPF
					AND SUBSTR(B.EARNINGCODEID,1,3) <> '801'
				--ALM 20191008: Anadimos condicion para no coger posibles resultados de los MODELS
				INNER JOIN TCMP.CS_PLRUN PL ON B.TRIALPIPELINERUNSEQ = PL.PIPELINERUNSEQ AND PL.MODELSEQ = 0
					--ALM 20211025: Anadimos condicion para mejorar el rendimeinto de la consulta
					AND PL.TENANTID = :v_idtenant AND PL.PROCESSINGUNITSEQ = 38280596832649217
				--ALM 20170609: Unimos los balances con los pagos para filtrar balances que finalmente no se abonen en el periodo
				INNER JOIN TCMP.CS_BALANCEPAYMENTTRACE BPAY ON B.BALANCESEQ = BPAY.BALANCESEQ
					--ALM 20211025: Anadimos condicion para mejorar el rendimiento de la consulta
					AND BPAY.TENANTID = :v_idtenant AND BPAY.PROCESSINGUNITSEQ = 38280596832649217
					AND BPAY.TARGETPERIODSEQ = :i_PeriodSeq
				--INNER JOIN INYCEXT.INYC_PAGOS_MES_TEMP PAY ON BPAY.PAYMENTSEQ = PAY.PAYMENTSEQ
				INNER JOIN TCMP.CS_EARNINGCODE EC ON (SUBSTR(B.EARNINGCODEID,1,1) || '00') = EC.EARNINGCODEID
					AND EC.TENANTID = :v_idtenant
					AND EC.REMOVEDATE = :v_eot;
			
			v_num_rows := ::ROWCOUNT;

			CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'Fin Carga TEST_OUT_PERC_AGENTES_REP. Balances. Filas: ' || v_num_rows, i_log_count, i_id_proceso, 'debug');

			CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'Inicio actualización de fecha en OUT_FECHAS_WEBI_REP', i_log_count, i_id_proceso, 'debug');

			CALL EXT.LIB_CREAR_TABLAS:UPDATE_FECHAS_WEBI(i_PeriodSeq, 'TEST_OUT_PERC_AGENTES_REP');

			CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'Fin actualización de fecha en OUT_FECHAS_WEBI_REP', i_log_count, i_id_proceso, 'debug');

			-- Revisamos si se debe detener el proceso
			call EXT.LIB_CREAR_TABLAS:w_stop(:v_stop);
			IF v_stop = 0 THEN
				CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'CONTROL PARA NO EJECUTAR EL PROCESO. REVISAR CLASIFICACION!!!!!!!' , i_log_count, i_id_proceso, 'warning');    	
				RETURN;
			END IF;
		
		-- Fin informe 1.11 Percepcion Agentes
		END IF;
		-------------------------------------------------------------------------------------------------------------------------------------
	
		-- DTB 20250522: TABLAS PARA INFORME 1.13 PERCEPCIONES INSPECTORES
		-- DTB 20250522: Tabla INYC_PERC_INSPECTORES pasa a ser OUT_PERC_INSPECTORES_REP

		-- FIN PROCEDIMIENTO	
		CALL EXT.LIB_CONSTANTES:WRITE_LOG(v_permisos_log,proc_name,'Fin procedure ' || proc_name, i_log_count, i_id_proceso, 'info');
		
	END;
END