DROP VIEW EXT.CSA_FECHAS_ACTUALIZACION_TABLAS_SVW;

CREATE OR REPLACE VIEW EXT.CSA_FECHAS_ACTUALIZACION_TABLAS_SVW (
	PERIODO, DESCRIPCION, ULTIMA_ACTUALIZACION, TABLA, ULTIMA_ACTUALIZACION_FORMATO
)
AS

SELECT PERIODO,
	DESCRIPCION,
	ULTIMA_ACTUALIZACION,
	TABLA,
	TO_VARCHAR(ULTIMA_ACTUALIZACION, 'DD/MM/YYYY') AS ULTIMA_ACTUALIZACION_FORMATO
FROM EXT.OUT_FECHAS_WEBI_REP