CREATE OR REPLACE VIEW "EXT"."CSA_ESTRUCTURA_COMERCIAL_CAPTACION_OLD_SVW" ( "ANYO", "FEC_ACTUALIZACION", "POSITIONSEQ", "IDREGIONAL", "IDSUCURSAL", "IDOFICINA", "PV", "CODIGO", "NIF", "NOMBRE", "EMAIL", "EMAIL_PERSONAL", "CUADRO", "INSPCAP_NIF", "INSPCAP", "TIPOLOGIA", "F_ALTA", "CARGO", "F_TIPO3", "F_BAJA", "PER_FORMAT", "IDTIPO", "MEDCOUNT" ) AS (
	WITH "ESTRUCTURA_OLD" AS (
		SELECT
            X.NAME as EPOS_NAME,X.RULEELEMENTOWNERSEQ as EPOSITIONSEQ,
            X.GENERICATTRIBUTE2 EPOS_GENERICATTRIBUTE2, X.GENERICATTRIBUTE3 AS EPOS_GENERICATTRIBUTE3,
            TO_INTEGER(X.GENERICNUMBER2) AS EPOS_GENERICNUMBER2, X.GENERICNUMBER3 AS EPOS_GENERICNUMBER3,
            IFNULL(RTRIM(Y.FIRSTNAME) || ' ','')  || IFNULL(RTRIM(Y.LASTNAME),'') || IFNULL(' ' || RTRIM(Y.SUFFIX), '') AS NOMBRE_COMPLETO, 
            Y.FIRSTNAME,Y.LASTNAME,Y.SUFFIX,Y.GENERICATTRIBUTE1 AS NIF, X.MANAGERSEQ as EPOS_MANAGERSEQ,
            Y.USERID as EPAR_USERID,
            Z.NAME AS ETITLE,
            X.EFFECTIVESTARTDATE as EPOS_EFFECTIVESTARTDATE, X.EFFECTIVEENDDATE as EPOS_EFFECTIVEENDDATE,
            Y.EFFECTIVESTARTDATE as EPAR_EFFECTIVESTARTDATE, Y.EFFECTIVEENDDATE as EPAR_EFFECTIVEENDDATE,
            Z.EFFECTIVESTARTDATE as ETIT_EFFECTIVESTARTDATE, Z.EFFECTIVEENDDATE as ETIT_EFFECTIVEENDDATE
        FROM TCMP.CS_POSITION X
        INNER JOIN TCMP.CS_PARTICIPANT Y ON Y.PAYEESEQ = X.PAYEESEQ and Y.REMOVEDATE = TO_DATE('22000101','yyyymmdd')  
            AND Y.EFFECTIVESTARTDATE <= TO_DATE((EXTRACT(YEAR FROM CURRENT_TIMESTAMP) - 1) || '-12-31','YYYY-MM-DD') and Y.EFFECTIVEENDDATE > '2025-12-31'
        INNER JOIN TCMP.CS_PAYEE R ON Y.PAYEESEQ = R.PAYEESEQ and R.REMOVEDATE = TO_DATE('22000101','yyyymmdd')
            AND R.EFFECTIVESTARTDATE <= '2025-12-31' and R.EFFECTIVEENDDATE > '2025-12-31'
        INNER JOIN TCMP.CS_TITLE Z ON X.TITLESEQ = Z.RULEELEMENTOWNERSEQ AND Z.REMOVEDATE = TO_DATE('22000101','yyyymmdd') 
            AND Z.EFFECTIVESTARTDATE <= '2025-12-31' and Z.EFFECTIVEENDDATE > '2025-12-31'
            where X.REMOVEDATE = TO_DATE('22000101','yyyymmdd')
	) 
	SELECT 
        TO_VARCHAR('2025-12-31', 'YYYY') AS ANYO,
        TO_VARCHAR('2025-12-31', 'DD/MM/YYYY') AS FEC_ACTUALIZACION,
        POS.RULEELEMENTOWNERSEQ as POSITIONSEQ,
        IFNULL( CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (5) THEN REG.EPOS_NAME
            ELSE CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (4,7) THEN SUC.EPOS_NAME
                ELSE CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (3,6,8,10,11) THEN OFI.EPOS_NAME
                    ELSE PTO_VENTA.EPOS_NAME END
            END END , ' ') as IDREGIONAL,
        IFNULL( CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (5) THEN SUC.EPOS_NAME
            ELSE CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (4,7) THEN OFI.EPOS_NAME
                ELSE PTO_VENTA.EPOS_NAME END 
            END , ' ' ) as IDSUCURSAL,                                                                                           --titleGenericAttribute2
        IFNULL( CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (5) THEN OFI.EPOS_NAME  
            ELSE PTO_VENTA.EPOS_NAME END, ' ') as IDOFICINA,
        IFNULL( LEFT(POS.GENERICATTRIBUTE3, 4), ' ') as PV, IFNULL( RIGHT(Pos.GENERICATTRIBUTE3, 4), ' ' ) as CODIGO,
        PAR.GENERICATTRIBUTE1 as NIF, -- Documento (GA1)
        IFNULL(RTRIM(PAR.FIRSTNAME) || ' ','')  || IFNULL(RTRIM(PAR.LASTNAME),'') || IFNULL(' ' || RTRIM(PAR.SUFFIX), '') AS NOMBRE, 
        IFNULL(PAR.PARTICIPANTEMAIL,' ') AS EMAIL, -- Correo electr�nico
        IFNULL(par.MIDDLENAME, ' ') AS EMAIL_PERSONAL, -- Email personal
        IFNULL(POS.GENERICATTRIBUTE6, ' ') as CUADRO, -- Cuadro RRGG Ocaso (GA6)
        IFNULL(INSP_CAP.NIF, ' ') as INSPCAP_NIF,
        IFNULL(INSP_CAP.EPOS_NAME, ' ') AS INSPCAP,
        FIRST_VALUE(TO_INTEGER(TIPO.POSITIONGENERICNUMBER2) || ' - ' || TIPO.POSITIONGENERICATTRIBUTE2) OVER (PARTITION BY POS.RULEELEMENTOWNERSEQ ORDER BY TIPO.STARTDATE) AS TIPOLOGIA,
        TO_VARCHAR(POS.GENERICDATE1, 'DD/MM/YYYY') AS F_ALTA,
        TO_VARCHAR((SELECT MIN(C.MAXDATE) FROM CS_RELATIONALMDLT A
                INNER JOIN CS_MDLTDIMENSION B ON A.RULEELEMENTSEQ = B.RULEELEMENTSEQ AND B.MODELSEQ = 0 AND B.REMOVEDATE = TO_DATE('22000101','yyyymmdd')
                INNER JOIN CS_MDLTINDEX C ON B.RULEELEMENTSEQ = C.RULEELEMENTSEQ AND B.DIMENSIONSEQ = C.DIMENSIONSEQ AND C.MODELSEQ = 0 AND C.REMOVEDATE = TO_DATE('22000101','yyyymmdd')
                WHERE A.REMOVEDATE = TO_DATE('22000101','yyyymmdd') AND A.NAME = 'MDLT-O-CargosProduccion' AND A.MODELSEQ = 0
                    AND C.MAXDATE > POS.GENERICDATE1
            ),'YYYYMM') AS CARGO,
        IFNULL(MIN(CASE WHEN TIPO.POSITIONGENERICNUMBER2 = 3
            THEN TO_VARCHAR(TIPO.STARTDATE, 'DD/MM/YYYY') 
            ELSE NULL END) OVER (PARTITION BY POS.RULEELEMENTOWNERSEQ), ' ') AS F_TIPO3,
        IFNULL(CASE WHEN POS.GENERICDATE2 = '2200-01-01' 
            THEN ' ' 
            ELSE TO_VARCHAR(POS.GENERICDATE2, 'DD/MM/YYYY') END, ' ') AS F_BAJA,
        TO_VARCHAR(TIPO.STARTDATE, 'YYYYMM') AS PER_FORMAT, 
        CASE WHEN (POS.GENERICDATE2 IS NULL OR TO_VARCHAR(TIPO.STARTDATE, 'YYYYMM') < TO_VARCHAR(POS.GENERICDATE2, 'YYYYMM'))
            THEN TO_INTEGER(TIPO.POSITIONGENERICNUMBER2)
            ELSE NULL END AS IDTIPO,
        1 as MEDCOUNT
    FROM CS_POSITION pos
    --JOIN pos_ids i
    --    ON pos.RULEELEMENTOWNERSEQ = i.RULEELEMENTOWNERSEQ and POS.REMOVEDATE = TO_DATE('22000101','yyyymmdd')
    INNER JOIN CS_PARTICIPANT PAR -- Se hace un JOIN con CS_PARTICIPANT a ultimo dia del mes de cada periodo para extraer: PAR.PARTICIPANTEMAIL, PAR.TAXID y fechas de efectividad por si quisieran filtrar por fecha concreta
        ON  PAR.PAYEESEQ = POS.PAYEESEQ and PAR.REMOVEDATE = TO_DATE('22000101','yyyymmdd')
        AND PAR.EFFECTIVESTARTDATE <=  '2025-12-31' and  PAR.EFFECTIVEENDDATE >  '2025-12-31'

    INNER JOIN TCMP.CS_PAYEE R ON PAR.PAYEESEQ = R.PAYEESEQ and R.REMOVEDATE = TO_DATE('22000101','yyyymmdd')
        AND R.EFFECTIVESTARTDATE <=  '2025-12-31'  and R.EFFECTIVEENDDATE >  '2025-12-31'

    INNER JOIN TCMP.CS_TITLE TIT ON  POS.TITLESEQ = TIT.RULEELEMENTOWNERSEQ  AND TIT.REMOVEDATE = TO_DATE('22000101','yyyymmdd') 
        AND TIT.EFFECTIVESTARTDATE <=  '2025-12-31'  and TIT.EFFECTIVEENDDATE >  '2025-12-31'
            
    -- MANAGER
    LEFT JOIN ESTRUCTURA_OLD MANAGER ON MANAGER.EPOSITIONSEQ = POS.MANAGERSEQ --PAD.MANAGERSEQ 
        AND MANAGER.EPOS_GENERICNUMBER2 is not null 
        AND MANAGER.EPOS_GENERICATTRIBUTE3 NOT IN ('0000000000','0') 
        AND MANAGER.EPOS_MANAGERSEQ IS NOT NULL
        AND MANAGER.EPOS_EFFECTIVESTARTDATE <= '2025-12-31' and  MANAGER.EPOS_EFFECTIVEENDDATE > '2025-12-31'
        AND MANAGER.EPAR_EFFECTIVESTARTDATE <=  '2025-12-31'  and  MANAGER.EPAR_EFFECTIVEENDDATE > '2025-12-31'  
        AND MANAGER.ETIT_EFFECTIVESTARTDATE <=  '2025-12-31'  and  MANAGER.ETIT_EFFECTIVEENDDATE > '2025-12-31'

    -- INSP_CAP      
    LEFT JOIN ESTRUCTURA_OLD INSP_CAP ON INSP_CAP.EPOS_NAME = POS.GENERICATTRIBUTE14  --PAD.POSITIONGENERICATTRIBUTE14
        AND INSP_CAP.EPOS_GENERICATTRIBUTE3 NOT IN ('0000000000','0') 
        AND INSP_CAP.EPOS_EFFECTIVESTARTDATE <= '2025-12-31' and  INSP_CAP.EPOS_EFFECTIVEENDDATE > '2025-12-31'
        AND INSP_CAP.EPAR_EFFECTIVESTARTDATE <=  '2025-12-31'  and  INSP_CAP.EPAR_EFFECTIVEENDDATE > '2025-12-31'  
        AND INSP_CAP.ETIT_EFFECTIVESTARTDATE <=  '2025-12-31'  and  INSP_CAP.ETIT_EFFECTIVEENDDATE > '2025-12-31'

    -- PTO_VENTA
    LEFT JOIN ESTRUCTURA_OLD PTO_VENTA ON SUBSTR(POS.GENERICATTRIBUTE3,1,4) = PTO_VENTA.EPOS_NAME --SUBSTR(PAD.POSITIONGENERICATTRIBUTE3,1,4) = PTO_VENTA.EPOS_NAME
        AND PTO_VENTA.EPOS_GENERICNUMBER2 IS NULL 
        AND PTO_VENTA.EPOS_EFFECTIVESTARTDATE <= '2025-12-31' and  PTO_VENTA.EPOS_EFFECTIVEENDDATE > '2025-12-31'
        AND PTO_VENTA.EPAR_EFFECTIVESTARTDATE <=  '2025-12-31'  and  PTO_VENTA.EPAR_EFFECTIVEENDDATE > '2025-12-31'  
        AND PTO_VENTA.ETIT_EFFECTIVESTARTDATE <=  '2025-12-31'  and  PTO_VENTA.ETIT_EFFECTIVEENDDATE > '2025-12-31'
    
    -- OFI
    LEFT JOIN ESTRUCTURA_OLD OFI ON PTO_VENTA.EPOS_MANAGERSEQ = OFI.EPOSITIONSEQ
        AND OFI.EPOS_GENERICNUMBER2 IS NULL 
        AND OFI.EPOS_EFFECTIVESTARTDATE <= '2025-12-31' and  OFI.EPOS_EFFECTIVEENDDATE > '2025-12-31'
        AND OFI.EPAR_EFFECTIVESTARTDATE <=  '2025-12-31'  and  OFI.EPAR_EFFECTIVEENDDATE > '2025-12-31'  
        AND OFI.ETIT_EFFECTIVESTARTDATE <=  '2025-12-31'  and  OFI.ETIT_EFFECTIVEENDDATE > '2025-12-31'

    -- SUC
    LEFT JOIN ESTRUCTURA_OLD SUC ON OFI.EPOS_MANAGERSEQ = SUC.EPOSITIONSEQ
        AND SUC.EPOS_GENERICNUMBER2 IS NULL 
        AND SUC.EPOS_EFFECTIVESTARTDATE <= '2025-12-31' and  SUC.EPOS_EFFECTIVEENDDATE > '2025-12-31'
        AND SUC.EPAR_EFFECTIVESTARTDATE <=  '2025-12-31'  and  SUC.EPAR_EFFECTIVEENDDATE > '2025-12-31'  
        AND SUC.ETIT_EFFECTIVESTARTDATE <=  '2025-12-31'  and  SUC.ETIT_EFFECTIVEENDDATE > '2025-12-31'
    
    -- REG
    LEFT JOIN ESTRUCTURA_OLD REG ON SUC.EPOS_MANAGERSEQ = REG.EPOSITIONSEQ
            AND REG.EPOS_GENERICNUMBER2 IS NULL 
            AND REG.EPOS_EFFECTIVESTARTDATE <= '2025-12-31' and  REG.EPOS_EFFECTIVEENDDATE > '2025-12-31'
            AND REG.EPAR_EFFECTIVESTARTDATE <=  '2025-12-31'  and  REG.EPAR_EFFECTIVEENDDATE > '2025-12-31'  
            AND REG.ETIT_EFFECTIVESTARTDATE <=  '2025-12-31'  and  REG.ETIT_EFFECTIVEENDDATE > '2025-12-31'
    
    -- TIPO 
    LEFT JOIN (SELECT PD.NAME, PD.STARTDATE, PAD.POSITIONGENERICNUMBER2, PAD.POSITIONGENERICATTRIBUTE2, PAD.TERMINATIONDATE, PAD.PARTICIPANTSEQ, PAD.POSITIONSEQ, PAD.POSITIONGENERICDATE2
        FROM TCMP.CSA_PADIMENSION PAD
        INNER JOIN TCMP.CSA_PERIODDIMENSION PD ON PAD.PERIODSEQ = PD.PERIODSEQ
            AND PD.STARTDATE <= '2025-12-31'
            AND PD.YEAR >= extract(year from '2025-12-31')
        WHERE PAD.ISPAYEE = 1
    ) TIPO ON PAR.PAYEESEQ = TIPO.PARTICIPANTSEQ
        AND POS.RULEELEMENTOWNERSEQ = TIPO.POSITIONSEQ
    
    where POS.EFFECTIVESTARTDATE <= '2025-12-31' and  POS.EFFECTIVEENDDATE > '2025-12-31'
        AND POS.REMOVEDATE = TO_DATE('22000101', 'YYYYMMDD')
        AND POS.GENERICNUMBER2 IS NOT NULL
        AND POS.GENERICATTRIBUTE3 NOT IN ('0000000000','0')
        AND POS.GENERICDATE1 >= TO_DATE('0101' || EXTRACT(YEAR FROM '2025-12-31'),'DDMMYYYY')) WITH READ ONLY STRUCTURED PRIVILEGE CHECK