CREATE VIEW "EXT"."CSA_PERCEPCION_INSPECTORES_SVW" ( "REGIONAL", "SUCURSAL", "OFICINA", "COD", "AGENTE", "NIF", "NIF_NOMBRE", "CUADRO", "COD_TIPO", "TIPO", "PERIODO", "MES_PERIODO", "PERCEPCION", "IMPORTE", "MES_PERCEPCION", "IGUALES", "ANYO", "INCLUIR_AGENCIAS", "FEC_ACTUALIZACION", "POSITIONSEQ", "PERIODSEQ" ) AS (SELECT
	REGIONAL,
	SUCURSAL,
	OFICINA,
	COD,
	AGENTE,
	NIF,
	NIF_NOMBRE,
	CUADRO,
	COD_TIPO,
	TIPO,
	PERIODO,
	MES_PERIODO,
	PERCEPCION,
	IMPORTE,
	MES_PERCEPCION,
	IGUALES,
	ANYO,
	INCLUIR_AGENCIAS,
	FEC_ACTUALIZACION,
	POSITIONSEQ,
	PERIODSEQ
FROM EXT.OUT_PERC_INSPECTORES_FINAL_REP
WHERE PERIODSEQ IN (SELECT PERIODSEQ FROM EXT.LIB_CREAR_TABLAS:N_MESES(13))) WITH READ ONLY STRUCTURED PRIVILEGE CHECK