CREATE VIEW "EXT"."CSA_REPARTO_PAGOS_COMMISSIONS_SVW"(
	"COMPANYA",
	"CONCEPTO_PAGO",
	"GRUPO_PAGO",
	"POS_PRIN",
	"ANYO",
	"PERIODO",
	"PERIODO_FORMATO",
	"NIF_NOMBRE",
	"IMPORTE",
	"POSITIONSEQ",
	"PERIODSEQ",
	"NIF") AS
( 		(SELECT 
			"COMPANYA",
			"CONCEPTO_PAGO",
			"GRUPO_PAGO",
			"POS_PRIN",
			"ANYO",
			"PERIODO",
			"PERIODO_FORMATO",
			"NIF_NOMBRE",
			"IMPORTE",
			"POSITIONSEQ",
			"PERIODSEQ",
			LEFT( NIF_NOMBRE, 9 ) AS NIF
		FROM EXT.OUT_REPARTO_PAGOS_COMMISSIONS_FINAL_REP
		WHERE (PERIODSEQ IN (SELECT PERIODSEQ
			FROM EXT.LIB_CREAR_TABLAS:N_MESES(5)))) );
