CREATE OR REPLACE VIEW "EXT"."CSA_LC_PP_RESUMEN_SVW" ( "PERIODO_FILTRO", "PERIODO_FORMATO", "CODIGO_AGENTE", "NOMBRE_AGENTE", "TIPO_AGENTE", "NIF", "NIF_NOMBRE", "FECHA_EFECTO", "PERIODO_TABLA", "STARTDATE", "POLIZ_CORR", "EXTORNO", "FEC_ACTUALIZACION", "SOLO_DIFERENCIAS", "POSITIONSEQ", "PERIODSEQ" ) AS (SELECT 
			"PERIODO_FILTRO",
			"PERIODO_FORMATO",
			"CODIGO_AGENTE",
			"NOMBRE_AGENTE",
			"TIPO_AGENTE",
			"NIF",
			"NIF_NOMBRE",
			"FECHA_EFECTO",
			"PERIODO_TABLA",
			"STARTDATE",
			"POLIZ_CORR",
			"EXTORNO",
			"FEC_ACTUALIZACION",
			"SOLO_DIFERENCIAS",
			"POSITIONSEQ",
			"PERIODSEQ"
		FROM EXT.OUT_PP_RESUMEN_FINAL_REP
		WHERE TIPO_INFORME = 'LC'
		AND PERIODSEQ IN (SELECT PERIODSEQ FROM EXT.LIB_CREAR_TABLAS:N_MESES(13))) WITH  STRUCTURED PRIVILEGE CHECK