CREATE VIEW "EXT"."CSA_PROD_AGENTES_SVW_E" ( "COMPANYA", "ANYO", "PERIODSEQ", "PERIODO", "MES", "PARTICIPANTSEQ", "POSITIONSEQ", "POSITIONNAME", "POSITIONSEQ_PRIN", "POS_PRIN", "ID_TIPO_AGENTE", "TIPO_AGENTE", "COD_REGIONAL", "REGIONAL", "COD_SUCURSAL", "SUCURSAL", "COD_OFICINA", "OFICINA", "NOMBRE", "NIF", "MANAGER_POS_PRIN", "NAME", "ORDEN_AGRUPACIONES_RAMOS", "AGRUPACIONES_RAMOS", "ORDEN_TIPO", "TIPO", "VALUE", "LASTUPDATE" ) AS (SELECT DISTINCT 'ETERNA' COMPANYA
    , INYC_PROD_AGENTES.YEAR ANYO              
    , INYC_PROD_AGENTES.PERIODSEQ
    , INYC_PROD_AGENTES.PERIODO
	, CASE WHEN SUBSTR_BEFORE(INYC_PROD_AGENTES.PERIODO, ' ') = 'Enero' THEN '01 Enero'
		WHEN SUBSTR_BEFORE(INYC_PROD_AGENTES.PERIODO, ' ') = 'Febrero' THEN '02 Febrero'
		WHEN SUBSTR_BEFORE(INYC_PROD_AGENTES.PERIODO, ' ') = 'Marzo' THEN '03 Marzo'
		WHEN SUBSTR_BEFORE(INYC_PROD_AGENTES.PERIODO, ' ') = 'Abril' THEN '04 Abril'
		WHEN SUBSTR_BEFORE(INYC_PROD_AGENTES.PERIODO, ' ') = 'Mayo' THEN '05 Mayo'
		WHEN SUBSTR_BEFORE(INYC_PROD_AGENTES.PERIODO, ' ') = 'Junio' THEN '06 Junio'
		WHEN SUBSTR_BEFORE(INYC_PROD_AGENTES.PERIODO, ' ') = 'Julio' THEN '07 Julio'
		WHEN SUBSTR_BEFORE(INYC_PROD_AGENTES.PERIODO, ' ') = 'Agosto' THEN '08 Agosto'
		WHEN SUBSTR_BEFORE(INYC_PROD_AGENTES.PERIODO, ' ') = 'Septiembre' THEN '09 Septiembre'
		WHEN SUBSTR_BEFORE(INYC_PROD_AGENTES.PERIODO, ' ') = 'Octubre' THEN '10 Octubre'
		WHEN SUBSTR_BEFORE(INYC_PROD_AGENTES.PERIODO, ' ') = 'Noviembre' THEN '11 Noviembre'
		WHEN SUBSTR_BEFORE(INYC_PROD_AGENTES.PERIODO, ' ') = 'Diciembre' THEN '12 Diciembre'
		END MES
    , INYC_JERARQUIA.PARTICIPANTSEQ
    , INYC_JERARQUIA.POSITIONSEQ_PRIN POSITIONSEQ
    , INYC_JERARQUIA.POS_PRIN POSITIONNAME
    , INYC_JERARQUIA.POSITIONSEQ_PRIN
    , INYC_JERARQUIA.POS_PRIN
    , TO_INTEGER(INYC_JERARQUIA.ID_TIPO_AGENTE)
    , INYC_JERARQUIA.TIPO_AGENTE
    , INYC_JERARQUIA.COD_REGIONAL
    , INYC_JERARQUIA.REGIONAL
    , INYC_JERARQUIA.COD_SUCURSAL
    , INYC_JERARQUIA.SUCURSAL
    , INYC_JERARQUIA.COD_OFICINA
    , INYC_JERARQUIA.OFICINA
    , INYC_JERARQUIA.NOMBRE
    , INYC_JERARQUIA.NIF
    , INYC_JERARQUIA.MANAGER_POS_PRIN
    , INYC_PROD_AGENTES.NAME
    , CASE WHEN (INYC_PROD_AGENTES.NAME LIKE '%998%' OR INYC_PROD_AGENTES.NAME LIKE '%TotalProduccion') 
    		THEN 1
    	WHEN (INYC_PROD_AGENTES.NAME LIKE '%004%' OR INYC_PROD_AGENTES.NAME = 'SM-E-GEN-Agente-NumeroPolizasFisicas-TotalMes' OR INYC_PROD_AGENTES.NAME = 'SM-E-GEN-Agente-NumeroPolizasCorregidas-TotalMes' OR INYC_PROD_AGENTES.NAME LIKE '%ProdPrioritarios%') 
    		THEN 2
    	WHEN (INYC_PROD_AGENTES.NAME LIKE '%001%' OR INYC_PROD_AGENTES.NAME = 'SM-E-GEN-Agente-NumeroPolizasFisicas-TotalMes' OR INYC_PROD_AGENTES.NAME = 'SM-E-GEN-Agente-NumeroPolizasCorregidas-TotalMes' OR INYC_PROD_AGENTES.NAME LIKE '%-Decesos%')
			THEN 3
    	WHEN (INYC_PROD_AGENTES.NAME LIKE '%006%'OR INYC_PROD_AGENTES.NAME LIKE '%RRGG%') 
			THEN 4
		WHEN INYC_PROD_AGENTES.NAME LIKE '%Comunidades%'
			THEN 5
		WHEN INYC_PROD_AGENTES.NAME LIKE '%Hogar%' 
			THEN 6
		WHEN INYC_PROD_AGENTES.NAME LIKE '%Accidente%'
			THEN 7
		WHEN INYC_PROD_AGENTES.NAME LIKE '%OtrosDecesos%'
			THEN 8
		WHEN INYC_PROD_AGENTES.NAME LIKE '%Asegurados%'
			THEN 9
    	ELSE 999
    	END ORDEN_AGRUPACIONES_RAMOS
    , CASE WHEN (INYC_PROD_AGENTES.NAME LIKE '%998%' OR INYC_PROD_AGENTES.NAME LIKE '%TotalProduccion') 
    		THEN 'TOTAL PRODUCTOS'
    	WHEN (INYC_PROD_AGENTES.NAME LIKE '%004%' OR INYC_PROD_AGENTES.NAME = 'SM-E-GEN-Agente-NumeroPolizasFisicas-TotalMes' OR INYC_PROD_AGENTES.NAME = 'SM-E-GEN-Agente-NumeroPolizasCorregidas-TotalMes' OR INYC_PROD_AGENTES.NAME LIKE '%ProdPrioritarios%') 
    		THEN 'PROD. PRIORITARIOS'
    	WHEN (INYC_PROD_AGENTES.NAME LIKE '%001%' OR INYC_PROD_AGENTES.NAME = 'SM-E-GEN-Agente-NumeroPolizasFisicas-TotalMes' OR INYC_PROD_AGENTES.NAME = 'SM-E-GEN-Agente-NumeroPolizasCorregidas-TotalMes' OR INYC_PROD_AGENTES.NAME LIKE '%-Decesos%')
			THEN 'RRTT'
    	WHEN (INYC_PROD_AGENTES.NAME LIKE '%006%'OR INYC_PROD_AGENTES.NAME LIKE '%RRGG%') 
			THEN 'RRGG / RRPP'
		WHEN INYC_PROD_AGENTES.NAME LIKE '%Comunidades%'
			THEN 'COMUNIDADES'
		WHEN INYC_PROD_AGENTES.NAME LIKE '%Hogar%' 
			THEN 'HOGAR'
		WHEN INYC_PROD_AGENTES.NAME LIKE '%Accidente%'
			THEN 'ACCIDENTES'
		WHEN INYC_PROD_AGENTES.NAME LIKE '%OtrosDecesos%'
			THEN 'OTROS DECESOS'
		WHEN INYC_PROD_AGENTES.NAME LIKE '%Asegurados%'
			THEN 'ASEGURADOS'
    	ELSE 'NA'
    	END AGRUPACIONES_RAMOS
    , CASE WHEN (INYC_PROD_AGENTES.NAME LIKE '%998%' OR INYC_PROD_AGENTES.NAME LIKE '%TotalProduccion') AND (INYC_PROD_AGENTES.NAME LIKE 'PM-E-GEN-%-NumeroPolizas-%' OR INYC_PROD_AGENTES.NAME = 'PM-E-GEN-Agente-NumAsegurados')
    		THEN 1.1
    	WHEN (INYC_PROD_AGENTES.NAME LIKE '%998%' OR INYC_PROD_AGENTES.NAME LIKE '%TotalProduccion') AND INYC_PROD_AGENTES.NAME LIKE 'PM-E-GEN-%-NumeroPolizasCorregidas%'
    		THEN 1.2
    	WHEN (INYC_PROD_AGENTES.NAME LIKE '%998%' OR INYC_PROD_AGENTES.NAME LIKE '%TotalProduccion') AND INYC_PROD_AGENTES.NAME LIKE 'PM-E-GEN-%-Prima%'
    		THEN 1.3
		WHEN (INYC_PROD_AGENTES.NAME LIKE '%004%' OR INYC_PROD_AGENTES.NAME = 'SM-E-GEN-Agente-NumeroPolizasFisicas-TotalMes' OR INYC_PROD_AGENTES.NAME = 'SM-E-GEN-Agente-NumeroPolizasCorregidas-TotalMes' OR INYC_PROD_AGENTES.NAME LIKE '%ProdPrioritarios%')  AND (INYC_PROD_AGENTES.NAME LIKE 'PM-E-GEN-%-NumeroPolizas-%' OR INYC_PROD_AGENTES.NAME = 'PM-E-GEN-Agente-NumAsegurados')
    		THEN 2.1
    	WHEN (INYC_PROD_AGENTES.NAME LIKE '%004%' OR INYC_PROD_AGENTES.NAME = 'SM-E-GEN-Agente-NumeroPolizasFisicas-TotalMes' OR INYC_PROD_AGENTES.NAME = 'SM-E-GEN-Agente-NumeroPolizasCorregidas-TotalMes' OR INYC_PROD_AGENTES.NAME LIKE '%ProdPrioritarios%')  AND INYC_PROD_AGENTES.NAME LIKE 'PM-E-GEN-%-NumeroPolizasCorregidas%'
    		THEN 2.2
    	WHEN (INYC_PROD_AGENTES.NAME LIKE '%004%' OR INYC_PROD_AGENTES.NAME = 'SM-E-GEN-Agente-NumeroPolizasFisicas-TotalMes' OR INYC_PROD_AGENTES.NAME = 'SM-E-GEN-Agente-NumeroPolizasCorregidas-TotalMes' OR INYC_PROD_AGENTES.NAME LIKE '%ProdPrioritarios%')  AND INYC_PROD_AGENTES.NAME LIKE 'PM-E-GEN-%-Prima%'
    		THEN 2.3
    	WHEN (INYC_PROD_AGENTES.NAME LIKE '%001%' OR INYC_PROD_AGENTES.NAME = 'SM-E-GEN-Agente-NumeroPolizasFisicas-TotalMes' OR INYC_PROD_AGENTES.NAME = 'SM-E-GEN-Agente-NumeroPolizasCorregidas-TotalMes' OR INYC_PROD_AGENTES.NAME LIKE '%-Decesos%') AND (INYC_PROD_AGENTES.NAME LIKE 'PM-E-GEN-%-NumeroPolizas-%' OR INYC_PROD_AGENTES.NAME = 'PM-E-GEN-Agente-NumAsegurados')
    		THEN 3.1
    	WHEN (INYC_PROD_AGENTES.NAME LIKE '%001%' OR INYC_PROD_AGENTES.NAME = 'SM-E-GEN-Agente-NumeroPolizasFisicas-TotalMes' OR INYC_PROD_AGENTES.NAME = 'SM-E-GEN-Agente-NumeroPolizasCorregidas-TotalMes' OR INYC_PROD_AGENTES.NAME LIKE '%-Decesos%') AND INYC_PROD_AGENTES.NAME LIKE 'PM-E-GEN-%-NumeroPolizasCorregidas%'
    		THEN 3.2
    	WHEN (INYC_PROD_AGENTES.NAME LIKE '%001%' OR INYC_PROD_AGENTES.NAME = 'SM-E-GEN-Agente-NumeroPolizasFisicas-TotalMes' OR INYC_PROD_AGENTES.NAME = 'SM-E-GEN-Agente-NumeroPolizasCorregidas-TotalMes' OR INYC_PROD_AGENTES.NAME LIKE '%-Decesos%') AND INYC_PROD_AGENTES.NAME LIKE 'PM-E-GEN-%-Prima%'
    		THEN 3.3
		WHEN (INYC_PROD_AGENTES.NAME LIKE '%006%'OR INYC_PROD_AGENTES.NAME LIKE '%RRGG%')  AND (INYC_PROD_AGENTES.NAME LIKE 'PM-E-GEN-%-NumeroPolizas-%' OR INYC_PROD_AGENTES.NAME = 'PM-E-GEN-Agente-NumAsegurados')
    		THEN 4.1
    	WHEN (INYC_PROD_AGENTES.NAME LIKE '%006%'OR INYC_PROD_AGENTES.NAME LIKE '%RRGG%')  AND INYC_PROD_AGENTES.NAME LIKE 'PM-E-GEN-%-NumeroPolizasCorregidas%'
    		THEN 4.2
    	WHEN (INYC_PROD_AGENTES.NAME LIKE '%006%'OR INYC_PROD_AGENTES.NAME LIKE '%RRGG%')  AND INYC_PROD_AGENTES.NAME LIKE 'PM-E-GEN-%-Prima%'
    		THEN 4.3
    	WHEN INYC_PROD_AGENTES.NAME LIKE '%Comunidades%' AND (INYC_PROD_AGENTES.NAME LIKE 'PM-E-GEN-%-NumeroPolizas-%' OR INYC_PROD_AGENTES.NAME = 'PM-E-GEN-Agente-NumAsegurados')
    		THEN 5.1
    	WHEN INYC_PROD_AGENTES.NAME LIKE '%Comunidades%' AND INYC_PROD_AGENTES.NAME LIKE 'PM-E-GEN-%-NumeroPolizasCorregidas%'
    		THEN 5.2
    	WHEN INYC_PROD_AGENTES.NAME LIKE '%Comunidades%' AND INYC_PROD_AGENTES.NAME LIKE 'PM-E-GEN-%-Prima%'
    		THEN 5.3
    	WHEN INYC_PROD_AGENTES.NAME LIKE '%Hogar%' AND (INYC_PROD_AGENTES.NAME LIKE 'PM-E-GEN-%-NumeroPolizas-%' OR INYC_PROD_AGENTES.NAME = 'PM-E-GEN-Agente-NumAsegurados')
    		THEN 6.1
    	WHEN INYC_PROD_AGENTES.NAME LIKE '%Hogar%' AND INYC_PROD_AGENTES.NAME LIKE 'PM-E-GEN-%-NumeroPolizasCorregidas%'
    		THEN 6.2
    	WHEN INYC_PROD_AGENTES.NAME LIKE '%Hogar%' AND INYC_PROD_AGENTES.NAME LIKE 'PM-E-GEN-%-Prima%'
    		THEN 6.3
    	WHEN INYC_PROD_AGENTES.NAME LIKE '%Accidente%' AND (INYC_PROD_AGENTES.NAME LIKE 'PM-E-GEN-%-NumeroPolizas-%' OR INYC_PROD_AGENTES.NAME = 'PM-E-GEN-Agente-NumAsegurados')
    		THEN 7.1
    	WHEN INYC_PROD_AGENTES.NAME LIKE '%Accidente%' AND INYC_PROD_AGENTES.NAME LIKE 'PM-E-GEN-%-NumeroPolizasCorregidas%'
    		THEN 7.2
    	WHEN INYC_PROD_AGENTES.NAME LIKE '%Accidente%' AND INYC_PROD_AGENTES.NAME LIKE 'PM-E-GEN-%-Prima%'
    		THEN 7.3
    	WHEN INYC_PROD_AGENTES.NAME LIKE '%OtrosDecesos%' AND (INYC_PROD_AGENTES.NAME LIKE 'PM-E-GEN-%-NumeroPolizas-%' OR INYC_PROD_AGENTES.NAME = 'PM-E-GEN-Agente-NumAsegurados')
    		THEN 8.1
    	WHEN INYC_PROD_AGENTES.NAME LIKE '%OtrosDecesos%' AND INYC_PROD_AGENTES.NAME LIKE 'PM-E-GEN-%-NumeroPolizasCorregidas%'
    		THEN 8.2
    	WHEN INYC_PROD_AGENTES.NAME LIKE '%OtrosDecesos%' AND INYC_PROD_AGENTES.NAME LIKE 'PM-E-GEN-%-Prima%'
    		THEN 8.3
    	WHEN INYC_PROD_AGENTES.NAME LIKE '%Asegurados%' AND (INYC_PROD_AGENTES.NAME LIKE 'PM-E-GEN-%-NumeroPolizas-%' OR INYC_PROD_AGENTES.NAME = 'PM-E-GEN-Agente-NumAsegurados')
    		THEN 9.1
    	WHEN INYC_PROD_AGENTES.NAME LIKE '%Asegurados%' AND INYC_PROD_AGENTES.NAME LIKE 'PM-E-GEN-%-NumeroPolizasCorregidas%'
    		THEN 9.2
    	WHEN INYC_PROD_AGENTES.NAME LIKE '%Asegurados%' AND INYC_PROD_AGENTES.NAME LIKE 'PM-E-GEN-%-Prima%'
    		THEN 9.3
    	ELSE 999
    	END ORDEN_TIPO
    , CASE WHEN (INYC_PROD_AGENTES.NAME = 'PM-E-GEN-Agente-NumAsegurados')
    		THEN 'ASEGURADOS'
    	WHEN (INYC_PROD_AGENTES.NAME LIKE 'PM-E-GEN-%-NumeroPolizas-%' OR INYC_PROD_AGENTES.NAME = 'PM-E-GEN-Agente-NumAsegurados')
    		THEN 'POL. FIS.'
    	WHEN INYC_PROD_AGENTES.NAME LIKE 'PM-E-GEN-%-NumeroPolizasCorregidas%'
    		THEN 'POL. CORR.'
    	WHEN INYC_PROD_AGENTES.NAME LIKE 'PM-E-GEN-%-Prima%'
    		THEN 'PRIMAS'
    	ELSE 'NA'
    	END TIPO
    , INYC_PROD_AGENTES.VALUE
	, CASE WHEN MONTH(CURRENT_DATE) = 1 THEN 'Ene'
			WHEN MONTH(CURRENT_DATE) = 2 THEN 'Feb'
			WHEN MONTH(CURRENT_DATE) = 3 THEN 'Mar'
			WHEN MONTH(CURRENT_DATE) = 4 THEN 'Abr'
			WHEN MONTH(CURRENT_DATE) = 5 THEN 'May'
			WHEN MONTH(CURRENT_DATE) = 6 THEN 'Jun'
			WHEN MONTH(CURRENT_DATE) = 7 THEN 'Jul'
			WHEN MONTH(CURRENT_DATE) = 8 THEN 'Ago'
			WHEN MONTH(CURRENT_DATE) = 9 THEN 'Sep'
			WHEN MONTH(CURRENT_DATE) = 10 THEN 'Oct'
			WHEN MONTH(CURRENT_DATE) = 11 THEN 'Nov'
			WHEN MONTH(CURRENT_DATE) = 12 THEN 'Dic'
			END || ' ' || DAYOFMONTH(CURRENT_DATE) || ', ' || YEAR(CURRENT_DATE)
		LASTUPDATE
FROM EXT.OUT_JERARQUIA_REP INYC_JERARQUIA
LEFT JOIN EXT.OUT_PROD_E_AGENTES_REP INYC_PROD_AGENTES 
	ON INYC_JERARQUIA.PARTICIPANTSEQ = INYC_PROD_AGENTES.PARTICIPANTSEQ
    	AND INYC_JERARQUIA.POSITIONSEQ_PRIN = INYC_PROD_AGENTES.POSITIONSEQ_PRIN
    	AND INYC_JERARQUIA.PERIODSEQ = INYC_PROD_AGENTES.PERIODSEQ
WHERE INYC_JERARQUIA.PERIODSEQ IS NOT NULL AND INYC_PROD_AGENTES.PERIODSEQ IS NOT NULL ORDER BY INYC_JERARQUIA.COD_REGIONAL, INYC_JERARQUIA.COD_SUCURSAL, INYC_JERARQUIA.COD_OFICINA, INYC_JERARQUIA.POS_PRIN) WITH READ ONLY STRUCTURED PRIVILEGE CHECK