CREATE VIEW "EXT"."CSA_REPARTO_PAGOS_VISTO_BUENO_SVW"(
	"PERIODO",
	"COMPANYA",
	"COD_AGENTE",
	"TIPO_PAGO",
	"CONCEPTO_PAGO",
	"NUM_TRAMO",
	"PRODUCTO",
	"IMPORTE_REPARTO",
	"PAGO_MES",
	"NIF",
	"COD_UNICO",
	"MANAGER",
	"TIPO_AGENTE",
	"GRUPO_PAGO",
	"IMPORTE",
	"TIPO_REPARTO",
	"REPARTO_TIPO_BASE",
	"REPARTO_PORCENTAJE",
	"COD_POLIZA",
	"COD_RECIBO",
	"PERMANENCIA",
	"POL_FISICA",
	"POL_CORR",
	"PRIMA_CORR",
	"PRIMA_NETA",
	"PRIMA_NETA_ANUAL",
	"PRIMA_COMIS",
	"COEF_TIPO_BASE",
	"COEF_CORRECTOR",
	"FILTRO",
	"QUERY",
	"REPORT") AS
( 		(SELECT 
			PERIODO,
			NULL AS COMPANYA,
			POS_PRIN AS COD_AGENTE,
			TIPO_PAGO,
			EARNINGCODEID AS CONCEPTO_PAGO,
			TO_VARCHAR(NUM_TRAMO),
			PRODUCTID AS PRODUCTO,
			IMPORTE AS IMPORTE_REPARTO,
			NULL AS PAGO_MES,
			NIF,
			POSITIONNAME AS COD_UNICO,
			MANAGER_POS_PRIN AS MANAGER,
			TO_VARCHAR(TO_INTEGER(TIPO_AGENTE)) AS TIPO_AGENTE,
			EARNINGGROUPID AS 
-- TIPO_PAGO,

		-- EARNINGCODEID AS "CONCEPTO DE PAGO",
		GRUPO_PAGO,
			IMPORTE_PAGO AS IMPORTE,
			IFNULL( 
-- NUM_TRAMO,
			TIPO_REPARTO, ' ' ),
			IFNULL( REPARTO_TIPO_BASE, ' ' ),
			IFNULL( TO_VARCHAR(REPARTO_PORCENTAJE), ' ' ),
			
-- PRODUCTID AS PRODUCTO,
		CODIGO_POLIZA,
			CASE
				WHEN RIGHT( LEFT( PRODUCTID, 3 ), 1 ) = '2' THEN RIGHT( ORDERID, 11 )
				ELSE LEFT( TO_VARCHAR(SUBLINENUMBER), 11 )
			END AS COD_RECIBO,
			EVENTTYPEID AS PERMANENCIA,
			POLIZA_FISICA,
			POLIZA_CORREGIDA,
			PRIMA_CORREGIDA,
			PRIMA_NETA,
			PRIMA_NETA_ANUAL,
			PRIMA_COMIS,
			IFNULL( COEF_TIPO_BASE, ' ' ),
			IFNULL( TO_VARCHAR(COEF_CORRECTOR), ' ' ),
			-- IMPORTE AS IMPORTE_REPARTO,
		NIF || ' - ' || POSITIONNAME || ' - ' || TIPO_PAGO || ' - ' || EARNINGCODEID || ' - ' || EARNINGGROUPID || ' - ' || NUM_TRAMO AS FILTRO,
			'D' AS QUERY,
			CASE
				WHEN POS_PRIN LIKE '%999999' THEN 'AGENCIAS'
				ELSE 'NORMAL'
			END AS REPORT
		FROM EXT.FINAL_REPEXT_FILE
		WHERE TIPO_PAGO IS NOT NULL

		UNION

		(SELECT 
			PERIODO,
			SUBSTR( EARNINGGROUPID, 7, 2 ) AS COMPANYA,
			POS_PRIN AS "CODIGO AGENTE",
			TIPO_PAGO,
			EARNINGCODEID AS CONCEPTO_CONTABLE,
			TO_VARCHAR(NUM_TRAMO) AS TRAMO,
			PRODUCTID,
			IMPORTE AS IMPORTE_REPARTO,
			NULL AS PAGO_MES,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			'R1' AS QUERY,
			CASE
				WHEN POS_PRIN LIKE '%999999' THEN 'AGENCIAS'
				ELSE 'NORMAL'
			END AS REPORT
		FROM EXT.FINAL_REPEXT_FILE
		WHERE TIPO_PAGO IS NOT NULL)

		UNION

		(SELECT 
			PER.NAME AS PERIODO,
			SUBSTR( PAG.EARNINGGROUPID, 7, 2 ) AS COMPANYA,
			POS_PRIN AS COD_AGENTE,
			IFNULL( PAG.TIPO_PAGO, 'VACIO' ) AS TIPO_PAGO,
			PAG.EARNINGCODEID AS CONCEPTO_CONTABLE,
			'TOTAL' AS TRAMO,
			NULL AS PRODUCTID,
			SUM_REPEXT AS IMPORTE_REPARTO,
			SUM(PAG.IMPORTE) AS PAGO_MES,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			'R2' AS QUERY,
			CASE
				WHEN POS_PRIN LIKE '%999999' THEN 'AGENCIAS'
				ELSE 'NORMAL'
			END AS REPORT
		FROM 
			EXT.FINAL_REPEXT_PAGOS_FILE AS PAG
			LEFT OUTER JOIN
			(
				(SELECT 
					PERIODSEQ,
					SUBSTR( EARNINGGROUPID, 7, 2 ) AS COMPANYA,
					EARNINGCODEID AS CONCEPTO_CONTABLE,
					TIPO_PAGO,
					SUM(IMPORTE) AS SUM_REPEXT
				FROM EXT.FINAL_REPEXT_FILE
				WHERE TIPO_PAGO IS NOT NULL
					AND POS_PRIN NOT LIKE '%999999'
				GROUP BY 
					PERIODSEQ,
					SUBSTR( EARNINGGROUPID, 7, 2 ),
					EARNINGCODEID,
					TIPO_PAGO)
			) AS FIN
			ON FIN.TIPO_PAGO = PAG.TIPO_PAGO
				AND FIN.COMPANYA = SUBSTR( PAG.EARNINGGROUPID, 7, 2 )
				AND FIN.CONCEPTO_CONTABLE = PAG.EARNINGCODEID
				AND FIN.PERIODSEQ = PAG.PERIODSEQ
			INNER JOIN
			TCMP.CS_PERIOD AS PER
			ON PAG.PERIODSEQ = PER.PERIODSEQ
				AND PER.REMOVEDATE = TO_DATE( '22000101', 'YYYYMMDD' )
		GROUP BY 
			PER.NAME,
			SUBSTR( PAG.EARNINGGROUPID, 7, 2 ),
			POS_PRIN,
			PAG.EARNINGCODEID,
			IFNULL( PAG.TIPO_PAGO, 'VACIO' ),
			'TOTAL',
			NULL,
			SUM_REPEXT,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			'R2')

		UNION

		(SELECT 
			PERIODO,
			SUBSTR( EARNINGGROUPID, 7, 2 ) AS COMPANYA,
			POS_PRIN AS COD_AGENTE,
			TIPO_PAGO,
			EARNINGCODEID AS CONCEPTO_CONTABLE,
			TO_VARCHAR(NUM_TRAMO) AS TRAMO,
			NULL AS PRODUCTID,
			IMPORTE AS IMPORTE_REPARTO,
			NULL AS PAGO_MES,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			'R2' AS QUERY,
			CASE
				WHEN POS_PRIN LIKE '%999999' THEN 'AGENCIAS'
				ELSE 'NORMAL'
			END AS REPORT
		FROM 
			EXT.FINAL_REPEXT_FILE AS FIN
			INNER JOIN
			TCMP.CS_PERIOD AS PER
			ON FIN.PERIODSEQ = PER.PERIODSEQ
				AND PER.REMOVEDATE = TO_DATE( '22000101', 'YYYYMMDD' )
		WHERE TIPO_PAGO IS NOT NULL)) )
WITH READ ONLY;
