CREATE or replace VIEW "EXT"."CSA_S4_E_FACTURA_SVW" ( "PERIODSEQ", "POSITIONSEQ", "PERIODO", "FECHA_EMISION", "NUM_FACTURA", "OFICINA", "AGENTE", "POS_PRIN", "NIF", "DOMICILIO", "MUNICIPIO", "CP", "MES", "ANYO", "COMISION", "TOTAL_DEVENGADO", "CORRECCION", "IRPF", "VALOR_IRPF", "NETO_A_PERCIBIR", "TEXTO_LEGAL", "TEXTO_LEGAL_2", "TEXTO_LEGAL_3", "TEXTO_LEGAL_4", "TEXTO_LEGAL_5", "TEXTO_LEGAL_6", "TEXTO_LEGAL_7", "FILTRO" ) AS (SELECT 
			PERIODSEQ,
			POSITIONSEQ_PRIN AS POSITIONSEQ,
			PERIODO,
			FECHA_EMISION,
			N_FACTURA AS NUM_FACTURA,
			OFICINA_CONCAT AS OFICINA,
			AGENTE,
			POS_PRIN,
			NIF,
			DOMICILIO,
			MUNICIPIO,
			TO_VARCHAR(TO_INTEGER(CP)) AS CP,
			MES,
			ANYO,
			COMISION,
			IMP_TOTAL AS TOTAL_DEVENGADO,
			IMP_CORRECCION AS CORRECCION,
			IRPF,
			VALOR_IRPF,
			NETO_A_PERCIBIR,
			CASE
				WHEN COD_REGIONAL = '0557' THEN 'Operación sujeta y exenta de I.G.I.C. Ley 4/2012, art. 50.Uno. 16º'
				ELSE 'Operación sujeta y exenta de I.V.A. Ley 37/1992, art. 20.Uno. 16º'
			END AS TEXTO_LEGAL,
			CASE
				WHEN TO_INTEGER(ANYO) > 2025 
					THEN 'Con fecha 12/01/2026 se ha inscrito en el Registro Mercantil la Fusión por Absorción por la que OCASO, S.A. absorbe el 100% de capital de la sociedad ETERNA, S.A.U., que desaparece, adquiriendo todos sus derechos y obligaciones. En consecuencia, la sociedad absorbente (OCASO, S.A.) es la DESTINATARIA de los servicios facturados en este documento.'
				ELSE 'ETERNA ASEGURADORA, S.A. COMPAÑIA DE SEGUROS Y REASEGUROS (SOCIEDAD UNIPERSONAL), PRINCESA 23 - 28008 - MADRID - ESPAÑA - TELÉFONO 915380100 INSCRITA EN EL REGISTRO MERCANTIL DE MADRID, TOMO 5588, FOLIO 180, SECCIÓN 8, HOJA M-91466 CIF: A15009244.'
			END AS TEXTO_LEGAL_2,
			CASE
				WHEN TO_INTEGER(ANYO) > 2025
					THEN 'DATOS FISCALES:'
				ELSE ' '
			END AS TEXTO_LEGAL_3,
			CASE
				WHEN TO_INTEGER(ANYO) > 2025
					THEN 'OCASO, S.A. COMPAÑÍA DE SEGUROS Y REASEGUROS'
				ELSE ' '
			END AS TEXTO_LEGAL_4,
			CASE
				WHEN TO_INTEGER(ANYO) > 2025
					THEN 'C/ PRINCESA 23 - 28008 - MADRID - ESPAÑA'
				ELSE ' '
			END AS TEXTO_LEGAL_5,
			CASE
				WHEN TO_INTEGER(ANYO) > 2025
					THEN 'NIF: A28016608'
				ELSE ' '
			END AS TEXTO_LEGAL_6,
			CASE
				WHEN TO_INTEGER(ANYO) > 2025
					THEN 'INSCRITA EN EL REGISTRO MERCANTIL DE MADRID, TOMO 3773, FOLIO 33, SECCIÓN 8, HOJA M-62817'
				ELSE ' '
			END AS TEXTO_LEGAL_7,
			FILTRO
		FROM EXT.OUT_S4_FACTURA_FINAL_REP
		WHERE COMPANYA = 'ETERNA'
			AND TIPO_PAGO = 'CIERRE'
	AND PERIODSEQ IN (SELECT PERIODSEQ FROM EXT.LIB_CREAR_TABLAS:N_MESES(13))) WITH  STRUCTURED PRIVILEGE CHECK