CREATE VIEW "EXT"."CSA_FINAL_HACEXT_FILE_SVW"("LINE") AS
( 		(SELECT "LINE"
		FROM 
			(
				(SELECT LINE
				FROM EXT.FINAL_HACEXT_FILE

				UNION ALL

				SELECT NULL
				FROM DUMMY)
			)
		ORDER BY 
			CASE
				WHEN LINE IS NULL THEN 1
				ELSE 0
			END ASC, 
			LINE ASC) )
WITH READ ONLY;
