CREATE OR REPLACE VIEW "EXT"."CSA_LC_RE_RESUMEN_SVW" ( "PERIODO", "PERIODO_FORMATO", "CODIGO_AGENTE", "NIF", "NOMBRE_AGENTE", "NIF_NOMBRE", "TIPO_AGENTE", "RRPP", "ASEG_RRTT", "PRIMA_ANUALIZ", "IMPORTE_RRPP", "IMPORTE_ASEG_RRTT", "CODIGO_AGENTE_TABLA", "NOMBRE_AGENTE_TABLA", "RRPP_TABLA", "ASEG_RRTT_TABLA", "FEC_ACTUALIZACION", "SOLO_DIFERENCIAS", "POSITIONSEQ", "PERIODSEQ" ) AS (SELECT "PERIODO", PERIODO_FORMATO, "CODIGO_AGENTE",
	"NIF", "NOMBRE_AGENTE", "NIF_NOMBRE", "TIPO_AGENTE",
	"RRPP", "ASEG_RRTT", "PRIMA_ANUALIZ", "IMPORTE_RRPP", "IMPORTE_ASEG_RRTT",
	"CODIGO_AGENTE_TABLA" , "NOMBRE_AGENTE_TABLA" , "RRPP_TABLA" , "ASEG_RRTT_TABLA",
	"FEC_ACTUALIZACION" , SOLO_DIFERENCIAS, "POSITIONSEQ" , "PERIODSEQ"
FROM EXT.OUT_RE_RESUMEN_FINAL_REP
WHERE TIPO_INFORME = 'LC'
	AND PERIODSEQ IN (SELECT PERIODSEQ FROM EXT.LIB_CREAR_TABLAS:N_MESES(13))) WITH  STRUCTURED PRIVILEGE CHECK