CREATE VIEW "EXT"."CSA_LC_S5_FACTURA_SVW" ( "PERIODSEQ", "PERIODO", "ANYO", "MES", "POSITIONSEQ", "POS_PRIN", "COMISION", "IMPORTE", "OFICINA_CONCAT", "INSPECTOR", "DOMICILIO", "MUNICIPIO", "CP", "IRPF", "NIF", "N_FACTURA", "IMP_TOTAL", "IMP_CORRECCION", "VALOR_IRPF", "NETO_A_PERCIBIR", "FECHA_EMISION", "FILTRO", "TEXTO_LEGAL" ) AS (SELECT 
	PERIODSEQ, 
	PERIODO, 
	ANYO, 
	MES, 
	POSITIONSEQ_PRIN AS POSITIONSEQ, 
	POS_PRIN, 
	COMISION, 
	IMPORTE, 
	OFICINA_CONCAT, 
	INSPECTOR, 
	DOMICILIO, 
	MUNICIPIO, 
	CP, 
	IRPF, 
	NIF,
	N_FACTURA, 
	IMP_TOTAL, 
	IMP_CORRECCION, 
	VALOR_IRPF, 
	NETO_A_PERCIBIR, 
	FECHA_EMISION,
	FILTRO,
	CASE WHEN COD_REGIONAL = '0557' THEN 'Operación sujeta y exenta de I.G.I.C. Ley 4/2012, art. 50.Uno. 16º'
		ELSE 'Operación sujeta y exenta de I.V.A. Ley 37/1992, art. 20.Uno. 16º'
		END AS TEXTO_LEGAL
	
FROM EXT.OUT_S5_FACTURA_FINAL_REP
  WHERE COMPANYA = 'OCASO'
   AND TIPO_PAGO = 'LC'
	AND PERIODSEQ IN (SELECT PERIODSEQ FROM EXT.LIB_CREAR_TABLAS:N_MESES(13))) WITH  STRUCTURED PRIVILEGE CHECK