CREATE VIEW "EXT"."CSA_S5_RPI_RESUMEN_SVW" ( "TIPO_PAGO", "PERIODO_ORIGINAL", "PERIODO_CAMPO", "PERIODO", "QUARTER", "NIF_NOMBRE", "OFICINA", "INSPECTOR", "NIF", "TIPO_AGENTE", "POS_PRIN", "COMISION_PAGO", "V_MEDIDA_CALC", "POSITIONNAME_AG", "NOMBRE_AGENTE", "COMISION_AGENTE", "VALOR_COMISION_AGENTE", "RAPPEL_2_3", "COMISION_OBJETIVOS", "TIPO_SEGUIMIENTO", "COMISION_SEGUIMIENTO", "COMISION_TRIM_PAGOS", "FEC_ACTUALIZACION_FORMATO", "PERIODSEQ", "POSITIONSEQ" ) AS (SELECT
	TIPO_PAGO,
	PERIODO_ORIGINAL,
	PERIODO_CAMPO,
	PERIODO,
	QUARTER,
	NIF_NOMBRE,
	OFICINA,
	INSPECTOR,
	NIF,
	TIPO_AGENTE,
	POS_PRIN,
	COMISION_PAGO,
	V_MEDIDA_CALC,
	POSITIONNAME_AG,
	NOMBRE_AGENTE,
	COMISION_AGENTE,
	VALOR_COMISION_AGENTE,
	RAPPEL_2_3,
	COMISION_OBJETIVOS,
	TIPO_SEGUIMIENTO,
	COMISION_SEGUIMIENTO,
	COMISION_TRIM_PAGOS, 
	FEC_ACTUALIZACION_FORMATO,
	PERIODSEQ,
	POSITIONSEQ
FROM EXT.OUT_S5_RPI_RESUMEN_FINAL_REP
WHERE TIPO_PAGO = 'CIERRE'
	AND PERIODSEQ IN (SELECT PERIODSEQ FROM EXT.LIB_CREAR_TABLAS:N_MESES(13))) WITH  STRUCTURED PRIVILEGE CHECK