CREATE OR REPLACE VIEW "EXT"."CSA_LC_S4_E_POLIZAS_SVW" ( "PERIODSEQ", "POSITIONSEQ", "PERIODO_FILTRO", "PERIODO", "NIF_NOMBRE", "REGIONAL", "SUCURSAL", "OFICINA", "AGENTE", "NIF", "TIPO", "SALESTRANSACTIONSEQ", "PRODUCTO", "GEST", "AGENTE_TABLA", "POLIZA", "FECHA_CARGO", "FECHA_VENCIMIENTO", "TIPO_RECIBO", "POLIZ_NP", "PRIMA_NETA_CALC", "PRIMA_COMISIONABLE", "PRODUCCION", "CONSERVACION", "PREMIO", "POLIZA_CORREGIDA", "ASEGURADOS", "FEC_ACTUALIZACION", "SOLO_DIFERENCIAS" ) AS (SELECT 
	PERIODSEQ,
	POSITIONSEQ,
	--Filtros
	PERIODO,
	UPPER(RIGHT(PERIODO, LENGTH(PERIODO)-8) || ' ' || LEFT(PERIODO, 4)) AS PERIODO_OLD,
	NIF_NOMBRE,

	--Cabecera
	CAMPO_REGIONAL,
	CAMPO_SUCURSAL,
	CAMPO_OFICINA,
	CAMPO_AGENTE,
	NIF,
	CAMPO_TIPO_AGENTE,

	--Tabla
	SALESTRANSACTIONSEQ,
	CAMPO_PRODUCTO,
	LEFT(POSITIONNAME, 4) AS GEST,
	RIGHT(POSITIONNAME, 6) AS AGENTE_TABLA,
	POLIZA,
	FECHA_CARGO,
	FECHA_VENCIMIENTO,
	TIPO_RECIBO,

	--Medidas
	POLIZ_NP,
	PRIMA_NETA_CALC,
	PRIMA_COMISIONABLE,
	PRODUCCION,
	CONSERVACION,
	PREMIO,
	IFNULL(POLIZA_CORREGIDA, 0),
	IFNULL(ASEGURADOS, 0),

	--Última actualización
	FEC_ACTUALIZACION_FORMATO,
	SOLO_DIFERENCIAS

FROM EXT.OUT_S4_POLIZAS_FINAL_REP
WHERE EMPRESA = 'ETERNA' AND INFORME_EA = 'LC') WITH  STRUCTURED PRIVILEGE CHECK