CREATE VIEW "EXT"."CSA_LC_S4_FACTURA_SVW" ( "PERIODSEQ", "POSITIONSEQ", "PERIODO", "FECHA_EMISION", "NUM_FACTURA", "OFICINA", "AGENTE", "POS_PRIN", "NIF", "DOMICILIO", "MUNICIPIO", "CP", "MES", "ANYO", "COMISION", "TOTAL_DEVENGADO", "CORRECCION", "IRPF", "VALOR_IRPF", "NETO_A_PERCIBIR", "TEXTO_LEGAL", "FILTRO" ) AS (SELECT 
			PERIODSEQ,
			POSITIONSEQ_PRIN AS POSITIONSEQ,
			PERIODO,
			FECHA_EMISION,
			N_FACTURA,
			OFICINA_CONCAT,
			AGENTE,
			POS_PRIN,
			NIF,
			DOMICILIO,
			MUNICIPIO,
			TO_VARCHAR(TO_INTEGER(CP)) AS CP,
			MES,
			ANYO,
			COMISION,
			IMP_TOTAL AS TOTAL_DEVENGADO,
			IMP_CORRECCION AS CORRECCION,
			IRPF,
			VALOR_IRPF,
			NETO_A_PERCIBIR,
			CASE
				WHEN COD_REGIONAL = '0557' THEN 'Operación sujeta y exenta de I.G.I.C. Ley 4/2012, art. 50.Uno. 16º'
				ELSE 'Operación sujeta y exenta de I.V.A. Ley 37/1992, art. 20.Uno. 16º'
			END AS TEXTO_LEGAL,
			FILTRO
		FROM EXT.OUT_S4_FACTURA_FINAL_REP
		WHERE COMPANYA = 'OCASO'
			AND TIPO_PAGO = 'LC'
	AND PERIODSEQ IN (SELECT PERIODSEQ FROM EXT.LIB_CREAR_TABLAS:N_MESES(13))) WITH  STRUCTURED PRIVILEGE CHECK