CREATE VIEW "EXT"."CSA_FECHAS_ACTUALIZACION_TABLAS_SVW"(
	"PERIODO",
	"DESCRIPCION",
	"ULTIMA_ACTUALIZACION",
	"TABLA",
	"ULTIMA_ACTUALIZACION_FORMATO",
	"NUMERO") AS
( 		(SELECT 
			PERIODO,
			DESCRIPCION,
			ULTIMA_ACTUALIZACION,
			TABLA,
			TO_VARCHAR( ULTIMA_ACTUALIZACION, 'DD/MM/YYYY' ) AS ULTIMA_ACTUALIZACION_FORMATO,
			CASE
				WHEN TABLA LIKE 'INYC%' THEN 0
				ELSE 1
			END AS NUMERO
		FROM EXT.OUT_FECHAS_WEBI_REP) );
