CREATE OR REPLACE VIEW "EXT"."CSA_RESUMEN_REPARTO_PAGOS_VB2_SVW"(
	"PERIODSEQ",
	"PERIODO",
	"PERIODO_FORMATO",
	"COMPANIA",
	"TIPO_PAGO",
	"TRAMO",
	"REPARTO",
	"PAGO_MES",
	"AGENCIA") AS
( 		(SELECT 
			"PERIODSEQ",
			"PERIODO",
			"PERIODO_FORMATO",
			"COMPANIA",
			"TIPO_PAGO",
			"TRAMO",
			"REPARTO",
			"PAGO_MES",
			"AGENCIA"
		FROM EXT.OUT_RESUMEN_REPARTO_PAGOS_VB2_FINAL_REP
		WHERE (PERIODSEQ IN (SELECT PERIODSEQ FROM  cs_period where startdate like'2026-%' and removedate= TO_DATE('2200-01-01','YYYY-MM-DD')))) );
