CREATE VIEW "EXT"."CSA_MEDIADOR_SVW"(
	"PARTICIPANTEMAIL",
	"TAXID",
	"PAR_EFFECTIVESTARTDATE",
	"PAR_EFFECTIVEENDDATE",
	"PERIODNAME",
	"PERIODSHORTNAME",
	"PERIODDESCRIPTION",
	"STARTDATE",
	"ENDDATE",
	"NOMBRE_COMPLETO",
	"PERIODSEQ",
	"POSITIONSEQ",
	"PARTICIPANTSEQ",
	"PARTICIPANTID",
	"USERID",
	"PREFIX",
	"FIRSTNAME",
	"MIDDLENAME",
	"LASTNAME",
	"SUFFIX",
	"FULLNAME",
	"SALARY",
	"HIREDATE",
	"TERMINATIONDATE",
	"BUSINESSUNITMAP",
	"BUSINESSUNITNAME",
	"POSITIONNAME",
	"POSITIONDESCRIPTION",
	"POSITIONGROUPNAME",
	"TITLENAME",
	"TITLEDESCRIPTION",
	"TARGETCOMPENSATION",
	"PLANNAME",
	"PLANSEQ",
	"POSITIONGENERICATTRIBUTE1",
	"POSITIONGENERICATTRIBUTE2",
	"POSITIONGENERICATTRIBUTE3",
	"POSITIONGENERICATTRIBUTE4",
	"POSITIONGENERICATTRIBUTE5",
	"POSITIONGENERICATTRIBUTE6",
	"POSITIONGENERICATTRIBUTE7",
	"POSITIONGENERICATTRIBUTE8",
	"POSITIONGENERICATTRIBUTE9",
	"POSITIONGENERICATTRIBUTE10",
	"POSITIONGENERICATTRIBUTE11",
	"POSITIONGENERICATTRIBUTE12",
	"POSITIONGENERICATTRIBUTE13",
	"POSITIONGENERICATTRIBUTE14",
	"POSITIONGENERICATTRIBUTE15",
	"POSITIONGENERICATTRIBUTE16",
	"POSITIONGENERICNUMBER1",
	"POSITIONGENERICNUMBER2",
	"POSITIONGENERICNUMBER3",
	"POSITIONGENERICNUMBER4",
	"POSITIONGENERICNUMBER5",
	"POSITIONGENERICNUMBER6",
	"POSITIONGENERICDATE1",
	"POSITIONGENERICDATE2",
	"POSITIONGENERICDATE3",
	"POSITIONGENERICDATE4",
	"POSITIONGENERICDATE5",
	"POSITIONGENERICDATE6",
	"POSITIONGENERICBOOLEAN1",
	"POSITIONGENERICBOOLEAN2",
	"POSITIONGENERICBOOLEAN3",
	"POSITIONGENERICBOOLEAN4",
	"POSITIONGENERICBOOLEAN5",
	"POSITIONGENERICBOOLEAN6",
	"PARTICIPANTGENERICATTRIBUTE1",
	"PARTICIPANTGENERICATTRIBUTE2",
	"PARTICIPANTGENERICATTRIBUTE3",
	"PARTICIPANTGENERICATTRIBUTE4",
	"PARTICIPANTGENERICATTRIBUTE5",
	"PARTICIPANTGENERICATTRIBUTE6",
	"PARTICIPANTGENERICATTRIBUTE7",
	"PARTICIPANTGENERICATTRIBUTE8",
	"PARTICIPANTGENERICATTRIBUTE9",
	"PARTICIPANTGENERICATTRIBUTE10",
	"PARTICIPANTGENERICATTRIBUTE11",
	"PARTICIPANTGENERICATTRIBUTE12",
	"PARTICIPANTGENERICATTRIBUTE13",
	"PARTICIPANTGENERICATTRIBUTE14",
	"PARTICIPANTGENERICATTRIBUTE15",
	"PARTICIPANTGENERICATTRIBUTE16",
	"PARTICIPANTGENERICNUMBER1",
	"PARTICIPANTGENERICNUMBER2",
	"PARTICIPANTGENERICNUMBER3",
	"PARTICIPANTGENERICNUMBER4",
	"PARTICIPANTGENERICNUMBER5",
	"PARTICIPANTGENERICNUMBER6",
	"PARTICIPANTGENERICDATE1",
	"PARTICIPANTGENERICDATE2",
	"PARTICIPANTGENERICDATE3",
	"PARTICIPANTGENERICDATE4",
	"PARTICIPANTGENERICDATE5",
	"PARTICIPANTGENERICDATE6",
	"PARTICIPANTGENERICBOOLEAN1",
	"PARTICIPANTGENERICBOOLEAN2",
	"PARTICIPANTGENERICBOOLEAN3",
	"PARTICIPANTGENERICBOOLEAN4",
	"PARTICIPANTGENERICBOOLEAN5",
	"PARTICIPANTGENERICBOOLEAN6",
	"TITLEGENERICATTRIBUTE1",
	"TITLEGENERICATTRIBUTE2",
	"TITLEGENERICATTRIBUTE3",
	"TITLEGENERICATTRIBUTE4",
	"TITLEGENERICNUMBER1",
	"TITLEGENERICNUMBER2",
	"TITLEGENERICNUMBER3",
	"TITLEGENERICNUMBER4",
	"TITLEGENERICDATE1",
	"TITLEGENERICDATE2",
	"TITLEGENERICBOOLEAN1",
	"TITLEGENERICBOOLEAN2",
	"MANAGERSEQ",
	"MANAGERFULLNAME",
	"ISPAYEE",
	"BOUSERID",
	"MANAGERPARTICIPANTSEQ",
	"PA_SK",
	"MEDCOUNT") AS
( 		(SELECT DISTINCT 
			PAR.PARTICIPANTEMAIL,
			-- Correo electrónico
		PAR.TAXID,
			-- Tipo de IRPF
		PAR.EFFECTIVESTARTDATE AS PAR_EFFECTIVESTARTDATE,
			-- Fecha Inicio Efectividad
		PAR.EFFECTIVEENDDATE AS PAR_EFFECTIVEENDDATE,
			-- Fecha Fin Efectividad
		PER.NAME AS PERIODNAME,
			PER.SHORTNAME AS PERIODSHORTNAME,
			PER.DESCRIPTION AS PERIODDESCRIPTION,
			PER.STARTDATE,
			PER.ENDDATE,
			IFNULL( RTRIM(PAD.FIRSTNAME) || ' ', '' ) || IFNULL( RTRIM(PAD.LASTNAME), '' ) || IFNULL( ' ' || RTRIM(PAD.SUFFIX), '' ) AS NOMBRE_COMPLETO,
			PAD.PERIODSEQ,
			POSITIONSEQ,
			PARTICIPANTSEQ,
			PARTICIPANTID,
			-- ID de participante
		PAD.USERID,
			-- Usuario LDAP
		PAD.PREFIX,
			PAD.FIRSTNAME,
			-- Nombre
		PAD.MIDDLENAME,
			-- Email personal
		PAD.LASTNAME,
			-- Apellido 1/Razón social
		PAD.SUFFIX,
			-- Apellido 2
		PAD.FULLNAME,
			PAD.SALARY,
			-- Pago por IBAN
		PAD.HIREDATE,
			-- Fecha de Contrato
		PAD.TERMINATIONDATE,
			-- Fecha Fin Agente
		PAD.BUSINESSUNITMAP,
			PAD.BUSINESSUNITNAME,
			POSITIONNAME,
			-- Posición
		POSITIONDESCRIPTION,
			-- Descripción Posición
		POSITIONGROUPNAME,
			-- Grupo de Posición
		TITLENAME,
			-- Título
		TITLEDESCRIPTION,
			-- Descripción Título
		TARGETCOMPENSATION,
			-- Objetivo Comisiones
		PLANNAME,
			-- PLAN
		PLANSEQ,
			POSITIONGENERICATTRIBUTE1,
			-- Tipo Principal Agente / Clase Oficina (GA1)
		POSITIONGENERICATTRIBUTE2,
			-- Tipo Agente / Tipo Oficina (GA2)
		POSITIONGENERICATTRIBUTE3,
			-- Código de Agente OCASO (GA3)
		POSITIONGENERICATTRIBUTE4,
			-- Rehabilitación (GA4)
		POSITIONGENERICATTRIBUTE5,
			-- Cuadro Inspector Ocaso (GA5)
		POSITIONGENERICATTRIBUTE6,
			-- Cuadro RRGG Ocaso (GA6)
		POSITIONGENERICATTRIBUTE7,
			-- Cuadro RRTT Ocaso (GA7)
		POSITIONGENERICATTRIBUTE8,
			-- Compañía (GA8)
		POSITIONGENERICATTRIBUTE9,
			-- Promoción Agente (GA9)
		POSITIONGENERICATTRIBUTE10,
			-- Cuadro Inspector Eterna (GA10)
		POSITIONGENERICATTRIBUTE11,
			-- Cuadro RRGG Eterna (GA11)
		POSITIONGENERICATTRIBUTE12,
			-- Cuadro RRTT Eterna (GA12)
		POSITIONGENERICATTRIBUTE13,
			-- Año Captación (GA13)
		POSITIONGENERICATTRIBUTE14,
			-- Inspector Captador (GA14)
		POSITIONGENERICATTRIBUTE15,
			-- Número Meses Preplan (GA15)
		POSITIONGENERICATTRIBUTE16,
			-- Escalado Asistencia (GA16)
		POSITIONGENERICNUMBER1,
			-- ID Tipo Principal Agente (GN1)
		POSITIONGENERICNUMBER2,
			-- ID Tipo Agente (GN2)
		POSITIONGENERICNUMBER3,
			-- ID Clase Oficina (GN3)
		POSITIONGENERICNUMBER4,
			-- ID Tipo Oficina (GN4)
		POSITIONGENERICNUMBER5,
			-- % Comisión Cartera (GN5)
		POSITIONGENERICNUMBER6,
			-- Importe Comisión Cartera (GN6)
		POSITIONGENERICDATE1,
			-- Fecha de Alta (GD1)
		POSITIONGENERICDATE2,
			-- Fecha de Baja (GD2)
		POSITIONGENERICDATE3,
			-- Fecha Inicio Consolidación P.C. (GD3)
		POSITIONGENERICDATE4,
			-- Fecha Fin Consolidación P.C. (GD4)
		POSITIONGENERICDATE5,
			-- Fecha Inicio Asistencia (GD5)
		POSITIONGENERICDATE6,
			-- Fecha Límite Comisiones Cartera (GD6)
		POSITIONGENERICBOOLEAN1,
			-- Reducción (GB1)
		POSITIONGENERICBOOLEAN2,
			-- Productor Ocaso (GB2)
		POSITIONGENERICBOOLEAN3,
			-- Consolida (GB3)
		POSITIONGENERICBOOLEAN4,
			-- Inicio Agente Asistencia (GB4)
		POSITIONGENERICBOOLEAN5,
			-- Productor Eterna (GB5)
		POSITIONGENERICBOOLEAN6,
			-- Ag. Lider (GB6)
		PARTICIPANTGENERICATTRIBUTE1,
			-- Documento (GA1)
		PARTICIPANTGENERICATTRIBUTE2,
			-- Tipo Documento (GA2)
		PARTICIPANTGENERICATTRIBUTE3,
			-- Tipo Persona (GA3)
		PARTICIPANTGENERICATTRIBUTE4,
			-- Código DGS (GA4)
		PARTICIPANTGENERICATTRIBUTE5,
			-- Compañía (GA5)
		PARTICIPANTGENERICATTRIBUTE6,
			-- Tipo Mediador (GA6)
		PARTICIPANTGENERICATTRIBUTE7,
			-- Localidad (GA7)
		PARTICIPANTGENERICATTRIBUTE8,
			-- Tipo Vía (GA8)
		PARTICIPANTGENERICATTRIBUTE9,
			-- Domicilio (GA9)
		PARTICIPANTGENERICATTRIBUTE10,
			-- Número (GA10)
		PARTICIPANTGENERICATTRIBUTE11,
			-- Resto Domicilio (GA11)
		PARTICIPANTGENERICATTRIBUTE12,
			-- Sexo (GA12)
		PARTICIPANTGENERICATTRIBUTE13,
			-- Estado Civil (GA13)
		PARTICIPANTGENERICATTRIBUTE14,
			-- Teléfono Fijo (GA14)
		PARTICIPANTGENERICATTRIBUTE15,
			-- Teléfono Móvil (GA15)
		PARTICIPANTGENERICATTRIBUTE16,
			-- IBAN (GA16)
		PARTICIPANTGENERICNUMBER1,
			-- Código Postal (GN1)
		PARTICIPANTGENERICNUMBER2,
			-- Provincia (GN2)
		PARTICIPANTGENERICNUMBER3,
			-- Municipio (GN3)
		PARTICIPANTGENERICNUMBER4,
			-- ID_Empleado (GN4)
		PARTICIPANTGENERICNUMBER5,
			-- % IRPF (GN5)
		PARTICIPANTGENERICNUMBER6,
			-- Fax (GN6)
		PARTICIPANTGENERICDATE1,
			-- Fecha Nacimiento (GD1)
		PARTICIPANTGENERICDATE2,
			-- Fecha Registro DGS (GD2)
		PARTICIPANTGENERICDATE3,
			-- Fecha Envío DGS (GD3)
		PARTICIPANTGENERICDATE4,
			-- Fin CIASE 1 (GD4)
		PARTICIPANTGENERICDATE5,
			-- Fecha Efecto SuperRappel (GD5)
		PARTICIPANTGENERICDATE6,
			-- Fecha Regularización SuperRappel (GD6)
		PARTICIPANTGENERICBOOLEAN1,
			-- Autoliquida (GB1)
		PARTICIPANTGENERICBOOLEAN2,
			-- Corredor (GB2)
		PARTICIPANTGENERICBOOLEAN3,
			-- Autorización Factura (GB3)
		PARTICIPANTGENERICBOOLEAN4,
			-- SuperRappel (GB4)
		PARTICIPANTGENERICBOOLEAN5,
			-- Comisiones Anualizadas RRPP OCASO (GB5)
		PARTICIPANTGENERICBOOLEAN6,
			-- Cartera RRTT (GB6)
		TITLEGENERICATTRIBUTE1,
			-- Tipo Principal Agente / Clase Oficina (GA1)
		TITLEGENERICATTRIBUTE2,
			-- Tipo Agente / Tipo Oficina (GA2)
		TITLEGENERICATTRIBUTE3,
			TITLEGENERICATTRIBUTE4,
			TITLEGENERICNUMBER1,
			-- ID Tipo Principal  Agente (GN1)
		TITLEGENERICNUMBER2,
			-- ID Tipo  Agente (GN2)
		TITLEGENERICNUMBER3,
			-- ID Clase Oficina (GN3)
		TITLEGENERICNUMBER4,
			-- ID Tipo Oficina (GN4)
		TITLEGENERICDATE1,
			TITLEGENERICDATE2,
			TITLEGENERICBOOLEAN1,
			-- Genera Informe (GB1)
		TITLEGENERICBOOLEAN2,
			MANAGERSEQ,
			-- MANAGERSEQ
		MANAGERFULLNAME,
			ISPAYEE,
			BOUSERID,
			MANAGERPARTICIPANTSEQ,
			PA_SK,
			1 AS MEDCOUNT
		FROM 
			CSA_PADIMENSION AS PAD
			INNER JOIN
			CSA_PERIODDIMENSION AS PER
			ON PAD.PERIODSEQ = PER.PERIODSEQ
			INNER JOIN
			CS_PARTICIPANT AS PAR
			ON -- Se hace un JOIN con CS_PARTICIPANT a ultimo dia del mes de cada periodo para extraer: PAR.PARTICIPANTEMAIL, PAR.TAXID y fechas de efectividad por si quisieran filtrar por fecha concreta
				PAD.PARTICIPANTSEQ = PAR.PAYEESEQ
				AND PAR.REMOVEDATE = TO_DATE( '22000101', 'yyyymmdd' )
				AND PAR.EFFECTIVESTARTDATE < PER.ENDDATE
				AND PAR.EFFECTIVEENDDATE >= PER.ENDDATE
		WHERE PAD.USERID = PAR.USERID
			AND BUSINESSUNITMAP = 1) )
WITH READ ONLY;
