CREATE VIEW "EXT"."CSA_DIST_RAPPEL_MENSUAL_SVW_E" ( "REGIONAL", "SUCURSAL", "OFICINA_CONCAT", "POS_PRIN", "AGENTE", "NIF", "TIPO_AGENTE", "PRODUCTO", "POSITIONSEQ_PRIN", "POSITIONSEQ", "GEST", "COD_AGENTE", "POLIZA", "POLIZ_NP", "FEC_CARGO", "IMPUT_POL_CORR_RAPPEL", "POLIZ_CORR", "SUMA_POLIZ_CORR", "N_ASEG", "TIPO_RECIBO", "V_MEDIDA", "LASTUPDATE", "PERIODO", "PERIODSEQ" ) AS (WITH "SUMA" AS (SELECT DISTINCT
		S4_E_POLIZAS.PERIODSEQ,
		S4_E_POLIZAS.POSITIONSEQ_PRIN,
		S4_E_POLIZAS.PARTICIPANTSEQ,
		SUM(IFNULL(S4_E_POLIZAS.POLIZ_CORR, 0)) AS SUM_POLIZ_CORR
	FROM EXT.OUT_S4_E_POLIZAS_REP S4_E_POLIZAS
	GROUP BY S4_E_POLIZAS.PERIODSEQ, S4_E_POLIZAS.POSITIONSEQ_PRIN, S4_E_POLIZAS.PARTICIPANTSEQ), "TOTAL_RAPPEL" AS (SELECT POSITIONSEQ_PRIN, PARTICIPANTSEQ, PERIODSEQ, SUM(V_MEDIDA) AS V_MEDIDA
	FROM (
		SELECT POSITIONSEQ_PRIN, PARTICIPANTSEQ, PERIODSEQ, N_MEDIDA, MAX(V_MEDIDA) AS V_MEDIDA
		FROM EXT.OUT_RA_RESUMEN_REP RA
		WHERE RA.N_MEDIDA IN ('SM-E-R-Agente-PagoMensual', 'SM-E-S-Agente-PagoMensual', 'SM-E-R-Agente-M-PagoMensual')
		AND RA.V_MEDIDA <> 0
		GROUP BY POSITIONSEQ_PRIN, PARTICIPANTSEQ, PERIODSEQ, N_MEDIDA
	) GROUP BY POSITIONSEQ_PRIN, PARTICIPANTSEQ, PERIODSEQ), "TOTAL_RAPPEL_317" AS (SELECT POSITIONSEQ_PRIN, PARTICIPANTSEQ, PERIODSEQ, SUM(V_MEDIDA) AS V_MEDIDA
	FROM (
		SELECT POSITIONSEQ_PRIN, PARTICIPANTSEQ, PERIODSEQ, N_MEDIDA, MAX(V_MEDIDA) AS V_MEDIDA
		FROM EXT.OUT_RA_RESUMEN_REP RA
		WHERE RA.N_MEDIDA IN ('SM-E-R-Agente-Tipo317-PagoMensual', 'SM-E-SR-Agente-Tipo317-PagoMensual')
		AND RA.V_MEDIDA <> 0
		GROUP BY POSITIONSEQ_PRIN, PARTICIPANTSEQ, PERIODSEQ, N_MEDIDA
	) GROUP BY POSITIONSEQ_PRIN, PARTICIPANTSEQ, PERIODSEQ) SELECT DISTINCT
	J.COD_REGIONAL || ' - ' || J.REGIONAL AS REGIONAL,
	J.COD_SUCURSAL || ' - ' || J.SUCURSAL AS SUCURSAL,
	S4_E_POLIZAS.COD_OFICINA || ' - ' || S4_E_POLIZAS.OFICINA AS OFICINA_CONCAT,
	S4_E_POLIZAS.POS_PRIN AS "POSICION PRINCIPAL",
	IFNULL(' ' || S4_E_POLIZAS.CUADRO_RRGG,'')
		|| ' -' || IFNULL(' ' || S4_E_POLIZAS.CUADRO_RRTT,'')
		|| ' - ' || S4_E_POLIZAS.NOMBRE AS AGENTE,
	S4_E_POLIZAS.NIF,
	S4_E_POLIZAS.TIPO_AGENTE AS "TIPO AGENTE",
	RIGHT(S4_E_POLIZAS.PRODUCTID,5) || ' - ' || S4_E_POLIZAS.PRODUCTO AS PRODUCTO,
	S4_E_POLIZAS.POSITIONSEQ_PRIN AS POSITION_SEQ,
	S4_E_POLIZAS.POSITIONSEQ_PRIN AS POSITIONSEQ,
	S4_E_POLIZAS.COD_OFICINA AS GEST,
	RIGHT(S4_E_POLIZAS.POSITIONNAME,6) AS "COD. AGENTE",
	S4_E_POLIZAS.POLIZA,
	S4_E_POLIZAS.POLIZ_NP,
	TO_VARCHAR(S4_E_POLIZAS.FEC_CARGO, 'MM-yyyy') AS "FEC. CARGO",
	-- NEW COLUMN: IMPUTACIÓN PÓLIZA CORREGIDA - RAPPEL
	CASE
		WHEN S4_E_POLIZAS.ID_TIPO_AGENTE = 317
			THEN IFNULL((TOTAL_RAPPEL_317.V_MEDIDA*S4_E_POLIZAS.POLIZ_CORR)/SUMA.SUM_POLIZ_CORR, 0)
		ELSE IFNULL((TOTAL_RAPPEL.V_MEDIDA*S4_E_POLIZAS.POLIZ_CORR)/SUMA.SUM_POLIZ_CORR, 0)
		END AS "IMPUTACIÓN POL. CORR. - RAPPEL",
	-- END NEW COLUMN
	IFNULL(S4_E_POLIZAS.POLIZ_CORR, 0) AS "POLIZA CORREGIDA",
	SUMA.SUM_POLIZ_CORR AS "SUMA POLIZA CORREGIDA",
	IFNULL(TO_INTEGER(S4_E_POLIZAS.ASEGURADOS), 0) AS "Nº ASEGURADOS",
	CASE
		WHEN S4_E_POLIZAS.NAME LIKE '%Recuperadas%'
			THEN 'Recuperación'
		WHEN S4_E_POLIZAS.NAME LIKE '%DC-E-SER-COM%'
			THEN 'CA 13 Comisión'
		WHEN S4_E_POLIZAS.NAME LIKE '%DC-E-SER-SUBV%'
			THEN 'CA 13 Gratificación'
		WHEN S4_E_POLIZAS.EVENTO LIKE '%Alta Nueva Pr%'
			THEN 'Alta N. P.'
		WHEN S4_E_POLIZAS.EVENTO LIKE '%Recibo Cart%'
			THEN 'R. Cartera'
		WHEN S4_E_POLIZAS.EVENTO LIKE '%Rehab%'
			THEN 'Rehab.'
		ELSE S4_E_POLIZAS.EVENTO
		END "TIPO RECIBO",
	CASE
		WHEN S4_E_POLIZAS.ID_TIPO_AGENTE = 317
			THEN IFNULL(TOTAL_RAPPEL_317.V_MEDIDA, 0)
		ELSE IFNULL(TOTAL_RAPPEL.V_MEDIDA, 0)
		END AS SUMA_V_MEDIDA,
	TO_VARCHAR(CASE WHEN F.ULTIMA_ACTUALIZACION > LAST_DAY(J.STARTDATE)
        THEN LAST_DAY(J.STARTDATE)
        ELSE F.ULTIMA_ACTUALIZACION
        END,'DD/MM/YYYY') AS LASTUPDATE,
	SUBSTR_AFTER(S4_E_POLIZAS.PERIODO, ' ') || CASE 
		WHEN SUBSTR_BEFORE(S4_E_POLIZAS.PERIODO, ' ') = 'Enero' THEN ' 01 '
		WHEN SUBSTR_BEFORE(S4_E_POLIZAS.PERIODO, ' ') = 'Febrero' THEN ' 02 '
		WHEN SUBSTR_BEFORE(S4_E_POLIZAS.PERIODO, ' ') = 'Marzo' THEN ' 03 '
		WHEN SUBSTR_BEFORE(S4_E_POLIZAS.PERIODO, ' ') = 'Abril' THEN ' 04 '
		WHEN SUBSTR_BEFORE(S4_E_POLIZAS.PERIODO, ' ') = 'Mayo' THEN ' 05 '
		WHEN SUBSTR_BEFORE(S4_E_POLIZAS.PERIODO, ' ') = 'Junio' THEN ' 06 '
		WHEN SUBSTR_BEFORE(S4_E_POLIZAS.PERIODO, ' ') = 'Julio' THEN ' 07 '
		WHEN SUBSTR_BEFORE(S4_E_POLIZAS.PERIODO, ' ') = 'Agosto' THEN ' 08 '
		WHEN SUBSTR_BEFORE(S4_E_POLIZAS.PERIODO, ' ') = 'Septiembre' THEN ' 09 '
		WHEN SUBSTR_BEFORE(S4_E_POLIZAS.PERIODO, ' ') = 'Octubre' THEN ' 10 '
		WHEN SUBSTR_BEFORE(S4_E_POLIZAS.PERIODO, ' ') = 'Noviembre' THEN ' 11 '
		WHEN SUBSTR_BEFORE(S4_E_POLIZAS.PERIODO, ' ') = 'Diciembre' THEN ' 12 '
		END || SUBSTR_BEFORE(S4_E_POLIZAS.PERIODO, ' ') AS PERIODO,
	S4_E_POLIZAS.PERIODSEQ
FROM EXT.OUT_S4_E_POLIZAS_REP S4_E_POLIZAS
INNER JOIN EXT.OUT_JERARQUIA_REP J ON S4_E_POLIZAS.PERIODSEQ = J.PERIODSEQ
 	AND S4_E_POLIZAS.PARTICIPANTSEQ = J.PARTICIPANTSEQ
 	AND S4_E_POLIZAS.POSITIONSEQ_PRIN = J.POSITIONSEQ_PRIN
 	-- START COMMON TABLE EXPRESSION
	LEFT JOIN TOTAL_RAPPEL_317 ON S4_E_POLIZAS.PERIODSEQ = TOTAL_RAPPEL_317.PERIODSEQ
		AND S4_E_POLIZAS.PARTICIPANTSEQ = TOTAL_RAPPEL_317.PARTICIPANTSEQ
	 	AND S4_E_POLIZAS.POSITIONSEQ_PRIN = TOTAL_RAPPEL_317.POSITIONSEQ_PRIN
	LEFT JOIN TOTAL_RAPPEL ON S4_E_POLIZAS.PERIODSEQ = TOTAL_RAPPEL.PERIODSEQ
		AND S4_E_POLIZAS.PARTICIPANTSEQ = TOTAL_RAPPEL.PARTICIPANTSEQ
	 	AND S4_E_POLIZAS.POSITIONSEQ_PRIN = TOTAL_RAPPEL.POSITIONSEQ_PRIN
	INNER JOIN SUMA ON S4_E_POLIZAS.PERIODSEQ = SUMA.PERIODSEQ
		AND S4_E_POLIZAS.PARTICIPANTSEQ = SUMA.PARTICIPANTSEQ
	 	AND S4_E_POLIZAS.POSITIONSEQ_PRIN = SUMA.POSITIONSEQ_PRIN
	 -- END COMMON TABLE EXPRESSION
LEFT JOIN EXT.OUT_FECHAS_WEBI_REP F ON F.PERIODO = J.PERIODO
    AND F.TABLA = 'OUT_S4_E_POLIZAS_REP'
WHERE
	S4_E_POLIZAS.POLIZ_CORR <> 0
	AND S4_E_POLIZAS.ID_TIPO_AGENTE IN (317, 319, 332, 338, 340, 341)
	AND S4_E_POLIZAS.FEC_CARGO IS NOT NULL ORDER BY "POSICION PRINCIPAL", "FEC. CARGO", POLIZA) WITH READ ONLY STRUCTURED PRIVILEGE CHECK