CREATE OR REPLACE VIEW "EXT"."CSA_CARTERA_AGENTES_SVW"(
	"YEAR",
	"COMPANIA",
	"AGENTE",
	"NIF_NOMBRE",
	"TIPO",
	"TABLA",
	"PRODUCTO",
	"POLIZAS",
	"PRIMAS",
	"PRODUCCION",
	"CARTERA",
	"TOTAL",
	"ULTIMA_ACTUALIZACION",
	"POSITIONSEQ",
	"PERIODSEQ") AS
( 		(SELECT 
			"YEAR",
			"COMPANIA",
			"AGENTE",
			NIF || ' - '|| RIGHT(AGENTE, LENGTH(AGENTE) - 10) || ' - ' || SUBSTR(AGENTE, 6, 4) AS NIF_NOMBRE,
			CASE WHEN ID_TIPO_AGENTE IN (5,6)
				THEN 'CORREDORES'
				ELSE 'AGENTES'
				END AS TIPO,
			"TABLA",
			"PRODUCTO",
			"POLIZAS",
			"PRIMAS",
			"PRODUCCION",
			"CARTERA",
			"TOTAL",
			"ULTIMA_ACTUALIZACION",
			"POSITIONSEQ",
			"PERIODSEQ"
		FROM EXT.OUT_CARTERA_AGENTES_FINAL_REP
		WHERE PERIODSEQ IN (SELECT PERIODSEQ FROM EXT.LIB_CREAR_TABLAS:N_MESES(13)) ))
WITH STRUCTURED PRIVILEGE CHECK;
