CREATE VIEW "EXT"."VW_COMPARAR_GARANTIAS_RECIBOS_DEBUG"("LINE") AS
( 		(SELECT "LINE"
		FROM 
			(
				(SELECT 'CODIGO_POLIZA;CODIGO_RECIBO;CLAVE3;PRODUCTO_CONTABLE;ESTADO_RECIBO;PRIMA_NETA_RECIBO;PRIMA_BRUTA_RECIBO;RECARGO;PORCENTAJE_BONIFICACION;INCREMENTO_PRIMA_ANUAL;PRIMA_COMISIONABLE;UNIDAD_DE_POLIZA;MESES_COBRADOS;FECHA_ALTA_GAR_POL;FECHA_BAJA_GAR_POL;PORCENTAJE_NIVELADA;PERIODO_EXTORNABLE;INDICADOR_COMISION_CALCULADA;INDICADOR_PORCENTAJE_CALCULA;PORCENTAJE_COMISION_CALCULAD;IMPORTE_COMISION;PRIMA_UNICA;NUM_ORDEN_MOVIMIENTO;AUMENTO_CAPITALES_GARANTIA;PRIMA_NETA_ANUALIZADA;PORC_COMISION_NP;PORC_COMISION_CONSERVACION;CODIGO_SUPLEMENTO;FILE_NAME;PORC_COMISION_COBRO' AS LINE
				FROM DUMMY

				UNION ALL

				SELECT LINE AS LINE
				FROM EXT.COMPARAR_GARANTIAS_RECIBOS_DEBUG)
			)
		ORDER BY 
			CASE
				WHEN LINE = 'CODIGO_POLIZA;CODIGO_RECIBO;CLAVE3;PRODUCTO_CONTABLE;ESTADO_RECIBO;PRIMA_NETA_RECIBO;PRIMA_BRUTA_RECIBO;RECARGO;PORCENTAJE_BONIFICACION;INCREMENTO_PRIMA_ANUAL;PRIMA_COMISIONABLE;UNIDAD_DE_POLIZA;MESES_COBRADOS;FECHA_ALTA_GAR_POL;FECHA_BAJA_GAR_POL;PORCENTAJE_NIVELADA;PERIODO_EXTORNABLE;INDICADOR_COMISION_CALCULADA;INDICADOR_PORCENTAJE_CALCULA;PORCENTAJE_COMISION_CALCULAD;IMPORTE_COMISION;PRIMA_UNICA;NUM_ORDEN_MOVIMIENTO;AUMENTO_CAPITALES_GARANTIA;PRIMA_NETA_ANUALIZADA;PORC_COMISION_NP;PORC_COMISION_CONSERVACION;CODIGO_SUPLEMENTO;FILE_NAME;PORC_COMISION_COBRO' THEN 0
				ELSE 1
			END ASC, 
			LINE ASC) )
WITH READ ONLY;
