CREATE VIEW "EXT"."VW_COMPARAR_RECIBOS_DEBUG"("LINE") AS
( 		(SELECT "LINE"
		FROM 
			(
				(SELECT 'CODIGO_POLIZA;CODIGO_RECIBO;CODIGO_SUPLEMENTO;ZONA_EXPLOTACION;CODIGO_AGENTE_ZONA;PERMANENCIA;TIPO_RECIBO;ESTADO_RECIBO;FECHA_COBRO;FECHA_COMPENSACION;FECHA_EFECTO_RECIBO;FECHA_VTO_RECIBO;TIPO_MOVIMIENTO;PORCENTAJE_DESCUENTO_SOBRE_PC;VALOR_POLIZA;CODIGO_UNICO_AGENTE;CODIGO_AGENTE_ORIGINAL;INSPECTOR;OFICINA_COBRADORA;OFICINA_GESTORA;MARCA_RECUPERADO;MARCA_CUENTA;PRIMER_RECIBO;ASEGURADOS_NETOS;AUMENTO_ASEGURADOS;EXCLUIDO_COMISIONES;BONIFICACION_POLIZA;DISMINUCION_PRIMA;TIPO_RECUPERACION;ES_PERMANENCIA_20;CODIGO_AGENTE_COMMISSIONS;FECHA_EMISION_REC;FCHA_EFECTO_SUPLEMENTO;DISTRITO_COBRO;CODIGO_SINIESTRO;FILE_NAME' AS LINE
				FROM DUMMY

				UNION ALL

				SELECT LINE AS LINE
				FROM EXT.COMPARAR_RECIBOS_DEBUG)
			)
		ORDER BY 
			CASE
				WHEN LINE = 'CODIGO_POLIZA;CODIGO_RECIBO;CODIGO_SUPLEMENTO;ZONA_EXPLOTACION;CODIGO_AGENTE_ZONA;PERMANENCIA;TIPO_RECIBO;ESTADO_RECIBO;FECHA_COBRO;FECHA_COMPENSACION;FECHA_EFECTO_RECIBO;FECHA_VTO_RECIBO;TIPO_MOVIMIENTO;PORCENTAJE_DESCUENTO_SOBRE_PC;VALOR_POLIZA;CODIGO_UNICO_AGENTE;CODIGO_AGENTE_ORIGINAL;INSPECTOR;OFICINA_COBRADORA;OFICINA_GESTORA;MARCA_RECUPERADO;MARCA_CUENTA;PRIMER_RECIBO;ASEGURADOS_NETOS;AUMENTO_ASEGURADOS;EXCLUIDO_COMISIONES;BONIFICACION_POLIZA;DISMINUCION_PRIMA;TIPO_RECUPERACION;ES_PERMANENCIA_20;CODIGO_AGENTE_COMMISSIONS;FECHA_EMISION_REC;FCHA_EFECTO_SUPLEMENTO;DISTRITO_COBRO;CODIGO_SINIESTRO;FILE_NAME' THEN 0
				ELSE 1
			END ASC, 
			LINE ASC) )
WITH READ ONLY;
