CREATE VIEW "EXT"."VW_COMPARAR_ASEGURADOS_DEBUG"("LINE") AS
( 		(SELECT "LINE"
		FROM 
			(
				(SELECT 'CODIGO_POLIZA;NUMERO_ASEGURADO;NIF;FECHA_NACIMIENTO;FECHA_DE_DERECHOS;MOTIVO_ALTA;CONTO_COMO_ALTA;CONTO_COMO_NUEVO;FECHA_ALTA;MOTIVO_BAJA;FECHA_BAJA;FECHA_REHABILITACION;POLIZA_ORIGEN;ASEGURADO_ORIGEN;EDAD;EDAD_DERECHOS;FILE_NAME' AS LINE
				FROM DUMMY

				UNION ALL

				SELECT LINE AS LINE
				FROM EXT.COMPARAR_ASEGURADOS_DEBUG)
			)
		ORDER BY 
			CASE
				WHEN LINE = 'CODIGO_POLIZA;NUMERO_ASEGURADO;NIF;FECHA_NACIMIENTO;FECHA_DE_DERECHOS;MOTIVO_ALTA;CONTO_COMO_ALTA;CONTO_COMO_NUEVO;FECHA_ALTA;MOTIVO_BAJA;FECHA_BAJA;FECHA_REHABILITACION;POLIZA_ORIGEN;ASEGURADO_ORIGEN;EDAD;EDAD_DERECHOS;FILE_NAME' THEN 0
				ELSE 1
			END ASC, 
			LINE ASC) )
WITH READ ONLY;
