CREATE VIEW "EXT"."VW_COMPARAR_POLIZAS_DEBUG"("LINE") AS
( 		(SELECT "LINE"
		FROM 
			(
				(SELECT 'CODIGO_POLIZA;RAMO;MOTIVO_ALTA;FILE_NAME;FECHA_EFECTO_POLIZA;FECHA_EMISION_POLIZA;FECHA_CESION_POLIZA;MOTIVO_BAJA;FECHA_BAJA;FECHA_VENCIMIENTO;FECHA_REHABILITACION;FORMA_PAGO;TIPO_CAMPANIA;SEGUNDA_RESIDENCIA;TARIFA;ZONA;CLAVE_RIESGO;MODALIDAD;DURACION;CLAUSULA;SUSTITUCION_INCENDIOS;EXCLUIDO_COMISIONES;TRASPASADA;DESCUENTO_IMPORTE_SINIESTRALID;DESCUENTO_POR_PRIORITARIO;RIESGO;COLECTIVO;AUTOLIQUIDA;KILOMETROS;MOVILIDAD;POLIZA_CON_AGENTE;AGENTE_CARTERA;IMP_COMISION_CARTERA;PORC_COMISION_CARTERA;FECHA_FIN_COMISION_CARTERA' AS LINE
				FROM DUMMY

				UNION ALL

				SELECT LINE
				FROM EXT.COMPARAR_POLIZAS_DEBUG)
			)
		ORDER BY 
			CASE
				WHEN LINE = 'CODIGO_POLIZA;RAMO;MOTIVO_ALTA;FILE_NAME;FECHA_EFECTO_POLIZA;FECHA_EMISION_POLIZA;FECHA_CESION_POLIZA;MOTIVO_BAJA;FECHA_BAJA;FECHA_VENCIMIENTO;FECHA_REHABILITACION;FORMA_PAGO;TIPO_CAMPANIA;SEGUNDA_RESIDENCIA;TARIFA;ZONA;CLAVE_RIESGO;MODALIDAD;DURACION;CLAUSULA;SUSTITUCION_INCENDIOS;EXCLUIDO_COMISIONES;TRASPASADA;DESCUENTO_IMPORTE_SINIESTRALID;DESCUENTO_POR_PRIORITARIO;RIESGO;COLECTIVO;AUTOLIQUIDA;KILOMETROS;MOVILIDAD;POLIZA_CON_AGENTE;AGENTE_CARTERA;IMP_COMISION_CARTERA;PORC_COMISION_CARTERA;FECHA_FIN_COMISION_CARTERA' THEN 0
				ELSE 1
			END ASC, 
			LINE ASC) )
WITH READ ONLY;
