CREATE VIEW "EXT"."VW_COMPARAR_GARANTIAS_ASEGURADOS_DEBUG"("LINE") AS
( 		(SELECT "LINE"
		FROM 
			(
				(SELECT 'CLAVE1;NUMERO_ASEGURADO;PRIMA_NETA_ASEGURADO;PRIMA_UNICA;GARANTIA_IP;PORCENTAJE_PARTICIPACION;PORCENTAJE_NIVELADA;CAPITAL_NATURAL;CAPITAL_NIVELADO;SUBTIPO_MOVIMIENTO;MARCA_CUENTA;PRIMA_COMISIONABLE;UNIDAD_DE_POLIZA;MESES_COBRADOS;FECHA_ALTA_GAR_ASE;FECHA_BAJA_GAR_ASE;NUM_ORDEN_MOVIMIENTO;FILE_NAME;PC_PERIODO;NUM_PERIODOS' AS LINE
				FROM DUMMY

				UNION ALL

				SELECT LINE AS LINE
				FROM EXT.COMPARAR_GARANTIAS_ASEGURADOS_DEBUG)
			)
		ORDER BY 
			CASE
				WHEN LINE = 'CLAVE1;NUMERO_ASEGURADO;PRIMA_NETA_ASEGURADO;PRIMA_UNICA;GARANTIA_IP;PORCENTAJE_PARTICIPACION;PORCENTAJE_NIVELADA;CAPITAL_NATURAL;CAPITAL_NIVELADO;SUBTIPO_MOVIMIENTO;MARCA_CUENTA;PRIMA_COMISIONABLE;UNIDAD_DE_POLIZA;MESES_COBRADOS;FECHA_ALTA_GAR_ASE;FECHA_BAJA_GAR_ASE;NUM_ORDEN_MOVIMIENTO;FILE_NAME;PC_PERIODO;NUM_PERIODOS' THEN 0
				ELSE 1
			END ASC, 
			LINE ASC) )
WITH READ ONLY;
