CREATE VIEW "EXT"."VW_COMPARAR_TA_DEBUG"("LINE") AS
( 		(SELECT "LINE"
		FROM 
			(
				(SELECT 'ORDERID;LINENUMBER;CLAVE3;PAYEEID;PAYEETYPE;POSITIONNAME;TITLENAME;GENERICATTRIBUTE1;GENERICATTRIBUTE2;GENERICATTRIBUTE3;GENERICATTRIBUTE4;GENERICATTRIBUTE5;GENERICATTRIBUTE6;GENERICATTRIBUTE7;GENERICATTRIBUTE8;GENERICATTRIBUTE9;GENERICATTRIBUTE10;GENERICATTRIBUTE11;GENERICATTRIBUTE12;GENERICATTRIBUTE13;GENERICATTRIBUTE14;GENERICATTRIBUTE15;GENERICATTRIBUTE16;GENERICNUMBER1;UNITTYPEFORGENERICNUMBER1;GENERICNUMBER2;UNITTYPEFORGENERICNUMBER2;GENERICNUMBER3;UNITTYPEFORGENERICNUMBER3;GENERICNUMBER4;UNITTYPEFORGENERICNUMBER4;GENERICNUMBER5;UNITTYPEFORGENERICNUMBER5;GENERICNUMBER6;UNITTYPEFORGENERICNUMBER6;GENERICDATE1;GENERICDATE2;GENERICDATE3;GENERICDATE4;GENERICDATE5;GENERICDATE6;GENERICBOOLEAN1;GENERICBOOLEAN2;GENERICBOOLEAN3;GENERICBOOLEAN4;GENERICBOOLEAN5;GENERICBOOLEAN6;BATCHNAME' AS LINE
				FROM DUMMY

				UNION ALL

				SELECT LINE AS LINE
				FROM EXT.COMPARAR_TA_DEBUG)
			)
		ORDER BY 
			CASE
				WHEN LINE = 'ORDERID;LINENUMBER;CLAVE3;PAYEEID;PAYEETYPE;POSITIONNAME;TITLENAME;GENERICATTRIBUTE1;GENERICATTRIBUTE2;GENERICATTRIBUTE3;GENERICATTRIBUTE4;GENERICATTRIBUTE5;GENERICATTRIBUTE6;GENERICATTRIBUTE7;GENERICATTRIBUTE8;GENERICATTRIBUTE9;GENERICATTRIBUTE10;GENERICATTRIBUTE11;GENERICATTRIBUTE12;GENERICATTRIBUTE13;GENERICATTRIBUTE14;GENERICATTRIBUTE15;GENERICATTRIBUTE16;GENERICNUMBER1;UNITTYPEFORGENERICNUMBER1;GENERICNUMBER2;UNITTYPEFORGENERICNUMBER2;GENERICNUMBER3;UNITTYPEFORGENERICNUMBER3;GENERICNUMBER4;UNITTYPEFORGENERICNUMBER4;GENERICNUMBER5;UNITTYPEFORGENERICNUMBER5;GENERICNUMBER6;UNITTYPEFORGENERICNUMBER6;GENERICDATE1;GENERICDATE2;GENERICDATE3;GENERICDATE4;GENERICDATE5;GENERICDATE6;GENERICBOOLEAN1;GENERICBOOLEAN2;GENERICBOOLEAN3;GENERICBOOLEAN4;GENERICBOOLEAN5;GENERICBOOLEAN6;BATCHNAME' THEN 0
				ELSE 1
			END ASC, 
			LINE ASC) )
WITH READ ONLY;
