CREATE VIEW "EXT"."VW_GEN_PRODUCTOS"(
	"CODIGO",
	"PRODUCTO",
	"PERIODO_EXTORNABLE",
	"UNIDAD_DE_POLIZA",
	"COMISION_ANTICIPADA",
	"UNIDAD_DE_CUENTA",
	"COMISION_CARTERA",
	"PAGO_MENSUAL",
	"DIFERENCIAL_ANTICIPADO",
	"COND_ESP_RESCATE") AS
( 		(SELECT 
			CL.CLASSIFIERID AS CODIGO,
			CL.NAME AS PRODUCTO,
			PROD.GENERICNUMBER2 AS PERIODO_EXTORNABLE,
			PROD.GENERICNUMBER3 AS UNIDAD_DE_POLIZA,
			PROD.GENERICBOOLEAN6 AS COMISION_ANTICIPADA,
			PROD.GENERICBOOLEAN4 AS UNIDAD_DE_CUENTA,
			PROD.GENERICATTRIBUTE9 AS COMISION_CARTERA,
			PROD.GENERICATTRIBUTE10 AS PAGO_MENSUAL,
			PROD.GENERICATTRIBUTE11 AS DIFERENCIAL_ANTICIPADO,
			PROD.GENERICATTRIBUTE12 AS COND_ESP_RESCATE
		FROM 
			TCMP.CS_CLASSIFIER AS CL
			INNER JOIN
			TCMP.CS_PRODUCT AS PROD
			ON CL.CLASSIFIERSEQ = PROD.CLASSIFIERSEQ
				AND PROD.REMOVEDATE = TO_DATE( '22000101', 'YYYYMMDD' )
				AND PROD.ISLAST = 1
		WHERE CL.REMOVEDATE = TO_DATE( '22000101', 'YYYYMMDD' )
			AND CL.ISLAST = 1) )
WITH READ ONLY;
