CREATE VIEW "EXT"."VW_MOTIVOS_BAJA"(
	"CODIGO",
	"DESCRIPCION",
	"CUENTA_COMO_BAJA",
	"EXTORNABLE") AS
( 		(SELECT 
			c.classifierid AS "CODIGO",
			c.description AS "DESCRIPCION",
			gc.genericboolean1 AS "CUENTA_COMO_BAJA",
			gc.genericboolean2 AS "EXTORNABLE"
		FROM 
			TCMP.CS_CLASSIFIER AS c
			INNER JOIN
			TCMP.CS_GENERICCLASSIFIER AS gc
			ON C.CLASSIFIERSEQ = GC.CLASSIFIERSEQ
				AND gc.REMOVEDATE = TO_DATE( '22000101', 'yyyymmdd' )
				AND gc.islast = 1
			INNER JOIN
			TCMP.CS_CATEGORY_CLASSIFIERS AS ccc
			ON ccc.CLASSIFIERSEQ = c.CLASSIFIERSEQ
				AND CCC.REMOVEDATE = TO_DATE( '22000101', 'yyyymmdd' )
				AND CCC.ISLAST = 1
			INNER JOIN
			TCMP.CS_CATEGORYTREE AS CT
			ON CCC.CATEGORYTREESEQ = CT.CATEGORYTREESEQ
				AND ct.REMOVEDATE = TO_DATE( '22000101', 'yyyymmdd' )
				AND ct.ISLAST = 1
		WHERE ct.NAME = 'Motivos Baja'
			AND --and c.classifierid = 'Bonificacion Poliza'
			c.REMOVEDATE = TO_DATE( '22000101', 'yyyymmdd' )
			AND c.ISLAST = 1) )
WITH READ ONLY;
