CREATE VIEW "EXT"."VW_OUT_AUDITORIA_INF_LIQ_FILE"("LINE") AS
( 		(SELECT "LINE"
		FROM 
			(
				(SELECT LINE
				FROM EXT.OUT_AUDITORIA_INF_LIQ_FILE

				UNION ALL

				SELECT NULL
				FROM DUMMY)
			)
		ORDER BY 
			CASE
				WHEN LINE IS NULL THEN 1
				ELSE 0
			END ASC, 
			LINE ASC) )
WITH READ ONLY;
