CREATE VIEW "EXT"."VW_OUT_REPEXT_INR_SAP_FILE"("LINE") AS
( 		(SELECT LINE
		FROM 
			(
				(SELECT LINE
				FROM EXT.OUT_REPEXT_INR_SAP_FILE

				UNION ALL

				SELECT NULL
				FROM DUMMY)
			) AS V
		ORDER BY 
			CASE
				WHEN LINE IS NULL OR LINE = '' THEN 1
				ELSE 0
			END ASC, 
			SUBSTR( LINE, 7, 10 ) ASC, 
			SUBSTR( LINE, 18, 23 ) ASC, 
			SUBSTR( LINE, 1, 2 ) ASC, 
			SUBSTR( LINE, 100, 3 ) ASC, 
			SUBSTR( LINE, 109, 5 ) ASC, 
			LINE ASC) )
WITH READ ONLY;
