CREATE VIEW "EXT"."VW_OUT_REPEXT_INF_PYG_OC_FILE"("LINE") AS
( 		(SELECT LINE
		FROM 
			(
				(SELECT LINE
				FROM EXT.OUT_REPEXT_INF_PYG_OC_FILE

				UNION ALL

				SELECT NULL
				FROM DUMMY)
			) AS V
		ORDER BY 
			CASE
				WHEN LINE IS NULL OR LINE = '' THEN 1
				ELSE 0
			END ASC, 
			SUBSTR( LINE, 1, 2 ) ASC, 
			SUBSTR( LINE, 64, 4 ) ASC, 
			SUBSTR( LINE, 96, 4 ) ASC, 
			SUBSTR( LINE, 44, 5 ) ASC, 
			SUBSTR( LINE, 25, 19 ) ASC) )
WITH READ ONLY;
