WITH  pos_ids AS (
    SELECT DISTINCT RULEELEMENTOWNERSEQ
    FROM CS_POSITION pos
    WHERE pos.removeDate = TO_DATE('22000101', 'YYYYMMDD')
      AND pos.effectiveEndDate >= '2020-01-01'
), 
"ESTRUCTURA" AS (SELECT X.NAME as EPOS_NAME,X.RULEELEMENTOWNERSEQ as EPOSITIONSEQ,
		X.GENERICATTRIBUTE2 EPOS_GENERICATTRIBUTE2, X.GENERICATTRIBUTE3 AS EPOS_GENERICATTRIBUTE3,
		TO_INTEGER(X.GENERICNUMBER2) AS EPOS_GENERICNUMBER2, X.GENERICNUMBER3 AS EPOS_GENERICNUMBER3,
		IFNULL(RTRIM(Y.FIRSTNAME) || ' ','')  || IFNULL(RTRIM(Y.LASTNAME),'') || IFNULL(' ' || RTRIM(Y.SUFFIX), '') AS NOMBRE_COMPLETO, 
        Y.FIRSTNAME,Y.LASTNAME,Y.SUFFIX,Y.GENERICATTRIBUTE1 AS NIF, X.MANAGERSEQ as EPOS_MANAGERSEQ,
        Y.USERID as EPAR_USERID,
        Z.NAME AS ETITLE,
    	X.EFFECTIVESTARTDATE as EPOS_EFFECTIVESTARTDATE, X.EFFECTIVEENDDATE as EPOS_EFFECTIVEENDDATE,
		Y.EFFECTIVESTARTDATE as EPAR_EFFECTIVESTARTDATE, Y.EFFECTIVEENDDATE as EPAR_EFFECTIVEENDDATE,
		Z.EFFECTIVESTARTDATE as ETIT_EFFECTIVESTARTDATE, Z.EFFECTIVEENDDATE as ETIT_EFFECTIVEENDDATE
    FROM 
	TCMP.CS_POSITION X 
        INNER JOIN TCMP.CS_PARTICIPANT Y ON Y.PAYEESEQ = X.PAYEESEQ and Y.REMOVEDATE = TO_DATE('22000101','yyyymmdd')  
        			AND X.EFFECTIVESTARTDATE <= Y.EFFECTIVEENDDATE and X.EFFECTIVEENDDATE >= Y.EFFECTIVESTARTDATE
    	INNER JOIN TCMP.CS_PAYEE R ON Y.PAYEESEQ = R.PAYEESEQ and R.REMOVEDATE = TO_DATE('22000101','yyyymmdd')
        			AND Y.EFFECTIVESTARTDATE = R.EFFECTIVESTARTDATE and Y.EFFECTIVEENDDATE = R.EFFECTIVEENDDATE
    	INNER JOIN TCMP.CS_TITLE Z ON X.TITLESEQ = Z.RULEELEMENTOWNERSEQ AND Z.REMOVEDATE = TO_DATE('22000101','yyyymmdd') 
        			AND X.EFFECTIVESTARTDATE <= Z.EFFECTIVEENDDATE and X.EFFECTIVEENDDATE >= Z.EFFECTIVESTARTDATE
        where X.REMOVEDATE = TO_DATE('22000101','yyyymmdd')) 
SELECT 
IFNULL(PAR.PARTICIPANTEMAIL,' '), -- Correo electrónico
PAR.TAXID , -- Tipo de IRPF
POS.EFFECTIVESTARTDATE as POS_EFFECTIVESTARTDATE, -- Fecha Inicio Efectividad
IFNULL(CASE WHEN POS.EFFECTIVEENDDATE = '22000101' THEN ADD_YEARS(POS.EFFECTIVEENDDATE, -100) ELSE ADD_SECONDS(POS.EFFECTIVEENDDATE, -1) END, ' ') as POS_EFFECTIVEENDDATE, -- Fecha Fin Efectividad, restado un segundo o 100 años
null AS PERIODNAME, 
null as PERIODSHORTNAME, 
null AS PERIODDESCRIPTION, 
null as STARTDATE, 
null as ENDDATE, 
IFNULL(RTRIM(PAR.FIRSTNAME) || ' ','')  || IFNULL(RTRIM(PAR.LASTNAME),'') || IFNULL(' ' || RTRIM(PAR.SUFFIX), '') AS NOMBRE_COMPLETO, 
null as PERIODSEQ, 
POS.RULEELEMENTOWNERSEQ as POSITIONSEQ, 
par.PAYEESEQ,
r.PAYEEID as PARTICIPANTID,
par.USERID, -- Usuario LDAP
par.PREFIX, -- NULL
par.FIRSTNAME, -- Nombre
par.MIDDLENAME, -- Email personal
par.LASTNAME, -- Apellido 1/Razón social
par.SUFFIX, -- Apellido 2
null as FULLNAME,
par.SALARY, -- Pago por IBAN
par.HIREDATE, -- Fecha de Contrato
par.TERMINATIONDATE, -- Fecha Fin Agente
null as BUSINESSUNITMAP, 
null as BUSINESSUNITNAME, 
POS.NAME as POSITIONNAME, -- Posición
null as DESCRIPTION, -- Descripción Posición
null as POSITIONGROUPNAME, -- Grupo de Posición
tit.NAME, -- Título
null as DESCRIPTION, -- Descripción Título
POS.TARGETCOMPENSATION, -- Objetivo Comisiones
null as PLANNAME, -- PLAN
null PLANSEQ, 
IFNULL(POS.GENERICATTRIBUTE1,' ') as POSITIONGENERICATTRIBUTE1, -- Tipo Principal Agente / Clase Oficina (GA1)
IFNULL(TO_VARCHAR(TO_INTEGER(POS.GENERICNUMBER2))  || ' - ','') || IFNULL(POS.GENERICATTRIBUTE2 ,'') as POSITIONGENERICATTRIBUTE2 , -- Tipo Agente / Tipo Oficina (GA2)
POS.GENERICATTRIBUTE3 as POSITIONGENERICATTRIBUTE3, -- Código de Agente OCASO (GA3)
POS.GENERICATTRIBUTE4 as POSITIONGENERICATTRIBUTE4, -- Rehabilitación (GA4)
POS.GENERICATTRIBUTE5 as POSITIONGENERICATTRIBUTE5, -- Cuadro Inspector Ocaso (GA5)
POS.GENERICATTRIBUTE6 as POSITIONGENERICATTRIBUTE6, -- Cuadro RRGG Ocaso (GA6)
POS.GENERICATTRIBUTE7 as POSITIONGENERICATTRIBUTE7, -- Cuadro RRTT Ocaso (GA7)
IFNULL(POS.GENERICATTRIBUTE8,' ') as POSITIONGENERICATTRIBUTE8, -- Compañía (GA8)
POS.GENERICATTRIBUTE9 as POSITIONGENERICATTRIBUTE9, -- Promoción Agente (GA9)
POS.GENERICATTRIBUTE10 as POSITIONGENERICATTRIBUTE10, -- Cuadro Inspector Eterna (GA10)
POS.GENERICATTRIBUTE11 as POSITIONGENERICATTRIBUTE11, -- Cuadro RRGG Eterna (GA11)
POS.GENERICATTRIBUTE12 as POSITIONGENERICATTRIBUTE12, -- Cuadro RRTT Eterna (GA12)
POS.GENERICATTRIBUTE13 as POSITIONGENERICATTRIBUTE13, -- Año Captación (GA13)
POS.GENERICATTRIBUTE14 as POSITIONGENERICATTRIBUTE14, -- Inspector Captador (GA14)
POS.GENERICATTRIBUTE15 as POSITIONGENERICATTRIBUTE15, -- Número Meses Preplan (GA15)
POS.GENERICATTRIBUTE16 as POSITIONGENERICATTRIBUTE16, -- Escalado Asistencia (GA16)
POS.GENERICNUMBER1 as POSITIONGENERICNUMBER1, -- ID Tipo Principal Agente (GN1)
POS.GENERICNUMBER2 as POSITIONGENERICNUMBER2, -- ID Tipo Agente (GN2)
POS.GENERICNUMBER3 as POSITIONGENERICNUMBER3, -- ID Clase Oficina (GN3)
POS.GENERICNUMBER4 as POSITIONGENERICNUMBER4, -- ID Tipo Oficina (GN4)
POS.GENERICNUMBER5 as POSITIONGENERICNUMBER5, -- % Comisión Cartera (GN5)
POS.GENERICNUMBER6 as POSITIONGENERICNUMBER6, -- Importe Comisión Cartera (GN6)
POS.GENERICDATE1 as POSITIONGENERICDATE1, -- Fecha de Alta (GD1)
POS.GENERICDATE2 as POSITIONGENERICDATE2, -- Fecha de Baja (GD2)
POS.GENERICDATE3 as POSITIONGENERICDATE3, -- Fecha Inicio Consolidación P.C. (GD3)
POS.GENERICDATE4 as POSITIONGENERICDATE4, -- Fecha Fin Consolidación P.C. (GD4)
POS.GENERICDATE5 as POSITIONGENERICDATE5, -- Fecha Inicio Asistencia (GD5)
POS.GENERICDATE6 as POSITIONGENERICDATE6, -- Fecha Límite Comisiones Cartera (GD6)
POS.GENERICBOOLEAN1 as POSITIONGENERICBOOLEAN1, -- Reducción (GB1)
POS.GENERICBOOLEAN2 as POSITIONGENERICBOOLEAN2, -- Productor Ocaso (GB2)
POS.GENERICBOOLEAN3 as POSITIONGENERICBOOLEAN3, -- Consolida (GB3)
POS.GENERICBOOLEAN4 as POSITIONGENERICBOOLEAN4, -- Inicio Agente Asistencia (GB4)
POS.GENERICBOOLEAN5 as POSITIONGENERICBOOLEAN5, -- Productor Eterna (GB5)
POS.GENERICBOOLEAN6 as POSITIONGENERICBOOLEAN6, -- Ag. Lider (GB6)
PAR.GENERICATTRIBUTE1 as PARTICIPANTGENERICATTRIBUTE1, -- Documento (GA1)
PAR.GENERICATTRIBUTE2 as PARTICIPANTGENERICATTRIBUTE2, -- Tipo Documento (GA2)
PAR.GENERICATTRIBUTE3 as PARTICIPANTGENERICATTRIBUTE3, -- Tipo Persona (GA3)
PAR.GENERICATTRIBUTE4 as PARTICIPANTGENERICATTRIBUTE4, -- Código DGS (GA4)
PAR.GENERICATTRIBUTE5 as PARTICIPANTGENERICATTRIBUTE5, -- Compañía (GA5)
PAR.GENERICATTRIBUTE6 as PARTICIPANTGENERICATTRIBUTE6, -- Tipo Mediador (GA6)
PAR.GENERICATTRIBUTE7 as PARTICIPANTGENERICATTRIBUTE7, -- Localidad (GA7)
PAR.GENERICATTRIBUTE8 as PARTICIPANTGENERICATTRIBUTE8, -- Tipo Vía (GA8)
PAR.GENERICATTRIBUTE9 as PARTICIPANTGENERICATTRIBUTE9, -- Domicilio (GA9)
PAR.GENERICATTRIBUTE10 as PARTICIPANTGENERICATTRIBUTE10, -- Número (GA10)
PAR.GENERICATTRIBUTE11 as PARTICIPANTGENERICATTRIBUTE11, -- Resto Domicilio (GA11)
PAR.GENERICATTRIBUTE12 as PARTICIPANTGENERICATTRIBUTE12, -- Sexo (GA12)
PAR.GENERICATTRIBUTE13 as PARTICIPANTGENERICATTRIBUTE13, -- Estado Civil (GA13)
PAR.GENERICATTRIBUTE14 as PARTICIPANTGENERICATTRIBUTE14, -- Teléfono Fijo (GA14)
PAR.GENERICATTRIBUTE15 as PARTICIPANTGENERICATTRIBUTE15, -- Teléfono Móvil (GA15)
PAR.GENERICATTRIBUTE16 as PARTICIPANTGENERICATTRIBUTE16, -- IBAN (GA16)
PAR.GENERICNUMBER1 as PARTICIPANTGENERICNUMBER1, -- Código Postal (GN1)
PAR.GENERICNUMBER2 as PARTICIPANTGENERICNUMBER2, -- Provincia (GN2)
PAR.GENERICNUMBER3 as PARTICIPANTGENERICNUMBER3, -- Municipio (GN3)
PAR.GENERICNUMBER4 as PARTICIPANTGENERICNUMBER4, -- ID_Empleado (GN4)
PAR.GENERICNUMBER5 as PARTICIPANTGENERICNUMBER5, -- % IRPF (GN5)
PAR.GENERICNUMBER6 as PARTICIPANTGENERICNUMBER6, -- Fax (GN6)
PAR.GENERICDATE1 as PARTICIPANTGENERICDATE1, -- Fecha Nacimiento (GD1)
PAR.GENERICDATE2 as PARTICIPANTGENERICDATE2, -- Fecha Registro DGS (GD2)
PAR.GENERICDATE3 as PARTICIPANTGENERICDATE3, -- Fecha Envío DGS (GD3)
PAR.GENERICDATE4 as PARTICIPANTGENERICDATE4, -- Fin CIASE 1 (GD4)
PAR.GENERICDATE5 as PARTICIPANTGENERICDATE5, -- Fecha Efecto SuperRappel (GD5)
PAR.GENERICDATE6 as PARTICIPANTGENERICDATE6, -- Fecha Regularización SuperRappel (GD6)
PAR.GENERICBOOLEAN1 as PARTICIPANTGENERICBOOLEAN1, -- Autoliquida (GB1)
PAR.GENERICBOOLEAN2 as PARTICIPANTGENERICBOOLEAN2, -- Corredor (GB2)
PAR.GENERICBOOLEAN3 as PARTICIPANTGENERICBOOLEAN3, -- Autorización Factura (GB3)
PAR.GENERICBOOLEAN4 as PARTICIPANTGENERICBOOLEAN4, -- SuperRappel (GB4)
PAR.GENERICBOOLEAN5 as PARTICIPANTGENERICBOOLEAN5, -- Comisiones Anualizadas RRPP OCASO (GB5)
PAR.GENERICBOOLEAN6 as PARTICIPANTGENERICBOOLEAN6, -- Cartera RRTT (GB6)
TIT.GENERICATTRIBUTE1 as TITLEGENERICATTRIBUTE1, -- Tipo Principal Agente / Clase Oficina (GA1)
TIT.GENERICATTRIBUTE2 as TITLEGENERICATTRIBUTE2, -- Tipo Agente / Tipo Oficina (GA2)
TIT.GENERICATTRIBUTE3 as TITLEGENERICATTRIBUTE3, 
TIT.GENERICATTRIBUTE4 as TITLEGENERICATTRIBUTE4, 
TIT.GENERICNUMBER1 as TITLEGENERICNUMBER1, -- ID Tipo Principal  Agente (GN1)
TIT.GENERICNUMBER2 as TITLEGENERICNUMBER2, -- ID Tipo  Agente (GN2)
TIT.GENERICNUMBER3 as TITLEGENERICNUMBER3, -- ID Clase Oficina (GN3)
TIT.GENERICNUMBER4 as TITLEGENERICNUMBER4, -- ID Tipo Oficina (GN4)
TIT.GENERICDATE1 as TITLEGENERICDATE1, 
TIT.GENERICDATE2 as TITLEGENERICDATE2, 
TIT.GENERICBOOLEAN1 as TITLEGENERICBOOLEAN1, -- Genera Informe (GB1)
TIT.GENERICBOOLEAN2 as TITLEGENERICBOOLEAN2, 
POS.MANAGERSEQ, -- MANAGERSEQ
MANAGER.NOMBRE_COMPLETO as MANAGERFULLNAME,
null as ISPAYEE, 
null as BOUSERID, 
null as MANAGERPARTICIPANTSEQ, 
null as PA_SK,
 IFNULL( CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (5) THEN REG.EPOS_NAME
        ELSE CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (4,7) THEN SUC.EPOS_NAME
            ELSE CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (3,6,8,10,11) THEN OFI.EPOS_NAME
                ELSE PTO_VENTA.EPOS_NAME END
    END END , ' ') as IDREGIONAL,
    IFNULL( CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (5) THEN REG.EPOS_NAME
        ELSE CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (4,7) THEN SUC.EPOS_NAME
            ELSE CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (3,6,8,10,11) THEN OFI.EPOS_NAME
                ELSE PTO_VENTA.EPOS_NAME END
    END END || ' - ' ||
    CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (5) THEN REG.LASTNAME
        ELSE CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (4,7) THEN SUC.LASTNAME
            ELSE CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (3,6,8,10,11) THEN OFI.LASTNAME
                ELSE PTO_VENTA.LASTNAME END
    END END  , ' ') AS REGIONAL, 
    IFNULL( CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (5) THEN SUC.EPOS_NAME
        ELSE CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (4,7) THEN OFI.EPOS_NAME
            ELSE PTO_VENTA.EPOS_NAME END 
    END , ' ' )as IDSUCURSAL,
    IFNULL( CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (5) THEN SUC.EPOS_NAME
        ELSE CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (4,7) THEN OFI.EPOS_NAME
            ELSE PTO_VENTA.EPOS_NAME END 
    END || ' - ' ||
    CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (5) THEN SUC.LASTNAME
        ELSE CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (4,7) THEN OFI.LASTNAME
            ELSE PTO_VENTA.LASTNAME END 
    END , ' ' ) AS SUCURSAL,                                                                                            --titleGenericAttribute2
    IFNULL( CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (5) THEN OFI.EPOS_NAME  
        ELSE PTO_VENTA.EPOS_NAME END, ' ') as IDOFICINA,
    IFNULL( CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (5) THEN OFI.EPOS_NAME  
        ELSE PTO_VENTA.EPOS_NAME END || ' - ' ||
    CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (5) THEN OFI.LASTNAME  
        ELSE PTO_VENTA.LASTNAME END, ' ') AS OFICINA,
IFNULL( LEFT(POS.GENERICATTRIBUTE3, 4), ' ') as PV, IFNULL( RIGHT(Pos.GENERICATTRIBUTE3, 4), ' ' ) as CODIGO,
MANAGER.EPOS_GENERICATTRIBUTE3 as INSPECTOR_NAME, MANAGER.NIF as INSPECTOR_NIF, MANAGER.NOMBRE_COMPLETO as INSPECTOR_NOMBRE_COMPLETO, 
MANAGER.ETITLE as INSPECTOR_TITLE, MANAGER.EPAR_USERID as INSPECTOR_LDAP,
MANAGER.EPOS_GENERICNUMBER2 AS INSPECTOR_IDTIPOAGENTE,MANAGER.EPOS_GENERICATTRIBUTE2 AS INSPECTOR_TIPOAGENTE,
INSP_CAP.EPOS_GENERICATTRIBUTE3 as INSPCAP_NAME, INSP_CAP.NIF as INSPCAP_NIF, INSP_CAP.NOMBRE_COMPLETO as INSPCAP_NOMBRE_COMPLETO, 
INSP_CAP.ETITLE as INSPCAP_TITLE, INSP_CAP.EPAR_USERID as INSPCAP_LDAP,
INSP_CAP.EPOS_GENERICNUMBER2 AS INSPCAP_IDTIPOAGENTE,INSP_CAP.EPOS_GENERICATTRIBUTE2 AS INSPCAP_TIPOAGENTE,
1 as MEDCOUNT
FROM CS_POSITION pos
JOIN pos_ids i
    ON pos.RULEELEMENTOWNERSEQ = i.RULEELEMENTOWNERSEQ and POS.REMOVEDATE = TO_DATE('22000101','yyyymmdd')
INNER JOIN CS_PARTICIPANT PAR -- Se hace un JOIN con CS_PARTICIPANT a ultimo dia del mes de cada periodo para extraer: PAR.PARTICIPANTEMAIL, PAR.TAXID y fechas de efectividad por si quisieran filtrar por fecha concreta
	ON  PAR.PAYEESEQ = POS.PAYEESEQ and PAR.REMOVEDATE = TO_DATE('22000101','yyyymmdd')
	AND PAR.EFFECTIVESTARTDATE<= POS.EFFECTIVESTARTDATE and  PAR.EFFECTIVEENDDATE > POS.EFFECTIVESTARTDATE

INNER JOIN TCMP.CS_PAYEE R ON PAR.PAYEESEQ = R.PAYEESEQ and R.REMOVEDATE = TO_DATE('22000101','yyyymmdd')
	AND PAR.EFFECTIVESTARTDATE = R.EFFECTIVESTARTDATE and PAR.EFFECTIVEENDDATE = R.EFFECTIVEENDDATE	

INNER JOIN TCMP.CS_TITLE TIT ON  POS.TITLESEQ = TIT.RULEELEMENTOWNERSEQ  AND TIT.REMOVEDATE = TO_DATE('22000101','yyyymmdd') 
	AND TIT.EFFECTIVESTARTDATE<= POS.EFFECTIVESTARTDATE and  TIT.EFFECTIVEENDDATE > POS.EFFECTIVESTARTDATE
        			
-- MANAGER
LEFT JOIN ESTRUCTURA MANAGER ON MANAGER.EPOSITIONSEQ = POS.MANAGERSEQ --PAD.MANAGERSEQ 
								AND MANAGER.EPOS_GENERICNUMBER2 is not null 
								AND MANAGER.EPOS_GENERICATTRIBUTE3 NOT IN ('0000000000','0') 
								AND MANAGER.EPOS_MANAGERSEQ IS NOT NULL
								AND MANAGER.EPOS_EFFECTIVESTARTDATE < POS.EFFECTIVESTARTDATE and  MANAGER.EPOS_EFFECTIVEENDDATE >= POS.EFFECTIVESTARTDATE
								AND MANAGER.EPAR_EFFECTIVESTARTDATE <  POS.EFFECTIVESTARTDATE  and  MANAGER.EPAR_EFFECTIVEENDDATE >=  POS.EFFECTIVESTARTDATE  
								AND MANAGER.ETIT_EFFECTIVESTARTDATE <  POS.EFFECTIVESTARTDATE  and  MANAGER.ETIT_EFFECTIVEENDDATE >= POS.EFFECTIVESTARTDATE

-- INSP_CAP						
LEFT JOIN ESTRUCTURA INSP_CAP ON INSP_CAP.EPOS_NAME = POS.GENERICATTRIBUTE14  --PAD.POSITIONGENERICATTRIBUTE14
								AND INSP_CAP.EPOS_GENERICATTRIBUTE3 NOT IN ('0000000000','0') 
								AND INSP_CAP.EPOS_EFFECTIVESTARTDATE < POS.EFFECTIVESTARTDATE and  INSP_CAP.EPOS_EFFECTIVEENDDATE >= POS.EFFECTIVESTARTDATE
								AND INSP_CAP.EPAR_EFFECTIVESTARTDATE <  POS.EFFECTIVESTARTDATE  and  INSP_CAP.EPAR_EFFECTIVEENDDATE >=  POS.EFFECTIVESTARTDATE  
								AND INSP_CAP.ETIT_EFFECTIVESTARTDATE <  POS.EFFECTIVESTARTDATE  and  INSP_CAP.ETIT_EFFECTIVEENDDATE >=  POS.EFFECTIVESTARTDATE 
-- PTO_VENTA
LEFT JOIN ESTRUCTURA PTO_VENTA ON SUBSTR(POS.GENERICATTRIBUTE3,1,4) = PTO_VENTA.EPOS_NAME --SUBSTR(PAD.POSITIONGENERICATTRIBUTE3,1,4) = PTO_VENTA.EPOS_NAME
								AND PTO_VENTA.EPOS_GENERICNUMBER2 IS NULL 
								AND PTO_VENTA.EPOS_EFFECTIVESTARTDATE < POS.EFFECTIVESTARTDATE and  PTO_VENTA.EPOS_EFFECTIVEENDDATE >= POS.EFFECTIVESTARTDATE
								AND PTO_VENTA.EPAR_EFFECTIVESTARTDATE <  POS.EFFECTIVESTARTDATE  and  PTO_VENTA.EPAR_EFFECTIVEENDDATE >=  POS.EFFECTIVESTARTDATE  
								AND PTO_VENTA.ETIT_EFFECTIVESTARTDATE <  POS.EFFECTIVESTARTDATE  and  PTO_VENTA.ETIT_EFFECTIVEENDDATE >=  POS.EFFECTIVESTARTDATE
-- OFI
LEFT JOIN ESTRUCTURA OFI ON PTO_VENTA.EPOS_MANAGERSEQ = OFI.EPOSITIONSEQ
								AND OFI.EPOS_GENERICNUMBER2 IS NULL 
								AND OFI.EPOS_EFFECTIVESTARTDATE < POS.EFFECTIVESTARTDATE and  OFI.EPOS_EFFECTIVEENDDATE >= POS.EFFECTIVESTARTDATE
								AND OFI.EPAR_EFFECTIVESTARTDATE <  POS.EFFECTIVESTARTDATE  and  OFI.EPAR_EFFECTIVEENDDATE >=  POS.EFFECTIVESTARTDATE  
								AND OFI.ETIT_EFFECTIVESTARTDATE <  POS.EFFECTIVESTARTDATE  and  OFI.ETIT_EFFECTIVEENDDATE >=  POS.EFFECTIVESTARTDATE


-- SUC
LEFT JOIN ESTRUCTURA SUC ON OFI.EPOS_MANAGERSEQ = SUC.EPOSITIONSEQ
								AND SUC.EPOS_GENERICNUMBER2 IS NULL 
								AND SUC.EPOS_EFFECTIVESTARTDATE < POS.EFFECTIVESTARTDATE and  SUC.EPOS_EFFECTIVEENDDATE >= POS.EFFECTIVESTARTDATE
								AND SUC.EPAR_EFFECTIVESTARTDATE <  POS.EFFECTIVESTARTDATE  and  SUC.EPAR_EFFECTIVEENDDATE >=  POS.EFFECTIVESTARTDATE  
								AND SUC.ETIT_EFFECTIVESTARTDATE <  POS.EFFECTIVESTARTDATE  and  SUC.ETIT_EFFECTIVEENDDATE >=  POS.EFFECTIVESTARTDATE 		

-- REG
LEFT JOIN ESTRUCTURA REG ON SUC.EPOS_MANAGERSEQ = REG.EPOSITIONSEQ
								AND REG.EPOS_GENERICNUMBER2 IS NULL 
								AND REG.EPOS_EFFECTIVESTARTDATE < POS.EFFECTIVESTARTDATE and  REG.EPOS_EFFECTIVEENDDATE >= POS.EFFECTIVESTARTDATE
								AND REG.EPAR_EFFECTIVESTARTDATE <  POS.EFFECTIVESTARTDATE  and  REG.EPAR_EFFECTIVEENDDATE >=  POS.EFFECTIVESTARTDATE  
								AND REG.ETIT_EFFECTIVESTARTDATE <  POS.EFFECTIVESTARTDATE  and  REG.ETIT_EFFECTIVEENDDATE >=  POS.EFFECTIVESTARTDATE 		

where Pos.effectiveenddate>'2020-01-01' --and par.USERID='OJJU'
	and Pos.GENERICNUMBER2 IS NOT NULL