CALL LIB_GLOBAL:WRITE_LOG(v_permisos_log, v_proc_name, 'Inicio INSERTS para informes 1.27', v_log_count, v_idproceso, 'debug');
CALL LIB_GLOBAL:WRITE_LOG(v_permisos_log, v_proc_name, 'Inicio Borrado OUT_REPARTO_PAGOS_FINAL_REP', v_log_count, v_idproceso, 'debug');
DELETE FROM EXT.OUT_REPARTO_PAGOS_FINAL_REP WHERE PERIODSEQ = :v_PeriodSeq;
v_num_rows := ::ROWCOUNT;
CALL LIB_GLOBAL:WRITE_LOG(v_permisos_log, v_proc_name, 'Fin Borrado OUT_REPARTO_PAGOS_FINAL_REP. Filas: ' || v_num_rows, v_log_count, v_idproceso, 'debug');

CALL LIB_GLOBAL:WRITE_LOG(v_permisos_log, v_proc_name, 'Inicio Carga OUT_REPARTO_PAGOS_FINAL_REP', v_log_count, v_idproceso, 'debug');
INSERT INTO EXT.OUT_REPARTO_PAGOS_FINAL_REP
	SELECT DISTINCT
		SUBSTR(PAG.EARNINGGROUPID, 7, 2) AS COMPANYA,
		PER.NAME,
		SUBSTR_AFTER(PER.NAME, ' ') ||
			CASE WHEN SUBSTR_BEFORE(PER.NAME, ' ') = 'Enero' THEN ' 01 '
				WHEN SUBSTR_BEFORE(PER.NAME, ' ') = 'Febrero' THEN ' 02 '
				WHEN SUBSTR_BEFORE(PER.NAME, ' ') = 'Marzo' THEN ' 03 '
				WHEN SUBSTR_BEFORE(PER.NAME, ' ') = 'Abril' THEN ' 04 '
				WHEN SUBSTR_BEFORE(PER.NAME, ' ') = 'Mayo' THEN ' 05 '
				WHEN SUBSTR_BEFORE(PER.NAME, ' ') = 'Junio' THEN ' 06 '
				WHEN SUBSTR_BEFORE(PER.NAME, ' ') = 'Julio' THEN ' 07 '
				WHEN SUBSTR_BEFORE(PER.NAME, ' ') = 'Agosto' THEN ' 08 '
				WHEN SUBSTR_BEFORE(PER.NAME, ' ') = 'Septiembre' THEN ' 09 '
				WHEN SUBSTR_BEFORE(PER.NAME, ' ') = 'Octubre' THEN ' 10 '
				WHEN SUBSTR_BEFORE(PER.NAME, ' ') = 'Noviembre' THEN ' 11 '
				WHEN SUBSTR_BEFORE(PER.NAME, ' ') = 'Diciembre' THEN ' 12 '
				END
			|| SUBSTR_BEFORE(PER.NAME, ' ') AS PERIODO,
		PAG.FECHA_CARGO AS "FECHA CARGO",
		PAG.EARNINGCODEID AS "EARNING CODE",
		PAG.EARNINGGROUPID AS "EARNING GROUP",
		PAG.PROGRAMA,
		IFNULL(PAG.DEPOSITO, ' ') AS DEPOSITO,
		IFNULL(PAG.TIPO_PAGO, ' ') AS "TIPO PAGO",
		PAG.POS_PRIN AS "CODIGO AGENTE",
		PAG.IMPORTE,
		IFNULL(CAST(TR.TIPO_REPARTO AS VARCHAR), ' ') AS "TIPO REPARTO",
		-- 1.27.2
		PAG.POS_CALLIDUS AS "CODIGO UNICO",
		PAG.NIF,
		CAST(TO_INTEGER(PAG.TIPO_AGENTE) AS VARCHAR) AS "TIPO AGENTE",
		PAG.MANAGER_POS_PRIN AS "MANAGER",
		CAST(PAG.ESTADO_REPARTO AS VARCHAR) AS "ESTADO REPARTO",
		PAG.POSITIONSEQ,
		PER.PERIODSEQ
	FROM EXT.FINAL_REPEXT_PAGOS_FILE AS PAG
	LEFT JOIN EXT.WF_REPEXT_TIPO_REPARTO_FILE AS TR
		ON PAG.TIPO_PAGO = TR.TIPO_PAGO
		AND SUBSTR(PAG.EARNINGGROUPID, 7, 2) = TR.CIA_CODIGO
		AND PAG.FECHA_CARGO BETWEEN TR.FECHA_INICIO AND TR.FECHA_FIN
		AND TR.FECHA_BAJA IS NULL
	INNER JOIN TCMP.CS_PERIOD PER
		ON PAG.PERIODSEQ = PER.PERIODSEQ
		AND PER.REMOVEDATE = TO_DATE('22000101','YYYYMMDD')
	WHERE PAG.POS_PRIN NOT LIKE '%999999'
		AND PER.PERIODSEQ = :v_PeriodSeq;
v_num_rows := ::ROWCOUNT;
CALL LIB_GLOBAL:WRITE_LOG(v_permisos_log, v_proc_name, 'Fin Carga OUT_REPARTO_PAGOS_FINAL_REP. Filas: ' || v_num_rows, v_log_count, v_idproceso, 'debug');


CALL LIB_GLOBAL:WRITE_LOG(v_permisos_log, v_proc_name, 'Inicio Borrado OUT_REPARTO_PAGOS_COMMISSIONS_FINAL_REP', v_log_count, v_idproceso, 'debug');
DELETE FROM EXT.OUT_REPARTO_PAGOS_COMMISSIONS_FINAL_REP WHERE PERIODSEQ = :v_PeriodSeq;
v_num_rows := ::ROWCOUNT;
CALL LIB_GLOBAL:WRITE_LOG(v_permisos_log, v_proc_name, 'Fin Borrado OUT_REPARTO_PAGOS_COMMISSIONS_FINAL_REP. Filas: ' || v_num_rows, v_log_count, v_idproceso, 'debug');

CALL LIB_GLOBAL:WRITE_LOG(v_permisos_log, v_proc_name, 'Inicio Carga OUT_REPARTO_PAGOS_COMMISSIONS_FINAL_REP', v_log_count, v_idproceso, 'debug');
INSERT INTO EXT.OUT_REPARTO_PAGOS_COMMISSIONS_FINAL_REP
	(SELECT
		SUBSTR(PAY.EARNINGGROUPID,7,2) AS CIA,
		PAY.EARNINGCODEID AS CONCEPTO_PAGO,
		PAY.EARNINGGROUPID AS GRUPO_PAGO,
		POS.GENERICATTRIBUTE3 AS POS_PRIN,
		PD.YEAR,
		PD.NAME AS PERIODO,
		SUBSTR_AFTER(PD.NAME, ' ') || CASE 
			WHEN SUBSTR_BEFORE(PD.NAME, ' ') = 'Enero' THEN ' 01 '
			WHEN SUBSTR_BEFORE(PD.NAME, ' ') = 'Febrero' THEN ' 02 '
			WHEN SUBSTR_BEFORE(PD.NAME, ' ') = 'Marzo' THEN ' 03 '
			WHEN SUBSTR_BEFORE(PD.NAME, ' ') = 'Abril' THEN ' 04 '
			WHEN SUBSTR_BEFORE(PD.NAME, ' ') = 'Mayo' THEN ' 05 '
			WHEN SUBSTR_BEFORE(PD.NAME, ' ') = 'Junio' THEN ' 06 '
			WHEN SUBSTR_BEFORE(PD.NAME, ' ') = 'Julio' THEN ' 07 '
			WHEN SUBSTR_BEFORE(PD.NAME, ' ') = 'Agosto' THEN ' 08 '
			WHEN SUBSTR_BEFORE(PD.NAME, ' ') = 'Septiembre' THEN ' 09 '
			WHEN SUBSTR_BEFORE(PD.NAME, ' ') = 'Octubre' THEN ' 10 '
			WHEN SUBSTR_BEFORE(PD.NAME, ' ') = 'Noviembre' THEN ' 11 '
			WHEN SUBSTR_BEFORE(PD.NAME, ' ') = 'Diciembre' THEN ' 12 '
			END || SUBSTR_BEFORE(PD.NAME, ' ') AS PERIODO_FORMATO,
		CAST(PAR.GENERICATTRIBUTE1 AS VARCHAR(255)) || ' - ' || TRIM(IFNULL(PAR.FIRSTNAME, '') || IFNULL(' ' || PAR.LASTNAME, '') || IFNULL(' ' || PAR.SUFFIX, '')) AS NIF_NOMBRE,
		SUM(ROUND(PAY.VALUE,2)) AS IMPORTE,
		PAY.POSITIONSEQ,
		PD.PERIODSEQ
	FROM TCMP.CS_PAYMENT PAY
	INNER JOIN TCMP.CSA_PERIODDIMENSION PD ON PAY.PERIODSEQ = PD.PERIODSEQ
	    AND PD.PERIODTYPESEQ = 2814749767106561
	INNER JOIN TCMP.CS_POSITION POS ON PAY.POSITIONSEQ = POS.RULEELEMENTOWNERSEQ
	    AND POS.EFFECTIVESTARTDATE <= ADD_SECONDS(PD.ENDDATE, -1)
	    AND POS.EFFECTIVEENDDATE > ADD_SECONDS(PD.ENDDATE, -1)
	    AND POS.CREATEDATE <= ADD_SECONDS(PD.ENDDATE, -1)
	    AND POS.REMOVEDATE > ADD_SECONDS(PD.ENDDATE, -1)
	    AND POS.TITLESEQ <> 5629499534213290 --TTL SIN PLAN
	    AND POS.GENERICATTRIBUTE3 NOT LIKE '%999999'
	INNER JOIN TCMP.CS_PARTICIPANT PAR ON POS.PAYEESEQ = PAR.PAYEESEQ
	    AND PAR.EFFECTIVESTARTDATE <= ADD_SECONDS(PD.ENDDATE, -1)
	    AND PAR.EFFECTIVEENDDATE > ADD_SECONDS(PD.ENDDATE, -1)
	    AND PAR.CREATEDATE <= ADD_SECONDS(PD.ENDDATE, -1)
	    AND PAR.REMOVEDATE > ADD_SECONDS(PD.ENDDATE, -1)
	    AND (PAR.TERMINATIONDATE IS NULL OR PAR.TERMINATIONDATE > ADD_SECONDS(PD.ENDDATE, -1))
	WHERE SUBSTR(PAY.EARNINGCODEID,1,1) NOT IN ('6','8')
		AND PAY.PERIODSEQ = :v_PeriodSeq
	GROUP BY
	    PAY.EARNINGCODEID, PAY.EARNINGGROUPID,
	    POS.GENERICATTRIBUTE3, 
	    PD.YEAR, PD.QUARTER, PD.NAME,
	    PAR.GENERICATTRIBUTE1, PAR.FIRSTNAME, PAR.LASTNAME, PAR.SUFFIX,
	    PAY.POSITIONSEQ, PD.PERIODSEQ
	
	UNION ALL
	
	SELECT
		SUBSTR(CAR_DDEE.EARNINGGROUPID,7,2) AS CIA,
		CAR_DDEE.EARNINGCODEID AS CONCEPTO_PAGO,
		CAR_DDEE.EARNINGGROUPID AS GRUPO_PAGO,
		POS.GENERICATTRIBUTE3 AS POS_PRIN,
		PD.YEAR,
		PD.NAME AS PERIODO,
		SUBSTR_AFTER(PD.NAME, ' ') || CASE 
			WHEN SUBSTR_BEFORE(PD.NAME, ' ') = 'Enero' THEN ' 01 '
			WHEN SUBSTR_BEFORE(PD.NAME, ' ') = 'Febrero' THEN ' 02 '
			WHEN SUBSTR_BEFORE(PD.NAME, ' ') = 'Marzo' THEN ' 03 '
			WHEN SUBSTR_BEFORE(PD.NAME, ' ') = 'Abril' THEN ' 04 '
			WHEN SUBSTR_BEFORE(PD.NAME, ' ') = 'Mayo' THEN ' 05 '
			WHEN SUBSTR_BEFORE(PD.NAME, ' ') = 'Junio' THEN ' 06 '
			WHEN SUBSTR_BEFORE(PD.NAME, ' ') = 'Julio' THEN ' 07 '
			WHEN SUBSTR_BEFORE(PD.NAME, ' ') = 'Agosto' THEN ' 08 '
			WHEN SUBSTR_BEFORE(PD.NAME, ' ') = 'Septiembre' THEN ' 09 '
			WHEN SUBSTR_BEFORE(PD.NAME, ' ') = 'Octubre' THEN ' 10 '
			WHEN SUBSTR_BEFORE(PD.NAME, ' ') = 'Noviembre' THEN ' 11 '
			WHEN SUBSTR_BEFORE(PD.NAME, ' ') = 'Diciembre' THEN ' 12 '
			END || SUBSTR_BEFORE(PD.NAME, ' ') AS PERIODO_FORMATO,
		CAST(PAR.GENERICATTRIBUTE1 AS VARCHAR(255)) || ' - ' || TRIM(IFNULL(PAR.FIRSTNAME, '') || IFNULL(' ' || PAR.LASTNAME, '') || IFNULL(' ' || PAR.SUFFIX, '')) AS NIF_NOMBRE,
		SUM(ROUND(CAR_DDEE.IMPORTE,2)) AS IMPORTE,
		POS.RULEELEMENTOWNERSEQ,
		PD.PERIODSEQ
	FROM EXT.CARTERA_DDEE CAR_DDEE
	INNER JOIN TCMP.CSA_PERIODDIMENSION PD ON CAR_DDEE.COMPENSATIONDATE = PD.STARTDATE
	    AND PD.PERIODTYPESEQ = 2814749767106561
	INNER JOIN TCMP.CS_POSITION POS ON CAR_DDEE.POSITIONNAME = POS.NAME
	    AND POS.EFFECTIVESTARTDATE <= ADD_SECONDS(PD.ENDDATE, -1)
	    AND POS.EFFECTIVEENDDATE > ADD_SECONDS(PD.ENDDATE, -1)
	    AND POS.CREATEDATE <= ADD_SECONDS(PD.ENDDATE, -1)
	    AND POS.REMOVEDATE > ADD_SECONDS(PD.ENDDATE, -1)
	INNER JOIN TCMP.CS_PARTICIPANT PAR ON POS.PAYEESEQ = PAR.PAYEESEQ
	    AND PAR.EFFECTIVESTARTDATE <= ADD_SECONDS(PD.ENDDATE, -1)
	    AND PAR.EFFECTIVEENDDATE > ADD_SECONDS(PD.ENDDATE, -1)
	    AND PAR.CREATEDATE <= ADD_SECONDS(PD.ENDDATE, -1)
	    AND PAR.REMOVEDATE > ADD_SECONDS(PD.ENDDATE, -1)
	    AND (PAR.TERMINATIONDATE IS NULL OR PAR.TERMINATIONDATE > ADD_SECONDS(PD.ENDDATE, -1))
	WHERE CAR_DDEE.ESTADO = 'C'
	    AND CAR_DDEE.SEQ_POST IS NOT NULL
	    AND POS.GENERICATTRIBUTE3 NOT LIKE '%999999'
		AND PD.PERIODSEQ = :v_PeriodSeq
	GROUP BY
	    CAR_DDEE.EARNINGCODEID, CAR_DDEE.EARNINGGROUPID,
	    POS.GENERICATTRIBUTE3, 
	    PD.YEAR, PD.QUARTER, PD.NAME,
	    PAR.GENERICATTRIBUTE1, PAR.FIRSTNAME, PAR.LASTNAME, PAR.SUFFIX,
	    POS.RULEELEMENTOWNERSEQ, PD.PERIODSEQ);
v_num_rows := ::ROWCOUNT;
CALL LIB_GLOBAL:WRITE_LOG(v_permisos_log, v_proc_name, 'Fin Carga OUT_REPARTO_PAGOS_COMMISSIONS_FINAL_REP. Filas: ' || v_num_rows, v_log_count, v_idproceso, 'debug');


CALL LIB_GLOBAL:WRITE_LOG(v_permisos_log, v_proc_name, 'Inicio Borrado OUT_DETALLE_REPARTO_PAGOS_FINAL_REP', v_log_count, v_idproceso, 'debug');
DELETE FROM EXT.OUT_DETALLE_REPARTO_PAGOS_FINAL_REP WHERE PERIODSEQ = :v_PeriodSeq;
v_num_rows := ::ROWCOUNT;
CALL LIB_GLOBAL:WRITE_LOG(v_permisos_log, v_proc_name, 'Fin Borrado OUT_DETALLE_REPARTO_PAGOS_FINAL_REP. Filas: ' || v_num_rows, v_log_count, v_idproceso, 'debug');

CALL LIB_GLOBAL:WRITE_LOG(v_permisos_log, v_proc_name, 'Inicio Carga OUT_DETALLE_REPARTO_PAGOS_FINAL_REP', v_log_count, v_idproceso, 'debug');
INSERT INTO EXT.OUT_DETALLE_REPARTO_PAGOS_FINAL_REP
	SELECT
		PERIODO,
		SUBSTR_AFTER(PERIODO, ' ') ||
		CASE WHEN SUBSTR_BEFORE(PERIODO, ' ') = 'Enero' THEN ' 01 '
			WHEN SUBSTR_BEFORE(PERIODO, ' ') = 'Febrero' THEN ' 02 '
			WHEN SUBSTR_BEFORE(PERIODO, ' ') = 'Marzo' THEN ' 03 '
			WHEN SUBSTR_BEFORE(PERIODO, ' ') = 'Abril' THEN ' 04 '
			WHEN SUBSTR_BEFORE(PERIODO, ' ') = 'Mayo' THEN ' 05 '
			WHEN SUBSTR_BEFORE(PERIODO, ' ') = 'Junio' THEN ' 06 '
			WHEN SUBSTR_BEFORE(PERIODO, ' ') = 'Julio' THEN ' 07 '
			WHEN SUBSTR_BEFORE(PERIODO, ' ') = 'Agosto' THEN ' 08 '
			WHEN SUBSTR_BEFORE(PERIODO, ' ') = 'Septiembre' THEN ' 09 '
			WHEN SUBSTR_BEFORE(PERIODO, ' ') = 'Octubre' THEN ' 10 '
			WHEN SUBSTR_BEFORE(PERIODO, ' ') = 'Noviembre' THEN ' 11 '
			WHEN SUBSTR_BEFORE(PERIODO, ' ') = 'Diciembre' THEN ' 12 '
			END
		|| SUBSTR_BEFORE(PERIODO, ' ') AS PERIODO_FORMATO,
		
		NIF,
		POSITIONNAME AS "CODIGO UNICO", 
		POS_PRIN AS "CODIGO AGENTE",
		MANAGER_POS_PRIN AS MANAGER,
		TO_VARCHAR(TO_INTEGER(TIPO_AGENTE)),
		
		TIPO_PAGO,
		
		EARNINGCODEID AS "CONCEPTO DE PAGO",
		EARNINGGROUPID AS "GRUPO DE PAGO",
		IMPORTE_PAGO AS IMPORTE,
		
		NUM_TRAMO,
		IFNULL(TIPO_REPARTO, ' '), 
		IFNULL(REPARTO_TIPO_BASE, ' '),
		IFNULL(TO_VARCHAR(REPARTO_PORCENTAJE), ' '),
		
		PRODUCTID AS PRODUCTO,
		CODIGO_POLIZA,
		CASE
			WHEN RIGHT(LEFT(PRODUCTID,3),1) = '2'
				THEN RIGHT(ORDERID,11)
			ELSE
				LEFT(TO_VARCHAR(SUBLINENUMBER),11)
			END AS "CODIGO RECIBO",
		EVENTTYPEID AS PERMANENCIA,
		POLIZA_FISICA,
		POLIZA_CORREGIDA,
		PRIMA_CORREGIDA,
		PRIMA_NETA,
		PRIMA_NETA_ANUAL,
		PRIMA_COMIS,
		IFNULL(COEF_TIPO_BASE, ' '),
		IFNULL(TO_VARCHAR(COEF_CORRECTOR), ' '),
		IMPORTE AS IMPORTE_REPARTO,
		CASE
			WHEN POS_PRIN LIKE '%999999'
				THEN 'SI'
			ELSE 'NO' 
			END AS AGENCIA,
		PERIODSEQ,
		POSITIONSEQ
	FROM EXT.FINAL_REPEXT_FILE
	WHERE TIPO_PAGO IS NOT NULL
		AND PERIODSEQ = :v_PeriodSeq;
v_num_rows := ::ROWCOUNT;
CALL LIB_GLOBAL:WRITE_LOG(v_permisos_log, v_proc_name, 'Fin Carga OUT_DETALLE_REPARTO_PAGOS_FINAL_REP. Filas: ' || v_num_rows, v_log_count, v_idproceso, 'debug');


CALL LIB_GLOBAL:WRITE_LOG(v_permisos_log, v_proc_name, 'Inicio Borrado OUT_RESUMEN_REPARTO_PAGOS_VB1_FINAL_REP', v_log_count, v_idproceso, 'debug');
DELETE FROM EXT.OUT_RESUMEN_REPARTO_PAGOS_VB1_FINAL_REP WHERE PERIODSEQ = :v_PeriodSeq;
v_num_rows := ::ROWCOUNT;
CALL LIB_GLOBAL:WRITE_LOG(v_permisos_log, v_proc_name, 'Fin Borrado OUT_RESUMEN_REPARTO_PAGOS_VB1_FINAL_REP. Filas: ' || v_num_rows, v_log_count, v_idproceso, 'debug');

CALL LIB_GLOBAL:WRITE_LOG(v_permisos_log, v_proc_name, 'Inicio Carga OUT_RESUMEN_REPARTO_PAGOS_VB1_FINAL_REP', v_log_count, v_idproceso, 'debug');
INSERT INTO EXT.OUT_RESUMEN_REPARTO_PAGOS_VB1_FINAL_REP (
	SELECT 
		PERIODSEQ,
	    PERIODO,
	    SUBSTR_AFTER(PERIODO, ' ') || CASE 
			WHEN SUBSTR_BEFORE(PERIODO, ' ') = 'Enero' THEN ' 01 '
			WHEN SUBSTR_BEFORE(PERIODO, ' ') = 'Febrero' THEN ' 02 '
			WHEN SUBSTR_BEFORE(PERIODO, ' ') = 'Marzo' THEN ' 03 '
			WHEN SUBSTR_BEFORE(PERIODO, ' ') = 'Abril' THEN ' 04 '
			WHEN SUBSTR_BEFORE(PERIODO, ' ') = 'Mayo' THEN ' 05 '
			WHEN SUBSTR_BEFORE(PERIODO, ' ') = 'Junio' THEN ' 06 '
			WHEN SUBSTR_BEFORE(PERIODO, ' ') = 'Julio' THEN ' 07 '
			WHEN SUBSTR_BEFORE(PERIODO, ' ') = 'Agosto' THEN ' 08 '
			WHEN SUBSTR_BEFORE(PERIODO, ' ') = 'Septiembre' THEN ' 09 '
			WHEN SUBSTR_BEFORE(PERIODO, ' ') = 'Octubre' THEN ' 10 '
			WHEN SUBSTR_BEFORE(PERIODO, ' ') = 'Noviembre' THEN ' 11 '
			WHEN SUBSTR_BEFORE(PERIODO, ' ') = 'Diciembre' THEN ' 12 '
			END || SUBSTR_BEFORE(PERIODO, ' ') AS PERIODO_FORMATO,
	    SUBSTR(EARNINGGROUPID,7,2) AS COMPANIA,
	    TIPO_PAGO,
	    NUM_TRAMO,
	    PRODUCTID,
	    SUM(IMPORTE) AS IMPORTE,
	    CASE WHEN POS_PRIN LIKE '%999999' THEN 'SI' ELSE 'NO' END AS AGENCIA
	FROM EXT.FINAL_REPEXT_FILE
	WHERE TIPO_PAGO IS NOT NULL
		AND PERIODSEQ = :v_PeriodSeq
	GROUP BY PERIODSEQ, PERIODO, SUBSTR(EARNINGGROUPID,7,2), TIPO_PAGO, NUM_TRAMO, PRODUCTID,
		CASE WHEN POS_PRIN LIKE '%999999' THEN 'SI' ELSE 'NO' END);
v_num_rows := ::ROWCOUNT;
CALL LIB_GLOBAL:WRITE_LOG(v_permisos_log, v_proc_name, 'Fin Carga OUT_RESUMEN_REPARTO_PAGOS_VB1_FINAL_REP. Filas: ' || v_num_rows, v_log_count, v_idproceso, 'debug');


CALL LIB_GLOBAL:WRITE_LOG(v_permisos_log, v_proc_name, 'Inicio Borrado OUT_RESUMEN_REPARTO_PAGOS_VB2_FINAL_REP', v_log_count, v_idproceso, 'debug');
DELETE FROM EXT.OUT_RESUMEN_REPARTO_PAGOS_VB2_FINAL_REP WHERE PERIODSEQ = :v_PeriodSeq;
v_num_rows := ::ROWCOUNT;
CALL LIB_GLOBAL:WRITE_LOG(v_permisos_log, v_proc_name, 'Fin Borrado OUT_RESUMEN_REPARTO_PAGOS_VB2_FINAL_REP. Filas: ' || v_num_rows, v_log_count, v_idproceso, 'debug');

CALL LIB_GLOBAL:WRITE_LOG(v_permisos_log, v_proc_name, 'Inicio Carga OUT_RESUMEN_REPARTO_PAGOS_VB2_FINAL_REP', v_log_count, v_idproceso, 'debug');
INSERT INTO EXT.OUT_RESUMEN_REPARTO_PAGOS_VB2_FINAL_REP
	(WITH BASE_PAGOS AS (
	    SELECT 
	        PERIODSEQ,
	        SUBSTR(EARNINGGROUPID,7,2) AS COMPANIA,
	        COALESCE(TIPO_PAGO, 'VACIO') AS TIPO_PAGO,
	        IMPORTE,
	        CASE WHEN POS_PRIN LIKE '%999999' THEN 'SI' ELSE 'NO' END AS AGENCIA
	    FROM EXT.FINAL_REPEXT_PAGOS_FILE), 
	BASE_REPEXT AS (
	    SELECT 
	        PERIODSEQ,
	        SUBSTR(EARNINGGROUPID,7,2) AS COMPANIA,
	        TIPO_PAGO,
	        CASE WHEN POS_PRIN LIKE '%999999' THEN 'SI' ELSE 'NO' END AS AGENCIA,
	        SUM(IMPORTE) AS SUM_REPEXT
	    FROM EXT.FINAL_REPEXT_FILE
	    WHERE TIPO_PAGO IS NOT NULL
	    GROUP BY PERIODSEQ, SUBSTR(EARNINGGROUPID,7,2), TIPO_PAGO,
			CASE WHEN POS_PRIN LIKE '%999999' THEN 'SI' ELSE 'NO' END), 
	JOINED AS (
	    SELECT 
	    	PAG.PERIODSEQ,
	        PAG.COMPANIA,
	        PAG.TIPO_PAGO,
	        'TOTAL' AS TRAMO,
	        REP.SUM_REPEXT AS REPARTO,
	        SUM(PAG.IMPORTE) AS PAGO_MES,
	        PAG.AGENCIA
	    FROM base_pagos PAG
	    LEFT JOIN base_repext REP
	        ON PAG.COMPANIA = REP.COMPANIA
	       AND PAG.TIPO_PAGO = REP.TIPO_PAGO
	       AND PAG.PERIODSEQ = REP.PERIODSEQ
	       AND PAG.AGENCIA = REP.AGENCIA
	    GROUP BY PAG.PERIODSEQ, PAG.COMPANIA, PAG.TIPO_PAGO, REP.SUM_REPEXT, PAG.AGENCIA) 
	SELECT 
		P.PERIODSEQ AS PERIODSEQ,
		P.NAME AS PERIODO,
		SUBSTR_AFTER(P.NAME, ' ') || CASE 
			WHEN SUBSTR_BEFORE(P.NAME, ' ') = 'Enero' THEN ' 01 '
			WHEN SUBSTR_BEFORE(P.NAME, ' ') = 'Febrero' THEN ' 02 '
			WHEN SUBSTR_BEFORE(P.NAME, ' ') = 'Marzo' THEN ' 03 '
			WHEN SUBSTR_BEFORE(P.NAME, ' ') = 'Abril' THEN ' 04 '
			WHEN SUBSTR_BEFORE(P.NAME, ' ') = 'Mayo' THEN ' 05 '
			WHEN SUBSTR_BEFORE(P.NAME, ' ') = 'Junio' THEN ' 06 '
			WHEN SUBSTR_BEFORE(P.NAME, ' ') = 'Julio' THEN ' 07 '
			WHEN SUBSTR_BEFORE(P.NAME, ' ') = 'Agosto' THEN ' 08 '
			WHEN SUBSTR_BEFORE(P.NAME, ' ') = 'Septiembre' THEN ' 09 '
			WHEN SUBSTR_BEFORE(P.NAME, ' ') = 'Octubre' THEN ' 10 '
			WHEN SUBSTR_BEFORE(P.NAME, ' ') = 'Noviembre' THEN ' 11 '
			WHEN SUBSTR_BEFORE(P.NAME, ' ') = 'Diciembre' THEN ' 12 '
			END || SUBSTR_BEFORE(P.NAME, ' ') AS PERIODO_FORMATO,
		COMPANIA, 
		TIPO_PAGO, 
		TRAMO, 
		SUM(REPARTO) AS REPARTO, 
		PAGO_MES, 
		AGENCIA
	FROM JOINED J
	INNER JOIN CS_PERIOD P ON P.PERIODSEQ = J.PERIODSEQ
		AND P.REMOVEDATE = TO_DATE('22000101','YYYYMMDD')
	WHERE P.PERIODSEQ = :v_PeriodSeq
	GROUP BY P.PERIODSEQ, P.NAME, COMPANIA, TIPO_PAGO, TRAMO, PAGO_MES, AGENCIA
	
	UNION ALL 
	
	SELECT
		P.PERIODSEQ AS PERIODSEQ,
		P.NAME AS PERIODO,
		SUBSTR_AFTER(P.NAME, ' ') || CASE 
			WHEN SUBSTR_BEFORE(P.NAME, ' ') = 'Enero' THEN ' 01 '
			WHEN SUBSTR_BEFORE(P.NAME, ' ') = 'Febrero' THEN ' 02 '
			WHEN SUBSTR_BEFORE(P.NAME, ' ') = 'Marzo' THEN ' 03 '
			WHEN SUBSTR_BEFORE(P.NAME, ' ') = 'Abril' THEN ' 04 '
			WHEN SUBSTR_BEFORE(P.NAME, ' ') = 'Mayo' THEN ' 05 '
			WHEN SUBSTR_BEFORE(P.NAME, ' ') = 'Junio' THEN ' 06 '
			WHEN SUBSTR_BEFORE(P.NAME, ' ') = 'Julio' THEN ' 07 '
			WHEN SUBSTR_BEFORE(P.NAME, ' ') = 'Agosto' THEN ' 08 '
			WHEN SUBSTR_BEFORE(P.NAME, ' ') = 'Septiembre' THEN ' 09 '
			WHEN SUBSTR_BEFORE(P.NAME, ' ') = 'Octubre' THEN ' 10 '
			WHEN SUBSTR_BEFORE(P.NAME, ' ') = 'Noviembre' THEN ' 11 '
			WHEN SUBSTR_BEFORE(P.NAME, ' ') = 'Diciembre' THEN ' 12 '
			END || SUBSTR_BEFORE(P.NAME, ' ') AS PERIODO_FORMATO,
		SUBSTR(EARNINGGROUPID,7,2) AS COMPANIA,
		TIPO_PAGO,
	    TO_CHAR(NUM_TRAMO) AS TRAMO,
	    SUM(IMPORTE) AS REPARTO,
	    NULL AS PAGO_MES,
	    CASE WHEN POS_PRIN LIKE '%999999' THEN 'SI' ELSE 'NO' END AS AGENCIA
	FROM EXT.FINAL_REPEXT_FILE REP
	INNER JOIN CS_PERIOD P ON P.PERIODSEQ = REP.PERIODSEQ
		AND P.REMOVEDATE = TO_DATE('22000101','YYYYMMDD')
	WHERE TIPO_PAGO IS NOT NULL
		AND P.PERIODSEQ = :v_PeriodSeq
	GROUP BY P.PERIODSEQ,
		P.NAME,
		SUBSTR(EARNINGGROUPID,7,2),
		TIPO_PAGO,
	    NUM_TRAMO,
	    CASE WHEN POS_PRIN LIKE '%999999' THEN 'SI' ELSE 'NO' END);
v_num_rows := ::ROWCOUNT;
CALL LIB_GLOBAL:WRITE_LOG(v_permisos_log, v_proc_name, 'Fin Carga OUT_RESUMEN_REPARTO_PAGOS_VB2_FINAL_REP. Filas: ' || v_num_rows, v_log_count, v_idproceso, 'debug');
CALL LIB_GLOBAL:WRITE_LOG(v_permisos_log, v_proc_name, 'Fin INSERTS para informes 1.27', v_log_count, v_idproceso, 'debug');