--VERSIONES
	--	v1.1	20250402	Inicial
	--	v1.2	20250404	Añadidas las vistas CSA_PROD_AGENTES_SVW_E, CSA_S4_POLIZAS_SVW, CSA_S4_FACTURA_SVW
	--	v1.3	20250407	Añadidas las vistas CSA_S5_FACTURA_SVW, CSA_DIST_RAPPEL_MENSUAL_SVW_E, EXT.CSA_REPARTO_PAGOS_SVW, EXT.CSA_RESUMEN_REPARTO_PAGOS_SVW, EXT.CSA_S5_POLIZAS_SVW, EXT.CSA_S5_POLIZAS_SVW
	--  v1.4	20250410    Añadida la vista CSA_PERCEPCION_INSPECTORES_SVW
	--  v1.5	20250422    Añadida la vista CSA_PROD_AGENTES_SVW_O
	--  v1.6	20250423    Añadida la vista CSA_PERCEPCION_AGENTES_SVW
	--  v1.7	20250424    Añadida la vista CSA_INSPECTORES_ACTIVOS_SVW
	--  v1.8	20250506    Añadida la visibilidad de oficinas por posiciones con tipo de relación "Empleados"
	--  V1.9	20250507    Añadida la vista CSA_PROD_INSPECTORES_SVW
	--  V1.10	20250507    Añadida la vista CSA_RPA_RESUMEN_SVW
	--	v1.11	20250625	Modificada la estructura para incluír --SELECCIONAR--
	--	v1.12	20250630	Eliminada la vista CSA_RESUMEN_REPARTO_PAGOS_SVW
	--	v1.13	20250729	Para la visibilidad de oficinas, el userid tiene que se de la sesión también
	--	v1.14	20250801	Uso del FV-VisibilidadReporting para el bloqueo a payees de la visibilidd 
	--	v1.15	20251031	Añadidas las vistas CSA_S4_RPA_RESUMEN_SVW, CSA_S5_RPI_RESUMEN_SVW, CSA_PEPA_RESUMEN_SVW, CSA_BAL_PEPA_RESUMEN_SVW, CSA_LC_PEPA_RESUMEN_SVW, CSA_RPP_RESUMEN_SVW, CSA_BAL_RPP_RESUMEN_SVW, CSA_LC_RPP_RESUMEN_SVW, CSA_RPP_DETALLE_SVW, CSA_BAL_RPP_DETALLE_SVW, CSA_LC_RPP_DETALLE_SVW, CSA_PEPI_RESUMEN_SVW, CSA_BAL_PEPI_RESUMEN_SVW, CSA_LC_PEPI_RESUMEN_SVW
	--			20251031	Eliminada la vista CSA_REPARTO_PAGOS_SVW

ALTER STRUCTURED PRIVILEGE REP_SECURITY_EXT
FOR SELECT
ON EXT.CSA_ESTRUCTURA_COMERCIAL_SVW, EXT.CSA_PROD_AGENTES_SVW_E, EXT.CSA_S4_POLIZAS_SVW, EXT.CSA_S4_FACTURA_SVW, EXT.CSA_S5_FACTURA_SVW,
	EXT.CSA_DIST_RAPPEL_MENSUAL_SVW_E, EXT.CSA_S5_POLIZAS_SVW,
	EXT.CSA_PERCEPCION_INSPECTORES_SVW, EXT.CSA_PROD_AGENTES_SVW_O, EXT.CSA_PERCEPCION_AGENTES_SVW, EXT.CSA_INSPECTORES_ACTIVOS_SVW,
	EXT.CSA_PROD_INSPECTORES_SVW, EXT.CSA_RPA_RESUMEN_SVW
	, EXT.CSA_S4_RPA_RESUMEN_SVW, EXT.CSA_S5_RPI_RESUMEN_SVW
	, EXT.CSA_PEPA_RESUMEN_SVW, EXT.CSA_BAL_PEPA_RESUMEN_SVW, EXT.CSA_LC_PEPA_RESUMEN_SVW
	, EXT.CSA_RPP_RESUMEN_SVW, EXT.CSA_BAL_RPP_RESUMEN_SVW, EXT.CSA_LC_RPP_RESUMEN_SVW, EXT.CSA_RPP_DETALLE_SVW, EXT.CSA_BAL_RPP_DETALLE_SVW, EXT.CSA_LC_RPP_DETALLE_SVW
	, EXT.CSA_PEPI_RESUMEN_SVW, EXT.CSA_BAL_PEPI_RESUMEN_SVW, EXT.CSA_LC_PEPI_RESUMEN_SVW
WHERE (POSITIONSEQ, PERIODSEQ) IN ( 
	SELECT DESCENDANTPOSITIONSEQ, PERIODSEQ
	FROM CSA_PAREPORTINGDIMENSION 
	WHERE (ANCESTORPA_SK, PERIODSEQ) IN 
	(
		SELECT PA_SK, PERIODSEQ 
		FROM CSA_PADIMENSION PAD
		WHERE  ((USERID = SESSION_CONTEXT('APPLICATIONUSER')
				OR USERID IN (	SELECT PAR.USERID 
									FROM CSA_DATASECURITY DS
									INNER JOIN CS_POSITION POS ON DS.VALUE = POS.RULEELEMENTOWNERSEQ AND POS.REMOVEDATE = TO_DATE('22000101','YYYYMMDD') AND POS.ISLAST = 1
									INNER JOIN CS_PARTICIPANT PAR ON POS.PAYEESEQ = PAR.PAYEESEQ AND PAR.REMOVEDATE = TO_DATE('22000101','YYYYMMDD') AND PAR.ISLAST = 1
									WHERE 1 = 1
										AND DS.USERID = SESSION_CONTEXT('APPLICATIONUSER')
										AND DS.REMOVEDATE = TO_DATE('22000101','YYYYMMDD') 
										AND DS.SECURITYTYPE = 'POS'
									)
			-- visibilidad de oficinas por posiciones con tipo de relación "Empleados" 
				OR USERID IN (	SELECT PARPAR.USERID AS USERID_PADRE 
									FROM TCMP.CS_POSITIONRELATION POSREL
									INNER JOIN TCMP.CS_POSITIONRELATIONTYPE RELTYP ON RELTYP.DATATYPESEQ = POSREL.POSITIONRELATIONTYPESEQ
										AND RELTYP.REMOVEDATE = TO_DATE('22000101','YYYYMMDD')
										AND RELTYP.NAME = 'Empleados'
									INNER JOIN TCMP.CS_POSITION POSPAR ON POSPAR.RULEELEMENTOWNERSEQ = POSREL.PARENTPOSITIONSEQ
										AND POSPAR.REMOVEDATE = TO_DATE('22000101','YYYYMMDD')
									INNER JOIN TCMP.CS_PARTICIPANT PARPAR ON POSPAR.PAYEESEQ = PARPAR.PAYEESEQ 
										AND PARPAR.REMOVEDATE = TO_DATE('22000101','YYYYMMDD') 
										AND PARPAR.ISLAST = 1
									INNER JOIN TCMP.CS_POSITION POSCHI ON POSCHI.RULEELEMENTOWNERSEQ = POSREL.CHILDPOSITIONSEQ
										AND POSCHI.REMOVEDATE = TO_DATE('22000101','YYYYMMDD')
										AND POSCHI.ISLAST = 1
									INNER JOIN TCMP.CS_PARTICIPANT PARCHI ON POSCHI.PAYEESEQ = PARCHI.PAYEESEQ 
										AND PARCHI.REMOVEDATE = TO_DATE('22000101','YYYYMMDD') 
										AND PARCHI.ISLAST = 1
									WHERE 1 = 1
										AND POSREL.REMOVEDATE = TO_DATE('22000101','YYYYMMDD')
										AND POSREL.ISLAST = 1
										AND PARCHI.USERID = SESSION_CONTEXT('APPLICATIONUSER')
									)
						)
					AND 1 = (	SELECT VALUE 
								FROM TCMP.CS_FIXEDVALUE
								WHERE NAME = 'FV-VisibilidadReporting' AND REMOVEDATE = TO_DATE('22000101','YYYYMMDD')
							UNION ALL
								SELECT 1 FROM DUMMY 
								WHERE NOT EXISTS ( SELECT 1 FROM TCMP.CS_FIXEDVALUE WHERE NAME = 'FV-VisibilidadReporting' AND REMOVEDATE = TO_DATE('22000101','YYYYMMDD'))
							LIMIT 1)
					)
			OR EXISTS (	SELECT 1 
						FROM CSA_DATASECURITY 
						WHERE (USERID = SESSION_CONTEXT('APPLICATIONUSER') 
								AND SECURITYTYPE = 'ALL'  -- Visibilidad para usuarios de EA Admin con permisos ALL
								AND REMOVEDATE = TO_DATE('22000101','YYYYMMDD')) 
							OR (SESSION_CONTEXT('APPLICATIONUSER') LIKE 'WEBIDE_PS%')
						)
	)
							
	-- Caso --SELECCIONAR--, donde POSITIONSEQ está fijado a -1
	UNION
	SELECT -1, PERIODSEQ
	FROM CSA_PAREPORTINGDIMENSION 
	/*WHERE 1 = (SELECT VALUE
			FROM TCMP.CS_FIXEDVALUE
			WHERE NAME = 'FV-VisibilidadReporting'
				AND REMOVEDATE = TO_DATE('22000101','YYYYMMDD'))*/
);


