--VERSIONES
	--	v1.1	20250402	Inicial
	--	v1.2	20250404	Añadidas las vistas CSA_PROD_AGENTES_SVW_E, CSA_S4_POLIZAS_SVW, CSA_S4_FACTURA_SVW
	--	v1.3	20250407	Añadidas las vistas CSA_S5_FACTURA_SVW, CSA_DIST_RAPPEL_MENSUAL_SVW_E, EXT.CSA_REPARTO_PAGOS_SVW, EXT.CSA_RESUMEN_REPARTO_PAGOS_SVW, EXT.CSA_S5_POLIZAS_SVW, EXT.CSA_S5_POLIZAS_SVW
	--  v1.4	20250410    Añadida la vista CSA_PERCEPCION_INSPECTORES_SVW
	--  v1.5	20250422    Añadida la vista CSA_PROD_AGENTES_SVW_O
	--  v1.6	20250423    Añadida la vista CSA_PERCEPCION_AGENTES_SVW
	--  v1.7	20250424    Añadida la vista CSA_INSPECTORES_ACTIVOS_SVW
	--  v1.8	20250506    Añadida la visibilidad de oficinas por posiciones con tipo de relación "Empleados"
	--  V1.9	20250507    Añadida la vista CSA_PROD_INSPECTORES_SVW
	--  V1.10	20250507    Añadida la vista CSA_RPA_RESUMEN_SVW
	--	v1.11	20250625	Modificada la estructura para incluír --SELECCIONAR--
	--	v1.12	20250630	Eliminada la vista CSA_RESUMEN_REPARTO_PAGOS_SVW
	--	v1.13	20250729	Para la visibilidad de oficinas, el userid tiene que se de la sesión también
	--	v1.14	20250801	Uso del FV-VisibilidadReporting para el bloqueo a payees de la visibilidd 
	--	v1.15	20251031	Añadidas las vistas CSA_S4_RPA_RESUMEN_SVW, CSA_S5_RPI_RESUMEN_SVW, CSA_PEPA_RESUMEN_SVW, CSA_BAL_PEPA_RESUMEN_SVW, CSA_LC_PEPA_RESUMEN_SVW, CSA_RPP_RESUMEN_SVW, CSA_BAL_RPP_RESUMEN_SVW, CSA_LC_RPP_RESUMEN_SVW, CSA_RPP_DETALLE_SVW, CSA_BAL_RPP_DETALLE_SVW, CSA_LC_RPP_DETALLE_SVW, CSA_PEPI_RESUMEN_SVW, CSA_BAL_PEPI_RESUMEN_SVW, CSA_LC_PEPI_RESUMEN_SVW
	--			20251031	Eliminada la vista CSA_REPARTO_PAGOS_SVW
	--	v2.0	20251104	Cambiada completamente la estructura para mejorar rendimiento

ALTER STRUCTURED PRIVILEGE REP_SECURITY_EXT
FOR SELECT
ON EXT.CSA_ESTRUCTURA_COMERCIAL_SVW, EXT.CSA_PROD_AGENTES_SVW_E, EXT.CSA_S4_POLIZAS_SVW, EXT.CSA_S4_FACTURA_SVW, EXT.CSA_S5_FACTURA_SVW,
	EXT.CSA_DIST_RAPPEL_MENSUAL_SVW_E, EXT.CSA_S5_POLIZAS_SVW,
	EXT.CSA_PERCEPCION_INSPECTORES_SVW, EXT.CSA_PROD_AGENTES_SVW_O, EXT.CSA_PERCEPCION_AGENTES_SVW, EXT.CSA_INSPECTORES_ACTIVOS_SVW,
	EXT.CSA_PROD_INSPECTORES_SVW, EXT.CSA_RPA_RESUMEN_SVW,
	EXT.CSA_S4_RPA_RESUMEN_SVW, EXT.CSA_S5_RPI_RESUMEN_SVW,
	EXT.CSA_PEPA_RESUMEN_SVW, EXT.CSA_BAL_PEPA_RESUMEN_SVW, EXT.CSA_LC_PEPA_RESUMEN_SVW,
	EXT.CSA_RPP_RESUMEN_SVW, EXT.CSA_BAL_RPP_RESUMEN_SVW, EXT.CSA_LC_RPP_RESUMEN_SVW, EXT.CSA_RPP_DETALLE_SVW, EXT.CSA_BAL_RPP_DETALLE_SVW, EXT.CSA_LC_RPP_DETALLE_SVW,
	EXT.CSA_PEPI_RESUMEN_SVW, EXT.CSA_BAL_PEPI_RESUMEN_SVW, EXT.CSA_LC_PEPI_RESUMEN_SVW


WHERE (POSITIONSEQ, PERIODSEQ) IN ( 
	SELECT distinct PARD.DESCENDANTPOSITIONSEQ, PARD.PERIODSEQ
	FROM TCMP.CSA_PADIMENSION PAD
	INNER JOIN CS_PERIOD PER ON PAD.PERIODSEQ = PER.PERIODSEQ and PER.REMOVEDATE='2200-01-01'
	INNER JOIN CSA_PAREPORTINGDIMENSION PARD ON PAD.PERIODSEQ = PARD.PERIODSEQ AND 
												PAD.PARTICIPANTSEQ = PARD.ANCESTORPARTICIPANTSEQ AND
												PAD.POSITIONSEQ = PARD.ANCESTORPOSITIONSEQ AND 
												(
													(PAD.POSITIONGENERICNUMBER2 <> 73 AND PAD.POSITIONGENERICNUMBER2 BETWEEN 50 AND 82 AND PARD.RELATIVEDISTANCE = 0)
												OR 
													PAD.POSITIONGENERICNUMBER2 IS NULL
												OR NOT 
													(PAD.POSITIONGENERICNUMBER2 <> 73 AND PAD.POSITIONGENERICNUMBER2 BETWEEN 50 AND 82)
												)
	WHERE PAD.ISPAYEE=1 AND -- se aplican mismos filtros que en ORACLE
		  PAD.TITLENAME <> 'TTL SIN PLAN' AND 
		  (PAD.TERMINATIONDATE IS NULL OR PAD.TERMINATIONDATE >= PER.ENDDATE) AND 
		  PER.STARTDATE>='2020-01-01' AND -- Solo visibles datos desde 2020 (se podria recuperar de clasificacion)
		  ( 
			( --INICIO PAD USERS + Visibility
		  		( 
					PAD.USERID=SESSION_CONTEXT('APPLICATIONUSER')
					OR  -- Visibilidad por posicion definida por configuracion en EA
					PAD.POSITIONSEQ IN ( SELECT VALUE 
										FROM CSA_DATASECURITY DS
										WHERE DS.USERID = SESSION_CONTEXT('APPLICATIONUSER') AND 
										  DS.REMOVEDATE = TO_DATE('22000101','YYYYMMDD') AND
										  DS.SECURITYTYPE = 'POS'  )
					OR  -- visibilidad de oficinas por posiciones con tipo de relaci�n "Empleados" 
					PAD.POSITIONSEQ IN ( SELECT POSREL.PARENTPOSITIONSEQ
										FROM TCMP.CS_POSITIONRELATION POSREL
										INNER JOIN TCMP.CS_POSITIONRELATIONTYPE RELTYP ON RELTYP.DATATYPESEQ = POSREL.POSITIONRELATIONTYPESEQ AND
											RELTYP.REMOVEDATE = TO_DATE('22000101','YYYYMMDD') AND
											RELTYP.NAME = 'Empleados'
										INNER JOIN TCMP.CS_POSITION POSCHI ON POSCHI.RULEELEMENTOWNERSEQ = POSREL.CHILDPOSITIONSEQ AND
											POSCHI.REMOVEDATE = TO_DATE('22000101','YYYYMMDD') AND
											POSCHI.ISLAST = 1
										INNER JOIN TCMP.CS_PARTICIPANT PARCHI ON POSCHI.PAYEESEQ = PARCHI.PAYEESEQ AND
											PARCHI.REMOVEDATE = TO_DATE('22000101','YYYYMMDD') AND
											PARCHI.ISLAST = 1
										WHERE POSREL.REMOVEDATE = TO_DATE('22000101','YYYYMMDD') AND
											POSREL.ISLAST = 1 AND
											PARCHI.USERID = SESSION_CONTEXT('APPLICATIONUSER') -- 'O2RC'
								)
		  		) AND -- Visibilidad de datos en informes solo aplica a mediadores
		  		1 = (	SELECT VALUE 
								FROM TCMP.CS_FIXEDVALUE
								WHERE NAME = 'FV-VisibilidadReporting' AND REMOVEDATE = TO_DATE('22000101','YYYYMMDD')
							UNION ALL
								SELECT 1 FROM DUMMY 
								WHERE NOT EXISTS ( SELECT 1 FROM TCMP.CS_FIXEDVALUE WHERE NAME = 'FV-VisibilidadReporting' AND REMOVEDATE = TO_DATE('22000101','YYYYMMDD'))
							LIMIT 1
					)			
			)
		  OR -- Visibilidad de Administradores por configuracion en EA
			EXISTS (	SELECT 1 
						FROM CSA_DATASECURITY 
						WHERE (USERID = SESSION_CONTEXT('APPLICATIONUSER') 
								AND SECURITYTYPE = 'ALL' 
								AND REMOVEDATE = TO_DATE('22000101','YYYYMMDD')) 
							OR (SESSION_CONTEXT('APPLICATIONUSER') LIKE 'WEBIDE_xxPS%')
						)
		  )
	-- Caso --SELECCIONAR--, donde POSITIONSEQ est� fijado a -1
	UNION
	SELECT distinct -1, PARD.PERIODSEQ
	FROM CSA_PAREPORTINGDIMENSION PARD
	INNER JOIN CS_PERIOD PER ON PARD.PERIODSEQ = PER.PERIODSEQ and PER.REMOVEDATE='2200-01-01'
	WHERE PER.STARTDATE>='2020-01-01'
);