CREATE OR REPLACE VIEW EXT.CSA_ESTRUCTURA_COMERCIAL_SVW ("PARTICIPANTEMAIL", "TAXID", "PAR_EFFECTIVESTARTDATE", "PAR_EFFECTIVEENDDATE", "PERIODNAME", "PERIODSHORTNAME", "PERIODDESCRIPTION", "STARTDATE", "ENDDATE", "NOMBRE_COMPLETO", "PERIODSEQ", "POSITIONSEQ", "PARTICIPANTSEQ", "PARTICIPANTID", "USERID", "PREFIX", "FIRSTNAME", "MIDDLENAME", "LASTNAME", "SUFFIX", "FULLNAME", "SALARY", "HIREDATE", "TERMINATIONDATE", "BUSINESSUNITMAP", "BUSINESSUNITNAME", "POSITIONNAME", "POSITIONDESCRIPTION", "POSITIONGROUPNAME", "TITLENAME", "TITLEDESCRIPTION", "TARGETCOMPENSATION", "PLANNAME", "PLANSEQ", "POSITIONGENERICATTRIBUTE1", "POSITIONGENERICATTRIBUTE2", "POSITIONGENERICATTRIBUTE3", "POSITIONGENERICATTRIBUTE4", "POSITIONGENERICATTRIBUTE5", "POSITIONGENERICATTRIBUTE6", "POSITIONGENERICATTRIBUTE7", "POSITIONGENERICATTRIBUTE8", "POSITIONGENERICATTRIBUTE9", "POSITIONGENERICATTRIBUTE10", "POSITIONGENERICATTRIBUTE11", "POSITIONGENERICATTRIBUTE12", "POSITIONGENERICATTRIBUTE13", "POSITIONGENERICATTRIBUTE14", "POSITIONGENERICATTRIBUTE15", "POSITIONGENERICATTRIBUTE16", "POSITIONGENERICNUMBER1", "POSITIONGENERICNUMBER2", "POSITIONGENERICNUMBER3", "POSITIONGENERICNUMBER4", "POSITIONGENERICNUMBER5", "POSITIONGENERICNUMBER6", "POSITIONGENERICDATE1", "POSITIONGENERICDATE2", "POSITIONGENERICDATE3", "POSITIONGENERICDATE4", "POSITIONGENERICDATE5", "POSITIONGENERICDATE6", "POSITIONGENERICBOOLEAN1", "POSITIONGENERICBOOLEAN2", "POSITIONGENERICBOOLEAN3", "POSITIONGENERICBOOLEAN4", "POSITIONGENERICBOOLEAN5", "POSITIONGENERICBOOLEAN6", "PARTICIPANTGENERICATTRIBUTE1", "PARTICIPANTGENERICATTRIBUTE2", "PARTICIPANTGENERICATTRIBUTE3", "PARTICIPANTGENERICATTRIBUTE4", "PARTICIPANTGENERICATTRIBUTE5", "PARTICIPANTGENERICATTRIBUTE6", "PARTICIPANTGENERICATTRIBUTE7", "PARTICIPANTGENERICATTRIBUTE8", "PARTICIPANTGENERICATTRIBUTE9", "PARTICIPANTGENERICATTRIBUTE10", "PARTICIPANTGENERICATTRIBUTE11", "PARTICIPANTGENERICATTRIBUTE12", "PARTICIPANTGENERICATTRIBUTE13", "PARTICIPANTGENERICATTRIBUTE14", "PARTICIPANTGENERICATTRIBUTE15", "PARTICIPANTGENERICATTRIBUTE16", "PARTICIPANTGENERICNUMBER1", "PARTICIPANTGENERICNUMBER2", "PARTICIPANTGENERICNUMBER3", "PARTICIPANTGENERICNUMBER4", "PARTICIPANTGENERICNUMBER5", "PARTICIPANTGENERICNUMBER6", "PARTICIPANTGENERICDATE1", "PARTICIPANTGENERICDATE2", "PARTICIPANTGENERICDATE3", "PARTICIPANTGENERICDATE4", "PARTICIPANTGENERICDATE5", "PARTICIPANTGENERICDATE6", "PARTICIPANTGENERICBOOLEAN1", "PARTICIPANTGENERICBOOLEAN2", "PARTICIPANTGENERICBOOLEAN3", "PARTICIPANTGENERICBOOLEAN4", "PARTICIPANTGENERICBOOLEAN5", "PARTICIPANTGENERICBOOLEAN6", "TITLEGENERICATTRIBUTE1", "TITLEGENERICATTRIBUTE2", "TITLEGENERICATTRIBUTE3", "TITLEGENERICATTRIBUTE4", "TITLEGENERICNUMBER1", "TITLEGENERICNUMBER2", "TITLEGENERICNUMBER3", "TITLEGENERICNUMBER4", "TITLEGENERICDATE1", "TITLEGENERICDATE2", "TITLEGENERICBOOLEAN1", "TITLEGENERICBOOLEAN2", "MANAGERSEQ", "MANAGERFULLNAME", "ISPAYEE", "BOUSERID", "MANAGERPARTICIPANTSEQ", "PA_SK", "IDREGIONAL", "REGIONAL", "IDSUCURSAL", "SUCURSAL", "IDOFICINA", "OFICINA", "PV", "CODIGO", "INSPECTOR_NAME", "INSPECTOR_NIF", "INSPECTOR_NOMBRE_COMPLETO", "INSPECTOR_TITLE", "INSPECTOR_LDAP", "INSPECTOR_IDTIPOAGENTE", "INSPECTOR_TIPOAGENTE", "INSPCAP_NAME", "INSPCAP_NIF", "INSPCAP_NOMBRE_COMPLETO", "INSPCAP_TITLE", "INSPCAP_LDAP", "INSPCAP_IDTIPOAGENTE", "INSPCAP_TIPOAGENTE", "MEDCOUNT" ) 
AS (
WITH ESTRUCTURA AS (
	SELECT X.NAME as EPOS_NAME,X.RULEELEMENTOWNERSEQ as EPOSITIONSEQ,
		X.GENERICATTRIBUTE2 EPOS_GENERICATTRIBUTE2, X.GENERICATTRIBUTE3 AS EPOS_GENERICATTRIBUTE3,
		TO_INTEGER(X.GENERICNUMBER2) AS EPOS_GENERICNUMBER2, X.GENERICNUMBER3 AS EPOS_GENERICNUMBER3,
		IFNULL(RTRIM(Y.FIRSTNAME) || ' ','')  || IFNULL(RTRIM(Y.LASTNAME),'') || IFNULL(' ' || RTRIM(Y.SUFFIX), '') AS NOMBRE_COMPLETO, 
        Y.FIRSTNAME,Y.LASTNAME,Y.SUFFIX,Y.GENERICATTRIBUTE1 AS NIF, X.MANAGERSEQ as EPOS_MANAGERSEQ,
        Y.USERID as EPAR_USERID,
        Z.NAME AS ETITLE,
    	X.EFFECTIVESTARTDATE as EPOS_EFFECTIVESTARTDATE, X.EFFECTIVEENDDATE as EPOS_EFFECTIVEENDDATE,
		Y.EFFECTIVESTARTDATE as EPAR_EFFECTIVESTARTDATE, Y.EFFECTIVEENDDATE as EPAR_EFFECTIVEENDDATE,
		Z.EFFECTIVESTARTDATE as ETIT_EFFECTIVESTARTDATE, Z.EFFECTIVEENDDATE as ETIT_EFFECTIVEENDDATE
    FROM 
	TCMP.CS_POSITION X 
        INNER JOIN TCMP.CS_PARTICIPANT Y ON Y.PAYEESEQ = X.PAYEESEQ and Y.REMOVEDATE = TO_DATE('22000101','yyyymmdd')  
        			AND X.EFFECTIVESTARTDATE <= Y.EFFECTIVEENDDATE and X.EFFECTIVEENDDATE >= Y.EFFECTIVESTARTDATE
    	INNER JOIN TCMP.CS_PAYEE R ON Y.PAYEESEQ = R.PAYEESEQ and R.REMOVEDATE = TO_DATE('22000101','yyyymmdd')
        			AND Y.EFFECTIVESTARTDATE = R.EFFECTIVESTARTDATE and Y.EFFECTIVEENDDATE = R.EFFECTIVEENDDATE
    	INNER JOIN TCMP.CS_TITLE Z ON X.TITLESEQ = Z.RULEELEMENTOWNERSEQ AND Z.REMOVEDATE = TO_DATE('22000101','yyyymmdd') 
        			AND X.EFFECTIVESTARTDATE <= Z.EFFECTIVEENDDATE and X.EFFECTIVEENDDATE >= Z.EFFECTIVESTARTDATE
        where X.REMOVEDATE = TO_DATE('22000101','yyyymmdd') 
) 
Select  DISTINCT
PAR.PARTICIPANTEMAIL, -- Correo electrónico
PAR.TAXID , -- Tipo de IRPF
PAR.EFFECTIVESTARTDATE as PAR_EFFECTIVESTARTDATE, -- Fecha Inicio Efectividad
PAR.EFFECTIVEENDDATE as PAR_EFFECTIVEENDDATE, -- Fecha Fin Efectividad
PER.NAME AS PERIODNAME, 
PER.SHORTNAME as PERIODSHORTNAME, 
PER.DESCRIPTION AS PERIODDESCRIPTION, 
PER.STARTDATE, 
PER.ENDDATE, 
IFNULL(RTRIM(PAD.FIRSTNAME) || ' ','')  || IFNULL(RTRIM(PAD.LASTNAME),'') || IFNULL(' ' || RTRIM(PAD.SUFFIX), '') AS NOMBRE_COMPLETO, 
PAD.PERIODSEQ, 
POSITIONSEQ, 
PARTICIPANTSEQ, 
PARTICIPANTID, -- ID de participante
PAD.USERID, -- Usuario LDAP
PAD.PREFIX, 
PAD.FIRSTNAME, -- Nombre
PAD.MIDDLENAME, -- Email personal
PAD.LASTNAME, -- Apellido 1/Razón social
PAD.SUFFIX, -- Apellido 2
PAD.FULLNAME, 
PAD.SALARY, -- Pago por IBAN
PAD.HIREDATE, -- Fecha de Contrato
PAD.TERMINATIONDATE, -- Fecha Fin Agente
PAD.BUSINESSUNITMAP, 
PAD.BUSINESSUNITNAME, 
POSITIONNAME, -- Posición
POSITIONDESCRIPTION, -- Descripción Posición
POSITIONGROUPNAME, -- Grupo de Posición
TITLENAME, -- Título
TITLEDESCRIPTION, -- Descripción Título
TARGETCOMPENSATION, -- Objetivo Comisiones
PLANNAME, -- PLAN
PLANSEQ, 
POSITIONGENERICATTRIBUTE1, -- Tipo Principal Agente / Clase Oficina (GA1)
IFNULL(TO_VARCHAR(TO_INTEGER(POSITIONGENERICNUMBER2))  || ' - ','') || IFNULL(POSITIONGENERICATTRIBUTE2 ,'') as POSITIONGENERICATTRIBUTE2 , -- Tipo Agente / Tipo Oficina (GA2)
POSITIONGENERICATTRIBUTE3, -- Código de Agente OCASO (GA3)
POSITIONGENERICATTRIBUTE4, -- Rehabilitación (GA4)
POSITIONGENERICATTRIBUTE5, -- Cuadro Inspector Ocaso (GA5)
POSITIONGENERICATTRIBUTE6, -- Cuadro RRGG Ocaso (GA6)
POSITIONGENERICATTRIBUTE7, -- Cuadro RRTT Ocaso (GA7)
POSITIONGENERICATTRIBUTE8, -- Compañía (GA8)
POSITIONGENERICATTRIBUTE9, -- Promoción Agente (GA9)
POSITIONGENERICATTRIBUTE10, -- Cuadro Inspector Eterna (GA10)
POSITIONGENERICATTRIBUTE11, -- Cuadro RRGG Eterna (GA11)
POSITIONGENERICATTRIBUTE12, -- Cuadro RRTT Eterna (GA12)
POSITIONGENERICATTRIBUTE13, -- Año Captación (GA13)
POSITIONGENERICATTRIBUTE14, -- Inspector Captador (GA14)
POSITIONGENERICATTRIBUTE15, -- Número Meses Preplan (GA15)
POSITIONGENERICATTRIBUTE16, -- Escalado Asistencia (GA16)
POSITIONGENERICNUMBER1, -- ID Tipo Principal Agente (GN1)
POSITIONGENERICNUMBER2, -- ID Tipo Agente (GN2)
POSITIONGENERICNUMBER3, -- ID Clase Oficina (GN3)
POSITIONGENERICNUMBER4, -- ID Tipo Oficina (GN4)
POSITIONGENERICNUMBER5, -- % Comisión Cartera (GN5)
POSITIONGENERICNUMBER6, -- Importe Comisión Cartera (GN6)
POSITIONGENERICDATE1, -- Fecha de Alta (GD1)
POSITIONGENERICDATE2, -- Fecha de Baja (GD2)
POSITIONGENERICDATE3, -- Fecha Inicio Consolidación P.C. (GD3)
POSITIONGENERICDATE4, -- Fecha Fin Consolidación P.C. (GD4)
POSITIONGENERICDATE5, -- Fecha Inicio Asistencia (GD5)
POSITIONGENERICDATE6, -- Fecha Límite Comisiones Cartera (GD6)
POSITIONGENERICBOOLEAN1, -- Reducción (GB1)
POSITIONGENERICBOOLEAN2, -- Productor Ocaso (GB2)
POSITIONGENERICBOOLEAN3, -- Consolida (GB3)
POSITIONGENERICBOOLEAN4, -- Inicio Agente Asistencia (GB4)
POSITIONGENERICBOOLEAN5, -- Productor Eterna (GB5)
POSITIONGENERICBOOLEAN6, -- Ag. Lider (GB6)
PARTICIPANTGENERICATTRIBUTE1, -- Documento (GA1)
PARTICIPANTGENERICATTRIBUTE2, -- Tipo Documento (GA2)
PARTICIPANTGENERICATTRIBUTE3, -- Tipo Persona (GA3)
PARTICIPANTGENERICATTRIBUTE4, -- Código DGS (GA4)
PARTICIPANTGENERICATTRIBUTE5, -- Compañía (GA5)
PARTICIPANTGENERICATTRIBUTE6, -- Tipo Mediador (GA6)
PARTICIPANTGENERICATTRIBUTE7, -- Localidad (GA7)
PARTICIPANTGENERICATTRIBUTE8, -- Tipo Vía (GA8)
PARTICIPANTGENERICATTRIBUTE9, -- Domicilio (GA9)
PARTICIPANTGENERICATTRIBUTE10, -- Número (GA10)
PARTICIPANTGENERICATTRIBUTE11, -- Resto Domicilio (GA11)
PARTICIPANTGENERICATTRIBUTE12, -- Sexo (GA12)
PARTICIPANTGENERICATTRIBUTE13, -- Estado Civil (GA13)
PARTICIPANTGENERICATTRIBUTE14, -- Teléfono Fijo (GA14)
PARTICIPANTGENERICATTRIBUTE15, -- Teléfono Móvil (GA15)
PARTICIPANTGENERICATTRIBUTE16, -- IBAN (GA16)
PARTICIPANTGENERICNUMBER1, -- Código Postal (GN1)
PARTICIPANTGENERICNUMBER2, -- Provincia (GN2)
PARTICIPANTGENERICNUMBER3, -- Municipio (GN3)
PARTICIPANTGENERICNUMBER4, -- ID_Empleado (GN4)
PARTICIPANTGENERICNUMBER5, -- % IRPF (GN5)
PARTICIPANTGENERICNUMBER6, -- Fax (GN6)
PARTICIPANTGENERICDATE1, -- Fecha Nacimiento (GD1)
PARTICIPANTGENERICDATE2, -- Fecha Registro DGS (GD2)
PARTICIPANTGENERICDATE3, -- Fecha Envío DGS (GD3)
PARTICIPANTGENERICDATE4, -- Fin CIASE 1 (GD4)
PARTICIPANTGENERICDATE5, -- Fecha Efecto SuperRappel (GD5)
PARTICIPANTGENERICDATE6, -- Fecha Regularización SuperRappel (GD6)
PARTICIPANTGENERICBOOLEAN1, -- Autoliquida (GB1)
PARTICIPANTGENERICBOOLEAN2, -- Corredor (GB2)
PARTICIPANTGENERICBOOLEAN3, -- Autorización Factura (GB3)
PARTICIPANTGENERICBOOLEAN4, -- SuperRappel (GB4)
PARTICIPANTGENERICBOOLEAN5, -- Comisiones Anualizadas RRPP OCASO (GB5)
PARTICIPANTGENERICBOOLEAN6, -- Cartera RRTT (GB6)
TITLEGENERICATTRIBUTE1, -- Tipo Principal Agente / Clase Oficina (GA1)
TITLEGENERICATTRIBUTE2, -- Tipo Agente / Tipo Oficina (GA2)
TITLEGENERICATTRIBUTE3, 
TITLEGENERICATTRIBUTE4, 
TITLEGENERICNUMBER1, -- ID Tipo Principal  Agente (GN1)
TITLEGENERICNUMBER2, -- ID Tipo  Agente (GN2)
TITLEGENERICNUMBER3, -- ID Clase Oficina (GN3)
TITLEGENERICNUMBER4, -- ID Tipo Oficina (GN4)
TITLEGENERICDATE1, 
TITLEGENERICDATE2, 
TITLEGENERICBOOLEAN1, -- Genera Informe (GB1)
TITLEGENERICBOOLEAN2, 
MANAGERSEQ, -- MANAGERSEQ
MANAGERFULLNAME, 
ISPAYEE, 
BOUSERID, 
MANAGERPARTICIPANTSEQ, 
PA_SK,
    CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (5) THEN REG.EPOS_NAME
        ELSE CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (4,7) THEN SUC.EPOS_NAME
            ELSE CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (3,6,8,10,11) THEN OFI.EPOS_NAME
                ELSE PTO_VENTA.EPOS_NAME END
    END END as IDREGIONAL,
    CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (5) THEN REG.EPOS_NAME
        ELSE CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (4,7) THEN SUC.EPOS_NAME
            ELSE CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (3,6,8,10,11) THEN OFI.EPOS_NAME
                ELSE PTO_VENTA.EPOS_NAME END
    END END || ' - ' ||
    CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (5) THEN REG.LASTNAME
        ELSE CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (4,7) THEN SUC.LASTNAME
            ELSE CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (3,6,8,10,11) THEN OFI.LASTNAME
                ELSE PTO_VENTA.LASTNAME END
    END END AS REGIONAL, 
    CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (5) THEN SUC.EPOS_NAME
        ELSE CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (4,7) THEN OFI.EPOS_NAME
            ELSE PTO_VENTA.EPOS_NAME END 
    END as IDSUCURSAL,
    CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (5) THEN SUC.EPOS_NAME
        ELSE CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (4,7) THEN OFI.EPOS_NAME
            ELSE PTO_VENTA.EPOS_NAME END 
    END || ' - ' ||
    CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (5) THEN SUC.LASTNAME
        ELSE CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (4,7) THEN OFI.LASTNAME
            ELSE PTO_VENTA.LASTNAME END 
    END AS SUCURSAL,                                                                                            --titleGenericAttribute2
    CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (5) THEN OFI.EPOS_NAME  
        ELSE PTO_VENTA.EPOS_NAME END as IDOFICINA,
    CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (5) THEN OFI.EPOS_NAME  
        ELSE PTO_VENTA.EPOS_NAME END || ' - ' ||
    CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (5) THEN OFI.LASTNAME  
        ELSE PTO_VENTA.LASTNAME END AS OFICINA,
LEFT(PAD.POSITIONGENERICATTRIBUTE3, 4) as PV, RIGHT(PAD.POSITIONGENERICATTRIBUTE3, 4) as CODIGO,
MANAGER.EPOS_NAME as INSPECTOR_NAME, MANAGER.NIF as INSPECTOR_NIF, MANAGER.NOMBRE_COMPLETO as INSPECTOR_NOMBRE_COMPLETO, 
MANAGER.ETITLE as INSPECTOR_TITLE, MANAGER.EPAR_USERID as INSPECTOR_LDAP,
MANAGER.EPOS_GENERICNUMBER2 AS INSPECTOR_IDTIPOAGENTE,MANAGER.EPOS_GENERICATTRIBUTE2 AS INSPECTOR_TIPOAGENTE,
INSP_CAP.EPOS_NAME as INSPCAP_NAME, INSP_CAP.NIF as INSPCAP_NIF, INSP_CAP.NOMBRE_COMPLETO as INSPCAP_NOMBRE_COMPLETO, 
INSP_CAP.ETITLE as INSPCAP_TITLE, INSP_CAP.EPAR_USERID as INSPCAP_LDAP,
INSP_CAP.EPOS_GENERICNUMBER2 AS INSPCAP_IDTIPOAGENTE,INSP_CAP.EPOS_GENERICATTRIBUTE2 AS INSPCAP_TIPOAGENTE,
1 as MEDCOUNT
from CSA_PADIMENSION PAD 
INNER JOIN CSA_PERIODDIMENSION PER 
	ON PAD.PERIODSEQ = PER.PERIODSEQ

-- PARTICIPANT - DATOS PARTICIPANT QUE NO ESTAN EN PADIMENSION
INNER JOIN CS_PARTICIPANT PAR -- Se hace un JOIN con CS_PARTICIPANT a ultimo dia del mes de cada periodo para extraer: PAR.PARTICIPANTEMAIL, PAR.TAXID y fechas de efectividad por si quisieran filtrar por fecha concreta
	ON PAD.PARTICIPANTSEQ = PAR.PAYEESEQ and PAR.REMOVEDATE = TO_DATE('22000101','yyyymmdd')
	AND PAR.EFFECTIVESTARTDATE< PER.ENDDATE and  PAR.EFFECTIVEENDDATE >= PER.ENDDATE

-- MANAGER
LEFT JOIN ESTRUCTURA MANAGER ON MANAGER.EPOSITIONSEQ = PAD.MANAGERSEQ 
								AND MANAGER.EPOS_GENERICNUMBER2 is not null 
								AND MANAGER.EPOS_GENERICATTRIBUTE3 NOT IN ('0000000000','0') 
								AND MANAGER.EPOS_MANAGERSEQ IS NOT NULL
								AND MANAGER.EPOS_EFFECTIVESTARTDATE < PER.ENDDATE and  MANAGER.EPOS_EFFECTIVEENDDATE >= PER.ENDDATE
								AND MANAGER.EPAR_EFFECTIVESTARTDATE <  PER.ENDDATE  and  MANAGER.EPAR_EFFECTIVEENDDATE >=  PER.ENDDATE  
								AND MANAGER.ETIT_EFFECTIVESTARTDATE <  PER.ENDDATE  and  MANAGER.ETIT_EFFECTIVEENDDATE >=  PER.ENDDATE 
-- INSP_CAP						
LEFT JOIN ESTRUCTURA INSP_CAP ON INSP_CAP.EPOS_NAME = PAD.POSITIONGENERICATTRIBUTE14
								AND INSP_CAP.EPOS_GENERICATTRIBUTE3 NOT IN ('0000000000','0') 
								AND INSP_CAP.EPOS_EFFECTIVESTARTDATE < PER.ENDDATE and  INSP_CAP.EPOS_EFFECTIVEENDDATE >= PER.ENDDATE
								AND INSP_CAP.EPAR_EFFECTIVESTARTDATE <  PER.ENDDATE  and  INSP_CAP.EPAR_EFFECTIVEENDDATE >=  PER.ENDDATE  
								AND INSP_CAP.ETIT_EFFECTIVESTARTDATE <  PER.ENDDATE  and  INSP_CAP.ETIT_EFFECTIVEENDDATE >=  PER.ENDDATE 
-- PTO_VENTA
LEFT JOIN ESTRUCTURA PTO_VENTA ON SUBSTR(PAD.POSITIONGENERICATTRIBUTE3,1,4) = PTO_VENTA.EPOS_NAME
								AND PTO_VENTA.EPOS_GENERICNUMBER2 IS NULL 
								AND PTO_VENTA.EPOS_EFFECTIVESTARTDATE < PER.ENDDATE and  PTO_VENTA.EPOS_EFFECTIVEENDDATE >= PER.ENDDATE
								AND PTO_VENTA.EPAR_EFFECTIVESTARTDATE <  PER.ENDDATE  and  PTO_VENTA.EPAR_EFFECTIVEENDDATE >=  PER.ENDDATE  
								AND PTO_VENTA.ETIT_EFFECTIVESTARTDATE <  PER.ENDDATE  and  PTO_VENTA.ETIT_EFFECTIVEENDDATE >=  PER.ENDDATE
-- OFI
LEFT JOIN ESTRUCTURA OFI ON PTO_VENTA.EPOS_MANAGERSEQ = OFI.EPOSITIONSEQ
								AND OFI.EPOS_GENERICNUMBER2 IS NULL 
								AND OFI.EPOS_EFFECTIVESTARTDATE < PER.ENDDATE and  OFI.EPOS_EFFECTIVEENDDATE >= PER.ENDDATE
								AND OFI.EPAR_EFFECTIVESTARTDATE <  PER.ENDDATE  and  OFI.EPAR_EFFECTIVEENDDATE >=  PER.ENDDATE  
								AND OFI.ETIT_EFFECTIVESTARTDATE <  PER.ENDDATE  and  OFI.ETIT_EFFECTIVEENDDATE >=  PER.ENDDATE


-- SUC
LEFT JOIN ESTRUCTURA SUC ON OFI.EPOS_MANAGERSEQ = SUC.EPOSITIONSEQ
								AND SUC.EPOS_GENERICNUMBER2 IS NULL 
								AND SUC.EPOS_EFFECTIVESTARTDATE < PER.ENDDATE and  SUC.EPOS_EFFECTIVEENDDATE >= PER.ENDDATE
								AND SUC.EPAR_EFFECTIVESTARTDATE <  PER.ENDDATE  and  SUC.EPAR_EFFECTIVEENDDATE >=  PER.ENDDATE  
								AND SUC.ETIT_EFFECTIVESTARTDATE <  PER.ENDDATE  and  SUC.ETIT_EFFECTIVEENDDATE >=  PER.ENDDATE 		

-- REG
LEFT JOIN ESTRUCTURA REG ON SUC.EPOS_MANAGERSEQ = REG.EPOSITIONSEQ
								AND REG.EPOS_GENERICNUMBER2 IS NULL 
								AND REG.EPOS_EFFECTIVESTARTDATE < PER.ENDDATE and  REG.EPOS_EFFECTIVEENDDATE >= PER.ENDDATE
								AND REG.EPAR_EFFECTIVESTARTDATE <  PER.ENDDATE  and  REG.EPAR_EFFECTIVEENDDATE >=  PER.ENDDATE  
								AND REG.ETIT_EFFECTIVESTARTDATE <  PER.ENDDATE  and  REG.ETIT_EFFECTIVEENDDATE >=  PER.ENDDATE 		

WHERE PAD.USERID = PAR.USERID and BUSINESSUNITMAP = 1 -- Se filtran los que su usuario coincide con el Usuario del participante (No añadidos de CSA_PLUGIN ) y con BU informadas habia filas "raras" sin BU
) WITH READ ONLY