CREATE OR REPLACE VIEW "EXT"."CSA_ESTRUCTURA_SVW" ("PERIODSEQ", "POSITIONSEQ", "PARTICIPANTSEQ", "POSITIONNAME", "PARTICIPANTID", "USERID", "IDREGIONAL", "REGIONAL", "IDSUCURSAL", "SUCURSAL", "IDOFICINA", "OFICINA", "PV", "CODIGO", "INSPECTOR_NAME", "INSPECTOR_NIF", "INSPECTOR_NOMBRE_COMPLETO", "INSPECTOR_TITLE", "INSPECTOR_LDAP", "INSPECTOR_IDTIPOAGENTE", "INSPECTOR_TIPOAGENTE", "INSPCAP_NAME", "INSPCAP_NIF", "INSPCAP_NOMBRE_COMPLETO", "INSPCAP_TITLE", "INSPCAP_LDAP", "INSPCAP_IDTIPOAGENTE", "INSPCAP_TIPOAGENTE", "ESTCOUNT" ) 
AS (
WITH ESTRUCTURA AS (
	SELECT X.NAME as EPOS_NAME,X.RULEELEMENTOWNERSEQ as EPOSITIONSEQ,
		X.GENERICATTRIBUTE2 EPOS_GENERICATTRIBUTE2, X.GENERICATTRIBUTE3 AS EPOS_GENERICATTRIBUTE3,
		TO_INTEGER(X.GENERICNUMBER2) AS EPOS_GENERICNUMBER2, X.GENERICNUMBER3 AS EPOS_GENERICNUMBER3,
		IFNULL(RTRIM(Y.FIRSTNAME) || ' ','')  || IFNULL(RTRIM(Y.LASTNAME),'') || IFNULL(' ' || RTRIM(Y.SUFFIX), '') AS NOMBRE_COMPLETO, 
        Y.FIRSTNAME,Y.LASTNAME,Y.SUFFIX,Y.GENERICATTRIBUTE1 AS NIF, X.MANAGERSEQ as EPOS_MANAGERSEQ,
        Y.USERID as EPAR_USERID,
        Z.NAME AS ETITLE,
    	X.EFFECTIVESTARTDATE as EPOS_EFFECTIVESTARTDATE, X.EFFECTIVEENDDATE as EPOS_EFFECTIVEENDDATE,
		Y.EFFECTIVESTARTDATE as EPAR_EFFECTIVESTARTDATE, Y.EFFECTIVEENDDATE as EPAR_EFFECTIVEENDDATE,
		Z.EFFECTIVESTARTDATE as ETIT_EFFECTIVESTARTDATE, Z.EFFECTIVEENDDATE as ETIT_EFFECTIVEENDDATE
    FROM 
	TCMP.CS_POSITION X 
        INNER JOIN TCMP.CS_PARTICIPANT Y ON Y.PAYEESEQ = X.PAYEESEQ and Y.REMOVEDATE = TO_DATE('22000101','yyyymmdd')  
        			AND X.EFFECTIVESTARTDATE <= Y.EFFECTIVEENDDATE and X.EFFECTIVEENDDATE >= Y.EFFECTIVESTARTDATE
    	INNER JOIN TCMP.CS_PAYEE R ON Y.PAYEESEQ = R.PAYEESEQ and R.REMOVEDATE = TO_DATE('22000101','yyyymmdd')
        			AND Y.EFFECTIVESTARTDATE = R.EFFECTIVESTARTDATE and Y.EFFECTIVEENDDATE = R.EFFECTIVEENDDATE
    	INNER JOIN TCMP.CS_TITLE Z ON X.TITLESEQ = Z.RULEELEMENTOWNERSEQ AND Z.REMOVEDATE = TO_DATE('22000101','yyyymmdd') 
        			AND X.EFFECTIVESTARTDATE <= Z.EFFECTIVEENDDATE and X.EFFECTIVEENDDATE >= Z.EFFECTIVESTARTDATE
        where X.REMOVEDATE = TO_DATE('22000101','yyyymmdd') 
) 
select PAD.PERIODSEQ, PAD.POSITIONSEQ, PAD.PARTICIPANTSEQ, PAD.POSITIONNAME, PAD.PARTICIPANTID, PAD.USERID, 
    CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (5) THEN REG.EPOS_NAME
        ELSE CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (4,7) THEN SUC.EPOS_NAME
            ELSE CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (3,6,8,10,11) THEN OFI.EPOS_NAME
                ELSE PTO_VENTA.EPOS_NAME END
    END END as IDREGIONAL,
    CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (5) THEN REG.EPOS_NAME
        ELSE CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (4,7) THEN SUC.EPOS_NAME
            ELSE CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (3,6,8,10,11) THEN OFI.EPOS_NAME
                ELSE PTO_VENTA.EPOS_NAME END
    END END || ' - ' ||
    CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (5) THEN REG.LASTNAME
        ELSE CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (4,7) THEN SUC.LASTNAME
            ELSE CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (3,6,8,10,11) THEN OFI.LASTNAME
                ELSE PTO_VENTA.LASTNAME END
    END END AS REGIONAL, 
    CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (5) THEN SUC.EPOS_NAME
        ELSE CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (4,7) THEN OFI.EPOS_NAME
            ELSE PTO_VENTA.EPOS_NAME END 
    END as IDSUCURSAL,
    CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (5) THEN SUC.EPOS_NAME
        ELSE CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (4,7) THEN OFI.EPOS_NAME
            ELSE PTO_VENTA.EPOS_NAME END 
    END || ' - ' ||
    CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (5) THEN SUC.LASTNAME
        ELSE CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (4,7) THEN OFI.LASTNAME
            ELSE PTO_VENTA.LASTNAME END 
    END AS SUCURSAL,                                                                                            --titleGenericAttribute2
    CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (5) THEN OFI.EPOS_NAME  
        ELSE PTO_VENTA.EPOS_NAME END as IDOFICINA,
    CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (5) THEN OFI.EPOS_NAME  
        ELSE PTO_VENTA.EPOS_NAME END || ' - ' ||
    CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (5) THEN OFI.LASTNAME  
        ELSE PTO_VENTA.LASTNAME END AS OFICINA,
LEFT(PAD.POSITIONGENERICATTRIBUTE3, 4) as PV, RIGHT(PAD.POSITIONGENERICATTRIBUTE3, 4) as CODIGO,
MANAGER.EPOS_NAME as INSPECTOR_NAME, MANAGER.NIF as INSPECTOR_NIF, MANAGER.NOMBRE_COMPLETO as INSPECTOR_NOMBRE_COMPLETO, 
MANAGER.ETITLE as INSPECTOR_TITLE, MANAGER.EPAR_USERID as INSPECTOR_LDAP,
MANAGER.EPOS_GENERICNUMBER2 AS INSPECTOR_IDTIPOAGENTE,MANAGER.EPOS_GENERICATTRIBUTE2 AS INSPECTOR_TIPOAGENTE,
INSP_CAP.EPOS_NAME as INSPCAP_NAME, INSP_CAP.NIF as INSPCAP_NIF, INSP_CAP.NOMBRE_COMPLETO as INSPCAP_NOMBRE_COMPLETO, 
INSP_CAP.ETITLE as INSPCAP_TITLE, INSP_CAP.EPAR_USERID as INSPCAP_LDAP,
INSP_CAP.EPOS_GENERICNUMBER2 AS INSPCAP_IDTIPOAGENTE,INSP_CAP.EPOS_GENERICATTRIBUTE2 AS INSPCAP_TIPOAGENTE,
1 as ESTCOUNT
from CSA_PADIMENSION PAD 
INNER JOIN CSA_PERIODDIMENSION PER 
	ON PAD.PERIODSEQ = PER.PERIODSEQ
LEFT JOIN ESTRUCTURA MANAGER ON MANAGER.EPOSITIONSEQ = PAD.MANAGERSEQ 
								AND MANAGER.EPOS_GENERICNUMBER2 is not null 
								AND MANAGER.EPOS_GENERICATTRIBUTE3 NOT IN ('0000000000','0') 
								AND MANAGER.EPOS_MANAGERSEQ IS NOT NULL
								AND MANAGER.EPOS_EFFECTIVESTARTDATE < PER.ENDDATE and  MANAGER.EPOS_EFFECTIVEENDDATE >= PER.ENDDATE
								AND MANAGER.EPAR_EFFECTIVESTARTDATE <  PER.ENDDATE  and  MANAGER.EPAR_EFFECTIVEENDDATE >=  PER.ENDDATE  
								AND MANAGER.ETIT_EFFECTIVESTARTDATE <  PER.ENDDATE  and  MANAGER.ETIT_EFFECTIVEENDDATE >=  PER.ENDDATE 
-- INSP_CAP						
LEFT JOIN ESTRUCTURA INSP_CAP ON INSP_CAP.EPOS_NAME = PAD.POSITIONGENERICATTRIBUTE14
								AND INSP_CAP.EPOS_GENERICATTRIBUTE3 NOT IN ('0000000000','0') 
								AND INSP_CAP.EPOS_EFFECTIVESTARTDATE < PER.ENDDATE and  INSP_CAP.EPOS_EFFECTIVEENDDATE >= PER.ENDDATE
								AND INSP_CAP.EPAR_EFFECTIVESTARTDATE <  PER.ENDDATE  and  INSP_CAP.EPAR_EFFECTIVEENDDATE >=  PER.ENDDATE  
								AND INSP_CAP.ETIT_EFFECTIVESTARTDATE <  PER.ENDDATE  and  INSP_CAP.ETIT_EFFECTIVEENDDATE >=  PER.ENDDATE 
-- PTO_VENTA
LEFT JOIN ESTRUCTURA PTO_VENTA ON SUBSTR(PAD.POSITIONGENERICATTRIBUTE3,1,4) = PTO_VENTA.EPOS_NAME
								AND PTO_VENTA.EPOS_GENERICNUMBER2 IS NULL 
								AND PTO_VENTA.EPOS_EFFECTIVESTARTDATE < PER.ENDDATE and  PTO_VENTA.EPOS_EFFECTIVEENDDATE >= PER.ENDDATE
								AND PTO_VENTA.EPAR_EFFECTIVESTARTDATE <  PER.ENDDATE  and  PTO_VENTA.EPAR_EFFECTIVEENDDATE >=  PER.ENDDATE  
								AND PTO_VENTA.ETIT_EFFECTIVESTARTDATE <  PER.ENDDATE  and  PTO_VENTA.ETIT_EFFECTIVEENDDATE >=  PER.ENDDATE
-- OFI
LEFT JOIN ESTRUCTURA OFI ON PTO_VENTA.EPOS_MANAGERSEQ = OFI.EPOSITIONSEQ
								AND OFI.EPOS_GENERICNUMBER2 IS NULL 
								AND OFI.EPOS_EFFECTIVESTARTDATE < PER.ENDDATE and  OFI.EPOS_EFFECTIVEENDDATE >= PER.ENDDATE
								AND OFI.EPAR_EFFECTIVESTARTDATE <  PER.ENDDATE  and  OFI.EPAR_EFFECTIVEENDDATE >=  PER.ENDDATE  
								AND OFI.ETIT_EFFECTIVESTARTDATE <  PER.ENDDATE  and  OFI.ETIT_EFFECTIVEENDDATE >=  PER.ENDDATE


-- SUC
LEFT JOIN ESTRUCTURA SUC ON OFI.EPOS_MANAGERSEQ = SUC.EPOSITIONSEQ
								AND SUC.EPOS_GENERICNUMBER2 IS NULL 
								AND SUC.EPOS_EFFECTIVESTARTDATE < PER.ENDDATE and  SUC.EPOS_EFFECTIVEENDDATE >= PER.ENDDATE
								AND SUC.EPAR_EFFECTIVESTARTDATE <  PER.ENDDATE  and  SUC.EPAR_EFFECTIVEENDDATE >=  PER.ENDDATE  
								AND SUC.ETIT_EFFECTIVESTARTDATE <  PER.ENDDATE  and  SUC.ETIT_EFFECTIVEENDDATE >=  PER.ENDDATE 		

-- REG
LEFT JOIN ESTRUCTURA REG ON SUC.EPOS_MANAGERSEQ = REG.EPOSITIONSEQ
								AND REG.EPOS_GENERICNUMBER2 IS NULL 
								AND REG.EPOS_EFFECTIVESTARTDATE < PER.ENDDATE and  REG.EPOS_EFFECTIVEENDDATE >= PER.ENDDATE
								AND REG.EPAR_EFFECTIVESTARTDATE <  PER.ENDDATE  and  REG.EPAR_EFFECTIVEENDDATE >=  PER.ENDDATE  
								AND REG.ETIT_EFFECTIVESTARTDATE <  PER.ENDDATE  and  REG.ETIT_EFFECTIVEENDDATE >=  PER.ENDDATE 		

WHERE   BUSINESSUNITMAP = 1 
) WITH READ ONLY
