INSERT INTO "EXT"."ESTRUCTURA_COMERCIAL" 
	WITH "ESTRUCTURA" AS (SELECT X.NAME as EPOS_NAME,X.RULEELEMENTOWNERSEQ as EPOSITIONSEQ,
			X.GENERICATTRIBUTE2 EPOS_GENERICATTRIBUTE2, X.GENERICATTRIBUTE3 AS EPOS_GENERICATTRIBUTE3,
			TO_INTEGER(X.GENERICNUMBER2) AS EPOS_GENERICNUMBER2, X.GENERICNUMBER3 AS EPOS_GENERICNUMBER3,
			IFNULL(RTRIM(Y.FIRSTNAME) || ' ','')  || IFNULL(RTRIM(Y.LASTNAME),'') || IFNULL(' ' || RTRIM(Y.SUFFIX), '') AS NOMBRE_COMPLETO, 
			Y.FIRSTNAME,Y.LASTNAME,Y.SUFFIX,Y.GENERICATTRIBUTE1 AS NIF, X.MANAGERSEQ as EPOS_MANAGERSEQ,
			Y.USERID as EPAR_USERID,
			Z.NAME AS ETITLE,
			X.EFFECTIVESTARTDATE as EPOS_EFFECTIVESTARTDATE, X.EFFECTIVEENDDATE as EPOS_EFFECTIVEENDDATE,
			Y.EFFECTIVESTARTDATE as EPAR_EFFECTIVESTARTDATE, Y.EFFECTIVEENDDATE as EPAR_EFFECTIVEENDDATE,
			Z.EFFECTIVESTARTDATE as ETIT_EFFECTIVESTARTDATE, Z.EFFECTIVEENDDATE as ETIT_EFFECTIVEENDDATE
		FROM 
		TCMP.CS_POSITION X 
			INNER JOIN TCMP.CS_PARTICIPANT Y ON Y.PAYEESEQ = X.PAYEESEQ and Y.REMOVEDATE = TO_DATE('22000101','yyyymmdd')  
						AND X.EFFECTIVESTARTDATE <= Y.EFFECTIVEENDDATE and X.EFFECTIVEENDDATE >= Y.EFFECTIVESTARTDATE
			INNER JOIN TCMP.CS_PAYEE R ON Y.PAYEESEQ = R.PAYEESEQ and R.REMOVEDATE = TO_DATE('22000101','yyyymmdd')
						AND Y.EFFECTIVESTARTDATE = R.EFFECTIVESTARTDATE and Y.EFFECTIVEENDDATE = R.EFFECTIVEENDDATE
			INNER JOIN TCMP.CS_TITLE Z ON X.TITLESEQ = Z.RULEELEMENTOWNERSEQ AND Z.REMOVEDATE = TO_DATE('22000101','yyyymmdd') 
						AND X.EFFECTIVESTARTDATE <= Z.EFFECTIVEENDDATE and X.EFFECTIVEENDDATE >= Z.EFFECTIVESTARTDATE
			where X.REMOVEDATE = TO_DATE('22000101','yyyymmdd')) 
	Select  DISTINCT
		IFNULL(PAR.PARTICIPANTEMAIL,' '), -- Correo electrónico
		IFNULL(PAR.TAXID, ' '), -- Tipo de IRPF
		IFNULL(POS.EFFECTIVESTARTDATE, ' ') as POS_EFFECTIVESTARTDATE, -- Fecha Inicio Efectividad
		IFNULL(POS.EFFECTIVEENDDATE, ' ') as POS_EFFECTIVEENDDATE, -- Fecha Fin Efectividad
		IFNULL(PER.NAME, ' ') AS PERIODNAME, 
		IFNULL(PER.SHORTNAME, ' ') as PERIODSHORTNAME, 
		IFNULL(PER.DESCRIPTION, ' ') AS PERIODDESCRIPTION, 
		IFNULL(PER.STARTDATE, ' '), 
		IFNULL(PER.ENDDATE, ' '), 
		IFNULL(RTRIM(PAD.FIRSTNAME) || ' ','')  || IFNULL(RTRIM(PAD.LASTNAME),'') || IFNULL(' ' || RTRIM(PAD.SUFFIX), '') AS NOMBRE_COMPLETO, 
		PAD.PERIODSEQ, 
		POS.RULEELEMENTOWNERSEQ as POSITIONSEQ, 
		PARTICIPANTSEQ, 
		IFNULL(PARTICIPANTID, ' '), -- ID de participante
		IFNULL(PAD.USERID, ' '), -- Usuario LDAP
		IFNULL(PAD.PREFIX, ' '), 
		IFNULL(PAD.FIRSTNAME, ' '), -- Nombre
		IFNULL(PAD.MIDDLENAME, ' '), -- Email personal
		IFNULL(PAD.LASTNAME, ' '), -- Apellido 1/Razón social
		IFNULL(PAD.SUFFIX, ' '), -- Apellido 2
		IFNULL(PAD.FULLNAME, ' '), 
		IFNULL(PAD.SALARY, 0), -- Pago por IBAN
		IFNULL(PAD.HIREDATE, ' '), -- Fecha de Contrato
		IFNULL(PAD.TERMINATIONDATE, ' '), -- Fecha Fin Agente
		PAD.BUSINESSUNITMAP, 
		IFNULL(PAD.BUSINESSUNITNAME, ' '), 
		IFNULL(POS.NAME, ' ') as POSITIONNAME, -- Posición
		IFNULL(POSITIONDESCRIPTION, ' '), -- Descripción Posición
		IFNULL(POSITIONGROUPNAME, ' '), -- Grupo de Posición
		IFNULL(TITLENAME, ' '), -- Título
		IFNULL(TITLEDESCRIPTION, ' '), -- Descripción Título
		IFNULL(POS.TARGETCOMPENSATION, 0), -- Objetivo Comisiones
		IFNULL(PLANNAME, ' '), -- PLAN
		PLANSEQ, 
		IFNULL(POS.GENERICATTRIBUTE1,' ') as POSITIONGENERICATTRIBUTE1, -- Tipo Principal Agente / Clase Oficina (GA1)
		IFNULL(TO_VARCHAR(TO_INTEGER(POS.GENERICNUMBER2))  || ' - ','') || IFNULL(POS.GENERICATTRIBUTE2 ,'') as POSITIONGENERICATTRIBUTE2 , -- Tipo Agente / Tipo Oficina (GA2)
		IFNULL(POS.GENERICATTRIBUTE3, ' ') as POSITIONGENERICATTRIBUTE3, -- Código de Agente OCASO (GA3)
		IFNULL(POS.GENERICATTRIBUTE4, ' ') as POSITIONGENERICATTRIBUTE4, -- Rehabilitación (GA4)
		IFNULL(POS.GENERICATTRIBUTE5, ' ') as POSITIONGENERICATTRIBUTE5, -- Cuadro Inspector Ocaso (GA5)
		IFNULL(POS.GENERICATTRIBUTE6, ' ') as POSITIONGENERICATTRIBUTE6, -- Cuadro RRGG Ocaso (GA6)
		IFNULL(POS.GENERICATTRIBUTE7, ' ') as POSITIONGENERICATTRIBUTE7, -- Cuadro RRTT Ocaso (GA7)
		IFNULL(POS.GENERICATTRIBUTE8, ' ') as POSITIONGENERICATTRIBUTE8, -- Compañía (GA8)
		IFNULL(POS.GENERICATTRIBUTE9, ' ') as POSITIONGENERICATTRIBUTE9, -- Promoción Agente (GA9)
		IFNULL(POS.GENERICATTRIBUTE10, ' ') as POSITIONGENERICATTRIBUTE10, -- Cuadro Inspector Eterna (GA10)
		IFNULL(POS.GENERICATTRIBUTE11, ' ') as POSITIONGENERICATTRIBUTE11, -- Cuadro RRGG Eterna (GA11)
		IFNULL(POS.GENERICATTRIBUTE12, ' ') as POSITIONGENERICATTRIBUTE12, -- Cuadro RRTT Eterna (GA12)
		IFNULL(POS.GENERICATTRIBUTE13, ' ') as POSITIONGENERICATTRIBUTE13, -- Año Captación (GA13)
		IFNULL(POS.GENERICATTRIBUTE14, ' ') as POSITIONGENERICATTRIBUTE14, -- Inspector Captador (GA14)
		IFNULL(POS.GENERICATTRIBUTE15, ' ') as POSITIONGENERICATTRIBUTE15, -- Número Meses Preplan (GA15)
		IFNULL(POS.GENERICATTRIBUTE16, ' ') as POSITIONGENERICATTRIBUTE16, -- Escalado Asistencia (GA16)
		IFNULL(POS.GENERICNUMBER1, 0) as POSITIONGENERICNUMBER1, -- ID Tipo Principal Agente (GN1)
		IFNULL(POS.GENERICNUMBER2, 0) as POSITIONGENERICNUMBER2, -- ID Tipo Agente (GN2)
		IFNULL(POS.GENERICNUMBER3, 0) as POSITIONGENERICNUMBER3, -- ID Clase Oficina (GN3)
		IFNULL(POS.GENERICNUMBER4, 0) as POSITIONGENERICNUMBER4, -- ID Tipo Oficina (GN4)
		IFNULL(POS.GENERICNUMBER5, 0) as POSITIONGENERICNUMBER5, -- % Comisión Cartera (GN5)
		IFNULL(POS.GENERICNUMBER6, 0) as POSITIONGENERICNUMBER6, -- Importe Comisión Cartera (GN6)
		IFNULL(POS.GENERICDATE1, ' ') as POSITIONGENERICDATE1, -- Fecha de Alta (GD1)
		IFNULL(POS.GENERICDATE2, ' ') as POSITIONGENERICDATE2, -- Fecha de Baja (GD2)
		IFNULL(POS.GENERICDATE3, ' ') as POSITIONGENERICDATE3, -- Fecha Inicio Consolidación P.C. (GD3)
		IFNULL(POS.GENERICDATE4, ' ') as POSITIONGENERICDATE4, -- Fecha Fin Consolidación P.C. (GD4)
		IFNULL(POS.GENERICDATE5, ' ') as POSITIONGENERICDATE5, -- Fecha Inicio Asistencia (GD5)
		IFNULL(POS.GENERICDATE6, ' ') as POSITIONGENERICDATE6, -- Fecha Límite Comisiones Cartera (GD6)
		IFNULL(POS.GENERICBOOLEAN1, 0) as POSITIONGENERICBOOLEAN1, -- Reducción (GB1)
		IFNULL(POS.GENERICBOOLEAN2, 0) as POSITIONGENERICBOOLEAN2, -- Productor Ocaso (GB2)
		IFNULL(POS.GENERICBOOLEAN3, 0) as POSITIONGENERICBOOLEAN3, -- Consolida (GB3)
		IFNULL(POS.GENERICBOOLEAN4, 0) as POSITIONGENERICBOOLEAN4, -- Inicio Agente Asistencia (GB4)
		IFNULL(POS.GENERICBOOLEAN5, 0) as POSITIONGENERICBOOLEAN5, -- Productor Eterna (GB5)
		IFNULL(POS.GENERICBOOLEAN6, 0) as POSITIONGENERICBOOLEAN6, -- Ag. Lider (GB6)
		IFNULL(PARTICIPANTGENERICATTRIBUTE1, ' '), -- Documento (GA1)
		IFNULL(PARTICIPANTGENERICATTRIBUTE2, ' '), -- Tipo Documento (GA2)
		IFNULL(PARTICIPANTGENERICATTRIBUTE3, ' '), -- Tipo Persona (GA3)
		IFNULL(PARTICIPANTGENERICATTRIBUTE4, ' '), -- Código DGS (GA4)
		IFNULL(PARTICIPANTGENERICATTRIBUTE5, ' '), -- Compañía (GA5)
		IFNULL(PARTICIPANTGENERICATTRIBUTE6, ' '), -- Tipo Mediador (GA6)
		IFNULL(PARTICIPANTGENERICATTRIBUTE7, ' '), -- Localidad (GA7)
		IFNULL(PARTICIPANTGENERICATTRIBUTE8, ' '), -- Tipo Vía (GA8)
		IFNULL(PARTICIPANTGENERICATTRIBUTE9, ' '), -- Domicilio (GA9)
		IFNULL(PARTICIPANTGENERICATTRIBUTE10, ' '), -- Número (GA10)
		IFNULL(PARTICIPANTGENERICATTRIBUTE11, ' '), -- Resto Domicilio (GA11)
		IFNULL(PARTICIPANTGENERICATTRIBUTE12, ' '), -- Sexo (GA12)
		IFNULL(PARTICIPANTGENERICATTRIBUTE13, ' '), -- Estado Civil (GA13)
		IFNULL(PARTICIPANTGENERICATTRIBUTE14, ' '), -- Teléfono Fijo (GA14)
		IFNULL(PARTICIPANTGENERICATTRIBUTE15, ' '), -- Teléfono Móvil (GA15)
		IFNULL(PARTICIPANTGENERICATTRIBUTE16, ' '), -- IBAN (GA16)
		IFNULL(PARTICIPANTGENERICNUMBER1, 0), -- Código Postal (GN1)
		IFNULL(PARTICIPANTGENERICNUMBER2, 0), -- Provincia (GN2)
		IFNULL(PARTICIPANTGENERICNUMBER3, 0), -- Municipio (GN3)
		IFNULL(PARTICIPANTGENERICNUMBER4, 0), -- ID_Empleado (GN4)
		IFNULL(PARTICIPANTGENERICNUMBER5, 0), -- % IRPF (GN5)
		IFNULL(PARTICIPANTGENERICNUMBER6, 0), -- Fax (GN6)
		IFNULL(PARTICIPANTGENERICDATE1, ' '), -- Fecha Nacimiento (GD1)
		IFNULL(PARTICIPANTGENERICDATE2, ' '), -- Fecha Registro DGS (GD2)
		IFNULL(PARTICIPANTGENERICDATE3, ' '), -- Fecha Envío DGS (GD3)
		IFNULL(PARTICIPANTGENERICDATE4, ' '), -- Fin CIASE 1 (GD4)
		IFNULL(PARTICIPANTGENERICDATE5, ' '), -- Fecha Efecto SuperRappel (GD5)
		IFNULL(PARTICIPANTGENERICDATE6, ' '), -- Fecha Regularización SuperRappel (GD6)
		IFNULL(PARTICIPANTGENERICBOOLEAN1, 0), -- Autoliquida (GB1)
		IFNULL(PARTICIPANTGENERICBOOLEAN2, 0), -- Corredor (GB2)
		IFNULL(PARTICIPANTGENERICBOOLEAN3, 0), -- Autorización Factura (GB3)
		IFNULL(PARTICIPANTGENERICBOOLEAN4, 0), -- SuperRappel (GB4)
		IFNULL(PARTICIPANTGENERICBOOLEAN5, 0), -- Comisiones Anualizadas RRPP OCASO (GB5)
		IFNULL(PARTICIPANTGENERICBOOLEAN6, 0), -- Cartera RRTT (GB6)
		IFNULL(TITLEGENERICATTRIBUTE1, ' '), -- Tipo Principal Agente / Clase Oficina (GA1)
		IFNULL(TITLEGENERICATTRIBUTE2, ' '), -- Tipo Agente / Tipo Oficina (GA2)
		IFNULL(TITLEGENERICATTRIBUTE3, ' '), 
		IFNULL(TITLEGENERICATTRIBUTE4, ' '), 
		IFNULL(TITLEGENERICNUMBER1, 0), -- ID Tipo Principal  Agente (GN1)
		IFNULL(TITLEGENERICNUMBER2, 0), -- ID Tipo  Agente (GN2)
		IFNULL(TITLEGENERICNUMBER3, 0), -- ID Clase Oficina (GN3)
		IFNULL(TITLEGENERICNUMBER4, 0), -- ID Tipo Oficina (GN4)
		IFNULL(TITLEGENERICDATE1, ' '), 
		IFNULL(TITLEGENERICDATE2, ' '), 
		IFNULL(TITLEGENERICBOOLEAN1, 0), -- Genera Informe (GB1)
		IFNULL(TITLEGENERICBOOLEAN2, 0), 
		POS.MANAGERSEQ, -- MANAGERSEQ
		IFNULL(MANAGERFULLNAME, ' '), 
		IFNULL(ISPAYEE, 0), 
		IFNULL(BOUSERID, ' '), 
		MANAGERPARTICIPANTSEQ, 
		PA_SK,
		IFNULL( CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (5) THEN REG.EPOS_NAME
				ELSE CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (4,7) THEN SUC.EPOS_NAME
					ELSE CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (3,6,8,10,11) THEN OFI.EPOS_NAME
						ELSE PTO_VENTA.EPOS_NAME END
			END END , ' ') as IDREGIONAL,
		IFNULL( CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (5) THEN REG.EPOS_NAME
				ELSE CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (4,7) THEN SUC.EPOS_NAME
					ELSE CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (3,6,8,10,11) THEN OFI.EPOS_NAME
						ELSE PTO_VENTA.EPOS_NAME END
			END END || ' - ' ||
			CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (5) THEN REG.LASTNAME
				ELSE CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (4,7) THEN SUC.LASTNAME
					ELSE CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (3,6,8,10,11) THEN OFI.LASTNAME
						ELSE PTO_VENTA.LASTNAME END
			END END  , ' ') AS REGIONAL, 
		IFNULL( CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (5) THEN SUC.EPOS_NAME
				ELSE CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (4,7) THEN OFI.EPOS_NAME
					ELSE PTO_VENTA.EPOS_NAME END 
			END , ' ' )as IDSUCURSAL,
		IFNULL( CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (5) THEN SUC.EPOS_NAME
				ELSE CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (4,7) THEN OFI.EPOS_NAME
					ELSE PTO_VENTA.EPOS_NAME END 
			END || ' - ' ||
			CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (5) THEN SUC.LASTNAME
				ELSE CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (4,7) THEN OFI.LASTNAME
					ELSE PTO_VENTA.LASTNAME END 
			END , ' ' )AS SUCURSAL,                                                                                            --titleGenericAttribute2
		IFNULL( CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (5) THEN OFI.EPOS_NAME  
				ELSE PTO_VENTA.EPOS_NAME END, ' ') as IDOFICINA,
		IFNULL( CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (5) THEN OFI.EPOS_NAME  
				ELSE PTO_VENTA.EPOS_NAME END || ' - ' ||
			CASE WHEN PTO_VENTA.EPOS_GENERICNUMBER3 IN (5) THEN OFI.LASTNAME  
				ELSE PTO_VENTA.LASTNAME END, ' ') AS OFICINA,
		IFNULL( LEFT(PAD.POSITIONGENERICATTRIBUTE3, 4), ' ') as PV, IFNULL( RIGHT(PAD.POSITIONGENERICATTRIBUTE3, 4), ' ' ) as CODIGO,
		IFNULL(MANAGER.EPOS_GENERICATTRIBUTE3, ' ') as INSPECTOR_NAME, 
		IFNULL(MANAGER.NIF, ' ') as INSPECTOR_NIF, 
		IFNULL(MANAGER.NOMBRE_COMPLETO, ' ') as INSPECTOR_NOMBRE_COMPLETO, 
		IFNULL(MANAGER.ETITLE, ' ') as INSPECTOR_TITLE, 
		IFNULL(MANAGER.EPAR_USERID, ' ') as INSPECTOR_LDAP,
		IFNULL(MANAGER.EPOS_GENERICNUMBER2, 0) AS INSPECTOR_IDTIPOAGENTE,
		IFNULL(MANAGER.EPOS_GENERICATTRIBUTE2, ' ') AS INSPECTOR_TIPOAGENTE,
		IFNULL(INSP_CAP.EPOS_GENERICATTRIBUTE3, ' ') as INSPCAP_NAME, 
		IFNULL(INSP_CAP.NIF, ' ') as INSPCAP_NIF, 
		IFNULL(INSP_CAP.NOMBRE_COMPLETO, ' ') as INSPCAP_NOMBRE_COMPLETO, 
		IFNULL(INSP_CAP.ETITLE, ' ') as INSPCAP_TITLE, 
		IFNULL(INSP_CAP.EPAR_USERID, ' ') as INSPCAP_LDAP,
		IFNULL(INSP_CAP.EPOS_GENERICNUMBER2, 0) AS INSPCAP_IDTIPOAGENTE,
		IFNULL(INSP_CAP.EPOS_GENERICATTRIBUTE2, ' ') AS INSPCAP_TIPOAGENTE,
		1 as MEDCOUNT
	from TCMP.CSA_PADIMENSION PAD 
	INNER JOIN TCMP.CSA_PERIODDIMENSION PER 
		ON PAD.PERIODSEQ = PER.PERIODSEQ
	-- PARTICIPANT - DATOS PARTICIPANT QUE NO ESTAN EN PADIMENSION
	INNER JOIN TCMP.CS_PARTICIPANT PAR -- Se hace un JOIN con CS_PARTICIPANT a ultimo dia del mes de cada periodo para extraer: PAR.PARTICIPANTEMAIL, PAR.TAXID y fechas de efectividad por si quisieran filtrar por fecha concreta
		ON PAD.PARTICIPANTSEQ = PAR.PAYEESEQ and PAR.REMOVEDATE = TO_DATE('22000101','yyyymmdd')
		AND PAR.EFFECTIVESTARTDATE< PER.ENDDATE and  PAR.EFFECTIVEENDDATE >= PER.ENDDATE
	-- POSITION - VARIACIONES DE POSITION
	INNER JOIN TCMP.CS_POSITION POS ON PAD.POSITIONSEQ = POS.RULEELEMENTOWNERSEQ 
		and POS.REMOVEDATE = TO_DATE('22000101','yyyymmdd')
		and (pos.EFFECTIVESTARTDATE < PER.ENDDATE)  --pos.EFFECTIVESTARTDATE >= PER.STARTDATE and
		and (pos.EFFECTIVEENDDATE > PER.STARTDATE) -- and pos.EFFECTIVEENDDATE <= PER.ENDDATE
	-- MANAGER
	LEFT JOIN ESTRUCTURA MANAGER ON MANAGER.EPOSITIONSEQ = POS.MANAGERSEQ --PAD.MANAGERSEQ 
		AND MANAGER.EPOS_GENERICNUMBER2 is not null 
		AND MANAGER.EPOS_GENERICATTRIBUTE3 NOT IN ('0000000000','0') 
		AND MANAGER.EPOS_MANAGERSEQ IS NOT NULL
		AND MANAGER.EPOS_EFFECTIVESTARTDATE < PER.ENDDATE and  MANAGER.EPOS_EFFECTIVEENDDATE >= PER.ENDDATE
		AND MANAGER.EPAR_EFFECTIVESTARTDATE <  PER.ENDDATE  and  MANAGER.EPAR_EFFECTIVEENDDATE >=  PER.ENDDATE  
		AND MANAGER.ETIT_EFFECTIVESTARTDATE <  PER.ENDDATE  and  MANAGER.ETIT_EFFECTIVEENDDATE >=  PER.ENDDATE 
	-- INSP_CAP						
	LEFT JOIN ESTRUCTURA INSP_CAP ON INSP_CAP.EPOS_NAME = POS.GENERICATTRIBUTE14  --PAD.POSITIONGENERICATTRIBUTE14
		AND INSP_CAP.EPOS_GENERICATTRIBUTE3 NOT IN ('0000000000','0') 
		AND INSP_CAP.EPOS_EFFECTIVESTARTDATE < PER.ENDDATE and  INSP_CAP.EPOS_EFFECTIVEENDDATE >= PER.ENDDATE
		AND INSP_CAP.EPAR_EFFECTIVESTARTDATE <  PER.ENDDATE  and  INSP_CAP.EPAR_EFFECTIVEENDDATE >=  PER.ENDDATE  
		AND INSP_CAP.ETIT_EFFECTIVESTARTDATE <  PER.ENDDATE  and  INSP_CAP.ETIT_EFFECTIVEENDDATE >=  PER.ENDDATE 
	-- PTO_VENTA
	LEFT JOIN ESTRUCTURA PTO_VENTA ON SUBSTR(POS.GENERICATTRIBUTE3,1,4) = PTO_VENTA.EPOS_NAME --SUBSTR(PAD.POSITIONGENERICATTRIBUTE3,1,4) = PTO_VENTA.EPOS_NAME
		AND PTO_VENTA.EPOS_GENERICNUMBER2 IS NULL 
		AND PTO_VENTA.EPOS_EFFECTIVESTARTDATE < PER.ENDDATE and  PTO_VENTA.EPOS_EFFECTIVEENDDATE >= PER.ENDDATE
		AND PTO_VENTA.EPAR_EFFECTIVESTARTDATE <  PER.ENDDATE  and  PTO_VENTA.EPAR_EFFECTIVEENDDATE >=  PER.ENDDATE  
		AND PTO_VENTA.ETIT_EFFECTIVESTARTDATE <  PER.ENDDATE  and  PTO_VENTA.ETIT_EFFECTIVEENDDATE >=  PER.ENDDATE
	-- OFI
	LEFT JOIN ESTRUCTURA OFI ON PTO_VENTA.EPOS_MANAGERSEQ = OFI.EPOSITIONSEQ
		AND OFI.EPOS_GENERICNUMBER2 IS NULL 
		AND OFI.EPOS_EFFECTIVESTARTDATE < PER.ENDDATE and  OFI.EPOS_EFFECTIVEENDDATE >= PER.ENDDATE
		AND OFI.EPAR_EFFECTIVESTARTDATE <  PER.ENDDATE  and  OFI.EPAR_EFFECTIVEENDDATE >=  PER.ENDDATE  
		AND OFI.ETIT_EFFECTIVESTARTDATE <  PER.ENDDATE  and  OFI.ETIT_EFFECTIVEENDDATE >=  PER.ENDDATE
	-- SUC
	LEFT JOIN ESTRUCTURA SUC ON OFI.EPOS_MANAGERSEQ = SUC.EPOSITIONSEQ
		AND SUC.EPOS_GENERICNUMBER2 IS NULL 
		AND SUC.EPOS_EFFECTIVESTARTDATE < PER.ENDDATE and  SUC.EPOS_EFFECTIVEENDDATE >= PER.ENDDATE
		AND SUC.EPAR_EFFECTIVESTARTDATE <  PER.ENDDATE  and  SUC.EPAR_EFFECTIVEENDDATE >=  PER.ENDDATE  
		AND SUC.ETIT_EFFECTIVESTARTDATE <  PER.ENDDATE  and  SUC.ETIT_EFFECTIVEENDDATE >=  PER.ENDDATE 		
	-- REG
	LEFT JOIN ESTRUCTURA REG ON SUC.EPOS_MANAGERSEQ = REG.EPOSITIONSEQ
		AND REG.EPOS_GENERICNUMBER2 IS NULL 
		AND REG.EPOS_EFFECTIVESTARTDATE < PER.ENDDATE and  REG.EPOS_EFFECTIVEENDDATE >= PER.ENDDATE
		AND REG.EPAR_EFFECTIVESTARTDATE <  PER.ENDDATE  and  REG.EPAR_EFFECTIVEENDDATE >=  PER.ENDDATE  
		AND REG.ETIT_EFFECTIVESTARTDATE <  PER.ENDDATE  and  REG.ETIT_EFFECTIVEENDDATE >=  PER.ENDDATE 		
	WHERE --PAD.USERID = PAR.USERID 
	PAD.ISPAYEE=1 and BUSINESSUNITMAP = 1;
	from TCMP.CSA_PADIMENSION PAD 
	INNER JOIN TCMP.CSA_PERIODDIMENSION PER 
		ON PAD.PERIODSEQ = PER.PERIODSEQ

	-- PARTICIPANT - DATOS PARTICIPANT QUE NO ESTAN EN PADIMENSION
	INNER JOIN TCMP.CS_PARTICIPANT PAR -- Se hace un JOIN con CS_PARTICIPANT a ultimo dia del mes de cada periodo para extraer: PAR.PARTICIPANTEMAIL, PAR.TAXID y fechas de efectividad por si quisieran filtrar por fecha concreta
		ON PAD.PARTICIPANTSEQ = PAR.PAYEESEQ and PAR.REMOVEDATE = TO_DATE('22000101','yyyymmdd')
		AND PAR.EFFECTIVESTARTDATE< PER.ENDDATE and  PAR.EFFECTIVEENDDATE >= PER.ENDDATE
		
	-- POSITION - VARIACIONES DE POSITION
	INNER JOIN TCMP.CS_POSITION POS ON PAD.POSITIONSEQ = POS.RULEELEMENTOWNERSEQ 
		and POS.REMOVEDATE = TO_DATE('22000101','yyyymmdd')
		and (pos.EFFECTIVESTARTDATE < PER.ENDDATE)  --pos.EFFECTIVESTARTDATE >= PER.STARTDATE and
		and (pos.EFFECTIVEENDDATE > PER.STARTDATE) -- and pos.EFFECTIVEENDDATE <= PER.ENDDATE

	-- MANAGER
	LEFT JOIN ESTRUCTURA MANAGER ON MANAGER.EPOSITIONSEQ = POS.MANAGERSEQ --PAD.MANAGERSEQ 
		AND MANAGER.EPOS_GENERICNUMBER2 is not null 
		AND MANAGER.EPOS_GENERICATTRIBUTE3 NOT IN ('0000000000','0') 
		AND MANAGER.EPOS_MANAGERSEQ IS NOT NULL
		AND MANAGER.EPOS_EFFECTIVESTARTDATE < PER.ENDDATE and  MANAGER.EPOS_EFFECTIVEENDDATE >= PER.ENDDATE
		AND MANAGER.EPAR_EFFECTIVESTARTDATE <  PER.ENDDATE  and  MANAGER.EPAR_EFFECTIVEENDDATE >=  PER.ENDDATE  
		AND MANAGER.ETIT_EFFECTIVESTARTDATE <  PER.ENDDATE  and  MANAGER.ETIT_EFFECTIVEENDDATE >=  PER.ENDDATE 
	-- INSP_CAP						
	LEFT JOIN ESTRUCTURA INSP_CAP ON INSP_CAP.EPOS_NAME = POS.GENERICATTRIBUTE14  --PAD.POSITIONGENERICATTRIBUTE14
		AND INSP_CAP.EPOS_GENERICATTRIBUTE3 NOT IN ('0000000000','0') 
		AND INSP_CAP.EPOS_EFFECTIVESTARTDATE < PER.ENDDATE and  INSP_CAP.EPOS_EFFECTIVEENDDATE >= PER.ENDDATE
		AND INSP_CAP.EPAR_EFFECTIVESTARTDATE <  PER.ENDDATE  and  INSP_CAP.EPAR_EFFECTIVEENDDATE >=  PER.ENDDATE  
		AND INSP_CAP.ETIT_EFFECTIVESTARTDATE <  PER.ENDDATE  and  INSP_CAP.ETIT_EFFECTIVEENDDATE >=  PER.ENDDATE 
	-- PTO_VENTA
	LEFT JOIN ESTRUCTURA PTO_VENTA ON SUBSTR(POS.GENERICATTRIBUTE3,1,4) = PTO_VENTA.EPOS_NAME --SUBSTR(PAD.POSITIONGENERICATTRIBUTE3,1,4) = PTO_VENTA.EPOS_NAME
		AND PTO_VENTA.EPOS_GENERICNUMBER2 IS NULL 
		AND PTO_VENTA.EPOS_EFFECTIVESTARTDATE < PER.ENDDATE and  PTO_VENTA.EPOS_EFFECTIVEENDDATE >= PER.ENDDATE
		AND PTO_VENTA.EPAR_EFFECTIVESTARTDATE <  PER.ENDDATE  and  PTO_VENTA.EPAR_EFFECTIVEENDDATE >=  PER.ENDDATE  
		AND PTO_VENTA.ETIT_EFFECTIVESTARTDATE <  PER.ENDDATE  and  PTO_VENTA.ETIT_EFFECTIVEENDDATE >=  PER.ENDDATE
	-- OFI
	LEFT JOIN ESTRUCTURA OFI ON PTO_VENTA.EPOS_MANAGERSEQ = OFI.EPOSITIONSEQ
		AND OFI.EPOS_GENERICNUMBER2 IS NULL 
		AND OFI.EPOS_EFFECTIVESTARTDATE < PER.ENDDATE and  OFI.EPOS_EFFECTIVEENDDATE >= PER.ENDDATE
		AND OFI.EPAR_EFFECTIVESTARTDATE <  PER.ENDDATE  and  OFI.EPAR_EFFECTIVEENDDATE >=  PER.ENDDATE  
		AND OFI.ETIT_EFFECTIVESTARTDATE <  PER.ENDDATE  and  OFI.ETIT_EFFECTIVEENDDATE >=  PER.ENDDATE
	-- SUC
	LEFT JOIN ESTRUCTURA SUC ON OFI.EPOS_MANAGERSEQ = SUC.EPOSITIONSEQ
		AND SUC.EPOS_GENERICNUMBER2 IS NULL 
		AND SUC.EPOS_EFFECTIVESTARTDATE < PER.ENDDATE and  SUC.EPOS_EFFECTIVEENDDATE >= PER.ENDDATE
		AND SUC.EPAR_EFFECTIVESTARTDATE <  PER.ENDDATE  and  SUC.EPAR_EFFECTIVEENDDATE >=  PER.ENDDATE  
		AND SUC.ETIT_EFFECTIVESTARTDATE <  PER.ENDDATE  and  SUC.ETIT_EFFECTIVEENDDATE >=  PER.ENDDATE 		
	-- REG
	LEFT JOIN ESTRUCTURA REG ON SUC.EPOS_MANAGERSEQ = REG.EPOSITIONSEQ
		AND REG.EPOS_GENERICNUMBER2 IS NULL 
		AND REG.EPOS_EFFECTIVESTARTDATE < PER.ENDDATE and  REG.EPOS_EFFECTIVEENDDATE >= PER.ENDDATE
		AND REG.EPAR_EFFECTIVESTARTDATE <  PER.ENDDATE  and  REG.EPAR_EFFECTIVEENDDATE >=  PER.ENDDATE  
		AND REG.ETIT_EFFECTIVESTARTDATE <  PER.ENDDATE  and  REG.ETIT_EFFECTIVEENDDATE >=  PER.ENDDATE 		
	WHERE --PAD.USERID = PAR.USERID 
	PAD.ISPAYEE=1 and BUSINESSUNITMAP = 1

