CREATE COLUMN TABLE "EXT"."ASEGURADOS_HIST_BKP"(
	"ID_PROCESO" BIGINT CS_FIXED NOT NULL,
	"IDENTIFICADOR" BIGINT CS_FIXED,
	"FILE_NAME" VARCHAR(100),
	"ESTADO" VARCHAR(255),
	"FECHA_MODIFICACION" LONGDATE CS_LONGDATE,
	"CODIGO_POLIZA" VARCHAR(255) NOT NULL,
	"NUMERO_ASEGURADO" VARCHAR(255) NOT NULL,
	"NIF" VARCHAR(255),
	"FECHA_NACIMIENTO" LONGDATE CS_LONGDATE,
	"FECHA_DE_DERECHOS" LONGDATE CS_LONGDATE,
	"MOTIVO_ALTA" VARCHAR(255),
	"CONTO_COMO_ALTA" VARCHAR(1),
	"CONTO_COMO_NUEVO" VARCHAR(1),
	"FECHA_ALTA" LONGDATE CS_LONGDATE,
	"MOTIVO_BAJA" VARCHAR(255),
	"FECHA_BAJA" LONGDATE CS_LONGDATE,
	"FECHA_REHABILITACION" LONGDATE CS_LONGDATE,
	"POLIZA_ORIGEN" VARCHAR(255),
	"ASEGURADO_ORIGEN" VARCHAR(255),
	"EDAD" BIGINT CS_FIXED,
	"EDAD_DERECHOS" BIGINT CS_FIXED
)
UNLOAD PRIORITY 5 AUTO MERGE;
