CREATE COLUMN TABLE "EXT"."C_CORRECCION_DEBUG"(
	"NIF" NVARCHAR(10),
	"CIA" NVARCHAR(2),
	"TIPO_DOC" NVARCHAR(1),
	"OFI" NVARCHAR(4),
	"AGE" NVARCHAR(6),
	"PERIODSEQ" BIGINT CS_FIXED NOT NULL,
	"REF" NVARCHAR(16),
	"AJUSTE" DECIMAL CS_DECIMAL_FLOAT
)
UNLOAD PRIORITY 5 AUTO MERGE;
