CREATE COLUMN TABLE "EXT"."C_TRAMOS1_DEBUG"(
	"PRODUCTO_DESDE" BIGINT CS_FIXED,
	"PRODUCTO_HASTA" BIGINT CS_FIXED,
	"COEF_TIPO_BASE_TRAMO1" VARCHAR(3),
	"COEF_CORRECTOR_TRAMO1" DECIMAL(15, 2) CS_FIXED
)
UNLOAD PRIORITY 5 AUTO MERGE;
