CREATE COLUMN TABLE "EXT"."CONF_AGENTES_REP"(
	"DESCRIPCION" VARCHAR(255),
	"F_FIN" LONGDATE CS_LONGDATE,
	"F_INICIO" LONGDATE CS_LONGDATE,
	"TABLA" VARCHAR(127) NOT NULL,
	"ID_TIPO_AGENTE" DECIMAL(25, 10) CS_FIXED NOT NULL,
	"COMPANIA" VARCHAR(2) NOT NULL,
	"BO_GROUP" VARCHAR(255),
	"COD_INFORME" DECIMAL(25, 10) CS_FIXED NOT NULL,
	CONSTRAINT "SYS_C0032187" CHECK ("COD_INFORME" IS NOT NULL),
	CONSTRAINT "SYS_C0032188" CHECK ("COMPANIA" IS NOT NULL),
	CONSTRAINT "SYS_C0032189" CHECK ("ID_TIPO_AGENTE" IS NOT NULL),
	CONSTRAINT "SYS_C0032190" CHECK ("TABLA" IS NOT NULL)
)
UNLOAD PRIORITY 5 AUTO MERGE;
CREATE CPBTREE INDEX "CONF_AGENTES_REP_IDX1" ON "EXT"."CONF_AGENTES_REP" ( "COD_INFORME" ASC );
CREATE CPBTREE INDEX "CONF_AGENTES_REP_IDX2" ON "EXT"."CONF_AGENTES_REP" ( "TABLA" ASC );
CREATE CPBTREE INDEX "CONF_AGENTES_REP_IDX3" ON "EXT"."CONF_AGENTES_REP" ( "ID_TIPO_AGENTE" ASC );
