CREATE COLUMN TABLE "EXT"."CONF_REPEXT_CONTROL_FILE_BKP"(
	"FECHA_BAJA" LONGDATE CS_LONGDATE,
	"FECHA_ALTA" LONGDATE CS_LONGDATE,
	"ESTADO" BIGINT CS_FIXED,
	"POST_LC_SEQ" BIGINT CS_FIXED,
	"POST_CIERRE_SEQ" BIGINT CS_FIXED,
	"FECHA_CARGO" VARCHAR(8),
	"PERIODSEQ" BIGINT CS_FIXED
)
UNLOAD PRIORITY 5 AUTO MERGE;
