CREATE COLUMN TABLE "EXT"."CONF_REGLAS_REP"(
	"DESCRIPCION" VARCHAR(255),
	"F_FIN" LONGDATE CS_LONGDATE,
	"F_INICIO" LONGDATE CS_LONGDATE,
	"REGLA" VARCHAR(255) NOT NULL,
	"NOMBRE" VARCHAR(255),
	"TABLA" VARCHAR(127) NOT NULL,
	"COD_INFORME" DECIMAL(25, 10) CS_FIXED NOT NULL,
	CONSTRAINT "SYS_C0032191" CHECK ("COD_INFORME" IS NOT NULL),
	CONSTRAINT "SYS_C0032192" CHECK ("TABLA" IS NOT NULL),
	CONSTRAINT "SYS_C0032193" CHECK ("REGLA" IS NOT NULL)
)
UNLOAD PRIORITY 5 AUTO MERGE;
CREATE CPBTREE INDEX "CONF_REGLAS_REP_IDX1" ON "EXT"."CONF_REGLAS_REP" ( "COD_INFORME" ASC );
CREATE CPBTREE INDEX "CONF_REGLAS_REP_IDX2" ON "EXT"."CONF_REGLAS_REP" ( "TABLA" ASC );
CREATE CPBTREE INDEX "CONF_REGLAS_REP_IDX3" ON "EXT"."CONF_REGLAS_REP" ( "REGLA" ASC );
