CREATE COLUMN TABLE "EXT"."CONF_INFORMES_REP"(
	"DESCRIPCION" VARCHAR(255),
	"FORMATO" VARCHAR(255),
	"PUBLICACION" VARCHAR(255),
	"CARGA_TABLAS" VARCHAR(255),
	"F_FIN" LONGDATE CS_LONGDATE,
	"F_INICIO" LONGDATE CS_LONGDATE,
	"TABLA" VARCHAR(127) NOT NULL,
	"DESC_INFORME" VARCHAR(255),
	"COD_INFORME" DECIMAL(25, 10) CS_FIXED NOT NULL,
	CONSTRAINT "SYS_C0032185" CHECK ("COD_INFORME" IS NOT NULL),
	CONSTRAINT "SYS_C0032186" CHECK ("TABLA" IS NOT NULL)
)
UNLOAD PRIORITY 5 AUTO MERGE;
CREATE CPBTREE INDEX "CONF_INFORMES_REP_IDX1" ON "EXT"."CONF_INFORMES_REP" ( "COD_INFORME" ASC );
CREATE CPBTREE INDEX "CONF_INFORMES_REP_IDX2" ON "EXT"."CONF_INFORMES_REP" ( "TABLA" ASC );
