CREATE COLUMN TABLE "EXT"."CONF_REPEXT_CONCEPTOS_CONTABLES_FILE"(
	"DESC_CONCEPTO_CONT" VARCHAR(255),
	"CONCEPTO_CONTABLE" VARCHAR(10),
	"DESC_CONCEPTO_PAGO" VARCHAR(255),
	"CONCEPTO_PAGO" VARCHAR(10),
	"DESC_TIPO_AGENTE" VARCHAR(255),
	"TIPO_AGENTE" VARCHAR(10)
)
UNLOAD PRIORITY 5 AUTO MERGE;
