CREATE COLUMN TABLE "EXT"."CONF_PARAMETROS_FILE"(
	"DESCRIPCION" VARCHAR(127),
	"F_FIN" LONGDATE CS_LONGDATE,
	"F_INICIO" LONGDATE CS_LONGDATE,
	"VALOR" BIGINT CS_FIXED,
	"NOMBRE" VARCHAR(90)
)
UNLOAD PRIORITY 5 AUTO MERGE;
