CREATE COLUMN TABLE "EXT"."CSE_LOG"(
	"DATETIME" LONGDATE CS_LONGDATE,
	"OBJECT" VARCHAR(400),
	"TEXT" VARCHAR(5000),
	"VALUE" INTEGER CS_INT,
	"ID_PROCESO" BIGINT CS_FIXED,
	"LEVEL" VARCHAR(20)
)
UNLOAD PRIORITY 5 AUTO MERGE;
