CREATE COLUMN TABLE "EXT"."DATABASECHANGELOGLOCK"(
	"ID" INTEGER CS_INT NOT NULL,
	"LOCKED" BOOLEAN CS_INT NOT NULL,
	"LOCKGRANTED" LONGDATE CS_LONGDATE,
	"LOCKEDBY" NVARCHAR(255),
	CONSTRAINT "PK_DATABASECHANGELOGLOCK" PRIMARY KEY(
		"ID"
	)
)
UNLOAD PRIORITY 5 AUTO MERGE;
