CREATE COLUMN TABLE "EXT"."DATABASECHANGELOG"(
	"ID" NVARCHAR(255) NOT NULL,
	"AUTHOR" NVARCHAR(255) NOT NULL,
	"FILENAME" NVARCHAR(255) NOT NULL,
	"DATEEXECUTED" LONGDATE CS_LONGDATE NOT NULL,
	"ORDEREXECUTED" INTEGER CS_INT NOT NULL,
	"EXECTYPE" NVARCHAR(10) NOT NULL,
	"MD5SUM" NVARCHAR(35),
	"DESCRIPTION" NVARCHAR(255),
	"COMMENTS" NVARCHAR(255),
	"TAG" NVARCHAR(255),
	"LIQUIBASE" NVARCHAR(20),
	"CONTEXTS" NVARCHAR(255),
	"LABELS" NVARCHAR(255),
	"DEPLOYMENT_ID" NVARCHAR(10)
)
UNLOAD PRIORITY 5 AUTO MERGE;
