CREATE COLUMN TABLE "EXT"."DERECHOS_ECONOMICOS_CONTROL_AGENTE"(
	"COD_AGENTE" VARCHAR(50),
	"FECHA_CARGO" VARCHAR(50),
	"STATUS" INTEGER CS_INT,
	"EMAIL" VARCHAR(255),
	"FILE_NAME" VARCHAR(255),
	"FECHA_MODIFICACION" LONGDATE CS_LONGDATE,
	"MASK" VARCHAR(32),
	PRIMARY KEY(
		"COD_AGENTE",
		"FECHA_CARGO",
		"MASK"
	)
)
UNLOAD PRIORITY 5 AUTO MERGE;
