CREATE COLUMN TABLE "EXT"."FINAL_AUTOLIQUIDACION_FILE_BKP"(
	"PAGPREMI" DECIMAL(14, 2) CS_FIXED,
	"PAGSUBVE" DECIMAL(14, 2) CS_FIXED,
	"PAGCOMIS" DECIMAL(14, 2) CS_FIXED,
	"SERCO_CANARIAS" CHAR(1) CS_FIXEDSTRING,
	"ENVIO_SII" CHAR(1) CS_FIXEDSTRING,
	"IRPF" DECIMAL(5, 4) CS_FIXED,
	"IMPPREMI" DECIMAL(14, 2) CS_FIXED,
	"IMPSUBVE" DECIMAL(14, 2) CS_FIXED,
	"IMPCOMIS" DECIMAL(14, 2) CS_FIXED,
	"CAGENTE" CHAR(5) CS_FIXEDSTRING,
	"FCARGO" CHAR(6) CS_FIXEDSTRING,
	"COFICINA" CHAR(4) CS_FIXEDSTRING,
	"CCOMPANI" CHAR(1) CS_FIXEDSTRING
)
UNLOAD PRIORITY 5 AUTO MERGE;
