CREATE COLUMN TABLE "EXT"."FINAL_NOMINA_FILE"(
	"FCH_PAGA" CHAR(6) CS_FIXEDSTRING,
	"FCH_FIN" CHAR(6) CS_FIXEDSTRING,
	"FCH_INI" CHAR(6) CS_FIXEDSTRING,
	"IMPORTE" DECIMAL(9, 2) CS_FIXED,
	"CONCEPTO" CHAR(6) CS_FIXEDSTRING,
	"DNI" CHAR(11) CS_FIXEDSTRING,
	"CIA" CHAR(2) CS_FIXEDSTRING
)
UNLOAD PRIORITY 5 AUTO MERGE;
