CREATE COLUMN TABLE "EXT"."FINAL_LIQEXT_CABECERA_FILE"(
	"COMPANIA" VARCHAR(2) NOT NULL,
	"EARNINGGROUPID" VARCHAR(255),
	"DEPOSITO" VARCHAR(90),
	"DEPOSITSEQ" BIGINT CS_FIXED,
	"PERIODSEQ" BIGINT CS_FIXED,
	"PAG_REFERENCIA_ORIGEN" VARCHAR(16),
	"POLIZAS" DECIMAL(25, 10) CS_FIXED,
	"DOC_NIF" VARCHAR(11),
	"PROGRAMA" VARCHAR(8),
	"IMPORTE" DECIMAL(25, 10) CS_FIXED NOT NULL,
	"PRODUCTO" VARCHAR(5),
	"COD_CONCEPTO" VARCHAR(255) NOT NULL,
	"POSICION_COMERCIAL" VARCHAR(127),
	"FECHA" LONGDATE CS_LONGDATE,
	"TIPODOCUMENTO" VARCHAR(1) NOT NULL,
	CONSTRAINT "SYS_C0032035" CHECK ("COMPANIA" IS NOT NULL),
	CONSTRAINT "SYS_C0032036" CHECK ("TIPODOCUMENTO" IS NOT NULL),
	CONSTRAINT "SYS_C0032037" CHECK ("COD_CONCEPTO" IS NOT NULL),
	CONSTRAINT "SYS_C0032038" CHECK ("IMPORTE" IS NOT NULL)
)
UNLOAD PRIORITY 5 AUTO MERGE;
