CREATE COLUMN TABLE "EXT"."FINAL_REPEXT_INF_SAP_FILE"(
	"LINE" VARCHAR(255),
	"PERIODSEQ" BIGINT CS_FIXED NOT NULL,
	CONSTRAINT "SYS_C00129563" CHECK ("PERIODSEQ" IS NOT NULL)
)
UNLOAD PRIORITY 5 AUTO MERGE;
