CREATE COLUMN TABLE "EXT"."FINAL_PAGEXT_LIQ_CAB_ONLINE_FILE_BKP"(
	"PERIODSEQ" BIGINT CS_FIXED NOT NULL,
	"PAG_REFERENCIA_ORIGEN" VARCHAR(16),
	"POLIZAS" DECIMAL(25, 10) CS_FIXED,
	"DOC_NIF" VARCHAR(11),
	"PROGRAMA" VARCHAR(8),
	"IMPORTE" DECIMAL(25, 10) CS_FIXED NOT NULL,
	"PRODUCTO" VARCHAR(5),
	"COD_CONCEPTO" VARCHAR(255) NOT NULL,
	"POSICION_COMERCIAL" VARCHAR(127),
	"FECHA" LONGDATE CS_LONGDATE,
	"TIPODOCUMENTO" VARCHAR(1) NOT NULL,
	"COMPANIA" VARCHAR(2) NOT NULL,
	"EARNINGGROUPID" VARCHAR(255),
	"DEPOSITO" VARCHAR(90),
	"DEPOSITSEQ" BIGINT CS_FIXED
)
UNLOAD PRIORITY 5 AUTO MERGE;
