CREATE COLUMN TABLE "EXT"."FINAL_EXTRACTPAGOS_AUT_FILE_BKP"(
	"CCOMPANI" CHAR(1) CS_FIXEDSTRING,
	"COFICINA" CHAR(4) CS_FIXEDSTRING,
	"FCARGO" CHAR(6) CS_FIXEDSTRING,
	"CAGENTE" CHAR(5) CS_FIXEDSTRING,
	"IMPCOMIS" DECIMAL(14, 2) CS_FIXED,
	"IMPSUBVE" DECIMAL(14, 2) CS_FIXED,
	"IMPPREMI" DECIMAL(14, 2) CS_FIXED,
	"IRPF" DECIMAL(5, 4) CS_FIXED,
	"ENVIO_SII" CHAR(1) CS_FIXEDSTRING,
	"SERCO_CANARIAS" CHAR(1) CS_FIXEDSTRING,
	"PERIODSEQ" BIGINT CS_FIXED,
	"PAG_REFERENCIA_ORIGEN" CHAR(16) CS_FIXEDSTRING
)
UNLOAD PRIORITY 5 AUTO MERGE;
