CREATE COLUMN TABLE "EXT"."FINAL_REPEXT_INR_SAP_FILE"(
	"LINE" VARCHAR(255),
	"PERIODSEQ" BIGINT CS_FIXED NOT NULL,
	CONSTRAINT "SYS_C001672923" CHECK ("PERIODSEQ" IS NOT NULL)
)
UNLOAD PRIORITY 5 AUTO MERGE;
