CREATE COLUMN TABLE "EXT"."FINAL_REPEXT_PAGOS_FILE_BKP"(
	"TIPO_LIQ" VARCHAR(255),
	"DEPOSITO" VARCHAR(255),
	"TIPO_DOCUMENTO" VARCHAR(1),
	"ESTADO_REPARTO" BIGINT CS_FIXED,
	"IMPORTE" DECIMAL(15, 2) CS_FIXED,
	"TIPO_PAGO" VARCHAR(255),
	"PROGRAMA" VARCHAR(255),
	"MANAGER_POS_PRIN" VARCHAR(255),
	"TIPO_AGENTE" DECIMAL(5, 2) CS_FIXED,
	"NIF" VARCHAR(255),
	"POS_PRIN" VARCHAR(255),
	"POS_CALLIDUS" VARCHAR(255),
	"EARNINGGROUPID" VARCHAR(255),
	"EARNINGCODEID" VARCHAR(255),
	"DEPOSITSEQ" BIGINT CS_FIXED,
	"FECHA_CARGO" VARCHAR(6),
	"PERIODSEQ" BIGINT CS_FIXED NOT NULL,
	"POSITIONSEQ" BIGINT CS_FIXED,
	"PARTICIPANTSEQ" BIGINT CS_FIXED
)
UNLOAD PRIORITY 5 AUTO MERGE;
