CREATE COLUMN TABLE "EXT"."FINAL_COMREC_FILE"(
	"CCOMPANI" VARCHAR(100),
	"C_REGIONA" VARCHAR(100),
	"FCARGO" VARCHAR(100),
	"COFICINA" VARCHAR(100),
	"CCOBRADO" VARCHAR(100),
	"CTIPCOBR" VARCHAR(100),
	"CAGERECU" VARCHAR(100),
	"CRAMO" VARCHAR(100),
	"CFAMILIA" VARCHAR(100),
	"CFAMILIA_1" VARCHAR(100),
	"ICOMRECU" VARCHAR(100)
)
UNLOAD PRIORITY 5 AUTO MERGE;
