CREATE COLUMN TABLE "EXT"."GARANTIAS_ASEGURADO"(
	"IDENTIFICADOR" BIGINT CS_FIXED GENERATED ALWAYS AS IDENTITY,
	"ID_ASEGURADO" BIGINT CS_FIXED,
	"ID_REAJUSTE" BIGINT CS_FIXED,
	"FILE_NAME" VARCHAR(255),
	"ESTADO" VARCHAR(255),
	"FECHA_MODIFICACION" LONGDATE CS_LONGDATE,
	"CODIGO_POLIZA" VARCHAR(255) NOT NULL,
	"NUMERO_ASEGURADO" VARCHAR(255) NOT NULL,
	"PRODUCTO_CONTABLE" VARCHAR(255) NOT NULL,
	"CODIGO_RECIBO" VARCHAR(255) NOT NULL,
	"PRIMA_UNICA" VARCHAR(1),
	"GARANTIA_IP" VARCHAR(1),
	"PRIMA_NETA_ASEGURADO" DECIMAL(15, 2) CS_FIXED,
	"PORCENTAJE_PARTICIPACION" DECIMAL(15, 2) CS_FIXED,
	"PORCENTAJE_NIVELADA" DECIMAL(15, 2) CS_FIXED,
	"CAPITAL_NATURAL" DECIMAL(15, 2) CS_FIXED,
	"CAPITAL_NIVELADO" DECIMAL(15, 2) CS_FIXED,
	"SUBTIPO_MOVIMIENTO" VARCHAR(255),
	"MARCA_CUENTA" VARCHAR(1),
	"PRIMA_COMISIONABLE" DECIMAL(15, 2) CS_FIXED,
	"UNIDAD_DE_POLIZA" DECIMAL(15, 4) CS_FIXED,
	"MESES_COBRADOS" DECIMAL(15, 2) CS_FIXED,
	"FECHA_ALTA_GAR_ASE" LONGDATE CS_LONGDATE,
	"FECHA_BAJA_GAR_ASE" LONGDATE CS_LONGDATE,
	"NUM_ORDEN_MOVIMIENTO" BIGINT CS_FIXED,
	"PC_PERIODO" DECIMAL(15, 2) CS_FIXED,
	"NUM_PERIODOS" DECIMAL(15, 2) CS_FIXED
)
UNLOAD PRIORITY 5 AUTO MERGE;
CREATE UNIQUE CPBTREE INDEX "GARANTIAS_ASEGURADO_U_U_PK" ON "EXT"."GARANTIAS_ASEGURADO" ( "CODIGO_POLIZA" ASC, "NUMERO_ASEGURADO" ASC, "PRODUCTO_CONTABLE" ASC, "CODIGO_RECIBO" ASC );
CREATE CPBTREE INDEX "IX_LP_GARANTIAS_ASEGURADO_U_FN" ON "EXT"."GARANTIAS_ASEGURADO" ( "FILE_NAME" ASC );
