CREATE COLUMN TABLE "EXT"."GEN_AGE_COMIS_ANTICIPA"(
	"OFICINA" VARCHAR(255),
	"AGENTE" VARCHAR(255),
	"PRODUCTO_CONTABLE" VARCHAR(255),
	"DNI_AGENTE" VARCHAR(255),
	"CARGO_INI" LONGDATE CS_LONGDATE,
	"CARGO_FIN" LONGDATE CS_LONGDATE,
	"TIENE_COMIS_ANTICI_SN" VARCHAR(255)
)
UNLOAD PRIORITY 5 AUTO MERGE;
ALTER TABLE "EXT"."GEN_AGE_COMIS_ANTICIPA" WITH PARAMETERS ('CONCAT_ATTRIBUTE'=('$OFICINA$AGENTE$PRODUCTO_CONTABLE$','OFICINA','AGENTE','PRODUCTO_CONTABLE'));
ALTER TABLE "EXT"."GEN_AGE_COMIS_ANTICIPA" WITH PARAMETERS ('CONCAT_ATTRIBUTE'=('$OFICINA$AGENTE$','OFICINA','AGENTE'));
CREATE CPBTREE INDEX "GEN_AGE_COMIS_ANTICIPA_IDX1" ON "EXT"."GEN_AGE_COMIS_ANTICIPA" ( "OFICINA" ASC, "AGENTE" ASC, "PRODUCTO_CONTABLE" ASC );
CREATE CPBTREE INDEX "GEN_AGE_COMIS_ANTICIPA_IDX2" ON "EXT"."GEN_AGE_COMIS_ANTICIPA" ( "OFICINA" ASC, "AGENTE" ASC );
