CREATE COLUMN TABLE "EXT"."GEN_PRODUCTOS"(
	"CODIGO" VARCHAR(255),
	"PRODUCTO" VARCHAR(255),
	"PERIODO_EXTORNABLE" DECIMAL CS_DECIMAL_FLOAT,
	"UNIDAD_DE_POLIZA" DECIMAL CS_DECIMAL_FLOAT,
	"COMISION_ANTICIPADA" DECIMAL CS_DECIMAL_FLOAT,
	"UNIDAD_DE_CUENTA" DECIMAL CS_DECIMAL_FLOAT,
	"COMISION_CARTERA" VARCHAR(2),
	"PAGO_MENSUAL" VARCHAR(2),
	"DIFERENCIAL_ANTICIPADO" VARCHAR(2),
	"COND_ESP_RESCATE" VARCHAR(2)
)
UNLOAD PRIORITY 5 AUTO MERGE;
