CREATE COLUMN TABLE "EXT"."GEN_MOTIVOS_ALTA"(
	"CODIGO" VARCHAR(255),
	"DESCRIPCION" VARCHAR(255),
	"CUENTA_COMO_ALTA" VARCHAR(1)
)
UNLOAD PRIORITY 5 AUTO MERGE;
CREATE UNIQUE CPBTREE INDEX "GEN_MOTIVOS_ALTA_IDX1" ON "EXT"."GEN_MOTIVOS_ALTA" ( "CODIGO" ASC );
