CREATE COLUMN TABLE "EXT"."OUT_S4_FACTURA_REP"(
	"PARTICIPANTSEQ" BIGINT CS_FIXED,
	"POSITIONSEQ_PRIN" BIGINT CS_FIXED,
	"PERIODSEQ" BIGINT CS_FIXED NOT NULL,
	"PERIODO" VARCHAR(50) NOT NULL,
	"BOUSERID" VARCHAR(260),
	"NIF" VARCHAR(255),
	"NOMBRE" VARCHAR(260),
	"MUNICIPIO" VARCHAR(255),
	"DOMICILIO" VARCHAR(255),
	"CP" DECIMAL(25, 10) CS_FIXED,
	"POS_PRIN" VARCHAR(127),
	"CUADRO_RRGG" VARCHAR(255),
	"CUADRO_RRTT" VARCHAR(255),
	"COMPANIA" VARCHAR(2),
	"IRPF" DECIMAL(25, 10) CS_FIXED,
	"COD_OFICINA" VARCHAR(127),
	"OFICINA" VARCHAR(90),
	"COMISION" VARCHAR(255),
	"TIPO_INFORME" VARCHAR(2),
	"IMPORTE" DECIMAL(25, 10) CS_FIXED,
	"SECUENCIAL" BIGINT CS_FIXED,
	"NUMERO" VARCHAR(1023),
	"RESTO_DOMICILIO" VARCHAR(1023),
	CONSTRAINT "SYS_C0031913" CHECK ("PERIODSEQ" IS NOT NULL),
	CONSTRAINT "SYS_C0031914" CHECK ("PERIODO" IS NOT NULL)
)
UNLOAD PRIORITY 5 AUTO MERGE;
ALTER TABLE "EXT"."OUT_S4_FACTURA_REP" WITH PARAMETERS ('CONCAT_ATTRIBUTE'=('$PERIODSEQ$PARTICIPANTSEQ$POSITIONSEQ_PRIN$','PERIODSEQ','PARTICIPANTSEQ','POSITIONSEQ_PRIN'));
CREATE CPBTREE INDEX "OUT_S4_FACTURA_REP_IDX1" ON "EXT"."OUT_S4_FACTURA_REP" ( "PERIODSEQ" ASC, "PARTICIPANTSEQ" ASC, "POSITIONSEQ_PRIN" ASC );
