CREATE COLUMN TABLE "EXT"."OUT_REPARTO_PAGOS_FINAL_REP"(
	"COMPANYA" VARCHAR(2),
	"PERIODO" VARCHAR(50),
	"PERIODO_FORMATO" VARCHAR(104),
	"FEC_CARGO" VARCHAR(6),
	"EARNING_CODE" VARCHAR(255),
	"EARNING_GROUP" VARCHAR(255),
	"PROGRAMA" VARCHAR(255),
	"DEPOSITO" VARCHAR(255),
	"TIPO_PAGO" VARCHAR(255),
	"COD_AGENTE" VARCHAR(255),
	"IMPORTE" DECIMAL(25, 10) CS_FIXED,
	"TIPO_REPARTO" VARCHAR(3),
	"COD_UNICO" VARCHAR(255),
	"NIF_NOMBRE" VARCHAR(255),
	"TIPO_AGENTE" VARCHAR(4),
	"MANAGER" VARCHAR(255),
	"ESTADO_REPARTO" VARCHAR(20),
	"POSITIONSEQ" BIGINT CS_FIXED,
	"PERIODSEQ" BIGINT CS_FIXED
)
UNLOAD PRIORITY 5 AUTO MERGE;
