CREATE COLUMN TABLE "EXT"."OUT_PERC_INSPECTORES_FINAL_REP"(
	"REGIONAL" NVARCHAR(257),
	"SUCURSAL" NVARCHAR(257),
	"OFICINA" NVARCHAR(257),
	"COD" NVARCHAR(127),
	"AGENTE" NVARCHAR(255),
	"NIF" NVARCHAR(255),
	"NIF_NOMBRE" NVARCHAR(513),
	"CUADRO" NVARCHAR(255),
	"COD_TIPO" NVARCHAR(11),
	"TIPO" NVARCHAR(255),
	"PERIODO" NVARCHAR(104),
	"MES_PERIODO" NVARCHAR(2),
	"PERCEPCION" NVARCHAR(255),
	"IMPORTE" DECIMAL(25, 10) CS_FIXED,
	"MES_PERCEPCION" NVARCHAR(5000),
	"IGUALES" INTEGER CS_INT,
	"ANYO" NVARCHAR(50),
	"INCLUIR_AGENCIAS" NVARCHAR(2),
	"FEC_ACTUALIZACION" NVARCHAR(5000),
	"POSITIONSEQ" BIGINT CS_FIXED,
	"PERIODSEQ" BIGINT CS_FIXED
)
UNLOAD PRIORITY 5 AUTO MERGE;
