CREATE COLUMN TABLE "EXT"."OUT_INSP_ACTIVOS_REP"(
	"COD_REGIONAL" VARCHAR(127),
	"REGIONAL" VARCHAR(90),
	"COD_SUCURSAL" VARCHAR(127),
	"SUCURSAL" VARCHAR(90),
	"COD_OFICINA" VARCHAR(127),
	"OFICINA" VARCHAR(90),
	"POS_PRIN" VARCHAR(127),
	"NOMBRE" VARCHAR(202),
	"NIF" VARCHAR(255),
	"CUADRO_INSP" VARCHAR(255),
	"ID_TIPO_AGENTE" DECIMAL(25, 10) CS_FIXED,
	"TIPO_AGENTE" VARCHAR(255),
	"NUM_POL" DECIMAL(25, 10) CS_FIXED,
	"NUM_PRIMA_NETA" DECIMAL(25, 10) CS_FIXED,
	"NUM_PRIMA_CORR" DECIMAL(25, 10) CS_FIXED,
	"OBJ_POL" DECIMAL(25, 10) CS_FIXED,
	"OBJ_PRIMA" DECIMAL(25, 10) CS_FIXED,
	"FEC_ALTA_POS" LONGDATE CS_LONGDATE,
	"FEC_ALTA_CAT" LONGDATE CS_LONGDATE,
	"PARTICIPANTSEQ" BIGINT CS_FIXED,
	"POSITIONSEQ_PRIN" BIGINT CS_FIXED,
	"PERIODSEQ" BIGINT CS_FIXED NOT NULL,
	"PERIODO" VARCHAR(50) NOT NULL,
	"NUM_POL_CORR" DECIMAL(25, 10) CS_FIXED
)
UNLOAD PRIORITY 5 AUTO MERGE;
ALTER TABLE "EXT"."OUT_INSP_ACTIVOS_REP" WITH PARAMETERS ('CONCAT_ATTRIBUTE'=('$PERIODSEQ$PARTICIPANTSEQ$POSITIONSEQ_PRIN$','PERIODSEQ','PARTICIPANTSEQ','POSITIONSEQ_PRIN'));
ALTER TABLE "EXT"."OUT_INSP_ACTIVOS_REP" WITH PARAMETERS ('CONCAT_ATTRIBUTE'=('$PERIODSEQ$PERIODO$POS_PRIN$','PERIODSEQ','PERIODO','POS_PRIN'));
CREATE CPBTREE INDEX "OUT_INSP_ACTIVOS_REP_IDX1" ON "EXT"."OUT_INSP_ACTIVOS_REP" ( "PERIODSEQ" ASC, "PARTICIPANTSEQ" ASC, "POSITIONSEQ_PRIN" ASC );
