CREATE COLUMN TABLE "EXT"."OUT_AN_RESUMEN_REP"(
	"V_MEDIDA" DECIMAL(25, 10) CS_FIXED,
	"N_MEDIDA" VARCHAR(90),
	"STARTDATE" LONGDATE CS_LONGDATE NOT NULL,
	"YEAR" VARCHAR(50) NOT NULL,
	"QUARTER" VARCHAR(50) NOT NULL,
	"PERIODO" VARCHAR(50) NOT NULL,
	"PERIODSEQ" BIGINT CS_FIXED NOT NULL,
	"POSITIONSEQ_PRIN" BIGINT CS_FIXED,
	"PARTICIPANTSEQ" BIGINT CS_FIXED,
	"TIPO_AGENTE" VARCHAR(255),
	"ID_TIPO_AGENTE" DECIMAL(25, 10) CS_FIXED,
	"POS_PRIN" VARCHAR(127),
	"POSITIONNAME" VARCHAR(127),
	"LASTNAME" VARCHAR(90),
	"MIDDLENAME" VARCHAR(90),
	"FIRSTNAME" VARCHAR(90),
	"BOUSERID" VARCHAR(260),
	CONSTRAINT "SYS_C0031403" CHECK ("PERIODSEQ" IS NOT NULL),
	CONSTRAINT "SYS_C0031404" CHECK ("PERIODO" IS NOT NULL),
	CONSTRAINT "SYS_C0031405" CHECK ("QUARTER" IS NOT NULL),
	CONSTRAINT "SYS_C0031406" CHECK ("YEAR" IS NOT NULL),
	CONSTRAINT "SYS_C0031407" CHECK ("STARTDATE" IS NOT NULL)
)
UNLOAD PRIORITY 5 AUTO MERGE;
ALTER TABLE "EXT"."OUT_AN_RESUMEN_REP" WITH PARAMETERS ('CONCAT_ATTRIBUTE'=('$PERIODSEQ$PARTICIPANTSEQ$POSITIONSEQ_PRIN$','PERIODSEQ','PARTICIPANTSEQ','POSITIONSEQ_PRIN'));
CREATE CPBTREE INDEX "_TREE_CS_#1289939_#0_#0" ON "EXT"."OUT_AN_RESUMEN_REP" ( "PERIODSEQ" ASC, "PARTICIPANTSEQ" ASC, "POSITIONSEQ_PRIN" ASC );
