CREATE COLUMN TABLE "EXT"."OUT_BAL_RE_RESUMEN_REP"(
	"TIPO_AGENTE" VARCHAR(255),
	"ID_TIPO_AGENTE" DECIMAL(25, 10) CS_FIXED,
	"POS_PRIN" VARCHAR(127),
	"POSITIONNAME_AG" VARCHAR(127),
	"LASTNAME_AG" VARCHAR(90),
	"MIDDLENAME_AG" VARCHAR(90),
	"FIRSTNAME_AG" VARCHAR(90),
	"V_CREDITO" DECIMAL(25, 10) CS_FIXED,
	"N_CREDITO" VARCHAR(90),
	"POSITIONNAME" VARCHAR(127),
	"LASTNAME" VARCHAR(90),
	"MIDDLENAME" VARCHAR(90),
	"FIRSTNAME" VARCHAR(90),
	"BOUSERID" VARCHAR(260),
	"V_MEDIDA" DECIMAL(25, 10) CS_FIXED,
	"N_MEDIDA" VARCHAR(90),
	"STARTDATE" LONGDATE CS_LONGDATE NOT NULL,
	"YEAR" VARCHAR(50) NOT NULL,
	"QUARTER" VARCHAR(50) NOT NULL,
	"PERIODO" VARCHAR(50) NOT NULL,
	"PERIODSEQ" BIGINT CS_FIXED NOT NULL,
	"POSITIONSEQ_PRIN" BIGINT CS_FIXED,
	"PARTICIPANTSEQ" BIGINT CS_FIXED,
	"VCORRECCION" DECIMAL(25, 10) CS_FIXED,
	CONSTRAINT "SYS_C0031545" CHECK ("PERIODSEQ" IS NOT NULL),
	CONSTRAINT "SYS_C0031546" CHECK ("PERIODO" IS NOT NULL),
	CONSTRAINT "SYS_C0031547" CHECK ("QUARTER" IS NOT NULL),
	CONSTRAINT "SYS_C0031548" CHECK ("YEAR" IS NOT NULL),
	CONSTRAINT "SYS_C0031549" CHECK ("STARTDATE" IS NOT NULL)
)
UNLOAD PRIORITY 5 AUTO MERGE;
ALTER TABLE "EXT"."OUT_BAL_RE_RESUMEN_REP" WITH PARAMETERS ('CONCAT_ATTRIBUTE'=('$PERIODSEQ$PARTICIPANTSEQ$POSITIONSEQ_PRIN$','PERIODSEQ','PARTICIPANTSEQ','POSITIONSEQ_PRIN'));
CREATE CPBTREE INDEX "_TREE_CS_#1272915_#0_#0" ON "EXT"."OUT_BAL_RE_RESUMEN_REP" ( "PERIODSEQ" ASC, "PARTICIPANTSEQ" ASC, "POSITIONSEQ_PRIN" ASC );
