CREATE COLUMN TABLE "EXT"."OUT_PAC_MARCADO_EXTORNO_S5_FILE_HIST"(
	"PERIODSEQ" BIGINT CS_FIXED,
	"POSITIONNAME" VARCHAR(50),
	"CONTEO" INT,
	"BATCHNAME" VARCHAR(250),
	"CREATEDATE" TIMESTAMP
	
	
)
UNLOAD PRIORITY 5 AUTO MERGE;

