CREATE COLUMN TABLE "EXT"."OUT_RPA_RESUMEN_REP"(
	"NIF" VARCHAR(255),
	"TIPO_AGENTE" VARCHAR(255),
	"ID_TIPO_AGENTE" DECIMAL(25, 10) CS_FIXED,
	"POS_PRIN" VARCHAR(127),
	"POSITIONNAME" VARCHAR(127),
	"LASTNAME" VARCHAR(90),
	"MIDDLENAME" VARCHAR(90),
	"FIRSTNAME" VARCHAR(90),
	"BOUSERID" VARCHAR(260),
	"M_GN1" DECIMAL(25, 10) CS_FIXED,
	"V_MEDIDA" DECIMAL(25, 10) CS_FIXED,
	"N_MEDIDA" VARCHAR(90),
	"STARTDATE" LONGDATE CS_LONGDATE NOT NULL,
	"YEAR" VARCHAR(50) NOT NULL,
	"QUARTER" VARCHAR(50) NOT NULL,
	"PERIODO" VARCHAR(50) NOT NULL,
	"PERIODSEQ" BIGINT CS_FIXED NOT NULL,
	"POSITIONSEQ_PRIN" BIGINT CS_FIXED,
	"PARTICIPANTSEQ" BIGINT CS_FIXED,
	"GA1_MEDIDA" VARCHAR(255),
	CONSTRAINT "SYS_C0031897" CHECK ("PERIODSEQ" IS NOT NULL),
	CONSTRAINT "SYS_C0031898" CHECK ("PERIODO" IS NOT NULL),
	CONSTRAINT "SYS_C0031899" CHECK ("QUARTER" IS NOT NULL),
	CONSTRAINT "SYS_C0031900" CHECK ("YEAR" IS NOT NULL),
	CONSTRAINT "SYS_C0031901" CHECK ("STARTDATE" IS NOT NULL)
)
UNLOAD PRIORITY 5 AUTO MERGE;
ALTER TABLE "EXT"."OUT_RPA_RESUMEN_REP" WITH PARAMETERS ('CONCAT_ATTRIBUTE'=('$PERIODSEQ$PARTICIPANTSEQ$POSITIONSEQ_PRIN$','PERIODSEQ','PARTICIPANTSEQ','POSITIONSEQ_PRIN'));
CREATE CPBTREE INDEX "OUT_RPA_RESUMEN_REP_IDX1" ON "EXT"."OUT_RPA_RESUMEN_REP" ( "PERIODSEQ" ASC, "PARTICIPANTSEQ" ASC, "POSITIONSEQ_PRIN" ASC );
