CREATE COLUMN TABLE "EXT"."OUT_CUSTOMPURGE_FILE"(
	"FECHA_PURGADO" LONGDATE CS_LONGDATE,
	"NOMBRE_TABLA" VARCHAR(255),
	"DELETE_CLAUSE" VARCHAR(5000),
	"NUM_REGISTROS" INTEGER CS_INT
)
UNLOAD PRIORITY 5 AUTO MERGE;
