CREATE COLUMN TABLE "EXT"."OUT_RESUMEN_REPARTO_PAGOS_VB2_FINAL_REP"(
	"PERIODSEQ" BIGINT CS_FIXED,
	"PERIODO" VARCHAR(50),
	"PERIODO_FORMATO" VARCHAR(104),
	"COMPANIA" VARCHAR(2),
	"TIPO_PAGO" VARCHAR(255),
	"TRAMO" VARCHAR(20),
	"REPARTO" DECIMAL(18, 2) CS_FIXED,
	"PAGO_MES" DECIMAL(18, 2) CS_FIXED,
	"AGENCIA" VARCHAR(2)
)
UNLOAD PRIORITY 5 AUTO MERGE;
