CREATE COLUMN TABLE "EXT"."OUT_PP_RESUMEN_FINAL_REP"(
	"TIPO_INFORME" VARCHAR(50),
	"PERIODO_FILTRO" VARCHAR(50),
	"PERIODO_FORMATO" VARCHAR(50),
	"CODIGO_AGENTE" VARCHAR(50),
	"NOMBRE_AGENTE" VARCHAR(272),
	"TIPO_AGENTE" VARCHAR(272),
	"NIF" VARCHAR(255),
	"NIF_NOMBRE" VARCHAR(530),
	"FECHA_EFECTO" VARCHAR(50),
	"PERIODO_TABLA" VARCHAR(50),
	"STARTDATE" LONGDATE CS_LONGDATE,
	"POLIZ_CORR" DECIMAL(28, 10) CS_FIXED,
	"EXTORNO" DECIMAL(28, 10) CS_FIXED,
	"FEC_ACTUALIZACION" VARCHAR(50),
	"SOLO_DIFERENCIAS" VARCHAR(2),
	"POSITIONSEQ" BIGINT CS_FIXED,
	"PERIODSEQ" BIGINT CS_FIXED
)
UNLOAD PRIORITY 5 AUTO MERGE;
