CREATE COLUMN TABLE "EXT"."OUT_RESUMEN_REPARTO_PAGOS_VB1_FINAL_REP_BKP"(
	"PERIODSEQ" BIGINT CS_FIXED,
	"PERIODO" VARCHAR(40),
	"PERIODO_FORMATO" VARCHAR(84),
	"COMPANIA" VARCHAR(2),
	"TIPO_PAGO" VARCHAR(255),
	"NUM_TRAMO" BIGINT CS_FIXED,
	"PRODUCTID" VARCHAR(127),
	"IMPORTE" DECIMAL(18, 2) CS_FIXED,
	"AGENCIA" VARCHAR(2)
)
UNLOAD PRIORITY 5 AUTO MERGE;
