CREATE COLUMN TABLE "EXT"."OUT_CARTERA_AGENTES_FINAL_REP"(
	"YEAR" INTEGER CS_INT,
	"AGENTE" VARCHAR(266),
	"NIF" VARCHAR(255),
	"ID_TIPO_AGENTE" DECIMAL(28, 10) CS_FIXED,
	"TABLA" VARCHAR(50),
	"PRODUCTO" VARCHAR(135),
	"POLIZAS" DECIMAL(28, 10) CS_FIXED,
	"PRIMAS" DECIMAL(28, 10) CS_FIXED,
	"PRODUCCION" DECIMAL(28, 10) CS_FIXED,
	"CARTERA" DECIMAL(28, 10) CS_FIXED,
	"TOTAL" DECIMAL(28, 10) CS_FIXED,
	"ULTIMA_ACTUALIZACION" VARCHAR(50),
	"POSITIONSEQ" BIGINT CS_FIXED,
	"PERIODSEQ" BIGINT CS_FIXED,
	"COMPANIA" VARCHAR(10)
)
UNLOAD PRIORITY 5 AUTO MERGE;
