CREATE COLUMN TABLE "EXT"."OUT_BAL_S4_E_FACTURA_REP"(
	"IMPORTE" DECIMAL(25, 10) CS_FIXED,
	"TIPO_INFORME" VARCHAR(2),
	"COMISION" VARCHAR(255),
	"OFICINA" VARCHAR(90),
	"COD_OFICINA" VARCHAR(127),
	"IRPF" DECIMAL(25, 10) CS_FIXED,
	"COMPANIA" VARCHAR(2),
	"CUADRO_RRTT" VARCHAR(255),
	"CUADRO_RRGG" VARCHAR(255),
	"POS_PRIN" VARCHAR(127),
	"CP" DECIMAL(25, 10) CS_FIXED,
	"DOMICILIO" VARCHAR(255),
	"MUNICIPIO" VARCHAR(255),
	"NOMBRE" VARCHAR(260),
	"NIF" VARCHAR(255),
	"BOUSERID" VARCHAR(260),
	"PERIODO" VARCHAR(50) NOT NULL,
	"PERIODSEQ" BIGINT CS_FIXED NOT NULL,
	"POSITIONSEQ_PRIN" BIGINT CS_FIXED,
	"PARTICIPANTSEQ" BIGINT CS_FIXED,
	CONSTRAINT "SYS_C0031575" CHECK ("PERIODSEQ" IS NOT NULL),
	CONSTRAINT "SYS_C0031576" CHECK ("PERIODO" IS NOT NULL)
)
UNLOAD PRIORITY 5 AUTO MERGE;
ALTER TABLE "EXT"."OUT_BAL_S4_E_FACTURA_REP" WITH PARAMETERS ('CONCAT_ATTRIBUTE'=('$PERIODSEQ$PARTICIPANTSEQ$POSITIONSEQ_PRIN$','PERIODSEQ','PARTICIPANTSEQ','POSITIONSEQ_PRIN'));
CREATE CPBTREE INDEX "OUT_BAL_S4_E_FACTURA_REP_IDX1" ON "EXT"."OUT_BAL_S4_E_FACTURA_REP" ( "PERIODSEQ" ASC, "PARTICIPANTSEQ" ASC, "POSITIONSEQ_PRIN" ASC );
