CREATE COLUMN TABLE "EXT"."OUT_RA_RESUMEN_REP"(
	"TIPO_AGENTE" VARCHAR(255),
	"ID_TIPO_AGENTE" DECIMAL(25, 10) CS_FIXED,
	"POS_PRIN" VARCHAR(127),
	"LASTNAME" VARCHAR(90),
	"MIDDLENAME" VARCHAR(90),
	"FIRSTNAME" VARCHAR(90),
	"BOUSERID" VARCHAR(260),
	"V_MEDIDA" DECIMAL(25, 10) CS_FIXED,
	"N_MEDIDA" VARCHAR(90),
	"PERIODO" VARCHAR(50) NOT NULL,
	"PERIODSEQ" BIGINT CS_FIXED NOT NULL,
	"POSITIONSEQ_PRIN" BIGINT CS_FIXED,
	"PARTICIPANTSEQ" BIGINT CS_FIXED,
	CONSTRAINT "SYS_C0031858" CHECK ("PERIODSEQ" IS NOT NULL),
	CONSTRAINT "SYS_C0031859" CHECK ("PERIODO" IS NOT NULL)
)
UNLOAD PRIORITY 5 AUTO MERGE;
ALTER TABLE "EXT"."OUT_RA_RESUMEN_REP" WITH PARAMETERS ('CONCAT_ATTRIBUTE'=('$PERIODSEQ$PARTICIPANTSEQ$POSITIONSEQ_PRIN$','PERIODSEQ','PARTICIPANTSEQ','POSITIONSEQ_PRIN'));
CREATE CPBTREE INDEX "OUT_RA_RESUMEN_REP_IDX1" ON "EXT"."OUT_RA_RESUMEN_REP" ( "PERIODSEQ" ASC, "PARTICIPANTSEQ" ASC, "POSITIONSEQ_PRIN" ASC );
