CREATE COLUMN TABLE "EXT"."OUT_PERC_AGENTES_REP"(
	"YEAR" VARCHAR(50),
	"QUARTER" VARCHAR(50),
	"PERIODO" VARCHAR(50) NOT NULL,
	"STARTDATE" LONGDATE CS_LONGDATE NOT NULL,
	"PERIODSEQ" BIGINT CS_FIXED NOT NULL,
	"NIF" VARCHAR(255),
	"PERCEPCION" VARCHAR(255),
	"IMP_PERCEPCION" DECIMAL(25, 10) CS_FIXED,
	"MES_PERCEPCION" BIGINT CS_FIXED,
	"BALANCE" BIGINT CS_FIXED,
	"EARNINGCODEID" VARCHAR(255),
	"EARNINGGROUPID" VARCHAR(255),
	"POSITIONSEQ_PRIN" BIGINT CS_FIXED,
	"POSITIONSEQ" BIGINT CS_FIXED,
	"PARTICIPANTSEQ" BIGINT CS_FIXED,
	"POS_PRIN" VARCHAR(127),
	"POS_CALLIDUS" VARCHAR(127),
	"POSITIONNAME" VARCHAR(127),
	CONSTRAINT "SYS_C0031825" CHECK ("PERIODO" IS NOT NULL),
	CONSTRAINT "SYS_C0031826" CHECK ("STARTDATE" IS NOT NULL),
	CONSTRAINT "SYS_C0031827" CHECK ("PERIODSEQ" IS NOT NULL)
)
UNLOAD PRIORITY 5 AUTO MERGE;
ALTER TABLE "EXT"."OUT_PERC_AGENTES_REP" WITH PARAMETERS ('CONCAT_ATTRIBUTE'=('$PERIODSEQ$NIF$','PERIODSEQ','NIF'));
CREATE CPBTREE INDEX "OUT_PERC_AGENTES_REP_IDX1" ON "EXT"."OUT_PERC_AGENTES_REP" ( "PERIODSEQ" ASC, "NIF" ASC );
