CREATE COLUMN TABLE "EXT"."OUT_PERC_INSPECTORES_REP"(
	"EARNINGGROUPID" VARCHAR(255),
	"EARNINGCODEID" VARCHAR(255),
	"BALANCE" BIGINT CS_FIXED,
	"MES_PERCEPCION" BIGINT CS_FIXED,
	"IMP_PERCEPCION" DECIMAL(25, 10) CS_FIXED,
	"PERCEPCION" VARCHAR(255),
	"NIF" VARCHAR(255),
	"PERIODSEQ" BIGINT CS_FIXED NOT NULL,
	"STARTDATE" LONGDATE CS_LONGDATE NOT NULL,
	"PERIODO" VARCHAR(50) NOT NULL,
	"QUARTER" VARCHAR(50),
	"YEAR" VARCHAR(50),
	"POSITIONNAME" VARCHAR(127),
	"POS_CALLIDUS" VARCHAR(127),
	"POS_PRIN" VARCHAR(127),
	"PARTICIPANTSEQ" BIGINT CS_FIXED,
	"POSITIONSEQ" BIGINT CS_FIXED,
	"POSITIONSEQ_PRIN" BIGINT CS_FIXED,
	CONSTRAINT "SYS_C0031828" CHECK ("PERIODO" IS NOT NULL),
	CONSTRAINT "SYS_C0031829" CHECK ("STARTDATE" IS NOT NULL),
	CONSTRAINT "SYS_C0031830" CHECK ("PERIODSEQ" IS NOT NULL)
)
UNLOAD PRIORITY 5 AUTO MERGE;
ALTER TABLE "EXT"."OUT_PERC_INSPECTORES_REP" WITH PARAMETERS ('CONCAT_ATTRIBUTE'=('$PERIODSEQ$NIF$','PERIODSEQ','NIF'));
CREATE CPBTREE INDEX "OUT_PERC_INSPECTORES_REP_IDX1" ON "EXT"."OUT_PERC_INSPECTORES_REP" ( "PERIODSEQ" ASC, "NIF" ASC );
