CREATE COLUMN TABLE "EXT"."OUT_S5_FACTURA_REP"(
	"PARTICIPANTSEQ" BIGINT CS_FIXED,
	"POSITIONSEQ_PRIN" BIGINT CS_FIXED,
	"PERIODSEQ" BIGINT CS_FIXED NOT NULL,
	"PERIODO" VARCHAR(50) NOT NULL,
	"BOUSERID" NVARCHAR(260),
	"NIF" VARCHAR(255),
	"NOMBRE" NVARCHAR(260),
	"MUNICIPIO" VARCHAR(255),
	"DOMICILIO" VARCHAR(255),
	"CP" DECIMAL(25, 10) CS_FIXED,
	"POS_PRIN" NVARCHAR(127),
	"CUADRO_INSP" VARCHAR(255),
	"COMPANIA" VARCHAR(2),
	"IRPF" DECIMAL(25, 10) CS_FIXED,
	"COD_OFICINA" NVARCHAR(127),
	"OFICINA" NVARCHAR(90),
	"COMISION" NVARCHAR(255),
	"TIPO_INFORME" VARCHAR(2),
	"IMPORTE" DECIMAL(25, 10) CS_FIXED,
	"SECUENCIAL" BIGINT CS_FIXED,
	"NUMERO" NVARCHAR(1023),
	"RESTO_DOMICILIO" NVARCHAR(1023),
	CONSTRAINT "SYS_C0031921" CHECK ("PERIODSEQ" IS NOT NULL),
	CONSTRAINT "SYS_C0031922" CHECK ("PERIODO" IS NOT NULL)
)
UNLOAD PRIORITY 5 AUTO MERGE;
ALTER TABLE "EXT"."OUT_S5_FACTURA_REP" WITH PARAMETERS ('CONCAT_ATTRIBUTE'=('$PERIODSEQ$PARTICIPANTSEQ$POSITIONSEQ_PRIN$','PERIODSEQ','PARTICIPANTSEQ','POSITIONSEQ_PRIN'));
CREATE CPBTREE INDEX "OUT_S5_FACTURA_REP_IDX1" ON "EXT"."OUT_S5_FACTURA_REP" ( "PERIODSEQ" ASC, "PARTICIPANTSEQ" ASC, "POSITIONSEQ_PRIN" ASC );
