CREATE COLUMN TABLE "EXT"."OUT_PROD_E_AGENTES_REP"(
	"POSITIONNAME" VARCHAR(127),
	"POS_CALLIDUS" VARCHAR(127),
	"POS_PRIN" VARCHAR(127),
	"PARTICIPANTSEQ" BIGINT CS_FIXED,
	"POSITIONSEQ" BIGINT CS_FIXED,
	"POSITIONSEQ_PRIN" BIGINT CS_FIXED,
	"VALUE" DECIMAL(25, 10) CS_FIXED,
	"NAME" VARCHAR(90),
	"NIF" VARCHAR(255),
	"PERIODSEQ" BIGINT CS_FIXED NOT NULL,
	"STARTDATE" LONGDATE CS_LONGDATE NOT NULL,
	"PERIODO" VARCHAR(50) NOT NULL,
	"QUARTER" VARCHAR(50),
	"YEAR" VARCHAR(50),
	CONSTRAINT "SYS_C0031931" CHECK ("PERIODO" IS NOT NULL),
	CONSTRAINT "SYS_C0031932" CHECK ("STARTDATE" IS NOT NULL),
	CONSTRAINT "SYS_C0031933" CHECK ("PERIODSEQ" IS NOT NULL)
)
UNLOAD PRIORITY 5 AUTO MERGE;
ALTER TABLE "EXT"."OUT_PROD_E_AGENTES_REP" WITH PARAMETERS ('CONCAT_ATTRIBUTE'=('$PERIODSEQ$NIF$','PERIODSEQ','NIF'));
CREATE CPBTREE INDEX "OUT_PROD_E_AGENTES_REP_IDX1" ON "EXT"."OUT_PROD_E_AGENTES_REP" ( "PERIODSEQ" ASC, "NIF" ASC );
