CREATE COLUMN TABLE "EXT"."OUT_S5_E_FACTURA_REP"(
	"NIF" VARCHAR(255),
	"BOUSERID" VARCHAR(260),
	"PERIODO" VARCHAR(50) NOT NULL,
	"PERIODSEQ" BIGINT CS_FIXED NOT NULL,
	"POSITIONSEQ_PRIN" BIGINT CS_FIXED,
	"PARTICIPANTSEQ" BIGINT CS_FIXED,
	"NOMBRE" VARCHAR(260),
	"SECUENCIAL" BIGINT CS_FIXED,
	"IMPORTE" DECIMAL(25, 10) CS_FIXED,
	"TIPO_INFORME" VARCHAR(2),
	"COMISION" VARCHAR(255),
	"OFICINA" VARCHAR(90),
	"COD_OFICINA" VARCHAR(127),
	"IRPF" DECIMAL(25, 10) CS_FIXED,
	"COMPANIA" VARCHAR(2),
	"CUADRO_INSP" VARCHAR(255),
	"POS_PRIN" VARCHAR(127),
	"CP" DECIMAL(25, 10) CS_FIXED,
	"DOMICILIO" VARCHAR(255),
	"MUNICIPIO" VARCHAR(255),
	CONSTRAINT "SYS_C0031917" CHECK ("PERIODSEQ" IS NOT NULL),
	CONSTRAINT "SYS_C0031918" CHECK ("PERIODO" IS NOT NULL)
)
UNLOAD PRIORITY 5 AUTO MERGE;
ALTER TABLE "EXT"."OUT_S5_E_FACTURA_REP" WITH PARAMETERS ('CONCAT_ATTRIBUTE'=('$PERIODSEQ$PARTICIPANTSEQ$POSITIONSEQ_PRIN$','PERIODSEQ','PARTICIPANTSEQ','POSITIONSEQ_PRIN'));
CREATE CPBTREE INDEX "OUT_S5_E_FACTURA_REP_IDX1" ON "EXT"."OUT_S5_E_FACTURA_REP" ( "PERIODSEQ" ASC, "PARTICIPANTSEQ" ASC, "POSITIONSEQ_PRIN" ASC );
