CREATE COLUMN TABLE "EXT"."OUT_S4_POLIZAS_REP"(
	"COD_RECIBO" VARCHAR(255),
	"PARTICIPANTSEQ" BIGINT CS_FIXED,
	"POSITIONSEQ_PRIN" BIGINT CS_FIXED,
	"PERIODSEQ" BIGINT CS_FIXED NOT NULL,
	"PERIODO" VARCHAR(50) NOT NULL,
	"BOUSERID" VARCHAR(260),
	"POSITIONNAME" VARCHAR(127),
	"NIF" VARCHAR(255),
	"NOMBRE" VARCHAR(255),
	"POS_PRIN" VARCHAR(127),
	"CUADRO_RRGG" VARCHAR(255),
	"CUADRO_RRTT" VARCHAR(255),
	"COMPANIA" VARCHAR(2),
	"COD_OFICINA" VARCHAR(127),
	"OFICINA" VARCHAR(90),
	"NAME" VARCHAR(90),
	"VALUE" DECIMAL(25, 10) CS_FIXED,
	"POLIZ_CORR" DECIMAL(25, 10) CS_FIXED,
	"POLIZ_NP" DECIMAL(25, 10) CS_FIXED,
	"SALESTRANSACTIONSEQ" VARCHAR(127),
	"POLIZA" VARCHAR(255),
	"PRODUCTID" VARCHAR(127),
	"FEC_CARGO" LONGDATE CS_LONGDATE,
	"PRIMA_COMIS" DECIMAL(25, 10) CS_FIXED,
	"EVENTO" VARCHAR(255),
	"PRODUCTO" VARCHAR(127),
	"FEC_VTO_REC" LONGDATE CS_LONGDATE,
	"PRIMA_NETA" DECIMAL(25, 10) CS_FIXED,
	"ID_TIPO_AGENTE" DECIMAL(25, 10) CS_FIXED,
	"TIPO_AGENTE" VARCHAR(255),
	"NIVEL_PTO_VENTA" DECIMAL(25, 10) CS_FIXED,
	"COD_PTO_VENTA" VARCHAR(127),
	"PTO_VENTA" VARCHAR(90),
	"NIVEL_OFICINA" DECIMAL(25, 10) CS_FIXED,
	"NIVEL_SUCURSAL" DECIMAL(25, 10) CS_FIXED,
	"COD_SUCURSAL" VARCHAR(127),
	"SUCURSAL" VARCHAR(90),
	"NIVEL_REGIONAL" DECIMAL(25, 10) CS_FIXED,
	"COD_REGIONAL" VARCHAR(127),
	"REGIONAL" VARCHAR(90),
	"SUPERRAPEL" SMALLINT CS_INT,
	"ASEGURADOS" DECIMAL(25, 10) CS_FIXED
)
UNLOAD PRIORITY 5 AUTO MERGE;
ALTER TABLE "EXT"."OUT_S4_POLIZAS_REP" WITH PARAMETERS ('CONCAT_ATTRIBUTE'=('$PERIODSEQ$PARTICIPANTSEQ$POSITIONSEQ_PRIN$','PERIODSEQ','PARTICIPANTSEQ','POSITIONSEQ_PRIN'));
ALTER TABLE "EXT"."OUT_S4_POLIZAS_REP" WITH PARAMETERS ('CONCAT_ATTRIBUTE'=('$PERIODSEQ$PERIODO$COD_OFICINA$','PERIODSEQ','PERIODO','COD_OFICINA'));
ALTER TABLE "EXT"."OUT_S4_POLIZAS_REP" WITH PARAMETERS ('CONCAT_ATTRIBUTE'=('$PERIODO$POS_PRIN$','PERIODO','POS_PRIN'));
ALTER TABLE "EXT"."OUT_S4_POLIZAS_REP" WITH PARAMETERS ('CONCAT_ATTRIBUTE'=('$PERIODSEQ$PERIODO$NIF$','PERIODSEQ','PERIODO','NIF'));
CREATE CPBTREE INDEX "OUT_S4_POLIZAS_REP_IDX1" ON "EXT"."OUT_S4_POLIZAS_REP" ( "PERIODSEQ" ASC, "PARTICIPANTSEQ" ASC, "POSITIONSEQ_PRIN" ASC );
CREATE CPBTREE INDEX "OUT_S4_POLIZAS_REP_IDX2" ON "EXT"."OUT_S4_POLIZAS_REP" ( "PERIODSEQ" ASC, "PERIODO" ASC, "COD_OFICINA" ASC );
CREATE CPBTREE INDEX "OUT_S4_POLIZAS_REP_IDX3" ON "EXT"."OUT_S4_POLIZAS_REP" ( "PERIODO" ASC, "POS_PRIN" ASC );
CREATE CPBTREE INDEX "OUT_S4_POLIZAS_REP_IDX4" ON "EXT"."OUT_S4_POLIZAS_REP" ( "PERIODSEQ" ASC, "PERIODO" ASC, "NIF" ASC );
