CREATE COLUMN TABLE "EXT"."OUT_FECHAS_WEBI_REP"(
	"PERIODO" VARCHAR(255),
	"DESCRIPCION" VARCHAR(255),
	"ULTIMA_ACTUALIZACION" LONGDATE CS_LONGDATE,
	"TABLA" VARCHAR(255),
	"PERIODSEQ" BIGINT CS_FIXED
)
UNLOAD PRIORITY 5 AUTO MERGE;
