CREATE COLUMN TABLE "EXT"."OUT_RPP_DETALLE_FINAL_REP"(
	"TIPO_INFORME" VARCHAR(20),
	"PERIODSEQ" BIGINT CS_FIXED,
	"POSITIONSEQ" BIGINT CS_FIXED,
	"PERIODO" VARCHAR(50),
	"PERIODO_FORMATO" VARCHAR(50),
	"COD_AGENTE" VARCHAR(127),
	"NOMBRE_AGENTE" VARCHAR(300),
	"NIF" VARCHAR(255),
	"TIPO_AGE" VARCHAR(255),
	"COD_PROD" VARCHAR(50),
	"CODIGO_POLIZA" VARCHAR(255),
	"NOMBRE_PRODUCTO" VARCHAR(127),
	"TIPO_RECIBO" VARCHAR(255),
	"FECHA_EMISION" VARCHAR(50),
	"FECHA_COBRO" VARCHAR(50),
	"POLIZAS_FIS" DECIMAL(25, 10) CS_FIXED,
	"POLIZAS_CORR" DECIMAL(25, 10) CS_FIXED,
	"PRIMAS" DECIMAL(25, 10) CS_FIXED,
	"SOLO_DIFERENCIAS" VARCHAR(20),
	"FEC_ACTUALIZACION" VARCHAR(20)
)
UNLOAD PRIORITY 5 AUTO MERGE;
