CREATE COLUMN TABLE "EXT"."OUT_CARTERA_AGENTES_REP"(
	"POS_CALLIDUS" VARCHAR(127),
	"POS_PRIN" VARCHAR(127),
	"PARTICIPANTSEQ" BIGINT CS_FIXED,
	"POSITIONSEQ" BIGINT CS_FIXED,
	"POSITIONSEQ_PRIN" BIGINT CS_FIXED,
	"PRODUCTO" VARCHAR(127),
	"EVENTO" VARCHAR(255),
	"ST_GD2" LONGDATE CS_LONGDATE,
	"ACCOUNTINGDATE" LONGDATE CS_LONGDATE,
	"PRODUCTID" VARCHAR(127),
	"POLIZA" VARCHAR(255),
	"SALESTRANSACTIONSEQ" VARCHAR(127),
	"C_GN4" DECIMAL(25, 10) CS_FIXED,
	"VALUE" DECIMAL(25, 10) CS_FIXED,
	"NAME" VARCHAR(90),
	"NIF" VARCHAR(255),
	"PERIODSEQ" BIGINT CS_FIXED NOT NULL,
	"STARTDATE" LONGDATE CS_LONGDATE NOT NULL,
	"PERIODO" VARCHAR(50) NOT NULL,
	"QUARTER" VARCHAR(50),
	"YEAR" VARCHAR(50),
	"POSITIONNAME" VARCHAR(127),
	"PRIMA" DECIMAL(25, 10) CS_FIXED,
	"COMPANIA" VARCHAR(10),
	CONSTRAINT "SYS_C0031591_OUT_CARTERA_AGENTES_REP" CHECK ("PERIODO" IS NOT NULL),
	CONSTRAINT "SYS_C0031592_OUT_CARTERA_AGENTES_REP" CHECK ("STARTDATE" IS NOT NULL),
	CONSTRAINT "SYS_C0031593_OUT_CARTERA_AGENTES_REP" CHECK ("PERIODSEQ" IS NOT NULL)
)
UNLOAD PRIORITY 5 AUTO MERGE;
ALTER TABLE "EXT"."OUT_CARTERA_AGENTES_REP" WITH PARAMETERS ('CONCAT_ATTRIBUTE'=('$PERIODSEQ$PARTICIPANTSEQ$POSITIONSEQ_PRIN$','PERIODSEQ','PARTICIPANTSEQ','POSITIONSEQ_PRIN'));
ALTER TABLE "EXT"."OUT_CARTERA_AGENTES_REP" WITH PARAMETERS ('CONCAT_ATTRIBUTE'=('$PARTICIPANTSEQ$POSITIONSEQ_PRIN$','PARTICIPANTSEQ','POSITIONSEQ_PRIN'));
CREATE CPBTREE INDEX "_TREE_CS_#2527432_#0_#0" ON "EXT"."OUT_CARTERA_AGENTES_REP" ( "PERIODSEQ" ASC, "PARTICIPANTSEQ" ASC, "POSITIONSEQ_PRIN" ASC );
CREATE CPBTREE INDEX "_TREE_CS_#2527432_#0_#1" ON "EXT"."OUT_CARTERA_AGENTES_REP" ( "PARTICIPANTSEQ" ASC, "POSITIONSEQ_PRIN" ASC );
