CREATE COLUMN TABLE "EXT"."OUT_RPP_RESUMEN_FINAL_REP"(
	"TIPO_INFORME" VARCHAR(7) NOT NULL,
	"PERIODSEQ" BIGINT CS_FIXED,
	"POSITIONSEQ" BIGINT CS_FIXED,
	"PERIODO" VARCHAR(50),
	"PERIODO_FORMATO" VARCHAR(50),
	"COD_AGENTE" VARCHAR(127),
	"NOMBRE_AGENTE" VARCHAR(272),
	"NIF" VARCHAR(255),
	"TIPO_AGENTE" VARCHAR(269),
	"POL_CORR" DECIMAL(28, 10) CS_FIXED,
	"PRIMAS" DECIMAL(28, 10) CS_FIXED,
	"PAGOS" DECIMAL(28, 10) CS_FIXED,
	"SOLO_DIFERENCIAS" VARCHAR(2),
	"FEC_ACTUALIZACION" VARCHAR(127)
)
UNLOAD PRIORITY 5 AUTO MERGE;
