CREATE COLUMN TABLE "EXT"."OUT_REPARTO_PAGOS_COMMISSIONS_FINAL_REP"(
	"COMPANYA" VARCHAR(2),
	"CONCEPTO_PAGO" VARCHAR(255),
	"GRUPO_PAGO" VARCHAR(255),
	"POS_PRIN" NVARCHAR(255),
	"ANYO" VARCHAR(50),
	"PERIODO" VARCHAR(50),
	"PERIODO_FORMATO" VARCHAR(104),
	"NIF_NOMBRE" NVARCHAR(460),
	"IMPORTE" DECIMAL(28, 10) CS_FIXED,
	"POSITIONSEQ" BIGINT CS_FIXED,
	"PERIODSEQ" BIGINT CS_FIXED
)
UNLOAD PRIORITY 5 AUTO MERGE;
