CREATE COLUMN TABLE "EXT"."OUT_BATCH_CONTROL"(
	"ID_PROCESO" BIGINT CS_FIXED NOT NULL,
	"FILE_NAME" VARCHAR(100),
	"PROCEDURE_NAME" VARCHAR(50) NOT NULL,
	"TARGET_ROWS" INTEGER CS_INT,
	"STATUS" INTEGER CS_INT NOT NULL,
	"START_DATE" LONGDATE CS_LONGDATE,
	"END_DATE" LONGDATE CS_LONGDATE
)
UNLOAD PRIORITY 5 AUTO MERGE;
