CREATE COLUMN TABLE "EXT"."OUT_RE_RESUMEN_FINAL_REP"(
	"TIPO_INFORME" VARCHAR(50),
	"PERIODO" VARCHAR(50),
	"PERIODO_FORMATO" VARCHAR(50),
	"CODIGO_AGENTE" VARCHAR(127),
	"NIF" VARCHAR(255),
	"NOMBRE_AGENTE" VARCHAR(272),
	"NIF_NOMBRE" VARCHAR(530),
	"TIPO_AGENTE" VARCHAR(269),
	"RRPP" DECIMAL(28, 10) CS_FIXED,
	"ASEG_RRTT" DECIMAL(28, 10) CS_FIXED,
	"PRIMA_ANUALIZ" DECIMAL(28, 10) CS_FIXED,
	"IMPORTE_RRPP" DECIMAL(28, 10) CS_FIXED,
	"IMPORTE_ASEG_RRTT" DECIMAL(28, 10) CS_FIXED,
	"CODIGO_AGENTE_TABLA" VARCHAR(127),
	"NOMBRE_AGENTE_TABLA" VARCHAR(272),
	"RRPP_TABLA" DECIMAL(28, 10) CS_FIXED,
	"ASEG_RRTT_TABLA" DECIMAL(28, 10) CS_FIXED,
	"FEC_ACTUALIZACION" VARCHAR(50),
	"SOLO_DIFERENCIAS" VARCHAR(10),
	"POSITIONSEQ" BIGINT CS_FIXED,
	"PERIODSEQ" BIGINT CS_FIXED
)
UNLOAD PRIORITY 5 AUTO MERGE;
