CREATE COLUMN TABLE "EXT"."OUT_BAL_RPP_DETALLE_REP"(
	"PRODUCTO" VARCHAR(127),
	"TIPO_CREDITO" VARCHAR(255),
	"EVENTO" VARCHAR(255),
	"ST_GD3" LONGDATE CS_LONGDATE,
	"ST_GN3" DECIMAL(25, 10) CS_FIXED,
	"ST_GN2" DECIMAL(25, 10) CS_FIXED,
	"ST_GN1" DECIMAL(25, 10) CS_FIXED,
	"ACCOUNTINGDATE" LONGDATE CS_LONGDATE,
	"PRODUCTID" VARCHAR(127),
	"ST_GA1" VARCHAR(255),
	"C_GN1" DECIMAL(25, 10) CS_FIXED,
	"VALUE" DECIMAL(25, 10) CS_FIXED,
	"NAME" VARCHAR(90),
	"LASTNAME" VARCHAR(90),
	"MIDDLENAME" VARCHAR(90),
	"FIRSTNAME" VARCHAR(90),
	"BOUSERID" VARCHAR(260),
	"PERIODO" VARCHAR(50) NOT NULL,
	"PERIODSEQ" BIGINT CS_FIXED NOT NULL,
	"POSITIONSEQ_PRIN" BIGINT CS_FIXED,
	"PARTICIPANTSEQ" BIGINT CS_FIXED,
	"NIF" VARCHAR(255),
	"SALESTRANSACTIONSEQ" VARCHAR(127),
	"TIPO_AGENTE" VARCHAR(255),
	"ID_TIPO_AGENTE" DECIMAL(25, 10) CS_FIXED,
	"POS_PRIN" VARCHAR(127),
	CONSTRAINT "SYS_C0032039" CHECK ("PERIODSEQ" IS NOT NULL),
	CONSTRAINT "SYS_C0032040" CHECK ("PERIODO" IS NOT NULL)
)
UNLOAD PRIORITY 5 AUTO MERGE;
ALTER TABLE "EXT"."OUT_BAL_RPP_DETALLE_REP" WITH PARAMETERS ('CONCAT_ATTRIBUTE'=('$PERIODSEQ$PARTICIPANTSEQ$POSITIONSEQ_PRIN$','PERIODSEQ','PARTICIPANTSEQ','POSITIONSEQ_PRIN'));
CREATE CPBTREE INDEX "OUT_BAL_RPP_DETALLE_REP_IDX1" ON "EXT"."OUT_BAL_RPP_DETALLE_REP" ( "PERIODSEQ" ASC, "PARTICIPANTSEQ" ASC, "POSITIONSEQ_PRIN" ASC );
