CREATE COLUMN TABLE "EXT"."OUT_PROD_INSPECTORES_REP"(
	"YEAR" VARCHAR(50),
	"QUARTER" VARCHAR(50),
	"PERIODO" VARCHAR(50) NOT NULL,
	"STARTDATE" LONGDATE CS_LONGDATE NOT NULL,
	"PERIODSEQ" BIGINT CS_FIXED NOT NULL,
	"NIF" VARCHAR(255),
	"NAME" VARCHAR(90),
	"VALUE" DECIMAL(25, 10) CS_FIXED,
	"C_GN5" DECIMAL(25, 10) CS_FIXED,
	"SALESTRANSACTIONSEQ" VARCHAR(127),
	"POLIZA" VARCHAR(255),
	"PRODUCTID" VARCHAR(127),
	"ACCOUNTINGDATE" LONGDATE CS_LONGDATE,
	"ST_GD2" LONGDATE CS_LONGDATE,
	"EVENTO" VARCHAR(255),
	"PRODUCTO" VARCHAR(127),
	"POSITIONSEQ_PRIN" BIGINT CS_FIXED,
	"POSITIONSEQ" BIGINT CS_FIXED,
	"PARTICIPANTSEQ" BIGINT CS_FIXED,
	"POS_PRIN" VARCHAR(127),
	"POS_CALLIDUS" VARCHAR(127),
	"POSITIONNAME" VARCHAR(127),
	"POLIZ_CORR" DECIMAL(25, 10) CS_FIXED,
	"PRIMA_NETA" DECIMAL(25, 10) CS_FIXED,
	"C_GA4" VARCHAR(240)
)
UNLOAD PRIORITY 5 AUTO MERGE;
ALTER TABLE "EXT"."OUT_PROD_INSPECTORES_REP" WITH PARAMETERS ('CONCAT_ATTRIBUTE'=('$PERIODSEQ$NIF$','PERIODSEQ','NIF'));
CREATE CPBTREE INDEX "OUT_PROD_INSPECTORES_REP_IDX1" ON "EXT"."OUT_PROD_INSPECTORES_REP" ( "PERIODSEQ" ASC, "NIF" ASC );
