CREATE COLUMN TABLE "EXT"."OUT_PROD_AGENTES_REP"(
	"YEAR" VARCHAR(50),
	"QUARTER" VARCHAR(50),
	"PERIODO" VARCHAR(50) NOT NULL,
	"STARTDATE" LONGDATE CS_LONGDATE NOT NULL,
	"PERIODSEQ" BIGINT CS_FIXED NOT NULL,
	"NIF" VARCHAR(255),
	"NAME" VARCHAR(90),
	"VALUE" DECIMAL(25, 10) CS_FIXED,
	"C_GN4" DECIMAL(25, 10) CS_FIXED,
	"SALESTRANSACTIONSEQ" VARCHAR(127),
	"POLIZA" VARCHAR(255),
	"PRODUCTID" VARCHAR(127),
	"ACCOUNTINGDATE" LONGDATE CS_LONGDATE,
	"ST_GD2" LONGDATE CS_LONGDATE,
	"EVENTO" VARCHAR(255),
	"PRODUCTO" VARCHAR(127),
	"POSITIONSEQ_PRIN" BIGINT CS_FIXED,
	"POSITIONSEQ" BIGINT CS_FIXED,
	"PARTICIPANTSEQ" BIGINT CS_FIXED,
	"POS_PRIN" VARCHAR(127),
	"POS_CALLIDUS" VARCHAR(127),
	"POSITIONNAME" VARCHAR(127),
	"ID_TIPO_AGENTE" DECIMAL(25, 10) CS_FIXED,
	"TIPO_AGENTE" VARCHAR(255),
	"PRIMA_NETA" DECIMAL(25, 10) CS_FIXED,
	"COMPANIA" VARCHAR(10)
)
UNLOAD PRIORITY 5 AUTO MERGE;
ALTER TABLE "EXT"."OUT_PROD_AGENTES_REP" WITH PARAMETERS ('CONCAT_ATTRIBUTE'=('$PERIODSEQ$PARTICIPANTSEQ$POSITIONSEQ_PRIN$','PERIODSEQ','PARTICIPANTSEQ','POSITIONSEQ_PRIN'));
ALTER TABLE "EXT"."OUT_PROD_AGENTES_REP" WITH PARAMETERS ('CONCAT_ATTRIBUTE'=('$PARTICIPANTSEQ$POSITIONSEQ_PRIN$','PARTICIPANTSEQ','POSITIONSEQ_PRIN'));
CREATE CPBTREE INDEX "OUT_PROD_AGENTES_REP_IDX1" ON "EXT"."OUT_PROD_AGENTES_REP" ( "PERIODSEQ" ASC, "PARTICIPANTSEQ" ASC, "POSITIONSEQ_PRIN" ASC );
CREATE CPBTREE INDEX "OUT_PROD_AGENTES_REP_IDX2" ON "EXT"."OUT_PROD_AGENTES_REP" ( "PARTICIPANTSEQ" ASC, "POSITIONSEQ_PRIN" ASC );
