CREATE COLUMN TABLE "EXT"."OUT_BAL_ASI_E_DETALLE_REP"(
	"ESCALADO" VARCHAR(255),
	"NIF" VARCHAR(255),
	"TIPO_AGENTE" VARCHAR(255),
	"ID_TIPO_AGENTE" DECIMAL(25, 10) CS_FIXED,
	"POS_PRIN" VARCHAR(127),
	"LASTNAME_AG" VARCHAR(90),
	"MIDDLENAME_AG" VARCHAR(90),
	"FIRSTNAME_AG" VARCHAR(90),
	"POSITIONNAME_AG" VARCHAR(127),
	"PRODUCTO" VARCHAR(127),
	"TIPO_CREDITO" VARCHAR(255),
	"EVENTO" VARCHAR(255),
	"PRODUCTID" VARCHAR(127),
	"ST_GA1" VARCHAR(255),
	"KM" DECIMAL(25, 10) CS_FIXED,
	"VALUE" DECIMAL(25, 10) CS_FIXED,
	"NAME" VARCHAR(90),
	"LASTNAME" VARCHAR(90),
	"MIDDLENAME" VARCHAR(90),
	"FIRSTNAME" VARCHAR(90),
	"BOUSERID" VARCHAR(260),
	"PERIODO" VARCHAR(50) NOT NULL,
	"PERIODSEQ" BIGINT CS_FIXED NOT NULL,
	"POSITIONSEQ_PRIN" BIGINT CS_FIXED,
	"PARTICIPANTSEQ" BIGINT CS_FIXED
)
UNLOAD PRIORITY 5 AUTO MERGE;
ALTER TABLE "EXT"."OUT_BAL_ASI_E_DETALLE_REP" WITH PARAMETERS ('CONCAT_ATTRIBUTE'=('$PERIODSEQ$PARTICIPANTSEQ$POSITIONSEQ_PRIN$','PERIODSEQ','PARTICIPANTSEQ','POSITIONSEQ_PRIN'));
