CREATE COLUMN TABLE "EXT"."OUT_LC_S4_E_POLIZAS_REP"(
	"ASEGURADOS" DECIMAL(25, 10) CS_FIXED,
	"SUPERRAPEL" SMALLINT CS_INT,
	"TIPO_AGENTE" VARCHAR(255),
	"ID_TIPO_AGENTE" DECIMAL(25, 10) CS_FIXED,
	"PRIMA_NETA" DECIMAL(25, 10) CS_FIXED,
	"FEC_VTO_REC" LONGDATE CS_LONGDATE,
	"PRODUCTO" VARCHAR(127),
	"EVENTO" VARCHAR(255),
	"PRIMA_COMIS" DECIMAL(25, 10) CS_FIXED,
	"FEC_CARGO" LONGDATE CS_LONGDATE,
	"PRODUCTID" VARCHAR(127),
	"POLIZA" VARCHAR(255),
	"SALESTRANSACTIONSEQ" VARCHAR(127),
	"POLIZ_NP" DECIMAL(25, 10) CS_FIXED,
	"POLIZ_CORR" DECIMAL(25, 10) CS_FIXED,
	"VALUE" DECIMAL(25, 10) CS_FIXED,
	"NAME" VARCHAR(90),
	"OFICINA" VARCHAR(90),
	"COD_OFICINA" VARCHAR(127),
	"COMPANIA" VARCHAR(2),
	"CUADRO_RRTT" VARCHAR(255),
	"CUADRO_RRGG" VARCHAR(255),
	"POS_PRIN" VARCHAR(127),
	"NOMBRE" VARCHAR(255),
	"NIF" VARCHAR(255),
	"POSITIONNAME" VARCHAR(127),
	"BOUSERID" VARCHAR(260),
	"PERIODO" VARCHAR(50) NOT NULL,
	"PERIODSEQ" BIGINT CS_FIXED NOT NULL,
	"POSITIONSEQ_PRIN" BIGINT CS_FIXED,
	"PARTICIPANTSEQ" BIGINT CS_FIXED
)
UNLOAD PRIORITY 5 AUTO MERGE;
ALTER TABLE "EXT"."OUT_LC_S4_E_POLIZAS_REP" WITH PARAMETERS ('CONCAT_ATTRIBUTE'=('$PERIODSEQ$PARTICIPANTSEQ$POSITIONSEQ_PRIN$','PERIODSEQ','PARTICIPANTSEQ','POSITIONSEQ_PRIN'));
ALTER TABLE "EXT"."OUT_LC_S4_E_POLIZAS_REP" WITH PARAMETERS ('CONCAT_ATTRIBUTE'=('$PERIODO$POS_PRIN$','PERIODO','POS_PRIN'));
CREATE CPBTREE INDEX "OUT_LC_S4_E_POLIZAS_REP_IDX1" ON "EXT"."OUT_LC_S4_E_POLIZAS_REP" ( "PERIODSEQ" ASC, "PARTICIPANTSEQ" ASC, "POSITIONSEQ_PRIN" ASC );
CREATE CPBTREE INDEX "OUT_LC_S4_E_POLIZAS_REP_IDX2" ON "EXT"."OUT_LC_S4_E_POLIZAS_REP" ( "PERIODO" ASC, "POS_PRIN" ASC );
