CREATE COLUMN TABLE "EXT"."OUT_ASI_RESUMEN_REP"(
	"POS_PRIN" VARCHAR(127),
	"POSITIONNAME" VARCHAR(127),
	"LASTNAME" VARCHAR(90),
	"MIDDLENAME" VARCHAR(90),
	"FIRSTNAME" VARCHAR(90),
	"BOUSERID" VARCHAR(260),
	"V_MEDIDA" DECIMAL(25, 10) CS_FIXED,
	"N_MEDIDA" VARCHAR(90),
	"STARTDATE" LONGDATE CS_LONGDATE NOT NULL,
	"YEAR" VARCHAR(50) NOT NULL,
	"QUARTER" VARCHAR(50) NOT NULL,
	"PERIODO" VARCHAR(50) NOT NULL,
	"PERIODSEQ" BIGINT CS_FIXED NOT NULL,
	"POSITIONSEQ_PRIN" BIGINT CS_FIXED,
	"PARTICIPANTSEQ" BIGINT CS_FIXED,
	"GA1_MEDIDA" VARCHAR(255),
	"GN1_MEDIDA" DECIMAL(25, 10) CS_FIXED,
	"ESCALADO" VARCHAR(255),
	"NIF" VARCHAR(255),
	"TIPO_AGENTE" VARCHAR(255),
	"ID_TIPO_AGENTE" DECIMAL(25, 10) CS_FIXED
)
UNLOAD PRIORITY 5 AUTO MERGE;
ALTER TABLE "EXT"."OUT_ASI_RESUMEN_REP" WITH PARAMETERS ('CONCAT_ATTRIBUTE'=('$PERIODSEQ$PARTICIPANTSEQ$POSITIONSEQ_PRIN$','PERIODSEQ','PARTICIPANTSEQ','POSITIONSEQ_PRIN'));
