CREATE COLUMN TABLE "EXT"."PRESTAGE_HISTASEGURADOS"(
	"CODIGO_POLIZA" VARCHAR(255),
	"NUMERO_ASEGURADO" VARCHAR(255),
	"NIF" VARCHAR(255),
	"FECHA_NACIMIENTO" VARCHAR(255),
	"FECHA_DE_DERECHOS" VARCHAR(255),
	"MOTIVO_ALTA" VARCHAR(255),
	"CONTO_COMO_ALTA" VARCHAR(255),
	"CONTO_COMO_NUEVO" VARCHAR(255),
	"FECHA_ALTA" VARCHAR(255),
	"MOTIVO_BAJA" VARCHAR(255),
	"FECHA_BAJA" VARCHAR(255),
	"FECHA_REHABILITACION" VARCHAR(255),
	"POLIZA_ORIGEN" VARCHAR(255),
	"ASEGURADO_ORIGEN" VARCHAR(255),
	"EDAD" VARCHAR(255),
	"EDAD_DERECHOS" VARCHAR(255),
	"FILE_NAME" VARCHAR(255)
)
UNLOAD PRIORITY 5 AUTO MERGE;
