CREATE COLUMN TABLE "EXT"."PRESTAGE_REAJ_ETERNA"(
	"CODIGO_POLIZA" VARCHAR(255),
	"NUMERO_ASEGURADO" VARCHAR(255),
	"PRODUCTO_CONTABLE" VARCHAR(255),
	"PRIMA_NETA_ASEGURADO" VARCHAR(255),
	"CAPITAL_NATURAL" VARCHAR(255),
	"CAPITAL_NIVELADO" VARCHAR(255),
	"FECHA_BAJA_GAR_ASE" VARCHAR(255),
	"FECHA_EFECTO_SUPLEMENTO" VARCHAR(255),
	"NUM_ORDEN_MOVIMIENTO" VARCHAR(255)
)
UNLOAD PRIORITY 5 AUTO MERGE;
