CREATE COLUMN TABLE "EXT"."STAGE_REAJUSTES"(
	"IDENTIFICADOR" BIGINT CS_FIXED GENERATED ALWAYS AS IDENTITY,
	"FILE_NAME" VARCHAR(255),
	"ESTADO" INTEGER CS_INT,
	"FECHA_MODIFICACION" LONGDATE CS_LONGDATE,
	"CODIGO_POLIZA" VARCHAR(255),
	"NUMERO_ASEGURADO" VARCHAR(255),
	"PRODUCTO_CONTABLE" VARCHAR(255),
	"PRIMA_NETA_ASEGURADO" VARCHAR(255),
	"CAPITAL_NATURAL" VARCHAR(255),
	"CAPITAL_NIVELADO" VARCHAR(255),
	"FECHA_BAJA_GAR_ASE" DATE CS_DAYDATE,
	"FECHA_EFECTO_SUPLEMENTO" DATE CS_DAYDATE,
	"NUM_ORDEN_MOVIMIENTO" INTEGER CS_INT
)
UNLOAD PRIORITY 5 AUTO MERGE;
ALTER TABLE "EXT"."STAGE_REAJUSTES" WITH PARAMETERS ('CONCAT_ATTRIBUTE'=('$CODIGO_POLIZA$FILE_NAME$','CODIGO_POLIZA','FILE_NAME'));
ALTER TABLE "EXT"."STAGE_REAJUSTES" WITH PARAMETERS ('CONCAT_ATTRIBUTE'=('$CODIGO_POLIZA$NUMERO_ASEGURADO$PRODUCTO_CONTABLE$NUM_ORDEN_MOVIMIENTO$','CODIGO_POLIZA','NUMERO_ASEGURADO','PRODUCTO_CONTABLE','NUM_ORDEN_MOVIMIENTO'));
CREATE CPBTREE INDEX "STAGE_REAJUSTES_IDX1" ON "EXT"."STAGE_REAJUSTES" ( "CODIGO_POLIZA" ASC, "FILE_NAME" ASC );
CREATE CPBTREE INDEX "STAGE_REAJUSTES_IDX2" ON "EXT"."STAGE_REAJUSTES" ( "CODIGO_POLIZA" ASC, "NUMERO_ASEGURADO" ASC, "PRODUCTO_CONTABLE" ASC, "NUM_ORDEN_MOVIMIENTO" ASC );
