CREATE COLUMN TABLE "EXT"."TEMP_CARTERA_DDEE_NOMEXT_FILE"(
	"IMPORTE" BIGINT CS_FIXED,
	"SEQ_POST" BIGINT CS_FIXED,
	"EARNINGGROUPID" VARCHAR(255),
	"EARNINGCODEID" VARCHAR(255),
	"COMPENSATIONDATE" LONGDATE CS_LONGDATE NOT NULL,
	"POSITIONNAME" VARCHAR(127),
	CONSTRAINT "SYS_C0036399" CHECK ("COMPENSATIONDATE" IS NOT NULL)
)
UNLOAD PRIORITY 5 AUTO MERGE;
CREATE CPBTREE INDEX "TEMP_CARTERA_DDEE_NOMEXT_FILE_IDX1" ON "EXT"."TEMP_CARTERA_DDEE_NOMEXT_FILE" ( "POSITIONNAME" ASC );
