CREATE COLUMN TABLE "EXT"."TEMP_LIQEXT_IMP_COMISION_FILE"(
	"VALUE" DECIMAL(25, 10) CS_FIXED NOT NULL,
	"PERIODSEQ" BIGINT CS_FIXED NOT NULL,
	"POSITIONSEQ" BIGINT CS_FIXED NOT NULL,
	"PAYEESEQ" BIGINT CS_FIXED NOT NULL,
	"SALESTRANSACTIONSEQ" BIGINT CS_FIXED,
	"TENANTID" VARCHAR(4) NOT NULL,
	CONSTRAINT "SYS_C0032311" CHECK ("TENANTID" IS NOT NULL),
	CONSTRAINT "SYS_C0032312" CHECK ("PAYEESEQ" IS NOT NULL),
	CONSTRAINT "SYS_C0032313" CHECK ("POSITIONSEQ" IS NOT NULL),
	CONSTRAINT "SYS_C0032314" CHECK ("PERIODSEQ" IS NOT NULL),
	CONSTRAINT "SYS_C0032315" CHECK ("VALUE" IS NOT NULL)
)
UNLOAD PRIORITY 5 AUTO MERGE;
CREATE CPBTREE INDEX "TEMP_LIQEXT_IMP_COMISION_FILE_IDX1" ON "EXT"."TEMP_LIQEXT_IMP_COMISION_FILE" ( "SALESTRANSACTIONSEQ" ASC );
