CREATE COLUMN TABLE "EXT"."TEMP_LIQEXT_DET_PADIMENSION_FILE"(
	"TENANTID" VARCHAR(4) NOT NULL,
	"PARTICIPANTSEQ" BIGINT CS_FIXED NOT NULL,
	"POSITIONSEQ" BIGINT CS_FIXED NOT NULL,
	"PERIODSEQ" BIGINT CS_FIXED NOT NULL,
	"POSITIONNAME" VARCHAR(127),
	"PARTICIPANTID" VARCHAR(40),
	"ISPAYEE" SMALLINT CS_INT,
	"POSITIONGENERICATTRIBUTE3" VARCHAR(255),
	"POSITIONGENERICNUMBER2" DECIMAL(25, 10) CS_FIXED
)
UNLOAD PRIORITY 5 AUTO MERGE;
ALTER TABLE "EXT"."TEMP_LIQEXT_DET_PADIMENSION_FILE" WITH PARAMETERS ('CONCAT_ATTRIBUTE'=('$PARTICIPANTSEQ$POSITIONSEQ$','PARTICIPANTSEQ','POSITIONSEQ'));
CREATE CPBTREE INDEX "TEMP_LIQEXT_DET_PADIMENSION_FILE_IDX1" ON "EXT"."TEMP_LIQEXT_DET_PADIMENSION_FILE" ( "PARTICIPANTSEQ" ASC, "POSITIONSEQ" ASC );
CREATE CPBTREE INDEX "TEMP_LIQEXT_DET_PADIMENSION_FILE_IDX2" ON "EXT"."TEMP_LIQEXT_DET_PADIMENSION_FILE" ( "POSITIONNAME" ASC );
