CREATE COLUMN TABLE "EXT"."TEMP_LIQEXT_TXN_FILE_TEST"(
	"PRODUCTID" VARCHAR(127),
	"TIPO_RECIBO" VARCHAR(3),
	"TIPO_RECUPERACION" VARCHAR(255),
	"IND_PRIMA_UNICA" SMALLINT CS_INT,
	"FORMA_PAGO" VARCHAR(255),
	"UNIDAD_POLIZA" DECIMAL(25, 10) CS_FIXED,
	"PRIMA_COMISIONABLE" DECIMAL(25, 10) CS_FIXED NOT NULL,
	"INC_PRIMA" DECIMAL(25, 10) CS_FIXED,
	"PRIMA_NETA" DECIMAL(25, 10) CS_FIXED,
	"COD_SUPLEMENTO" VARCHAR(255),
	"COD_POLIZA" VARCHAR(255),
	"COD_PRODUCTO" VARCHAR(127),
	"ACCOUNTINGDATE" LONGDATE CS_LONGDATE,
	"COMPENSATIONDATE" LONGDATE CS_LONGDATE NOT NULL,
	"EVENTTYPESEQ" BIGINT CS_FIXED NOT NULL,
	"SUBLINENUMBER" BIGINT CS_FIXED NOT NULL,
	"LINENUMBER" BIGINT CS_FIXED NOT NULL,
	"SALESTRANSACTIONSEQ" BIGINT CS_FIXED NOT NULL,
	"SALESORDERSEQ" BIGINT CS_FIXED NOT NULL,
	"PERIODSEQ" BIGINT CS_FIXED NOT NULL,
	"TENANTID" VARCHAR(4)
)
UNLOAD PRIORITY 5 AUTO MERGE;
