CREATE COLUMN TABLE "EXT"."TEMP_REPEXT_CREDITOS_FILE"(
	"GENERICNUMBER5" DECIMAL(25, 10) CS_FIXED,
	"GENERICNUMBER4" DECIMAL(25, 10) CS_FIXED,
	"VALUE" DECIMAL(25, 10) CS_FIXED NOT NULL,
	"NAME" VARCHAR(100),
	"PERIODSEQ" BIGINT CS_FIXED NOT NULL,
	"POSITIONSEQ" BIGINT CS_FIXED NOT NULL,
	"PAYEESEQ" BIGINT CS_FIXED NOT NULL,
	"SALESTRANSACTIONSEQ" BIGINT CS_FIXED,
	"CREDITSEQ" BIGINT CS_FIXED NOT NULL,
	"GENERICBOOLEAN3" SMALLINT CS_INT,
	CONSTRAINT "SYS_C0034640" CHECK ("CREDITSEQ" IS NOT NULL),
	CONSTRAINT "SYS_C0034641" CHECK ("PAYEESEQ" IS NOT NULL),
	CONSTRAINT "SYS_C0034642" CHECK ("POSITIONSEQ" IS NOT NULL),
	CONSTRAINT "SYS_C0034643" CHECK ("PERIODSEQ" IS NOT NULL),
	CONSTRAINT "SYS_C0034644" CHECK ("VALUE" IS NOT NULL)
)
UNLOAD PRIORITY 5 AUTO MERGE;
