CREATE COLUMN TABLE "EXT"."TEMP_LIQEXT_PERCEPCIONES_FILE_TEST"(
	"PROGRAMA" NVARCHAR(255),
	"DEPOSITO" NVARCHAR(255),
	"GRUPOPAGO" NVARCHAR(255),
	"CONCEPTOPAGO" NVARCHAR(255),
	"TIPOPERCEPCION" NVARCHAR(255)
)
UNLOAD PRIORITY 5 AUTO MERGE;
