CREATE COLUMN TABLE "EXT"."TEMP_CARTERA_DDEE_PAGEXT_FILE_TEST"(
	"POSITIONNAME" VARCHAR(127),
	"COMPENSATIONDATE" LONGDATE CS_LONGDATE NOT NULL,
	"EARNINGGROUPID" VARCHAR(255),
	"SEQ_POST" BIGINT CS_FIXED,
	"IMPORTE" DECIMAL(18, 2) CS_FIXED
)
UNLOAD PRIORITY 5 AUTO MERGE;
