CREATE COLUMN TABLE "EXT"."TEMP_COMEXT_FILE"(
	"PIPELINERUNDATE" LONGDATE CS_LONGDATE,
	"GENERICATTRIBUTE14" VARCHAR(255),
	"GENERICATTRIBUTE13" VARCHAR(255),
	"DISCOUNTPERCENT" DECIMAL(25, 10) CS_FIXED,
	"NATIVECURRENCYAMOUNT" DECIMAL(25, 10) CS_FIXED,
	"VALUE" DECIMAL(25, 10) CS_FIXED,
	"GENERICBOOLEAN2" SMALLINT CS_INT,
	"GENERICNUMBER6" DECIMAL(25, 10) CS_FIXED,
	"GENERICATTRIBUTE8" VARCHAR(255),
	"GENERICNUMBER3" DECIMAL(25, 10) CS_FIXED,
	"GENERICDATE2" LONGDATE CS_LONGDATE,
	"CREDITTYPEID" VARCHAR(40),
	"EVENTTYPEID" VARCHAR(40) NOT NULL,
	"SUBLINENUMBER" DECIMAL(38) CS_FIXED NOT NULL,
	"LINENUMBER" BIGINT CS_FIXED NOT NULL,
	"ORDERID" VARCHAR(40) NOT NULL,
	CONSTRAINT "SYS_C0032165" CHECK ("ORDERID" IS NOT NULL),
	CONSTRAINT "SYS_C0032166" CHECK ("LINENUMBER" IS NOT NULL),
	CONSTRAINT "SYS_C0032167" CHECK ("SUBLINENUMBER" IS NOT NULL),
	CONSTRAINT "SYS_C0032168" CHECK ("EVENTTYPEID" IS NOT NULL)
)
UNLOAD PRIORITY 5 AUTO MERGE;
