CREATE COLUMN TABLE "EXT"."TEMP_LIQEXT_CAB_CREDIMED_FILE"(
	"POLIZAS" DECIMAL(25, 10) CS_FIXED,
	"PRODUCTO" VARCHAR(255),
	"SALESTRANSACTIONSEQ" BIGINT CS_FIXED,
	"IMPORTE" DECIMAL(25, 10) CS_FIXED,
	"CREDITNAME" VARCHAR(90),
	"CREDITSEQ" BIGINT CS_FIXED NOT NULL,
	"PMVALUE" DECIMAL(25, 10) CS_FIXED,
	"PMNAME" VARCHAR(90),
	"PMSEQ" BIGINT CS_FIXED NOT NULL,
	"SMVALUE" DECIMAL(25, 10) CS_FIXED,
	"SMNAME" VARCHAR(90),
	"SMSEQ" BIGINT CS_FIXED NOT NULL,
	"PERIODSEQ" BIGINT CS_FIXED NOT NULL,
	"TENANTID" VARCHAR(4) NOT NULL
)
UNLOAD PRIORITY 5 AUTO MERGE;
CREATE CPBTREE INDEX "TEMP_LIQEXT_CAB_CREDIMED_FILE_IDX1" ON "EXT"."TEMP_LIQEXT_CAB_CREDIMED_FILE" ( "SALESTRANSACTIONSEQ" ASC );
CREATE CPBTREE INDEX "TEMP_LIQEXT_CAB_CREDIMED_FILE_IDX2" ON "EXT"."TEMP_LIQEXT_CAB_CREDIMED_FILE" ( "SMSEQ" ASC );
