CREATE COLUMN TABLE "EXT"."TEMP_LIQEXT_PERCEPCIONES_FILE"(
	"PROGRAMA" VARCHAR(255),
	"DEPOSITO" VARCHAR(255),
	"GRUPOPAGO" VARCHAR(255),
	"CONCEPTOPAGO" VARCHAR(255),
	"TIPOPERCEPCION" VARCHAR(255)
)
UNLOAD PRIORITY 5 AUTO MERGE;
