CREATE COLUMN TABLE "EXT"."TEMP_LIQEXT_CAB_CREDIMED_FILE_TEST"(
	"POLIZAS" DECIMAL(25, 10) CS_FIXED,
	"PRODUCTO" VARCHAR(255),
	"SALESTRANSACTIONSEQ" BIGINT CS_FIXED,
	"IMPORTE" DECIMAL(25, 10) CS_FIXED NOT NULL,
	"CREDITNAME" VARCHAR(90),
	"CREDITSEQ" BIGINT CS_FIXED NOT NULL,
	"PMVALUE" DECIMAL(25, 10) CS_FIXED NOT NULL,
	"PMNAME" VARCHAR(90) NOT NULL,
	"PMSEQ" BIGINT CS_FIXED NOT NULL,
	"SMVALUE" DECIMAL(25, 10) CS_FIXED NOT NULL,
	"SMNAME" VARCHAR(90) NOT NULL,
	"SMSEQ" BIGINT CS_FIXED NOT NULL,
	"PERIODSEQ" BIGINT CS_FIXED NOT NULL,
	"TENANTID" VARCHAR(4)
)
UNLOAD PRIORITY 5 AUTO MERGE;
