CREATE COLUMN TABLE "EXT"."TEMP_LIQEXT_CABECERA_FILE_TEST"(
	"SEL" VARCHAR(10) NOT NULL,
	"POLIZAS" DECIMAL(25, 10) CS_FIXED,
	"DOC_NIF" VARCHAR(12),
	"PROGRAMA" VARCHAR(9),
	"IMPORTE" DECIMAL(25, 10) CS_FIXED,
	"PRODUCTO" VARCHAR(6),
	"COD_CONCEPTO" VARCHAR(256) NOT NULL,
	"POSICION_COMERCIAL" VARCHAR(128),
	"FECHA" LONGDATE CS_LONGDATE,
	"TIPODOCUMENTO" VARCHAR(2) NOT NULL,
	"COMPANIA" VARCHAR(3) NOT NULL,
	"EARNINGGROUPID" VARCHAR(256),
	"DEPOSITO" VARCHAR(91),
	"DEPOSITSEQ" BIGINT CS_FIXED
)
UNLOAD PRIORITY 5 AUTO MERGE;
