CREATE COLUMN TABLE "EXT"."TEMP_LIQEXT_COMMISSION_FILE"(
	"IMP_LOCOMOCION" DECIMAL(25, 10) CS_FIXED,
	"COEF_LOCOMOCION" DECIMAL(25, 10) CS_FIXED,
	"IMP_DIFERENCIAL" DECIMAL(25, 10) CS_FIXED,
	"COEF_DIFERENCIAL" DECIMAL(25, 10) CS_FIXED,
	"PERIODSEQ" BIGINT CS_FIXED NOT NULL,
	"POSITIONSEQ" BIGINT CS_FIXED,
	"CREDITSEQ" BIGINT CS_FIXED,
	"TENANTID" VARCHAR(4) NOT NULL,
	CONSTRAINT "SYS_C0032243" CHECK ("TENANTID" IS NOT NULL),
	CONSTRAINT "SYS_C0032244" CHECK ("PERIODSEQ" IS NOT NULL)
)
UNLOAD PRIORITY 5 AUTO MERGE;
CREATE CPBTREE INDEX "TEMP_LIQEXT_COMMISSION_FILE_IDX1" ON "EXT"."TEMP_LIQEXT_COMMISSION_FILE" ( "CREDITSEQ" ASC );
