CREATE COLUMN TABLE "EXT"."TEMP_REPEXT_TXN_FILE_BKP"(
	"LINENUMBER" BIGINT CS_FIXED NOT NULL,
	"ORDERID" VARCHAR(40) NOT NULL,
	"SALESTRANSACTIONSEQ" BIGINT CS_FIXED NOT NULL,
	"AUTOLIQUIDA" SMALLINT CS_INT,
	"FECHA_VTO_RECIBO" LONGDATE CS_LONGDATE,
	"FECHA_EMISION" LONGDATE CS_LONGDATE,
	"FECHA_EFECTO" LONGDATE CS_LONGDATE,
	"SUPLEMENTO" VARCHAR(255),
	"INCR_PRIMA" DECIMAL(25, 10) CS_FIXED,
	"PRIMA_NETA" DECIMAL(25, 10) CS_FIXED,
	"ESTADO" VARCHAR(255),
	"POLIZA" VARCHAR(255),
	"VALUE" DECIMAL(25, 10) CS_FIXED NOT NULL,
	"PRODUCTID" VARCHAR(127),
	"POS_PRIN" VARCHAR(255),
	"POSITIONNAME" VARCHAR(127),
	"COMPENSATIONDATE" LONGDATE CS_LONGDATE NOT NULL,
	"EVENTTYPEID" VARCHAR(40) NOT NULL,
	"SUBLINENUMBER" DECIMAL(38) CS_FIXED NOT NULL
)
UNLOAD PRIORITY 5 AUTO MERGE;
