CREATE COLUMN TABLE "EXT"."TEMP_REPEXT_PERCEPCIONES_FILE"(
	"TIPO_PAGO" VARCHAR(255),
	"PROGRAMA" VARCHAR(255),
	"DEPOSITO" VARCHAR(255),
	"GRUPO_PAGO" VARCHAR(255),
	"CONCEPTO_PAGO" VARCHAR(255),
	"TIPO_PERCEPCION" VARCHAR(255)
)
UNLOAD PRIORITY 5 AUTO MERGE;
