CREATE COLUMN TABLE "EXT"."TEMP_COMEXT_TXN_FILE"(
	"PIPELINERUNSEQ" BIGINT CS_FIXED NOT NULL,
	"GENERICDATE1" LONGDATE CS_LONGDATE,
	"GENERICATTRIBUTE14" VARCHAR(255),
	"GENERICATTRIBUTE13" VARCHAR(255),
	"DISCOUNTPERCENT" DECIMAL(25, 10) CS_FIXED,
	"NATIVECURRENCYAMOUNT" DECIMAL(25, 10) CS_FIXED,
	"COMPENSATIONDATE" LONGDATE CS_LONGDATE NOT NULL,
	"EVENTTYPESEQ" BIGINT CS_FIXED NOT NULL,
	"SUBLINENUMBER" DECIMAL(38) CS_FIXED NOT NULL,
	"LINENUMBER" BIGINT CS_FIXED NOT NULL,
	"SALESTRANSACTIONSEQ" BIGINT CS_FIXED,
	"SALESORDERSEQ" BIGINT CS_FIXED NOT NULL,
	"TENANTID" VARCHAR(4) NOT NULL,
	CONSTRAINT "SYS_C0032177" CHECK ("TENANTID" IS NOT NULL),
	CONSTRAINT "SYS_C0032178" CHECK ("SALESORDERSEQ" IS NOT NULL),
	CONSTRAINT "SYS_C0032179" CHECK ("LINENUMBER" IS NOT NULL),
	CONSTRAINT "SYS_C0032180" CHECK ("SUBLINENUMBER" IS NOT NULL),
	CONSTRAINT "SYS_C0032181" CHECK ("EVENTTYPESEQ" IS NOT NULL),
	CONSTRAINT "SYS_C0032182" CHECK ("COMPENSATIONDATE" IS NOT NULL),
	CONSTRAINT "SYS_C0032183" CHECK ("PIPELINERUNSEQ" IS NOT NULL)
)
UNLOAD PRIORITY 5 AUTO MERGE;
CREATE CPBTREE INDEX "TEMP_COMEXT_TXN_FILE_IDX1" ON "EXT"."TEMP_COMEXT_TXN_FILE" ( "SALESORDERSEQ" ASC );
