CREATE COLUMN TABLE "EXT"."TEMP_LIQEXT_CAB_DEPOSITOS_FILE"(
	"DOC_NIF" VARCHAR(11),
	"PROGRAMA" VARCHAR(8),
	"IMPORTE_TOTAL" DECIMAL(25, 10) CS_FIXED NOT NULL,
	"COD_CONCEPTO" VARCHAR(255) NOT NULL,
	"POSICION_COMERCIAL" VARCHAR(127),
	"FECHA" LONGDATE CS_LONGDATE,
	"TIPODOCUMENTO" VARCHAR(1) NOT NULL,
	"COMPANIA" VARCHAR(2) NOT NULL,
	"EARNINGGROUPID" VARCHAR(255) NOT NULL,
	"DEPOSITO" VARCHAR(90) NOT NULL,
	"PAYEESEQ" BIGINT CS_FIXED,
	"POSITIONSEQ" BIGINT CS_FIXED,
	"MEASUREMENTSEQ" BIGINT CS_FIXED,
	"INCENTIVESEQ" BIGINT CS_FIXED,
	"DEPOSITSEQ" BIGINT CS_FIXED NOT NULL,
	"PERIODSEQ" BIGINT CS_FIXED NOT NULL,
	"TENANTID" VARCHAR(4) NOT NULL,
	"PRODUCTID" VARCHAR(127)
)
UNLOAD PRIORITY 5 AUTO MERGE;
