CREATE COLUMN TABLE "EXT"."TEMP_LIQEXT_CREDIT_FILE"(
	"CREDITTYPEID" VARCHAR(40),
	"COEF_CORRECTOR" DECIMAL(25, 10) CS_FIXED,
	"GENERICNUMBER4" DECIMAL(25, 10) CS_FIXED,
	"POSITION" VARCHAR(255),
	"PRIMA_CORREGIDA" DECIMAL(25, 10) CS_FIXED,
	"POSITIONSEQ" BIGINT CS_FIXED,
	"PAYEESEQ" BIGINT CS_FIXED,
	"CREDITTYPESEQ" BIGINT CS_FIXED,
	"PERIODSEQ" BIGINT CS_FIXED NOT NULL,
	"SALESTRANSACTIONSEQ" BIGINT CS_FIXED,
	"SALESORDERSEQ" BIGINT CS_FIXED NOT NULL,
	"CREDITSEQ" BIGINT CS_FIXED NOT NULL,
	"TENANTID" VARCHAR(4) NOT NULL,
	CONSTRAINT "SYS_C0032245" CHECK ("TENANTID" IS NOT NULL),
	CONSTRAINT "SYS_C0032246" CHECK ("CREDITSEQ" IS NOT NULL),
	CONSTRAINT "SYS_C0032247" CHECK ("SALESORDERSEQ" IS NOT NULL),
	CONSTRAINT "SYS_C0032248" CHECK ("PERIODSEQ" IS NOT NULL)
)
UNLOAD PRIORITY 5 AUTO MERGE;
CREATE CPBTREE INDEX "TEMP_LIQEXT_CREDIT_FILE_IDX1" ON "EXT"."TEMP_LIQEXT_CREDIT_FILE" ( "SALESTRANSACTIONSEQ" ASC );
CREATE CPBTREE INDEX "TEMP_LIQEXT_CREDIT_FILE_IDX2" ON "EXT"."TEMP_LIQEXT_CREDIT_FILE" ( "SALESORDERSEQ" ASC );
