CREATE COLUMN TABLE "EXT"."TEMP_CUNEXT_FILE"(
	"EFFECTIVEENDDATE" LONGDATE CS_LONGDATE NOT NULL,
	"EFFECTIVESTARTDATE" LONGDATE CS_LONGDATE NOT NULL,
	"CODIGO_OCASO" VARCHAR(255),
	"CODIGO_CALLIDUS" VARCHAR(127) NOT NULL,
	CONSTRAINT "SYS_C0032211" CHECK ("CODIGO_CALLIDUS" IS NOT NULL),
	CONSTRAINT "SYS_C0032212" CHECK ("EFFECTIVESTARTDATE" IS NOT NULL),
	CONSTRAINT "SYS_C0032213" CHECK ("EFFECTIVEENDDATE" IS NOT NULL)
)
UNLOAD PRIORITY 5 AUTO MERGE;
