CREATE COLUMN TABLE "EXT"."TEMP_LIQEXT_CAB_DEPOSITOS_FILE_TEST"(
	"SEL" VARCHAR(10) NOT NULL,
	"DOC_NIF" VARCHAR(12),
	"PROGRAMA" VARCHAR(9),
	"IMPORTE_TOTAL" DECIMAL(25, 10) CS_FIXED,
	"COD_CONCEPTO" VARCHAR(256) NOT NULL,
	"POSICION_COMERCIAL" VARCHAR(128),
	"FECHA" LONGDATE CS_LONGDATE,
	"TIPODOCUMENTO" VARCHAR(2) NOT NULL,
	"COMPANIA" VARCHAR(3) NOT NULL,
	"EARNINGGROUPID" VARCHAR(256) NOT NULL,
	"DEPOSITO" VARCHAR(91) NOT NULL,
	"PAYEESEQ" BIGINT CS_FIXED,
	"POSITIONSEQ" BIGINT CS_FIXED,
	"MEASUREMENTSEQ" BIGINT CS_FIXED,
	"INCENTIVESEQ" BIGINT CS_FIXED,
	"DEPOSITSEQ" BIGINT CS_FIXED NOT NULL,
	"PERIODSEQ" BIGINT CS_FIXED NOT NULL,
	"TENANTID" VARCHAR(5) NOT NULL,
	"PRODUCTID" VARCHAR(128)
)
UNLOAD PRIORITY 5 AUTO MERGE;
