CREATE COLUMN TABLE "EXT"."WF_PAGEXT_DAC_RETEN_FILE"(
	"USUARIO_DAC" CHAR(10) CS_FIXEDSTRING,
	"ESTADO_RETENIDO" BIGINT CS_FIXED,
	"FECHA_MODIFICACION" LONGDATE CS_LONGDATE,
	"PERIODO_DESDE" CHAR(6) CS_FIXEDSTRING,
	"PAG_OFICINA" CHAR(4) CS_FIXEDSTRING,
	"PAG_AGENTE" CHAR(6) CS_FIXEDSTRING
)
UNLOAD PRIORITY 5 AUTO MERGE;
