CREATE COLUMN TABLE "EXT"."WF_PROVINCIAS_MUNICIPIOS"(
	"NOM_MUNICIPI" VARCHAR(255),
	"COD_MUNIC_PK" VARCHAR(255),
	"NOM_PROVINCI" VARCHAR(255),
	"COD_PROVI_PK" VARCHAR(255),
	"COD_PAIS_PK" VARCHAR(255)
)
UNLOAD PRIORITY 5 AUTO MERGE;
