CREATE COLUMN TABLE "EXT"."WF_REPEXT_PERIODO_CALCULO_FILE"(
	"ID_PERIODO_CALCULO" BIGINT CS_FIXED NOT NULL,
	"NOMBRE_PERIODO" CHAR(2) CS_FIXEDSTRING NOT NULL,
	"DESCRIPCION" VARCHAR(200),
	"FECHA_ALTA" LONGDATE CS_LONGDATE,
	"FECHA_BAJA" LONGDATE CS_LONGDATE,
	"EXPLICACION" VARCHAR(500),
	CONSTRAINT "SYS_C_ID_NOT_NULL" CHECK ("ID_PERIODO_CALCULO" IS NOT NULL),
	CONSTRAINT "SYS_C_NOMBRE_NOT_NULL" CHECK ("NOMBRE_PERIODO" IS NOT NULL)
)
UNLOAD PRIORITY 5 AUTO MERGE;
