CREATE COLUMN TABLE "EXT"."WF_REPEXT_TIPO_REPARTO_FILE"(
	"FECHA_BAJA" LONGDATE CS_LONGDATE,
	"FECHA_ALTA" LONGDATE CS_LONGDATE,
	"USUARIO" CHAR(10) CS_FIXEDSTRING,
	"FECHA_FIN" VARCHAR(8),
	"FECHA_INICIO" VARCHAR(8),
	"TIPO_REPARTO" CHAR(3) CS_FIXEDSTRING NOT NULL,
	"TIPO_AGENTE" CHAR(3) CS_FIXEDSTRING NOT NULL,
	"TIPO_PAGO" VARCHAR(3) NOT NULL,
	"CIA_CODIGO" CHAR(2) CS_FIXEDSTRING NOT NULL,
	"ID_TIPO_REPARTO" BIGINT CS_FIXED NOT NULL,
	CONSTRAINT "SYS_C0034762" CHECK ("ID_TIPO_REPARTO" IS NOT NULL),
	CONSTRAINT "SYS_C0034763" CHECK ("CIA_CODIGO" IS NOT NULL),
	CONSTRAINT "SYS_C0034764" CHECK ("TIPO_PAGO" IS NOT NULL),
	CONSTRAINT "SYS_C0034765" CHECK ("TIPO_AGENTE" IS NOT NULL),
	CONSTRAINT "SYS_C0034766" CHECK ("TIPO_REPARTO" IS NOT NULL)
)
UNLOAD PRIORITY 5 AUTO MERGE;
