CREATE COLUMN TABLE "EXT"."WF_REPEXT_BASE_REPARTO_FILE"(
	"ID_BASE_REPARTO" BIGINT CS_FIXED NOT NULL,
	"TIPO_BASE" VARCHAR(10) NOT NULL,
	"DESCRIPCION" VARCHAR(200),
	"FECHA_ALTA" LONGDATE CS_LONGDATE,
	"FECHA_BAJA" LONGDATE CS_LONGDATE,
	"EXPLICACION" VARCHAR(500),
	CONSTRAINT "CHK_ID_NOT_NULL" CHECK ("ID_BASE_REPARTO" IS NOT NULL),
	CONSTRAINT "CHK_TIPO_BASE_NOT_NULL" CHECK ("TIPO_BASE" IS NOT NULL)
)
UNLOAD PRIORITY 5 AUTO MERGE;
