CREATE PROCEDURE EXT.SP_COMPARAR_POLIZAS (OUT FILENAME VARCHAR(200) , IN i_fichero_entrada VARCHAR(500))
LANGUAGE SQLSCRIPT  
SQL SECURITY INVOKER 
DEFAULT SCHEMA EXT AS
/*---------------------------------------------------------------------
    | Author: Diego Teijo Barral
    | Company: Inycom
    | Initial Version Date: 26-Septiembre-2025
    |----------------------------------------------------------------------
    | Procedure Purpose: Exporta las pólizas
	|
	| Version: 0.1	DTB 20250926		Initial Version.
	|
    -----------------------------------------------------------------------
*/
BEGIN

    -- DECLARACIÓN DE NOMBRE FICHERO FINAL
    DECLARE v_file_name VARCHAR(25) := 'DEBUG_POLIZAS';
    SELECT :v_file_name || :i_fichero_entrada INTO FILENAME FROM DUMMY;
	
    TRUNCATE TABLE EXT.COMPARAR_POLIZAS_DEBUG;

    INSERT INTO EXT.COMPARAR_POLIZAS_DEBUG
        SELECT 
			IFNULL(TO_VARCHAR(CODIGO_POLIZA),'') ||';'|| IFNULL(TO_VARCHAR(RAMO),'') ||';'|| IFNULL(TO_VARCHAR(MOTIVO_ALTA),'') ||';'|| IFNULL(TO_VARCHAR(FILE_NAME),'') ||';'|| IFNULL(TO_VARCHAR(FECHA_EFECTO_POLIZA,'YYYY-MM-DD'),'') ||';'|| IFNULL(TO_VARCHAR(FECHA_EMISION_POLIZA,'YYYY-MM-DD'),'') ||';'|| IFNULL(TO_VARCHAR(FECHA_CESION_POLIZA,'YYYY-MM-DD'),'') ||';'|| IFNULL(TO_VARCHAR(MOTIVO_BAJA),'') ||';'|| IFNULL(TO_VARCHAR(FECHA_BAJA,'YYYY-MM-DD'),'') ||';'|| IFNULL(TO_VARCHAR(FECHA_VENCIMIENTO,'YYYY-MM-DD'),'') ||';'|| IFNULL(TO_VARCHAR(FECHA_REHABILITACION,'YYYY-MM-DD'),'') ||';'|| IFNULL(TO_VARCHAR(FORMA_PAGO),'') ||';'|| IFNULL(TO_VARCHAR(TIPO_CAMPANIA),'') ||';'|| IFNULL(TO_VARCHAR(SEGUNDA_RESIDENCIA),'') ||';'|| IFNULL(TO_VARCHAR(TARIFA),'') ||';'|| IFNULL(TO_VARCHAR(ZONA),'') ||';'|| IFNULL(TO_VARCHAR(CLAVE_RIESGO),'') ||';'|| IFNULL(TO_VARCHAR(MODALIDAD),'') ||';'|| IFNULL(TO_VARCHAR(DURACION),'') ||';'|| IFNULL(TO_VARCHAR(CLAUSULA),'') ||';'|| IFNULL(TO_VARCHAR(SUSTITUCION_INCENDIOS),'') ||';'|| IFNULL(TO_VARCHAR(EXCLUIDO_COMISIONES),'') ||';'|| IFNULL(TO_VARCHAR(TRASPASADA),'') ||';'|| IFNULL(TO_VARCHAR(DESCUENTO_IMPORTE_SINIESTRALID),'') ||';'|| IFNULL(TO_VARCHAR(DESCUENTO_POR_PRIORITARIO),'') ||';'|| IFNULL(TO_VARCHAR(RIESGO),'') ||';'|| IFNULL(TO_VARCHAR(COLECTIVO),'') ||';'|| IFNULL(TO_VARCHAR(AUTOLIQUIDA),'') ||';'|| IFNULL(TO_VARCHAR(KILOMETROS),'') ||';'|| IFNULL(TO_VARCHAR(MOVILIDAD),'') ||';'|| IFNULL(TO_VARCHAR(POLIZA_CON_AGENTE),'') ||';'|| IFNULL(TO_VARCHAR(AGENTE_CARTERA),'') ||';'|| IFNULL(TO_VARCHAR(IMP_COMISION_CARTERA),'') ||';'|| IFNULL(TO_VARCHAR(PORC_COMISION_CARTERA),'') ||';'|| IFNULL(TO_VARCHAR(FECHA_FIN_COMISION_CARTERA,'YYYY-MM-DD'),'')
        FROM EXT.POLIZAS WHERE FILE_NAME = :i_fichero_entrada;
END
