CREATE PROCEDURE EXT.SP_COMPARAR_GARANTIAS_RECIBOS (OUT FILENAME VARCHAR(200) , IN i_fichero_entrada VARCHAR(500))
LANGUAGE SQLSCRIPT  
SQL SECURITY INVOKER 
DEFAULT SCHEMA EXT AS
/*---------------------------------------------------------------------
    | Author: Diego Teijo Barral
    | Company: Inycom
    | Initial Version Date: 26-Septiembre-2025
    |----------------------------------------------------------------------
    | Procedure Purpose: Exporta las garantias de recibos
	|
	| Version: 0.1	DTB 20250926		Initial Version.
	|
    -----------------------------------------------------------------------
*/
BEGIN

    -- DECLARACIÓN DE NOMBRE FICHERO FINAL
    DECLARE v_file_name VARCHAR(25) := 'DEBUG_GARANTIAS_RECIBOS';
    SELECT :v_file_name || :i_fichero_entrada INTO FILENAME FROM DUMMY;
	
    TRUNCATE TABLE EXT.COMPARAR_GARANTIAS_RECIBOS_DEBUG;

    INSERT INTO EXT.COMPARAR_GARANTIAS_RECIBOS_DEBUG
        SELECT 
			IFNULL(TO_VARCHAR(CODIGO_POLIZA),'') || ';' || IFNULL(TO_VARCHAR(CODIGO_RECIBO),'') || ';' || IFNULL(TO_VARCHAR((CODIGO_SUPLEMENTO||ESTADO_RECIBO||PRODUCTO_CONTABLE)),'') || ';' || IFNULL(TO_VARCHAR(PRODUCTO_CONTABLE),'') || ';' || IFNULL(TO_VARCHAR(ESTADO_RECIBO),'') || ';' || IFNULL(TO_VARCHAR(PRIMA_NETA_RECIBO),'') || ';' || IFNULL(TO_VARCHAR(PRIMA_BRUTA_RECIBO),'') || ';' || IFNULL(TO_VARCHAR(RECARGO),'') || ';' || IFNULL(TO_VARCHAR(PORCENTAJE_BONIFICACION),'') || ';' || IFNULL(TO_VARCHAR(INCREMENTO_PRIMA_ANUAL),'') || ';' || IFNULL(TO_VARCHAR(PRIMA_COMISIONABLE),'') || ';' || IFNULL(TO_VARCHAR(UNIDAD_DE_POLIZA),'') || ';' || IFNULL(TO_VARCHAR(MESES_COBRADOS),'') || ';' || IFNULL(TO_VARCHAR(FECHA_ALTA_GAR_POL,'YYYY-MM-DD'),'') || ';' || IFNULL(TO_VARCHAR(FECHA_BAJA_GAR_POL,'YYYY-MM-DD'),'') || ';' || IFNULL(TO_VARCHAR(PORCENTAJE_NIVELADA),'') || ';' || IFNULL(TO_VARCHAR(PERIODO_EXTORNABLE),'') || ';' || IFNULL(TO_VARCHAR(INDICADOR_COMISION_CALCULADA),'') || ';' || IFNULL(TO_VARCHAR(INDICADOR_PORCENTAJE_CALCULA),'') || ';' || IFNULL(TO_VARCHAR(PORCENTAJE_COMISION_CALCULAD),'') || ';' || IFNULL(TO_VARCHAR(IMPORTE_COMISION),'') || ';' || IFNULL(TO_VARCHAR(PRIMA_UNICA),'') || ';' || IFNULL(TO_VARCHAR(NUM_ORDEN_MOVIMIENTO),'') || ';' || IFNULL(TO_VARCHAR(AUMENTO_CAPITALES_GARANTIA),'') || ';' || IFNULL(TO_VARCHAR(PRIMA_NETA_ANUALIZADA),'') || ';' || IFNULL(TO_VARCHAR(PORC_COMISION_NP),'') || ';' || IFNULL(TO_VARCHAR(PORC_COMISION_CONSERVACION),'') || ';' || IFNULL(TO_VARCHAR(CODIGO_SUPLEMENTO),'') || ';' || IFNULL(TO_VARCHAR(FILE_NAME),'') || ';' || IFNULL(TO_VARCHAR(PORC_COMISION_COBRO   ),'')
        FROM EXT.GARANTIAS_RECIBO WHERE FILE_NAME = :i_fichero_entrada;
END
