CREATE PROCEDURE EXT.SP_COMPARAR_TA (OUT FILENAME VARCHAR(250) , IN i_fichero_entrada VARCHAR(500))
LANGUAGE SQLSCRIPT  
SQL SECURITY INVOKER 
DEFAULT SCHEMA EXT AS
/*---------------------------------------------------------------------
    | Author: Diego Teijo Barral
    | Company: Inycom
    | Initial Version Date: 26-Septiembre-2025
    |----------------------------------------------------------------------
    | Procedure Purpose: Exporta las TA (ASIGNACION TRANSACCION)
	|
	| Version: 0.1	DTB 20250926		Initial Version.
	|		   0.2	BRG	20251006		Modificada la query
	|
    -----------------------------------------------------------------------
*/
BEGIN

    -- DECLARACIÓN DE NOMBRE FICHERO FINAL
    DECLARE v_file_name VARCHAR(25) := 'DEBUG_TA';
    SELECT :v_file_name || :i_fichero_entrada INTO FILENAME FROM DUMMY;
	
    TRUNCATE TABLE EXT.COMPARAR_TA_DEBUG;

    INSERT INTO EXT.COMPARAR_TA_DEBUG
        SELECT 
		IFNULL(TO_VARCHAR(ta.ORDERID),'') || ';' || IFNULL(TO_VARCHAR(ta.LINENUMBER),'') || ';' || IFNULL(TO_VARCHAR(( ta.SUBLINENUMBER || ta.EVENTTYPEID)),'') || ';' || IFNULL(TO_VARCHAR(ta.PAYEEID),'') || ';' || IFNULL(TO_VARCHAR(ta.PAYEETYPE),'') || ';' || IFNULL(TO_VARCHAR(ta.POSITIONNAME),'') || ';' || IFNULL(TO_VARCHAR(ta.TITLENAME),'') || ';' || IFNULL(TO_VARCHAR(ta.GENERICATTRIBUTE1),'') || ';' || IFNULL(TO_VARCHAR(ta.GENERICATTRIBUTE2),'') || ';' || IFNULL(TO_VARCHAR(ta.GENERICATTRIBUTE3),'') || ';' || IFNULL(TO_VARCHAR(ta.GENERICATTRIBUTE4),'') || ';' || IFNULL(TO_VARCHAR(ta.GENERICATTRIBUTE5),'') || ';' || IFNULL(TO_VARCHAR(ta.GENERICATTRIBUTE6),'') || ';' || IFNULL(TO_VARCHAR(ta.GENERICATTRIBUTE7),'') || ';' || IFNULL(TO_VARCHAR(ta.GENERICATTRIBUTE8),'') || ';' || IFNULL(TO_VARCHAR(ta.GENERICATTRIBUTE9),'') || ';' || IFNULL(TO_VARCHAR(ta.GENERICATTRIBUTE10),'') || ';' || IFNULL(TO_VARCHAR(ta.GENERICATTRIBUTE11),'') || ';' || IFNULL(TO_VARCHAR(ta.GENERICATTRIBUTE12),'') || ';' || IFNULL(TO_VARCHAR(ta.GENERICATTRIBUTE13),'') || ';' || IFNULL(TO_VARCHAR(ta.GENERICATTRIBUTE14),'') || ';' || IFNULL(TO_VARCHAR(ta.GENERICATTRIBUTE15),'') || ';' || IFNULL(TO_VARCHAR(ta.GENERICATTRIBUTE16),'') || ';' || IFNULL(TO_VARCHAR(ta.GENERICNUMBER1),'') || ';' || IFNULL(TO_VARCHAR(ta.UNITTYPEFORGENERICNUMBER1),'') || ';' || IFNULL(TO_VARCHAR(ta.GENERICNUMBER2),'') || ';' || IFNULL(TO_VARCHAR(ta.UNITTYPEFORGENERICNUMBER2),'') || ';' || IFNULL(TO_VARCHAR(ta.GENERICNUMBER3),'') || ';' || IFNULL(TO_VARCHAR(ta.UNITTYPEFORGENERICNUMBER3),'') || ';' || IFNULL(TO_VARCHAR(ta.GENERICNUMBER4),'') || ';' || IFNULL(TO_VARCHAR(ta.UNITTYPEFORGENERICNUMBER4),'') || ';' || IFNULL(TO_VARCHAR(ta.GENERICNUMBER5),'') || ';' || IFNULL(TO_VARCHAR(ta.UNITTYPEFORGENERICNUMBER5),'') || ';' || IFNULL(TO_VARCHAR(ta.GENERICNUMBER6),'') || ';' || IFNULL(TO_VARCHAR(ta.UNITTYPEFORGENERICNUMBER6),'') || ';' || IFNULL(TO_VARCHAR(ta.GENERICDATE1,'YYYY-MM-DD'),'') || ';' || IFNULL(TO_VARCHAR(ta.GENERICDATE2,'YYYY-MM-DD'),'') || ';' || IFNULL(TO_VARCHAR(ta.GENERICDATE3,'YYYY-MM-DD'),'') || ';' || IFNULL(TO_VARCHAR(ta.GENERICDATE4,'YYYY-MM-DD'),'') || ';' || IFNULL(TO_VARCHAR(ta.GENERICDATE5,'YYYY-MM-DD'),'') || ';' || IFNULL(TO_VARCHAR(ta.GENERICDATE6,'YYYY-MM-DD'),'') || ';' || IFNULL(TO_VARCHAR(ta.GENERICBOOLEAN1),'') || ';' || IFNULL(TO_VARCHAR(ta.GENERICBOOLEAN2),'') || ';' || IFNULL(TO_VARCHAR(ta.GENERICBOOLEAN3),'') || ';' || IFNULL(TO_VARCHAR(ta.GENERICBOOLEAN4),'') || ';' || IFNULL(TO_VARCHAR(ta.GENERICBOOLEAN5),'') || ';' || IFNULL(TO_VARCHAR(ta.GENERICBOOLEAN6),'') || ';' || IFNULL(TO_VARCHAR(ta.BATCHNAME),'')
        FROM CS_STAGETRANSACTIONASSIGN ta
		WHERE BATCHNAME = :i_fichero_entrada;
END
