CREATE PROCEDURE EXT.SP_COMPARAR_ST (OUT FILENAME VARCHAR(200) , IN i_fichero_entrada VARCHAR(500))
LANGUAGE SQLSCRIPT  
SQL SECURITY INVOKER 
DEFAULT SCHEMA EXT AS
/*---------------------------------------------------------------------
    | Author: Diego Teijo Barral
    | Company: Inycom
    | Initial Version Date: 26-Septiembre-2025
    |----------------------------------------------------------------------
    | Procedure Purpose: Exporta las ST (TRANSACCIONES)
	|
	| Version: 0.1	DTB 20250926		Initial Version.
	|
    -----------------------------------------------------------------------
*/
BEGIN

    -- DECLARACIÓN DE NOMBRE FICHERO FINAL
    DECLARE v_file_name VARCHAR(25) := 'DEBUG_ST';
    SELECT :v_file_name || :i_fichero_entrada INTO FILENAME FROM DUMMY;
	
    TRUNCATE TABLE EXT.COMPARAR_ST_DEBUG;

    INSERT INTO EXT.COMPARAR_ST_DEBUG
        SELECT 
			IFNULL(TO_VARCHAR(ORDERID),'') || ';' || IFNULL(TO_VARCHAR(LINENUMBER),'') || ';' || IFNULL(TO_VARCHAR((SUBLINENUMBER || EVENTTYPEID)),'') || ';' || IFNULL(TO_VARCHAR(BATCHNAME),'') || ';' || IFNULL(TO_VARCHAR(ACCOUNTINGDATE,'YYYY-MM-DD'),'') || ';' || IFNULL(TO_VARCHAR(PRODUCTID),'') || ';' || IFNULL(TO_VARCHAR(PRODUCTNAME),'') || ';' || IFNULL(TO_VARCHAR(PRODUCTDESCRIPTION),'') || ';' || IFNULL(TO_VARCHAR(VALUE),'') || ';' || IFNULL(TO_VARCHAR(UNITTYPEFORVALUE),'') || ';' || IFNULL(TO_VARCHAR(NUMBEROFUNITS),'') || ';' || IFNULL(TO_VARCHAR(UNITVALUE),'') || ';' || IFNULL(TO_VARCHAR(UNITTYPEFORUNITVALUE),'') || ';' || IFNULL(TO_VARCHAR(COMPENSATIONDATE,'YYYY-MM-DD'),'') || ';' || IFNULL(TO_VARCHAR(PAYMENTTERMS),'') || ';' || IFNULL(TO_VARCHAR(NATIVECURRENCY),'') || ';' || IFNULL(TO_VARCHAR(NATIVECURRENCYAMOUNT),'') || ';' || IFNULL(TO_VARCHAR(DISCOUNTPERCENT),'') || ';' || IFNULL(TO_VARCHAR(DISCOUNTTYPE),'') || ';' || IFNULL(TO_VARCHAR(GENERICATTRIBUTE1),'') || ';' || IFNULL(TO_VARCHAR(GENERICATTRIBUTE2),'') || ';' || IFNULL(TO_VARCHAR(GENERICATTRIBUTE3),'') || ';' || IFNULL(TO_VARCHAR(GENERICATTRIBUTE4),'') || ';' || IFNULL(TO_VARCHAR(GENERICATTRIBUTE5),'') || ';' || IFNULL(TO_VARCHAR(GENERICATTRIBUTE6),'') || ';' || IFNULL(TO_VARCHAR(GENERICATTRIBUTE7),'') || ';' || IFNULL(TO_VARCHAR(GENERICATTRIBUTE8),'') || ';' || IFNULL(TO_VARCHAR(GENERICATTRIBUTE9),'') || ';' || IFNULL(TO_VARCHAR(GENERICATTRIBUTE10),'') || ';' || IFNULL(TO_VARCHAR(GENERICATTRIBUTE11),'') || ';' || IFNULL(TO_VARCHAR(GENERICATTRIBUTE12),'') || ';' || IFNULL(TO_VARCHAR(GENERICATTRIBUTE13),'') || ';' || IFNULL(TO_VARCHAR(GENERICATTRIBUTE14),'') || ';' || IFNULL(TO_VARCHAR(GENERICATTRIBUTE15),'') || ';' || IFNULL(TO_VARCHAR(GENERICATTRIBUTE16),'') || ';' || IFNULL(TO_VARCHAR(GENERICATTRIBUTE17),'') || ';' || IFNULL(TO_VARCHAR(GENERICATTRIBUTE18),'') || ';' || IFNULL(TO_VARCHAR(GENERICATTRIBUTE19),'') || ';' || IFNULL(TO_VARCHAR(GENERICATTRIBUTE20),'') || ';' || IFNULL(TO_VARCHAR(GENERICATTRIBUTE21),'') || ';' || IFNULL(TO_VARCHAR(GENERICATTRIBUTE22),'') || ';' || IFNULL(TO_VARCHAR(GENERICATTRIBUTE23),'') || ';' || IFNULL(TO_VARCHAR(GENERICATTRIBUTE24),'') || ';' || IFNULL(TO_VARCHAR(GENERICATTRIBUTE25),'') || ';' || IFNULL(TO_VARCHAR(GENERICATTRIBUTE26),'') || ';' || IFNULL(TO_VARCHAR(GENERICATTRIBUTE27),'') || ';' || IFNULL(TO_VARCHAR(GENERICATTRIBUTE28),'') || ';' || IFNULL(TO_VARCHAR(GENERICATTRIBUTE29),'') || ';' || IFNULL(TO_VARCHAR(GENERICATTRIBUTE30),'') || ';' || IFNULL(TO_VARCHAR(GENERICATTRIBUTE31),'') || ';' || IFNULL(TO_VARCHAR(GENERICATTRIBUTE32),'') || ';' || IFNULL(TO_VARCHAR(GENERICNUMBER1),'') || ';' || IFNULL(TO_VARCHAR(UNITTYPEFORGENERICNUMBER1),'') || ';' || IFNULL(TO_VARCHAR(GENERICNUMBER2),'') || ';' || IFNULL(TO_VARCHAR(UNITTYPEFORGENERICNUMBER2),'') || ';' || IFNULL(TO_VARCHAR(GENERICNUMBER3),'') || ';' || IFNULL(TO_VARCHAR(UNITTYPEFORGENERICNUMBER3),'') || ';' || IFNULL(TO_VARCHAR(GENERICNUMBER4),'') || ';' || IFNULL(TO_VARCHAR(UNITTYPEFORGENERICNUMBER4),'') || ';' || IFNULL(TO_VARCHAR(GENERICNUMBER5),'') || ';' || IFNULL(TO_VARCHAR(UNITTYPEFORGENERICNUMBER5),'') || ';' || IFNULL(TO_VARCHAR(GENERICNUMBER6),'') || ';' || IFNULL(TO_VARCHAR(UNITTYPEFORGENERICNUMBER6),'') || ';' || IFNULL(TO_VARCHAR(GENERICDATE1,'YYYY-MM-DD'),'') || ';' || IFNULL(TO_VARCHAR(GENERICDATE2,'YYYY-MM-DD'),'') || ';' || IFNULL(TO_VARCHAR(GENERICDATE3,'YYYY-MM-DD'),'') || ';' || IFNULL(TO_VARCHAR(GENERICDATE4,'YYYY-MM-DD'),'') || ';' || IFNULL(TO_VARCHAR(GENERICDATE5,'YYYY-MM-DD'),'') || ';' || IFNULL(TO_VARCHAR(GENERICDATE6,'YYYY-MM-DD'),'') || ';' || IFNULL(TO_VARCHAR(GENERICBOOLEAN1),'') || ';' || IFNULL(TO_VARCHAR(GENERICBOOLEAN2),'') || ';' || IFNULL(TO_VARCHAR(GENERICBOOLEAN3),'') || ';' || IFNULL(TO_VARCHAR(GENERICBOOLEAN4),'') || ';' || IFNULL(TO_VARCHAR(GENERICBOOLEAN5),'') || ';' || IFNULL(TO_VARCHAR(GENERICBOOLEAN6),'')
        FROM TCMP.CS_STAGESALESTRANSACTION where BATCHNAME = :i_fichero_entrada;
END
