CREATE PROCEDURE EXT.SP_COMPARAR_RECIBOS (OUT FILENAME VARCHAR(200) , IN i_fichero_entrada VARCHAR(500))
LANGUAGE SQLSCRIPT  
SQL SECURITY INVOKER 
DEFAULT SCHEMA EXT AS
/*---------------------------------------------------------------------
    | Author: Diego Teijo Barral
    | Company: Inycom
    | Initial Version Date: 26-Septiembre-2025
    |----------------------------------------------------------------------
    | Procedure Purpose: Exporta los recibos
	|
	| Version: 0.1	DTB 20250926		Initial Version.
	|
    -----------------------------------------------------------------------
*/
BEGIN

    -- DECLARACIÓN DE NOMBRE FICHERO FINAL
    DECLARE v_file_name VARCHAR(25) := 'DEBUG_RECIBOS';
    SELECT :v_file_name || :i_fichero_entrada INTO FILENAME FROM DUMMY;
	
    TRUNCATE TABLE EXT.COMPARAR_RECIBOS_DEBUG;

    INSERT INTO EXT.COMPARAR_RECIBOS_DEBUG
        SELECT 
			IFNULL(TO_VARCHAR(CODIGO_POLIZA),'') || ';' || IFNULL(TO_VARCHAR(CODIGO_RECIBO),'') || ';' || IFNULL(TO_VARCHAR(CODIGO_SUPLEMENTO),'') || ';' || IFNULL(TO_VARCHAR(ZONA_EXPLOTACION),'') || ';' || IFNULL(TO_VARCHAR(CODIGO_AGENTE_ZONA),'') || ';' || IFNULL(TO_VARCHAR(PERMANENCIA),'') || ';' || IFNULL(TO_VARCHAR(TIPO_RECIBO),'') || ';' || IFNULL(TO_VARCHAR(ESTADO_RECIBO),'') || ';' || IFNULL(TO_VARCHAR(FECHA_COBRO,'YYYY-MM-DD'),'') || ';' || IFNULL(TO_VARCHAR(FECHA_COMPENSACION,'YYYY-MM-DD'),'') || ';' || IFNULL(TO_VARCHAR(FECHA_EFECTO_RECIBO,'YYYY-MM-DD'),'') || ';' || IFNULL(TO_VARCHAR(FECHA_VTO_RECIBO,'YYYY-MM-DD'),'') || ';' || IFNULL(TO_VARCHAR(TIPO_MOVIMIENTO),'') || ';' || IFNULL(TO_VARCHAR(PORCENTAJE_DESCUENTO_SOBRE_PC),'') || ';' || IFNULL(TO_VARCHAR(VALOR_POLIZA),'') || ';' || IFNULL(TO_VARCHAR(CODIGO_UNICO_AGENTE),'') || ';' || IFNULL(TO_VARCHAR(CODIGO_AGENTE_ORIGINAL),'') || ';' || IFNULL(TO_VARCHAR(INSPECTOR),'') || ';' || IFNULL(TO_VARCHAR(OFICINA_COBRADORA),'') || ';' || IFNULL(TO_VARCHAR(OFICINA_GESTORA),'') || ';' || IFNULL(TO_VARCHAR(MARCA_RECUPERADO),'') || ';' || IFNULL(TO_VARCHAR(MARCA_CUENTA),'') || ';' || IFNULL(TO_VARCHAR(PRIMER_RECIBO),'') || ';' || IFNULL(TO_VARCHAR(ASEGURADOS_NETOS),'') || ';' || IFNULL(TO_VARCHAR(AUMENTO_ASEGURADOS),'') || ';' || IFNULL(TO_VARCHAR(EXCLUIDO_COMISIONES),'') || ';' || IFNULL(TO_VARCHAR(BONIFICACION_POLIZA),'') || ';' || IFNULL(TO_VARCHAR(DISMINUCION_PRIMA),'') || ';' || IFNULL(TO_VARCHAR(TIPO_RECUPERACION),'') || ';' || IFNULL(TO_VARCHAR(ES_PERMANENCIA_20),'') || ';' || IFNULL(TO_VARCHAR(CODIGO_AGENTE_COMMISSIONS),'') || ';' || IFNULL(TO_VARCHAR(FECHA_EMISION_REC,'YYYY-MM-DD'),'') || ';' || IFNULL(TO_VARCHAR(FCHA_EFECTO_SUPLEMENTO),'') || ';' || IFNULL(TO_VARCHAR(DISTRITO_COBRO),'') || ';' || IFNULL(TO_VARCHAR(CODIGO_SINIESTRO),'') || ';' || IFNULL(TO_VARCHAR(FILE_NAME),'')
        FROM EXT.RECIBOS WHERE FILE_NAME = :i_fichero_entrada;
END
