CREATE PROCEDURE EXT.SP_HIST_SALESTRANSACTION (IN i_file_name varchar(120))
LANGUAGE SQLSCRIPT 
SQL SECURITY INVOKER 
DEFAULT SCHEMA EXT AS

/*---------------------------------------------------------------------
    | Author: Rubén Martínez
    | Company: Inycom
    | Initial Version Date: 26/03/2025
    |----------------------------------------------------------------------
    | Procedure Purpose: Procedimiento que se ejecuta cuando se sube un fichero para historicos de SALESTRANSACTION a traves del CDL
    |
    | Version: 0.1  RMF 20250326    Initial Version.
    |
    -----------------------------------------------------------------------
*/

BEGIN
	
	USING SQLSCRIPT_STRING AS LIBRARY;
	
	DECLARE v_id_proceso INTEGER;
	DECLARE proc_name VARCHAR2(50) := ::CURRENT_OBJECT_SCHEMA ||'.'|| ::CURRENT_OBJECT_NAME;
	DECLARE v_version VARCHAR2(10) := '0.1';
	DECLARE v_num_rows INTEGER := 0;
	DECLARE v_log_count INTEGER := 0;
	DECLARE v_permisos_log VARCHAR(50) := EXT.LIB_GLOBAL:GET_PERMISOS_LOG();
	DECLARE v_const_prestage_status_load INT = EXT.LIB_CONSTANTES:CONST_PRESTAGE_STATUS_LOAD; --0
	DECLARE v_const_stage_status_ok INT := EXT.LIB_CONSTANTES:CONST_STAGE_STATUS_OK; --1
	DECLARE v_const_stage_status_error INT := EXT.LIB_CONSTANTES:CONST_STAGE_STATUS_ERROR; --3
	DECLARE v_tenantId VARCHAR(4) := EXT.LIB_GLOBAL:getTenantID();
	
	BEGIN
	
		DECLARE EXIT HANDLER FOR SQLEXCEPTION
		BEGIN
			CALL EXT.LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name , 'Error en procedimiento principal ' || proc_name || ' - SQL_ERROR_MESSAGE: ' || IFNULL(::SQL_ERROR_MESSAGE,'')
																												|| '. SQL_ERROR_CODE: ' || ::SQL_ERROR_CODE, v_log_count, v_id_proceso, 'error');
			--v_hayError := 1;
			v_num_rows := 0;
		
			UPDATE EXT.IN_BATCH_CONTROL
			SET STATUS = v_const_stage_status_error,
				END_DATE = CURRENT_TIMESTAMP
			WHERE FILE_NAME = i_file_name
				AND ID_PROCESO = v_id_proceso;
			
			COMMIT;
			
			RESIGNAL;
		END;
	
	--Inicializamos el idProceso
		SELECT EXT.ID_PROCESO.NEXTVAL INTO v_id_proceso FROM DUMMY;
		CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'Version: ' || v_version || ' - Procedure starting for ' || i_file_name, v_log_count, v_id_proceso, 'info');
	
		SELECT COUNT(*) INTO v_num_rows
		FROM EXT.PRESTAGE_HISTSALESTRANSACTION;
		
		INSERT INTO EXT.IN_BATCH_CONTROL (ID_PROCESO, FILE_NAME, PROCEDURE_NAME, SOURCE_ROWS, STATUS, START_DATE)
		VALUES (v_id_proceso, i_file_name, proc_name, v_num_rows, :v_const_prestage_status_load, CURRENT_TIMESTAMP);
		
		INSERT INTO EXT.EJEC_HIST_CONTROL
		SELECT DISTINCT :v_id_proceso 
			, :i_file_name
			, HIST.FILE_NAME_OUT
		FROM EXT.PRESTAGE_HISTSALESTRANSACTION HIST;
		
		v_num_rows = ::rowcount;
		
		CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'Fin INSERT en EJEC_HIST_CONTROL. Filas: ' || v_num_rows, v_log_count, v_id_proceso, 'info');
		
		TBL_EJEC_HIST_CONTROL = SELECT TBL.FILE_NAME_EXTRACCION
									, TBL.FILE_NAME_LP
								FROM EXT.EJEC_HIST_CONTROL TBL
								WHERE ID_PROCESO = :v_id_proceso
								;
		
		v_num_rows = RECORD_COUNT(:TBL_EJEC_HIST_CONTROL);
		
		CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'TBL_EJEC_HIST_CONTROL creada. Filas: ' || v_num_rows, v_log_count, v_id_proceso, 'info');
		/*	
		DELETE FROM EXT.SALESTRANSACTION REC
		WHERE BATCHNAME IN (SELECT FILE_NAME_LP FROM :TBL_EJEC_HIST_CONTROL);
			
		v_num_rows = ::rowcount;
		
		CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'Fin DELETE en SALESTRANSACTION. Filas: ' || v_num_rows, v_log_count, v_id_proceso, 'info');
		*/
		INSERT INTO EXT.SALESTRANSACTION
		SELECT :v_tenantId AS TENANTID
			, 99999999 AS STAGESALESTRANSACTIONSEQ
			, HIST.FILE_NAME_OUT AS BATCHNAME
			, HIST.FILE_IN_RECIBOS
			, HIST.ORDERID
			, TO_BIGINT(HIST.LINENUMBER)
			, TO_BIGINT(HIST.SUBLINENUMBER)
			, HIST.EVENTTYPEID
			, 99999999 AS SALESTRANSACTIONSEQ
			, 99999999 AS SALESORDERSEQ
			, TO_DATE(HIST.ACCOUNTINGDATE,'DD/MM/YYYY')
			, HIST.PRODUCTID
			, HIST.PRODUCTNAME
			, HIST.PRODUCTDESCRIPTION
			, TO_DECIMAL(REPLACE(HIST.VALUE,',','.'),25,10)
			, HIST.UNITTYPEFORVALUE
			, TO_DECIMAL(REPLACE(HIST.NUMBEROFUNITS,',','.'),25,10)
			, TO_DECIMAL(REPLACE(HIST.UNITVALUE,',','.'),25,10)
			, HIST.UNITTYPEFORUNITVALUE
			, TO_DATE(HIST.COMPENSATIONDATE,'DD/MM/YYYY')
			, HIST.PAYMENTTERMS
			, HIST.PONUMBER
			, HIST.CHANNEL
			, HIST.ALTERNATEORDERNUMBER
			, HIST.DATASOURCE
			, HIST.NATIVECURRENCY
			, TO_DECIMAL(REPLACE(HIST.NATIVECURRENCYAMOUNT,',','.'),25,10)
			, TO_DECIMAL(REPLACE(HIST.DISCOUNTPERCENT,',','.'),25,10)
			, HIST.DISCOUNTTYPE
			, HIST.BILLTOCUSTID
			, HIST.BILLTOCONTACT
			, HIST.BILLTOCOMPANY
			, HIST.BILLTOAREACODE
			, HIST.BILLTOPHONE
			, HIST.BILLTOFAX
			, HIST.BILLTOADDRESS1
			, HIST.BILLTOADDRESS2
			, HIST.BILLTOADDRESS3
			, HIST.BILLTOCITY
			, HIST.BILLTOSTATE
			, HIST.BILLTOCOUNTRY
			, HIST.BILLTOPOSTALCODE
			, HIST.BILLTOINDUSTRY
			, HIST.BILLTOGEOGRAPHY
			, HIST.SHIPTOCUSTID
			, HIST.SHIPTOCONTACT
			, HIST.SHIPTOCOMPANY
			, HIST.SHIPTOAREACODE
			, HIST.SHIPTOPHONE
			, HIST.SHIPTOFAX
			, HIST.SHIPTOADDRESS1
			, HIST.SHIPTOADDRESS2
			, HIST.SHIPTOADDRESS3
			, HIST.SHIPTOCITY
			, HIST.SHIPTOSTATE
			, HIST.SHIPTOCOUNTRY
			, HIST.SHIPTOPOSTALCODE
			, HIST.SHIPTOINDUSTRY
			, HIST.SHIPTOGEOGRAPHY
			, HIST.OTHERTOCUSTID
			, HIST.OTHERTOCONTACT
			, HIST.OTHERTOCOMPANY
			, HIST.OTHERTOAREACODE
			, HIST.OTHERTOPHONE
			, HIST.OTHERTOFAX
			, HIST.OTHERTOADDRESS1
			, HIST.OTHERTOADDRESS2
			, HIST.OTHERTOADDRESS3
			, HIST.OTHERTOCITY
			, HIST.OTHERTOSTATE
			, HIST.OTHERTOCOUNTRY
			, HIST.OTHERTOPOSTALCODE
			, HIST.OTHERTOINDUSTRY
			, HIST.OTHERTOGEOGRAPHY
			, HIST.REASONID
			, HIST.COMMENTS
			, TO_TIMESTAMP(HIST.STAGEPROCESSDATE,'DD/MM/YYYY HH24:MI:SS')
			, HIST.STAGEPROCESSFLAG
			, HIST.BUSINESSUNITNAME
			, NULL AS BUSINESSUNITMAP
			, HIST.GENERICATTRIBUTE1
			, HIST.GENERICATTRIBUTE2
			, HIST.GENERICATTRIBUTE3
			, HIST.GENERICATTRIBUTE4
			, HIST.GENERICATTRIBUTE5
			, HIST.GENERICATTRIBUTE6
			, HIST.GENERICATTRIBUTE7
			, HIST.GENERICATTRIBUTE8
			, HIST.GENERICATTRIBUTE9
			, HIST.GENERICATTRIBUTE10
			, HIST.GENERICATTRIBUTE11
			, HIST.GENERICATTRIBUTE12
			, HIST.GENERICATTRIBUTE13
			, HIST.GENERICATTRIBUTE14
			, HIST.GENERICATTRIBUTE15
			, HIST.GENERICATTRIBUTE16
			, HIST.GENERICATTRIBUTE17
			, HIST.GENERICATTRIBUTE18
			, HIST.GENERICATTRIBUTE19
			, HIST.GENERICATTRIBUTE20
			, HIST.GENERICATTRIBUTE21
			, HIST.GENERICATTRIBUTE22
			, HIST.GENERICATTRIBUTE23
			, HIST.GENERICATTRIBUTE24
			, HIST.GENERICATTRIBUTE25
			, HIST.GENERICATTRIBUTE26
			, HIST.GENERICATTRIBUTE27
			, HIST.GENERICATTRIBUTE28
			, HIST.GENERICATTRIBUTE29
			, HIST.GENERICATTRIBUTE30
			, HIST.GENERICATTRIBUTE31
			, HIST.GENERICATTRIBUTE32
			, TO_DECIMAL(REPLACE(HIST.GENERICNUMBER1,',','.'),25,10)
			, HIST.UNITTYPEFORGENERICNUMBER1
			, TO_DECIMAL(REPLACE(HIST.GENERICNUMBER2,',','.'),25,10)
			, HIST.UNITTYPEFORGENERICNUMBER2
			, TO_DECIMAL(REPLACE(HIST.GENERICNUMBER3,',','.'),25,10)
			, HIST.UNITTYPEFORGENERICNUMBER3
			, TO_DECIMAL(REPLACE(HIST.GENERICNUMBER4,',','.'),25,10)
			, HIST.UNITTYPEFORGENERICNUMBER4
			, TO_DECIMAL(REPLACE(HIST.GENERICNUMBER5,',','.'),25,10)
			, HIST.UNITTYPEFORGENERICNUMBER5
			, TO_DECIMAL(REPLACE(HIST.GENERICNUMBER6,',','.'),25,10)
			, HIST.UNITTYPEFORGENERICNUMBER6
			, TO_DATE(HIST.GENERICDATE1,'DD/MM/YYYY')
			, TO_DATE(HIST.GENERICDATE2,'DD/MM/YYYY')
			, TO_DATE(HIST.GENERICDATE3,'DD/MM/YYYY')
			, TO_DATE(HIST.GENERICDATE4,'DD/MM/YYYY')
			, TO_DATE(HIST.GENERICDATE5,'DD/MM/YYYY')
			, TO_DATE(HIST.GENERICDATE6,'DD/MM/YYYY')
			, HIST.GENERICBOOLEAN1
			, HIST.GENERICBOOLEAN2
			, HIST.GENERICBOOLEAN3
			, HIST.GENERICBOOLEAN4
			, HIST.GENERICBOOLEAN5
			, HIST.GENERICBOOLEAN6
			, TO_BIGINT(HIST.STAGEERRORCODE)
			, NULL AS COMPENSATIONDATE_OLD
			, NULL AS PUSEQ_OLD
		FROM EXT.PRESTAGE_HISTSALESTRANSACTION HIST
		;
		
		v_num_rows = ::rowcount;
		
		CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'Fin INSERT en SALESTRANSACTION. Filas: ' || v_num_rows, v_log_count, v_id_proceso, 'info');
		
		UPDATE EXT.IN_BATCH_CONTROL SET STATUS = :v_const_stage_status_ok, END_DATE = CURRENT_TIMESTAMP WHERE FILE_NAME = i_file_name AND ID_PROCESO = v_id_proceso;
		
		CALL EXT.LIB_GLOBAL:WRITE_LOG (v_permisos_log,proc_name, 'Fin procesamiento del fichero ' || i_file_name, v_log_count, v_id_proceso, 'info');
		
	END;
		
END
