CREATE PROCEDURE EXT.SP_POPULATE_GESTIONES (IN i_file_name varchar(120), IN i_id_proceso BIGINT, INOUT i_log_count INT)
LANGUAGE SQLSCRIPT 
SQL SECURITY INVOKER 
DEFAULT SCHEMA EXT AS
/*---------------------------------------------------------------------
    | Author: Jorge Gracia Estaun 
    | Company: Inycom
    | Initial Version Date: 05-Febrero-2025
    |----------------------------------------------------------------------
    | Procedure Purpose: Procedimiento que se ejecuta una vez que entra un fichero de GESTIONES e inserta los datos en las tablas finales de 
    |						RECIBOS, POLIZAS, GARANTIAS RECIBOS, SALESTRANSACTION Y TRANSACTIONASSIGN
	|
	| Version: 0.1	JGE 20250205		Initial Version.
	|
    -----------------------------------------------------------------------
*/

BEGIN
	DECLARE proc_name VARCHAR2(50) := ::CURRENT_OBJECT_SCHEMA ||'.'|| ::CURRENT_OBJECT_NAME;
	DECLARE v_version VARCHAR2(10) := '0.1';
	DECLARE v_num_rows INTEGER := 0;
	DECLARE v_log_count INTEGER := 0;
	DECLARE v_permisos_log VARCHAR(50) := EXT.LIB_GLOBAL:GET_PERMISOS_LOG();

	DECLARE v_const_stage_status_ok INT := EXT.LIB_CONSTANTES:CONST_STAGE_STATUS_OK;
	DECLARE v_const_stage_status_error INT := EXT.LIB_CONSTANTES:CONST_STAGE_STATUS_ERROR;
	DECLARE v_const_populate_status_ok INT := EXT.LIB_CONSTANTES:CONST_POPULATE_STATUS_OK;
	DECLARE v_const_populate_status_error INT := EXT.LIB_CONSTANTES:CONST_POPULATE_STATUS_ERROR;
	
	DECLARE v_const_carga_status_ok INT := EXT.LIB_CONSTANTES:CONST_GENERA_TRX_STATUS_OK;
	DECLARE v_const_recibo_cobrado VARCHAR(6) := EXT.LIB_CONSTANTES:CONST_RECIBO_COBRADO;
	DECLARE v_tenantid VARCHAR(4) := '';
	
	DECLARE CONST_TIPO_EURO VARCHAR(255) := EXT.LIB_CONSTANTES:CONST_TIPO_EURO;
    DECLARE CONST_TIPO_ESP VARCHAR(255) := EXT.LIB_CONSTANTES:CONST_TIPO_ESP;
    DECLARE CONST_TIPO_PERCENTAGE VARCHAR(255) := EXT.LIB_CONSTANTES:CONST_TIPO_PERCENTAGE;
    DECLARE CONST_NO_ENCONTRADO VARCHAR(20) := EXT.LIB_CONSTANTES:CONST_NO_ENCONTRADO; 
    
    DECLARE v_fecha_compensacion DATE;
    DECLARE v_vueltas INTEGER := 1;

	DECLARE EXIT HANDLER FOR SQLEXCEPTION
		BEGIN
			
			ROLLBACK;
		
			CALL EXT.LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name , 'Error en procedimiento principal ' || proc_name || ' - SQL_ERROR_MESSAGE: ' || IFNULL(::SQL_ERROR_MESSAGE,'')
																												|| '. SQL_ERROR_CODE: ' || ::SQL_ERROR_CODE, i_log_count, i_id_proceso, 'error');
			--v_hayError := 1;
			v_num_rows := 0;
			
			ROLLBACK;
        	-- SIGNAL SQL_ERROR 'Error al insertar';
			
			--Se obtiene la cuenta del fichero
			SELECT COUNT(*) INTO v_num_rows
			FROM EXT.STAGE_RECIBOS
			WHERE FILE_NAME = :i_file_name
				AND ESTADO = :v_const_stage_status_ok;
			
			--Se actualizan los campos de la in_batch_control para indicar el error
			UPDATE EXT.IN_BATCH_CONTROL
			SET REJECTED_ROWS = :v_num_rows,
				STATUS = :v_const_populate_status_error,
				END_DATE = CURRENT_TIMESTAMP
			WHERE FILE_NAME = :i_file_name
				AND STATUS = :v_const_stage_status_ok;
			
			--Se actualizan los registros de STAGE_RECIBOS con estado erróneo
			UPDATE EXT.STAGE_RECIBOS
				SET ESTADO = :v_const_populate_status_error,
				FECHA_MODIFICACION = CURRENT_TIMESTAMP
			WHERE FILE_NAME = :i_file_name
				AND ESTADO = :v_const_stage_status_ok;	
			
			COMMIT;

			--Captura el error y lo envía a xDL
			RESIGNAL;
		END;
	
		
	CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'Version: ' || v_version || ' - Procedure starting for ' || i_file_name, v_log_count, i_id_proceso, 'info');
	
	--Rellenamos el campo CODIGOAGENTEORIGINAL de la tabla de stage
	-- UPDATE EXT.STAGE_RECIBOS SET CODIGO_AGENTE_ORIGINAL = CODIGO_UNICO_AGENTE WHERE FILE_NAME = :i_file_name AND SR.ESTADO = :v_const_stage_status_ok;
	
	--Guardar datos en variable para evitar repetir la consulta
	TBL_GESTIONES_TEMP = SELECT SR.* FROM EXT.STAGE_RECIBOS SR WHERE SR.FILE_NAME = :i_file_name AND SR.ESTADO = :v_const_stage_status_ok ORDER BY SR.CODIGO_POLIZA,SR.PRODUCTO_CONTABLE,SR.FECHA_EMISION_REC DESC;
	
	v_num_rows = RECORD_COUNT(:TBL_GESTIONES_TEMP);

	CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'TBL_GESTIONES_TEMP creada: ' || v_num_rows || ' filas', v_log_count, i_id_proceso, 'info');	
	
	CALL LIB_GLOBAL:WRITE_LOG(v_permisos_log,proc_name,'Inicio INSERT en POLIZAS ', v_log_count, i_id_proceso, 'info');
	
	--se rellena la variable tenantid una vez en toda la ejecucion
	SELECT DISTINCT TENANTID INTO v_tenantid FROM TCMP.CS_TENANT;
	
	--Guardamos en una variable tabla información sobre jerarquía
	TBL_GEN_CODIGOS_AGENTE = SELECT * FROM EXT.VW_CODIGOS_DE_AGENTE VW
							WHERE 1=1
								AND VW.CODIGO_OCASO <> '0' 
								AND VW.CODIGO_OCASO <> '000000000' 
								AND VW.CODIGO_OCASO <> '0000000000'
							;
							
	v_num_rows = RECORD_COUNT(:TBL_GEN_CODIGOS_AGENTE);
	CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'tabla agentes creada. Filas: ' || v_num_rows || ' filas' , i_log_count, i_id_proceso, 'info');
	
	SELECT max(R.CARGO_COMPENSACION) INTO v_fecha_compensacion 
	FROM EXT.STAGE_RECIBOS R 
	WHERE R.FILE_NAME = :i_file_name 
	-- GROUP BY R.FECHA_COMPENSACION
	;
	
	--POLIZAS
	--Insert en polizas
	INSERT INTO EXT.POLIZAS (
	    ID_RECIBO, FILE_NAME, ESTADO, FECHA_MODIFICACION, CODIGO_POLIZA, RAMO,
	    MOTIVO_ALTA, FECHA_EFECTO_POLIZA, FECHA_EMISION_POLIZA, FECHA_CESION_POLIZA, 
	    MOTIVO_BAJA, FECHA_BAJA, FECHA_VENCIMIENTO, FECHA_REHABILITACION, FORMA_PAGO, 
	    TIPO_CAMPANIA, SEGUNDA_RESIDENCIA, TARIFA, ZONA, CLAVE_RIESGO, MODALIDAD, 
	    DURACION, CLAUSULA, SUSTITUCION_INCENDIOS, EXCLUIDO_COMISIONES, TRASPASADA, 
	    DESCUENTO_IMPORTE_SINIESTRALID, DESCUENTO_POR_PRIORITARIO, RIESGO, COLECTIVO, 
	    AUTOLIQUIDA, KILOMETROS, MOVILIDAD, POLIZA_CON_AGENTE, AGENTE_CARTERA, 
	    IMP_COMISION_CARTERA, PORC_COMISION_CARTERA, FECHA_FIN_COMISION_CARTERA
	)
	SELECT 
	    IDENTIFICADOR, FILE_NAME, NULL, CURRENT_TIMESTAMP, CODIGO_POLIZA, RAMO,
	    NULL, NULL, NULL, NULL, 
	    NULL, NULL, NULL, NULL, NULL, 
	    NULL, NULL, NULL, NULL, NULL, NULL, 
	    NULL, NULL, NULL, NULL, NULL, 
	    NULL, NULL, NULL, NULL, 
	    NULL, NULL, NULL, NULL, NULL, 
	    NULL, NULL, NULL
	FROM (
	    SELECT 
	        SRC.IDENTIFICADOR, SRC.FILE_NAME, SRC.CODIGO_POLIZA, SRC.RAMO,
	        ROW_NUMBER() OVER (PARTITION BY SRC.CODIGO_POLIZA) AS RN
	    FROM :TBL_GESTIONES_TEMP SRC
	) T
	WHERE T.RN = 1 -- Solo mantiene un registro por CODIGO_POLIZA
	AND NOT EXISTS (
	    SELECT 1 FROM EXT.POLIZAS X WHERE T.CODIGO_POLIZA = SUBSTR(X.CODIGO_POLIZA,1,28)
	);
	
	
	v_num_rows := ::rowcount;
	CALL EXT.LIB_CONSTANTES:WRITE_LOG(v_permisos_log,proc_name,'Fin INSERT en POLIZAS ' || v_num_rows , v_log_count, i_id_proceso, 'info');

	CALL EXT.LIB_CONSTANTES:WRITE_LOG(v_permisos_log,proc_name,'Inicio INSERT en RECIBOS ', v_log_count, i_id_proceso, 'info');

	-- TBL_GESTIONES_TEMP_CALCULADO = (
	-- 	SELECT SRC.*, 
	-- 	        IFNULL(
	-- 	            (SELECT IFNULL(MAX(R2.CODIGO_SUPLEMENTO),0)
	-- 	             FROM EXT.GARANTIAS_RECIBO R2
	-- 	             WHERE R2.CODIGO_POLIZA = SRC.CODIGO_POLIZA
	-- 	             --AND R2.PERMANENCIA = SRC.PERMANENCIA
	-- 	             AND R2.CODIGO_RECIBO = 'C_GESTIONES'
	-- 	             --AND R2.ESTADO_RECIBO = SRC.ESTADO_RECIBO
	-- 	            ), 
	-- 	        0) + ROW_NUMBER() OVER(PARTITION BY SRC.CODIGO_POLIZA /*, SRC.CODIGO_RECIBO, SRC.ESTADO_RECIBO, SRC.CODIGO_SUPLEMENTO*/ ORDER BY SRC.CODIGO_POLIZA ASC) AS CODIGO_SUPLEMENTO_CALCULADO, -- Calculamos CODIGO_SUPLEMENTO con ROW_NUMBER
	-- 			(
	-- 				SELECT COUNT(*) FROM :TBL_GEN_CODIGOS_AGENTE X WHERE X.CODIGO_OCASO = SRC.CODIGO_UNICO_AGENTE
	-- 			) AS v_existe_codigo_agente,
	-- 			(
	-- 				SELECT COUNT(*) FROM :TBL_GEN_CODIGOS_AGENTE X WHERE X.CODIGO_UNICO = SRC.CODIGO_UNICO_AGENTE
	-- 			) AS v_existe_codigo_unico
	-- 	FROM :TBL_GESTIONES_TEMP SRC
	-- );
	
	
	
	TBL_GESTIONES_TEMP_CALCULADO = (
		SELECT 
		    SRC.*,
		    IFNULL(MAX_R.MAX_COD_SUPLEMENTO, 0) + 1 AS CODIGO_SUPLEMENTO_CALCULADO,
		    (
		        SELECT COUNT(*) FROM :TBL_GEN_CODIGOS_AGENTE X WHERE X.CODIGO_OCASO = SRC.CODIGO_UNICO_AGENTE
		    ) AS v_existe_codigo_agente,
		    (
		        SELECT COUNT(*) FROM :TBL_GEN_CODIGOS_AGENTE X WHERE X.CODIGO_UNICO = SRC.CODIGO_UNICO_AGENTE
		    ) AS v_existe_codigo_unico
		FROM :TBL_GESTIONES_TEMP SRC
		LEFT JOIN (
		    SELECT 
		        R2.CODIGO_POLIZA,
		        IFNULL(MAX(R2.CODIGO_SUPLEMENTO),0) AS MAX_COD_SUPLEMENTO
		    FROM EXT.GARANTIAS_RECIBO R2
		    WHERE R2.CODIGO_RECIBO = 'C_GESTIONES'
		    GROUP BY R2.CODIGO_POLIZA
		) MAX_R
		  ON SRC.CODIGO_POLIZA = MAX_R.CODIGO_POLIZA
		  
	);
	  
	v_num_rows = RECORD_COUNT(:TBL_GESTIONES_TEMP_CALCULADO);
	CALL EXT.LIB_CONSTANTES:WRITE_LOG(v_permisos_log,proc_name,'TBL_GESTIONES_TEMP_CALCULADO filas: ' || v_num_rows , v_log_count, i_id_proceso, 'info');

	TBL_GESTIONES_TEMP_CALCULADO_2 = (
		SELECT SRC.*,
			IFNULL(AGE.CODIGO_UNICO,CONST_NO_ENCONTRADO) as CODIGO_UNICO,
			ROW_NUMBER() OVER (
			PARTITION BY SRC.CODIGO_POLIZA
				ORDER BY
					AGE.EFFECTIVEENDDATE DESC
					, CASE WHEN SRC.CODIGO_UNICO_AGENTE = AGE.CODIGO_OCASO 
						THEN 1 
						ELSE 2 
					END ASC
			) AS ROW_NUM_REC,
			AGE.CODIGO_OCASO AS v_codigo_ocaso
		FROM :TBL_GESTIONES_TEMP_CALCULADO SRC
		LEFT JOIN :TBL_GEN_CODIGOS_AGENTE AGE
	        ON ( (IFNULL(SRC.v_existe_codigo_agente,0) > 0 AND SRC.CODIGO_UNICO_AGENTE = AGE.CODIGO_OCASO)
	             OR
	             (IFNULL(SRC.v_existe_codigo_unico,0) > 0 AND SRC.CODIGO_UNICO_AGENTE = AGE.CODIGO_UNICO)
	           )
	);
	
	v_num_rows = RECORD_COUNT(:TBL_GESTIONES_TEMP_CALCULADO_2);
	CALL EXT.LIB_CONSTANTES:WRITE_LOG(v_permisos_log,proc_name,'TBL_GESTIONES_TEMP_CALCULADO_2 filas: ' || v_num_rows , v_log_count, i_id_proceso, 'info');
	
	TBL_GESTIONES_TEMP_CALCULADO_RECIBOS = (
		SELECT SRC.*
		FROM :TBL_GESTIONES_TEMP_CALCULADO_2 SRC
		WHERE ROW_NUM_REC = 1
	);
	
	v_num_rows = RECORD_COUNT(:TBL_GESTIONES_TEMP_CALCULADO_RECIBOS);
	CALL EXT.LIB_CONSTANTES:WRITE_LOG(v_permisos_log,proc_name,'TBL_GESTIONES_TEMP_CALCULADO_RECIBOS filas: ' || v_num_rows , v_log_count, i_id_proceso, 'info');

	--RECIBOS
	--No hace falta historificar porque iremos incrementando el cod_suplemento si viene mas de una gestion para la misma poliza
	--FALTA POR METER EL CODIGO_AGENTE_COMMISSIONS
	--Insert en recibos
		INSERT INTO EXT.RECIBOS (
	    IDENTIFICADOR, FILE_NAME, ESTADO, FECHA_MODIFICACION, 
	    CODIGO_POLIZA, CODIGO_RECIBO, PERMANENCIA, TIPO_RECIBO, ESTADO_RECIBO, FECHA_COBRO, 
	    FECHA_COMPENSACION, FECHA_EFECTO_RECIBO, FECHA_VTO_RECIBO, TIPO_MOVIMIENTO, PORCENTAJE_DESCUENTO_SOBRE_PC,
	    VALOR_POLIZA, CODIGO_UNICO_AGENTE, CODIGO_AGENTE_ORIGINAL, INSPECTOR, OFICINA_COBRADORA,
	    OFICINA_GESTORA, MARCA_RECUPERADO, MARCA_CUENTA, PRIMER_RECIBO, ASEGURADOS_NETOS, AUMENTO_ASEGURADOS,
	    EXCLUIDO_COMISIONES, BONIFICACION_POLIZA, DISMINUCION_PRIMA, TIPO_RECUPERACION, ES_PERMANENCIA_20,
	    CODIGO_AGENTE_COMMISSIONS, FECHA_EMISION_REC, FCHA_EFECTO_SUPLEMENTO, CODIGO_SUPLEMENTO, 
	    DISTRITO_COBRO, CODIGO_SINIESTRO, ZONA_EXPLOTACION, CODIGO_AGENTE_ZONA
		)
		SELECT 
		    IDENTIFICADOR, FILE_NAME, :v_const_carga_status_ok, CURRENT_TIMESTAMP,
		    IFNULL(CODIGO_POLIZA,'0'), 'C_GESTIONES', PERMANENCIA, NULL, 
		    IFNULL(ESTADO_RECIBO, :v_const_recibo_cobrado), FECHA_COBRO, 
		    CARGO_COMPENSACION, NULL, NULL, NULL, NULL, NULL, 
		    CASE WHEN IFNULL(v_existe_codigo_agente,0) > 0
		    	THEN CODIGO_UNICO_AGENTE
		    	ELSE v_codigo_ocaso
		    END, --CODIGO_UNICO_AGENTE 
		    CASE WHEN IFNULL(v_existe_codigo_agente,0) > 0
		    	THEN CODIGO_UNICO_AGENTE
		    	ELSE v_codigo_ocaso
		    END, --CODIGO_AGENTE_ORIGINAL 
		    NULL, NULL,
		    OFICINA_GESTORA, NULL, NULL, NULL, NULL, NULL, 
		    NULL, NULL, NULL, NULL, NULL,
		    CODIGO_UNICO --codigo_agente_commmisisons
		    , FECHA_EMISION_REC, NULL, 
		    IFNULL(CODIGO_SUPLEMENTO_CALCULADO, 0),
		    NULL, NULL, NULL, NULL
		FROM --:TBL_GESTIONES_TEMP_CALCULADO_2 T
		(
		    SELECT *, ROW_NUMBER() OVER (PARTITION BY CODIGO_POLIZA
		    , CODIGO_RECIBO, ESTADO_RECIBO, CODIGO_SUPLEMENTO_CALCULADO 
		    ORDER BY CODIGO_POLIZA ASC) AS RN
		    FROM :TBL_GESTIONES_TEMP_CALCULADO_RECIBOS 
		) T
		WHERE RN = 1;
	
	v_num_rows := ::rowcount;
	CALL EXT.LIB_CONSTANTES:WRITE_LOG(v_permisos_log,proc_name,'Fin INSERT en RECIBOS ' || v_num_rows , v_log_count, i_id_proceso, 'info');

	CALL EXT.LIB_CONSTANTES:WRITE_LOG(v_permisos_log,proc_name,'Inicio INSERT en GARANTIAS_RECIBO ', v_log_count, i_id_proceso, 'info');

	--GARANTIAS_RECIBO
	--Insert en garantias_recibos
	INSERT INTO EXT.GARANTIAS_RECIBO
	SELECT
	    SRC.IDENTIFICADOR, -- ID_RECIBO
	    SRC.FILE_NAME, -- FILE_NAME
	    :v_const_carga_status_ok AS ESTADO,
	    CURRENT_TIMESTAMP AS FECHA_MODIFICACION,
	    IFNULL(SRC.CODIGO_POLIZA, '0') AS CODIGO_POLIZA,
	    'C_GESTIONES' AS CODIGO_RECIBO,
	    IFNULL(SRC.PRODUCTO_CONTABLE, '0') AS PRODUCTO_CONTABLE,
	    IFNULL(SRC.ESTADO_RECIBO, v_const_recibo_cobrado) AS ESTADO_RECIBO,
	    NULL AS PRIMA_NETA_RECIBO,
	    NULL AS PRIMA_BRUTA_RECIBO,
	    NULL AS RECARGO,
	    NULL AS PORCENTAJE_BONIFICACION,
	    NULL AS INCREMENTO_PRIMA_ANUAL,
	    SRC.INCRE_PRIMA_ANUAL AS PRIMA_COMISIONABLE,
	    NULL AS UNIDAD_DE_POLIZA,
	    NULL AS MESES_COBRADOS,
	    NULL AS FECHA_ALTA_GAR_POL,
	    NULL AS FECHA_BAJA_GAR_POL,
	    NULL AS PORCENTAJE_NIVELADA,
	    NULL AS PERIODO_EXTORNABLE,
	    SUBSTR(SRC.IND_COMI_CALCULADA, 1, 1) AS INDICADOR_COMISION_CALCULADA,
	    SUBSTR(SRC.IND_POR_CALCULADO, 1, 1) AS INDICADOR_PORCENTAJE_CALCULA,
	    NULL AS PORCENTAJE_COMISION_CALCULADA,
	    NULL AS IMPORTE_COMISION,
	    NULL AS PRIMA_UNICA,
	    NULL AS NUM_ORDEN_MOVIMIENTO,
	    NULL AS AUMENTO_CAPITALES_GARANTIA,
	    NULL AS PRIMA_NETA_ANUALIZADA,
	    NULL AS PORC_COMISION_NP,
	    NULL AS PORC_COMISION_CONSERVACION,
	    IFNULL(SRC.CODIGO_SUPLEMENTO_CALCULADO, 0) AS CODIGO_SUPLEMENTO,
	    NULL AS PORC_COMISION_COBRO
	FROM --:TBL_GESTIONES_TEMP_CALCULADO_2 SRC
	(
	    SELECT *, ROW_NUMBER() OVER (PARTITION BY CODIGO_POLIZA, CODIGO_RECIBO, PRODUCTO_CONTABLE, ESTADO_RECIBO, CODIGO_SUPLEMENTO_CALCULADO
	    	
	    ) AS RN
	    FROM :TBL_GESTIONES_TEMP_CALCULADO_2
	) SRC
	WHERE SRC.RN = 1
	;
	
	v_num_rows := ::rowcount;
	CALL EXT.LIB_CONSTANTES:WRITE_LOG(v_permisos_log,proc_name,'Fin INSERT en GARANTIAS_RECIBO ' || v_num_rows , v_log_count, i_id_proceso, 'info');
	
	--TRANSACCIONES
	
	--Insert SALESTRANSACTION
	CALL EXT.LIB_CONSTANTES:WRITE_LOG(v_permisos_log,proc_name,'Inicio INSERT en SALESTRANSACTION ', v_log_count, i_id_proceso, 'info');
    
    
    INSERT INTO EXT.SALESTRANSACTION (
    	SELECT 
			v_tenantid						AS TENANTID
			,EXT.SEQSTAGESALESTRANSACTION.NEXTVAL						
											AS STAGESALESTRANSACTIONSEQ 
			,'TXSTA_' || SRC.FILE_NAME		AS BATCHNAME
			,SRC.FILE_NAME						AS FILE_IN_RECIBOS
			,SRC.PRODUCTO_CONTABLE || SUBSTR(SRC.CODIGO_POLIZA,8) || IFNULL(SRC.CODIGO_SUPLEMENTO_CALCULADO,0)			
											AS ORDERID
			,TO_NUMBER(SUBSTR(REPLACE(SRC.CARGO_COMPENSACION, '-', ''), 1, 6))			
											AS LINENUMBER
			,TO_NUMBER(SUBSTR(SRC.CODIGO_POLIZA,1,7))				
											AS SUBLINENUMBER
			,SRC.PERMANENCIA					AS EVENTTYPEID
			,NULL							AS SALESTRANSACTIONSEQ
			,NULL							AS SALESORDERSEQ
			,SRC.FECHA_COBRO					AS ACCOUNTINGDATE
			,SRC.PRODUCTO_CONTABLE				AS PRODUCTID
			,NULL							AS PRODUCTNAME
			,NULL							AS PRODUCTDESCRIPTION
			,SRC.INCRE_PRIMA_ANUAL				AS VALUE
			,CONST_TIPO_EURO				AS UNITTYPEFORVALUE
			,NULL							AS NUMBEROFUNITS
			,NULL							AS UNITVALUE
			,NULL							AS UNITTYPEFORUNITVALUE
			,SRC.CARGO_COMPENSACION				AS COMPENSATIONDATE
			,NULL							AS PAYMENTTERMS
			,NULL							AS PONUMBER
			,SUBSTR(SRC.CODIGO_POLIZA,1,2)		AS CHANNEL
			,NULL							AS ALTERNATEORDERNUMBER
			,NULL							AS DATASOURCE
			,CONST_TIPO_EURO				AS NATIVECURRENCY
			,SRC.IND_COMI_CALCULADA				AS NATIVECURRENCYAMOUNT
			,SRC.IND_POR_CALCULADO				AS DISCOUNTPERCENT
			,CONST_TIPO_PERCENTAGE			AS DISCOUNTTYPE
			,NULL							AS BILLTOCUSTID
			,NULL							AS BILLTOCONTACT
			,NULL							AS BILLTOCOMPANY
			,NULL							AS BILLTOAREACODE
			,NULL							AS BILLTOPHONE
			,NULL							AS BILLTOFAX
			,NULL							AS BILLTOADDRESS1
			,NULL							AS BILLTOADDRESS2
			,NULL							AS BILLTOADDRESS3
			,NULL							AS BILLTOCITY
			,NULL							AS BILLTOSTATE
			,NULL							AS BILLTOCOUNTRY
			,NULL							AS BILLTOPOSTALCODE
			,NULL							AS BILLTOINDUSTRY
			,NULL							AS BILLTOGEOGRAPHY
			,NULL							AS SHIPTOCUSTID
			,NULL							AS SHIPTOCONTACT
			,NULL							AS SHIPTOCOMPANY
			,NULL							AS SHIPTOAREACODE
			,NULL							AS SHIPTOPHONE
			,NULL							AS SHIPTOFAX
			,NULL							AS SHIPTOADDRESS1
			,NULL							AS SHIPTOADDRESS2
			,NULL							AS SHIPTOADDRESS3
			,NULL							AS SHIPTOCITY
			,NULL							AS SHIPTOSTATE
			,NULL							AS SHIPTOCOUNTRY
			,NULL							AS SHIPTOPOSTALCODE
			,NULL							AS SHIPTOINDUSTRY
			,NULL							AS SHIPTOGEOGRAPHY
			,NULL							AS OTHERTOCUSTID
			,NULL							AS OTHERTOCONTACT
			,NULL							AS OTHERTOCOMPANY
			,NULL							AS OTHERTOAREACODE
			,NULL							AS OTHERTOPHONE
			,NULL							AS OTHERTOFAX
			,NULL							AS OTHERTOADDRESS1
			,NULL							AS OTHERTOADDRESS2
			,NULL							AS OTHERTOADDRESS3
			,NULL							AS OTHERTOCITY
			,NULL							AS OTHERTOSTATE
			,NULL							AS OTHERTOCOUNTRY
			,NULL							AS OTHERTOPOSTALCODE
			,NULL							AS OTHERTOINDUSTRY
			,NULL							AS OTHERTOGEOGRAPHY
			,NULL							AS REASONID
			,NULL							AS COMMENTS
			,CURRENT_TIMESTAMP				AS STAGEPROCESSDATE
			,0								AS STAGEPROCESSFLAG
			,CONST_TIPO_ESP					AS BUSINESSUNITNAME
			,NULL							AS BUSINESSUNITMAP
			,SUBSTR(SRC.CODIGO_POLIZA,8)		AS GENERICATTRIBUTE1
			,NULL							AS GENERICATTRIBUTE2
			,NULL							AS GENERICATTRIBUTE3
			,NULL 							AS GENERICATTRIBUTE4
			,NULL							AS GENERICATTRIBUTE5
			,SRC.ESTADO_RECIBO					AS GENERICATTRIBUTE6
			,NULL							AS GENERICATTRIBUTE7
			,NULL							AS GENERICATTRIBUTE8
			,NULL							AS GENERICATTRIBUTE9
			,NULL 							AS GENERICATTRIBUTE10
			,NULL							AS GENERICATTRIBUTE11
			,NULL							AS GENERICATTRIBUTE12
			,NULL							AS GENERICATTRIBUTE13
			,NULL							AS GENERICATTRIBUTE14
			,NULL							AS GENERICATTRIBUTE15
			,NULL							AS GENERICATTRIBUTE16
			,NULL							AS GENERICATTRIBUTE17
			,NULL							AS GENERICATTRIBUTE18
			,NULL							AS GENERICATTRIBUTE19
			,NULL							AS GENERICATTRIBUTE20
			,NULL							AS GENERICATTRIBUTE21							
			,NULL							AS GENERICATTRIBUTE22
			,NULL			 				AS GENERICATTRIBUTE23
			,NULL							AS GENERICATTRIBUTE24
			,NULL							AS GENERICATTRIBUTE25
			,NULL							AS GENERICATTRIBUTE26
			,NULL							AS GENERICATTRIBUTE27
			,NULL							AS GENERICATTRIBUTE28
			,NULL							AS GENERICATTRIBUTE29
			,NULL							AS GENERICATTRIBUTE30
			,NULL							AS GENERICATTRIBUTE31
			,NULL							AS GENERICATTRIBUTE32
			,NULL							AS GENERICNUMBER1
			,NULL							AS UNITTYPEFORGENERICNUMBER1 
			,NULL							AS GENERICNUMBER2
			,NULL							AS UNITTYPEFORGENERICNUMBER2
			,NULL							AS GENERICNUMBER3
			,NULL							AS UNITTYPEFORGENERICNUMBER3
			,NULL							AS GENERICNUMBER4
			,NULL							AS UNITTYPEFORGENERICNUMBER4
			,NULL							AS GENERICNUMBER5
			,NULL							AS UNITTYPEFORGENERICNUMBER5
			,NULL							AS GENERICNUMBER6
			,NULL							AS UNITTYPEFORGENERICNUMBER6
			,NULL							AS GENERICDATE1
			,SRC.FECHA_EMISION_REC				AS GENERICDATE2 
			,NULL							AS GENERICDATE3
			,NULL							AS GENERICDATE4
			,NULL							AS GENERICDATE5
			,NULL							AS GENERICDATE6		
			,NULL			 				AS GENERICBOOLEAN1
			,NULL 							AS GENERICBOOLEAN2	
			,NULL							AS GENERICBOOLEAN3  
			,NULL							AS GENERICBOOLEAN4	
			,NULL							AS GENERICBOOLEAN5  
			,NULL							AS GENERICBOOLEAN6	
			,NULL							AS STAGEERRORCODE
			,NULL							AS COMPENSATIONDATE_OLD
			,NULL							AS PUSEQ_OLD
		FROM (
		    SELECT *, ROW_NUMBER() OVER (PARTITION BY CODIGO_POLIZA, CODIGO_RECIBO, PRODUCTO_CONTABLE, ESTADO_RECIBO, CODIGO_SUPLEMENTO_CALCULADO
		    	
		    ) AS RN
		    FROM :TBL_GESTIONES_TEMP_CALCULADO_2
		) SRC
		WHERE SRC.RN = 1
	    );

	
	v_num_rows := ::rowcount;
	CALL EXT.LIB_CONSTANTES:WRITE_LOG(v_permisos_log,proc_name,'Fin INSERT en SALESTRANSACTION ' || v_num_rows , v_log_count, i_id_proceso, 'info');
	
	
	--Insert TRANSACTIONASSIGN
	CALL EXT.LIB_CONSTANTES:WRITE_LOG(v_permisos_log,proc_name,'Inicio INSERT en TRANSACTIONASSIGN ', v_log_count, i_id_proceso, 'info');
	
	INSERT INTO EXT.TRANSACTIONASSIGN
		SELECT 
			v_tenantid						AS TENANTID
			,NULL							
											AS STAGESALESTRANSACTIONSEQ 
			,1 								AS SETNUMBER								
			,'TXSTA_' || SRC.FILE_NAME		AS BATCHNAME
			,SRC.FILE_NAME					AS FILE_IN_RECIBOS
			,SRC.PRODUCTO_CONTABLE || SUBSTR(SRC.CODIGO_POLIZA, 8) || IFNULL(SRC.CODIGO_SUPLEMENTO_CALCULADO,0)					
											AS ORDERID
			,TO_NUMBER(SUBSTR(REPLACE(SRC.CARGO_COMPENSACION,'-',''), 1, 6))					
											AS LINENUMBER
			,TO_NUMBER(SUBSTR(SRC.CODIGO_POLIZA, 1, 7))				
											AS SUBLINENUMBER
			,SRC.PERMANENCIA				    AS EVENTTYPEID
			,NULL							AS SALESTRANSACTIONSEQ
			,NULL							AS PAYEEID				
			,NULL							AS PAYEETYPE
			--usa el codigo_agente_commissions
			,IFNULL(SRC.CODIGO_UNICO,:CONST_NO_ENCONTRADO)				
											AS POSITIONNAME			
			,NULL							AS TITLENAME			
			,NULL							AS GENERICATTRIBUTE1	
			,NULL							AS GENERICATTRIBUTE2	
			,IFNULL(CASE WHEN IFNULL(SRC.v_existe_codigo_agente,0) > 0
		    	THEN SRC.CODIGO_UNICO_AGENTE
		    	ELSE SRC.v_codigo_ocaso
    		END, :CONST_NO_ENCONTRADO)		AS GENERICATTRIBUTE3	
			,NULL							AS GENERICATTRIBUTE4
			,NULL							AS GENERICATTRIBUTE5
			,NULL							AS GENERICATTRIBUTE6
			,NULL							AS GENERICATTRIBUTE7
			,NULL							AS GENERICATTRIBUTE8
			,NULL							AS GENERICATTRIBUTE9
			,NULL							AS GENERICATTRIBUTE10
			,NULL							AS GENERICATTRIBUTE11
			,NULL							AS GENERICATTRIBUTE12
			,NULL							AS GENERICATTRIBUTE13
			,NULL							AS GENERICATTRIBUTE14
			,NULL							AS GENERICATTRIBUTE15
			,NULL							AS GENERICATTRIBUTE16
			,NULL							AS GENERICNUMBER1
			,NULL							AS UNITTYPEFORGENERICNUMBER1
			,NULL							AS GENERICNUMBER2
			,NULL							AS UNITTYPEFORGENERICNUMBER2
			,NULL							AS GENERICNUMBER3
			,NULL							AS UNITTYPEFORGENERICNUMBER3
			,NULL							AS GENERICNUMBER4
			,NULL							AS UNITTYPEFORGENERICNUMBER4
			,NULL							AS	GENERICNUMBER5
			,NULL							AS UNITTYPEFORGENERICNUMBER5
			,NULL							AS GENERICNUMBER6
			,NULL 							AS UNITTYPEFORGENERICNUMBER6
			,NULL							AS GENERICDATE1
			,NULL							AS GENERICDATE2
			,NULL							AS GENERICDATE3
			,NULL							AS GENERICDATE4
			,NULL							AS GENERICDATE5
			,NULL							AS GENERICDATE6
			,NULL							AS GENERICBOOLEAN1
			,NULL							AS GENERICBOOLEAN2
			,NULL							AS GENERICBOOLEAN3
			,NULL							AS GENERICBOOLEAN4
			,NULL							AS GENERICBOOLEAN5
			,NULL							AS GENERICBOOLEAN6
		FROM (
		    SELECT *, ROW_NUMBER() OVER (PARTITION BY CODIGO_POLIZA, CODIGO_RECIBO, PRODUCTO_CONTABLE, ESTADO_RECIBO, CODIGO_SUPLEMENTO_CALCULADO
		    	
		    ) AS RN
		    FROM :TBL_GESTIONES_TEMP_CALCULADO_2
		) SRC
		WHERE SRC.RN = 1
		;

	v_num_rows := ::rowcount;
	CALL EXT.LIB_CONSTANTES:WRITE_LOG(v_permisos_log,proc_name,'Fin INSERT en TRANSACTIONASSIGN ' || v_num_rows , v_log_count, i_id_proceso, 'info');
	
	MERGE INTO EXT.TRANSACTIONASSIGN src
	USING (
		SELECT ST.ORDERID, ST.LINENUMBER, ST.SUBLINENUMBER, ST.EVENTTYPEID, ST.STAGESALESTRANSACTIONSEQ FROM EXT.SALESTRANSACTION ST
		WHERE ST.FILE_IN_RECIBOS = i_file_name
	) x
	ON src.ORDERID = x.ORDERID AND src.LINENUMBER = x.LINENUMBER AND src.SUBLINENUMBER = x.SUBLINENUMBER AND src.EVENTTYPEID = x.EVENTTYPEID AND src.FILE_IN_RECIBOS = i_file_name
	WHEN MATCHED THEN UPDATE 
		SET src.STAGESALESTRANSACTIONSEQ = x.STAGESALESTRANSACTIONSEQ
	;
	v_num_rows := ::rowcount;
			
	CALL EXT.LIB_GLOBAL:WRITE_LOG(v_permisos_log,proc_name,'Fin actualizar STAGESALESTRANSACTIONSEQ TRANSACTIONASSIGN. Filas: ' || v_num_rows, i_log_count, i_id_proceso, 'info');
				
	
	--ACTUALIZAR POSITIONNAME A MANAGERS PARA AGENTES TIPO 15
	WHILE (v_num_rows > 0) DO
	
		UPDATE EXT.TRANSACTIONASSIGN TA
		SET (TA.POSITIONNAME, TA.GENERICATTRIBUTE3, TA.GENERICATTRIBUTE2) = (
					SELECT IFNULL(MAX(POS.NAME), CONST_NO_ENCONTRADO), IFNULL(MAX(POS.GENERICATTRIBUTE3), CONST_NO_ENCONTRADO) , TA.GENERICATTRIBUTE3
					FROM TCMP.CS_POSITION POS
					WHERE POS.RULEELEMENTOWNERSEQ = (
						SELECT MAX(P.MANAGERSEQ) FROM :TBL_GEN_CODIGOS_AGENTE P
						WHERE P.CODIGO_UNICO = TA.POSITIONNAME
	                    AND P.EFFECTIVESTARTDATE <= CASE WHEN TA.EVENTTYPEID = '16' THEN LAST_DAY(:v_fecha_compensacion) 
	                    							ELSE LAST_DAY((SELECT MAX(R.FECHA_EMISION_REC)  FROM EXT.RECIBOS R WHERE SUBSTR(R.CODIGO_POLIZA,1,21) = SUBSTR(TA.ORDERID,1,21) AND R.FILE_NAME = :i_file_name)) END
	                    AND P.EFFECTIVEENDDATE > CASE WHEN TA.EVENTTYPEID = '16' THEN LAST_DAY(:v_fecha_compensacion) 
	                    							ELSE LAST_DAY((SELECT MAX(R.FECHA_EMISION_REC)  FROM EXT.RECIBOS R WHERE SUBSTR(R.CODIGO_POLIZA,1,21) = SUBSTR(TA.ORDERID,1,21) AND R.FILE_NAME = :i_file_name)) END
					)
	                AND POS.EFFECTIVESTARTDATE <= LAST_DAY(:v_fecha_compensacion)
	                AND POS.EFFECTIVEENDDATE > LAST_DAY(:v_fecha_compensacion)
	                AND POS.TENANTID = :v_tenantid
	                AND POS.REMOVEDATE = TO_DATE('22000101','YYYYMMDD')
	                -- No tenemos en cuenta las Position de manager que no tengan plan (TTL_SIN_PLAN).
	                AND POS.TITLESEQ <> 5629499534213290
		)
		WHERE (
				SELECT MAX(T.TIPO_AGENTE_PRIN) FROM :TBL_GEN_CODIGOS_AGENTE T WHERE T.CODIGO_UNICO = TA.POSITIONNAME 
				AND T.EFFECTIVESTARTDATE <= LAST_DAY(:v_fecha_compensacion) 
	            AND T.EFFECTIVEENDDATE > LAST_DAY(:v_fecha_compensacion)
			) = 15 
		AND FILE_IN_RECIBOS = :i_file_name;
		
		v_num_rows := ::rowcount;
		CALL EXT.LIB_CONSTANTES:WRITE_LOG(v_permisos_log,proc_name, v_vueltas || ' - POSITIONNAMEs actualizados a MANAGERS: ' || v_num_rows , v_log_count, i_id_proceso, 'info');
		v_vueltas := v_vueltas + 1;
	
	END WHILE;
	
	--BORRAMOS DATOS PREVIOS PARA SOBREESCRIBIRLOS		
	DELETE FROM TCMP.CS_STAGESALESTRANSACTION
	WHERE BATCHNAME = 'TXSTA_' || i_file_name;
	
	v_num_rows := ::rowcount;
	CALL EXT.LIB_CONSTANTES:WRITE_LOG(v_permisos_log,proc_name,'DELETE en TCMP.CS_STAGESALESTRANSACTION, filas : ' || v_num_rows , v_log_count, i_id_proceso, 'info');
	
	
	
	DELETE FROM TCMP.CS_STAGETRANSACTIONASSIGN
	WHERE BATCHNAME = 'TXSTA_' || i_file_name;
	v_num_rows := ::rowcount;
	CALL EXT.LIB_CONSTANTES:WRITE_LOG(v_permisos_log,proc_name,'DELETE en TCMP.CS_STAGETRANSACTIONASSIGN, filas : ' || v_num_rows , v_log_count, i_id_proceso, 'info');
	
	
	BEGIN
			DECLARE EXIT HANDLER FOR SQLEXCEPTION
				BEGIN
				
				ROLLBACK;
				
				CALL EXT.LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name , 'Error INSERT TCMP.CS_STAGESALESTRANSACTION - SQL_ERROR_MESSAGE: ' || IFNULL(::SQL_ERROR_MESSAGE,'')
											|| '. SQL_ERROR_CODE: ' || ::SQL_ERROR_CODE, v_log_count, i_id_proceso, 'error');
	
					v_num_rows := 0;
			
					ROLLBACK;
		        	-- SIGNAL SQL_ERROR 'Error al insertar';
					
					--Se obtiene la cuenta del fichero
					SELECT COUNT(*) INTO v_num_rows
					FROM EXT.STAGE_RECIBOS
					WHERE FILE_NAME = :i_file_name
						AND ESTADO = :v_const_stage_status_ok;
					
					--Se actualizan los campos de la in_batch_control para indicar el error
					UPDATE EXT.IN_BATCH_CONTROL
					SET REJECTED_ROWS = :v_num_rows,
						STATUS = :v_const_populate_status_error,
						END_DATE = CURRENT_TIMESTAMP
					WHERE FILE_NAME = :i_file_name
						AND STATUS = :v_const_stage_status_ok;
					
					--Se actualizan los registros de STAGE_RECIBOS con estado erróneo
					UPDATE EXT.STAGE_RECIBOS
						SET ESTADO = :v_const_populate_status_error,
						FECHA_MODIFICACION = CURRENT_TIMESTAMP
					WHERE FILE_NAME = :i_file_name
						AND ESTADO = :v_const_stage_status_ok;	
				
					COMMIT;
					RESIGNAL;
				END;
		
		--INSERTAR EN CS_SALESTRANSACTION Y CS_TRANSACTIONASSIGNMENT DE TCMP
		INSERT INTO TCMP.CS_STAGESALESTRANSACTION
		(
			SELECT 
				ST.TENANTID, ST.STAGESALESTRANSACTIONSEQ, ST.BATCHNAME, --ST.FILE_IN_RECIBOS,
				ST.ORDERID, ST.LINENUMBER, ST.SUBLINENUMBER, ST.EVENTTYPEID, 
				ST.SALESTRANSACTIONSEQ, ST.SALESORDERSEQ, ST.ACCOUNTINGDATE, ST.PRODUCTID, ST.PRODUCTNAME, ST.PRODUCTDESCRIPTION, ST.VALUE, ST.UNITTYPEFORVALUE, 
				ST.NUMBEROFUNITS, ST.UNITVALUE, ST.UNITTYPEFORUNITVALUE, ST.COMPENSATIONDATE, ST.PAYMENTTERMS, ST.PONUMBER, ST.CHANNEL, ST.ALTERNATEORDERNUMBER, 
				ST.DATASOURCE, ST.NATIVECURRENCY, ST.NATIVECURRENCYAMOUNT, ST.DISCOUNTPERCENT, ST.DISCOUNTTYPE, ST.BILLTOCUSTID, ST.BILLTOCONTACT, ST.BILLTOCOMPANY, 
				ST.BILLTOAREACODE, ST.BILLTOPHONE, ST.BILLTOFAX, ST.BILLTOADDRESS1, ST.BILLTOADDRESS2, ST.BILLTOADDRESS3, ST.BILLTOCITY, ST.BILLTOSTATE, 
				ST.BILLTOCOUNTRY, ST.BILLTOPOSTALCODE, ST.BILLTOINDUSTRY, ST.BILLTOGEOGRAPHY, ST.SHIPTOCUSTID, ST.SHIPTOCONTACT, ST.SHIPTOCOMPANY, ST.SHIPTOAREACODE, 
				ST.SHIPTOPHONE, ST.SHIPTOFAX, ST.SHIPTOADDRESS1, ST.SHIPTOADDRESS2, ST.SHIPTOADDRESS3, ST.SHIPTOCITY, ST.SHIPTOSTATE, ST.SHIPTOCOUNTRY, 
				ST.SHIPTOPOSTALCODE, ST.SHIPTOINDUSTRY, ST.SHIPTOGEOGRAPHY, ST.OTHERTOCUSTID, ST.OTHERTOCONTACT, ST.OTHERTOCOMPANY, ST.OTHERTOAREACODE, ST.OTHERTOPHONE, 
				ST.OTHERTOFAX, ST.OTHERTOADDRESS1, ST.OTHERTOADDRESS2, ST.OTHERTOADDRESS3, ST.OTHERTOCITY, ST.OTHERTOSTATE, ST.OTHERTOCOUNTRY, ST.OTHERTOPOSTALCODE, 
				ST.OTHERTOINDUSTRY, ST.OTHERTOGEOGRAPHY, ST.REASONID, ST.COMMENTS, ST.STAGEPROCESSDATE, ST.STAGEPROCESSFLAG, ST.BUSINESSUNITNAME, ST.BUSINESSUNITMAP, 
				ST.GENERICATTRIBUTE1, ST.GENERICATTRIBUTE2, ST.GENERICATTRIBUTE3, ST.GENERICATTRIBUTE4, ST.GENERICATTRIBUTE5, ST.GENERICATTRIBUTE6, 
				ST.GENERICATTRIBUTE7, ST.GENERICATTRIBUTE8, ST.GENERICATTRIBUTE9, ST.GENERICATTRIBUTE10, ST.GENERICATTRIBUTE11, ST.GENERICATTRIBUTE12, 
				ST.GENERICATTRIBUTE13, ST.GENERICATTRIBUTE14, ST.GENERICATTRIBUTE15, ST.GENERICATTRIBUTE16, ST.GENERICATTRIBUTE17, ST.GENERICATTRIBUTE18, 
				ST.GENERICATTRIBUTE19, ST.GENERICATTRIBUTE20, ST.GENERICATTRIBUTE21, ST.GENERICATTRIBUTE22, ST.GENERICATTRIBUTE23, ST.GENERICATTRIBUTE24, 
				ST.GENERICATTRIBUTE25, ST.GENERICATTRIBUTE26, ST.GENERICATTRIBUTE27, ST.GENERICATTRIBUTE28, ST.GENERICATTRIBUTE29, ST.GENERICATTRIBUTE30, 
				ST.GENERICATTRIBUTE31, ST.GENERICATTRIBUTE32, ST.GENERICNUMBER1, ST.UNITTYPEFORGENERICNUMBER1, ST.GENERICNUMBER2, ST.UNITTYPEFORGENERICNUMBER2, 
				ST.GENERICNUMBER3, ST.UNITTYPEFORGENERICNUMBER3, ST.GENERICNUMBER4, ST.UNITTYPEFORGENERICNUMBER4, ST.GENERICNUMBER5, ST.UNITTYPEFORGENERICNUMBER5, 
				ST.GENERICNUMBER6, ST.UNITTYPEFORGENERICNUMBER6, ST.GENERICDATE1, ST.GENERICDATE2, ST.GENERICDATE3, ST.GENERICDATE4, ST.GENERICDATE5, 
				ST.GENERICDATE6, ST.GENERICBOOLEAN1, ST.GENERICBOOLEAN2, ST.GENERICBOOLEAN3, ST.GENERICBOOLEAN4, ST.GENERICBOOLEAN5, ST.GENERICBOOLEAN6, ST.STAGEERRORCODE, 
				ST.COMPENSATIONDATE_OLD, ST.PUSEQ_OLD
			 FROM EXT.SALESTRANSACTION ST
			WHERE ST.BATCHNAME = 'TXSTA_' || :i_file_name
			AND (ST.ORDERID, ST.SUBLINENUMBER, ST.LINENUMBER, ST.EVENTTYPEID) IN (
				SELECT TA.ORDERID, TA.SUBLINENUMBER, TA.LINENUMBER, TA.EVENTTYPEID FROM EXT.TRANSACTIONASSIGN TA WHERE TA.FILE_IN_RECIBOS = :i_file_name AND TA.POSITIONNAME <> :CONST_NO_ENCONTRADO 
			)
			
		);
		
		v_num_rows := ::rowcount;
		CALL EXT.LIB_CONSTANTES:WRITE_LOG(v_permisos_log,proc_name,'Insert en TCMP.CS_STAGESALESTRANSACTION, filas : ' || v_num_rows , v_log_count, i_id_proceso, 'info');
	END;
	
	BEGIN
			DECLARE EXIT HANDLER FOR SQLEXCEPTION
				BEGIN
				
				ROLLBACK;
				
				CALL EXT.LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name , 'Error INSERT TCMP.CS_STAGETRANSACTIONASSIGN - SQL_ERROR_MESSAGE: ' || IFNULL(::SQL_ERROR_MESSAGE,'')
											|| '. SQL_ERROR_CODE: ' || ::SQL_ERROR_CODE, v_log_count, i_id_proceso, 'error');
	
					ROLLBACK;
		        	-- SIGNAL SQL_ERROR 'Error al insertar';
					
					--Se obtiene la cuenta del fichero
					SELECT COUNT(*) INTO v_num_rows
					FROM EXT.STAGE_RECIBOS
					WHERE FILE_NAME = :i_file_name
						AND ESTADO = :v_const_stage_status_ok;
					
					--Se actualizan los campos de la in_batch_control para indicar el error
					UPDATE EXT.IN_BATCH_CONTROL
					SET REJECTED_ROWS = :v_num_rows,
						STATUS = :v_const_populate_status_error,
						END_DATE = CURRENT_TIMESTAMP
					WHERE FILE_NAME = :i_file_name
						AND STATUS = :v_const_stage_status_ok;
					
					--Se actualizan los registros de STAGE_RECIBOS con estado erróneo
					UPDATE EXT.STAGE_RECIBOS
						SET ESTADO = :v_const_populate_status_error,
						FECHA_MODIFICACION = CURRENT_TIMESTAMP
					WHERE FILE_NAME = :i_file_name
						AND ESTADO = :v_const_stage_status_ok;	
					
					COMMIT;
					RESIGNAL;
				END;
	
		INSERT INTO TCMP.CS_STAGETRANSACTIONASSIGN
		(
			SELECT 
				TA.TENANTID, TA.STAGESALESTRANSACTIONSEQ, TA.SETNUMBER, TA.BATCHNAME, --TA.FILE_IN_RECIBOS, 
				TA.ORDERID, TA.LINENUMBER, TA.SUBLINENUMBER, TA.EVENTTYPEID, TA.SALESTRANSACTIONSEQ, TA.PAYEEID, TA.PAYEETYPE,
				TA.POSITIONNAME, TA.TITLENAME, TA.GENERICATTRIBUTE1, TA.GENERICATTRIBUTE2, TA.GENERICATTRIBUTE3, TA.GENERICATTRIBUTE4,
				TA.GENERICATTRIBUTE5, TA.GENERICATTRIBUTE6, TA.GENERICATTRIBUTE7, TA.GENERICATTRIBUTE8, TA.GENERICATTRIBUTE9, TA.GENERICATTRIBUTE10,
				TA.GENERICATTRIBUTE11, TA.GENERICATTRIBUTE12, TA.GENERICATTRIBUTE13, TA.GENERICATTRIBUTE14, TA.GENERICATTRIBUTE15, TA.GENERICATTRIBUTE16,
				TA.GENERICNUMBER1, TA.UNITTYPEFORGENERICNUMBER1, TA.GENERICNUMBER2, TA.UNITTYPEFORGENERICNUMBER2, TA.GENERICNUMBER3, TA.UNITTYPEFORGENERICNUMBER3,
				TA.GENERICNUMBER4, TA.UNITTYPEFORGENERICNUMBER4, TA.GENERICNUMBER5, TA.UNITTYPEFORGENERICNUMBER5, TA.GENERICNUMBER6, TA.UNITTYPEFORGENERICNUMBER6,
				TA.GENERICDATE1, TA.GENERICDATE2, TA.GENERICDATE3, TA.GENERICDATE4, TA.GENERICDATE5, TA.GENERICDATE6,
				TA.GENERICBOOLEAN1, TA.GENERICBOOLEAN2, TA.GENERICBOOLEAN3, TA.GENERICBOOLEAN4, TA.GENERICBOOLEAN5, TA.GENERICBOOLEAN6
			 FROM EXT.TRANSACTIONASSIGN TA
			WHERE TA.BATCHNAME = 'TXSTA_' || :i_file_name
			AND TA.POSITIONNAME <> :CONST_NO_ENCONTRADO 
		);
		
		v_num_rows := ::rowcount;
		CALL EXT.LIB_CONSTANTES:WRITE_LOG(v_permisos_log,proc_name,'Insert en TCMP.CS_STAGETRANSACTIONASSIGN, filas : ' || v_num_rows , v_log_count, i_id_proceso, 'info');
		
	END;
	
	
	CALL EXT.LIB_CONSTANTES:WRITE_LOG(v_permisos_log,proc_name,'Actualiza estado IN_BATCH_CONTROL: 9', v_log_count, i_id_proceso, 'info');
	--Si todo OK, update status en inbatch
	UPDATE EXT.IN_BATCH_CONTROL
		SET STATUS = :v_const_carga_status_ok, --9
			END_DATE = CURRENT_TIMESTAMP
		WHERE FILE_NAME = :i_file_name
		AND ID_PROCESO = :i_id_proceso;
	
	--Se actualizan los registros de STAGE_RECIBOS con estado correcto
	UPDATE EXT.STAGE_RECIBOS
		SET ESTADO = :v_const_populate_status_ok,
			FECHA_MODIFICACION = CURRENT_TIMESTAMP
		WHERE FILE_NAME = :i_file_name
		AND ESTADO = :v_const_stage_status_ok;
	
	COMMIT;


END
