CREATE PROCEDURE EXT.SP_VALIDACION_RRTT (v_FILE_NAME VARCHAR(250), v_FILE_IN_RECIBOS VARCHAR(250))
LANGUAGE SQLSCRIPT  
SQL SECURITY INVOKER 
DEFAULT SCHEMA EXT AS 
BEGIN
	
	DECLARE v_ESPACIO_3 VARCHAR(10) := '   ';
	DECLARE v_ESPACIO_6 VARCHAR(10) := '      ';
	DECLARE v_proc_name VARCHAR2(50) := ::CURRENT_OBJECT_SCHEMA ||'.'|| ::CURRENT_OBJECT_NAME;
	DECLARE v_log_count INTEGER := 0;
	DECLARE v_permisos_log VARCHAR(50) := EXT.LIB_GLOBAL:GET_PERMISOS_LOG();
	

	--TABLA TEMPORAL
	-- DECLARE TEMP_LOG TABLE (
 --       DESCRIP VARCHAR(250),
 --       CANT_REGISTROS BIGINT
        
 --   );
    
    -----------------------------------------------------------------------------------------
    -- CREAR TABLA TEMPORAL
    -----------------------------------------------------------------------------------------
    
    --CONTROLADOR DE EXCEPCIONES
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;

        CALL EXT.LIB_GLOBAL:WRITE_LOG (v_permisos_log, v_proc_name , 'Error en procedimiento principal ' || v_proc_name || ' - SQL_ERROR_MESSAGE: ' || IFNULL(::SQL_ERROR_MESSAGE,'')
    																											|| '. SQL_ERROR_CODE: ' || ::SQL_ERROR_CODE, v_log_count, 0, 'error');
	RESIGNAL;
    END;

    IF (SELECT TABLE_NAME FROM SYS.TABLES where SCHEMA_NAME= ::CURRENT_OBJECT_SCHEMA and TABLE_NAME = 'VALIDACIONES_TEMP_RRTT') IS NULL THEN
	    
        CREATE COLUMN TABLE EXT.VALIDACIONES_TEMP_RRTT(
            DESCRIP VARCHAR(250),
        	CANT_REGISTROS BIGINT
        )
        UNLOAD PRIORITY 5 AUTO MERGE;

        -- CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, v_proc_name, 'CREADA TABLA EXT.VALIDACIONES_TEMP_RRTT', v_log_count, v_idproceso, 'info');
        
    END IF;

    TRUNCATE TABLE EXT.VALIDACIONES_TEMP_RRTT;
    
    INSERT INTO EXT.VALIDACIONES_TEMP_RRTT (DESCRIP)
    VALUES ('VALIDACIÓN RRTT');
    
    INSERT INTO EXT.VALIDACIONES_TEMP_RRTT (DESCRIP)
    VALUES (v_ESPACIO_3||'FICHERO DE ENTRADA ASEGURADOS: ' || :v_FILE_NAME);
    
    INSERT INTO EXT.VALIDACIONES_TEMP_RRTT (DESCRIP)
    VALUES (v_ESPACIO_3||'FICHERO DE ENTRADA RECIBOS: ' || :v_FILE_IN_RECIBOS);
    
    --VALIDACIÓN DE CANTIDAD DE REGISTROS
    INSERT INTO EXT.VALIDACIONES_TEMP_RRTT (DESCRIP)
    VALUES ('######### VALIDACIÓN DE CANTIDAD DE REGISTROS #########');
    
    -- Validación de cantidad de registros STAGE_RECIBOS
    INSERT INTO EXT.VALIDACIONES_TEMP_RRTT (DESCRIP, CANT_REGISTROS)
    VALUES (v_ESPACIO_6||'Validación de cantidad de registros STAGE_RECIBOS: ', (SELECT COUNT(*) FROM EXT.STAGE_RECIBOS WHERE FILE_NAME = :v_FILE_NAME));
    
    -- Validación de cantidad de registros POLIZAS
    INSERT INTO EXT.VALIDACIONES_TEMP_RRTT (DESCRIP,CANT_REGISTROS)
    VALUES (v_ESPACIO_6||'Validación de cantidad de registros POLIZAS: ' ,(SELECT COUNT(*) FROM EXT.POLIZAS  WHERE FILE_NAME = :v_FILE_NAME));
    
    -- Validación de cantidad de registros RECIBOS 
    INSERT INTO EXT.VALIDACIONES_TEMP_RRTT (DESCRIP,CANT_REGISTROS)
    VALUES (v_ESPACIO_6||'Validación de cantidad de registros RECIBOS: ' ,(SELECT COUNT(*) FROM EXT.RECIBOS   WHERE FILE_NAME = :v_FILE_NAME));
    
    -- Validación de cantidad de registros GARANTIAS_RECIBO 
    INSERT INTO EXT.VALIDACIONES_TEMP_RRTT (DESCRIP,CANT_REGISTROS)
    VALUES (v_ESPACIO_6||'Validación de cantidad de registros GARANTIAS_RECIBO: ' ,(SELECT COUNT(*) FROM EXT.GARANTIAS_RECIBO   WHERE FILE_NAME = :v_FILE_NAME));
    
    -- Validación de cantidad de registros ASEGURADOS 
    INSERT INTO EXT.VALIDACIONES_TEMP_RRTT (DESCRIP,CANT_REGISTROS)
    VALUES (v_ESPACIO_6||'Validación de cantidad de registros ASEGURADOS: ' ,(SELECT COUNT(*) FROM EXT.ASEGURADOS WHERE FILE_NAME = :v_FILE_NAME));
    
    -- Validación de cantidad de registros GARANTIAS_ASEGURADOS 
    INSERT INTO EXT.VALIDACIONES_TEMP_RRTT (DESCRIP,CANT_REGISTROS)
    VALUES (v_ESPACIO_6||'Validación de cantidad de registros GARANTIAS_ASEGURADOS: ' ,(SELECT COUNT(*) FROM EXT.GARANTIAS_ASEGURADO WHERE FILE_NAME = :v_FILE_NAME));
    
    -- Validación de cantidad de registros TRANSACCIONES 
    INSERT INTO EXT.VALIDACIONES_TEMP_RRTT (DESCRIP,CANT_REGISTROS)
    VALUES (v_ESPACIO_6||'Validación de cantidad de registros TRANSACCIONES - SALESTRANSACTION : ' ,(SELECT COUNT(*) FROM EXT.SALESTRANSACTION WHERE FILE_IN_RECIBOS = :v_FILE_IN_RECIBOS));
    
    INSERT INTO EXT.VALIDACIONES_TEMP_RRTT (DESCRIP,CANT_REGISTROS)
    SELECT v_ESPACIO_6||'Validacion de cantidad de registros EVENTTYPEID : ' || EVENTTYPEID , COUNT(*) 
    FROM EXT.SALESTRANSACTION 
    WHERE FILE_IN_RECIBOS = :v_FILE_IN_RECIBOS
    GROUP BY EVENTTYPEID
	ORDER BY EVENTTYPEID;
    
    INSERT INTO EXT.VALIDACIONES_TEMP_RRTT (DESCRIP,CANT_REGISTROS)
    VALUES (v_ESPACIO_6||'Validación de cantidad de registros TRANSACCIONES - TRANSACTIONASSIGN : ' ,(SELECT COUNT(*) FROM EXT.TRANSACTIONASSIGN WHERE FILE_IN_RECIBOS = :v_FILE_IN_RECIBOS));
    
    INSERT INTO EXT.VALIDACIONES_TEMP_RRTT (DESCRIP,CANT_REGISTROS)
    SELECT v_ESPACIO_6||'Validacion de cantidad de registros EVENTTYPEID : ' || EVENTTYPEID , COUNT(*) 
    FROM EXT.TRANSACTIONASSIGN 
    WHERE FILE_IN_RECIBOS = :v_FILE_IN_RECIBOS
    GROUP BY EVENTTYPEID
	ORDER BY EVENTTYPEID;
	
	--COMPROBACIÓN TRANSACCIONES
	IF( (SELECT COUNT(*) FROM EXT.SALESTRANSACTION WHERE FILE_IN_RECIBOS = :v_FILE_IN_RECIBOS) != (SELECT COUNT(*) FROM EXT.TRANSACTIONASSIGN WHERE FILE_IN_RECIBOS = :v_FILE_IN_RECIBOS)) THEN
		INSERT INTO EXT.VALIDACIONES_TEMP_RRTT (DESCRIP,CANT_REGISTROS)
    	VALUES (v_ESPACIO_3||v_ESPACIO_6||'¡¡¡ERROR!!! cantidad de registros en TRANSACCIONES no coincide SALESTRANSACTION - TRANSACTIONASSIGN : ' ,
    		(SELECT COUNT(*) FROM EXT.SALESTRANSACTION WHERE FILE_IN_RECIBOS = :v_FILE_IN_RECIBOS) - (SELECT COUNT(*) FROM EXT.TRANSACTIONASSIGN WHERE FILE_IN_RECIBOS = :v_FILE_IN_RECIBOS));
	END IF;
    

	-- -- EXCLUIDO COMISIONES 
 --   INSERT INTO EXT.VALIDACIONES_TEMP_RRTT (DESCRIP,CANT_REGISTROS)
 --   SELECT v_ESPACIO_6||'Validacion de cantidad de registros EXCLUIDO COMISIONES : ' || COALESCE(EXCLUIDO_COMISIONES,'NULL') , COUNT(*) 
 --   FROM  EXT.RECIBOS
	-- WHERE FILE_NAME = :v_FILE_NAME
	-- GROUP BY EXCLUIDO_COMISIONES;
	
	-- --DISMINUCIÓN PRIMA
	-- --NULL se considera como 0
	-- INSERT INTO EXT.VALIDACIONES_TEMP_RRTT (DESCRIP,CANT_REGISTROS)
	-- SELECT v_ESPACIO_6||'Validacion de cantidad de registros DISMINUCIÓN PRIMA : ' || COALESCE(DISMINUCION_PRIMA,0) , COUNT(*) 
 --   FROM  EXT.RECIBOS
	-- WHERE FILE_NAME = :v_FILE_NAME
	-- GROUP BY COALESCE(DISMINUCION_PRIMA,0);
	
	
	--VALIDACIÓN DE CANTIDAD DE REGISTROS
    INSERT INTO EXT.VALIDACIONES_TEMP_RRTT (DESCRIP)
    VALUES ('######### VALIDACIÓN POR TIPO DE CAMPO #########');
    
    -- Validacion de cantidad de registros ES_PERMANENCIA_20 
    INSERT INTO EXT.VALIDACIONES_TEMP_RRTT (DESCRIP,CANT_REGISTROS)
    SELECT v_ESPACIO_6||'Validacion de cantidad de registros ES_PERMANENCIA_20 : ' || ES_PERMANENCIA_20 , COUNT(*) 
    FROM  EXT.RECIBOS
	WHERE FILE_NAME = :v_FILE_NAME
	GROUP BY ES_PERMANENCIA_20
	ORDER BY 
		CASE WHEN ES_PERMANENCIA_20 = 'N' THEN 1
			WHEN ES_PERMANENCIA_20 = 'D' THEN 2
			WHEN ES_PERMANENCIA_20 = 'S' THEN 3
		END
	;
    
	--MARCA CUENTA
	--NULL se considera como N
	INSERT INTO EXT.VALIDACIONES_TEMP_RRTT (DESCRIP,CANT_REGISTROS)
	SELECT v_ESPACIO_6||'Validacion de cantidad de registros MARCA CUENTA : ' || COALESCE(MARCA_CUENTA,'N') , COUNT(*) 
    FROM  EXT.RECIBOS
	WHERE FILE_NAME = :v_FILE_NAME
	GROUP BY COALESCE(MARCA_CUENTA,'N');
	
	
	--PORC_COMISION_CARTERA
	INSERT INTO EXT.VALIDACIONES_TEMP_RRTT (DESCRIP,CANT_REGISTROS)
	SELECT v_ESPACIO_6||'PORC_COMISION_CARTERA de POLIZAS: ' ,SUM(COALESCE(PORC_COMISION_CARTERA,0)) 
    FROM  EXT.POLIZAS
	WHERE FILE_NAME = :v_FILE_NAME;
	
	
	--IMP_COMISION_CARTERA
	INSERT INTO EXT.VALIDACIONES_TEMP_RRTT (DESCRIP,CANT_REGISTROS)
	SELECT v_ESPACIO_6||'IMP_COMISION_CARTERA de POLIZAS: ' ,SUM(COALESCE(IMP_COMISION_CARTERA,0)) 
    FROM  EXT.POLIZAS
	WHERE FILE_NAME = :v_FILE_NAME;
	
	--MOTIVO_ALTA
	INSERT INTO EXT.VALIDACIONES_TEMP_RRTT (DESCRIP,CANT_REGISTROS)
	SELECT v_ESPACIO_6||'MOTIVO_ALTA de POLIZAS: ' || MOTIVO_ALTA,COUNT(*) 
    FROM  EXT.POLIZAS
	WHERE FILE_NAME = :v_FILE_NAME
	GROUP BY MOTIVO_ALTA;
	
	--MOTIVO_BAJA
	INSERT INTO EXT.VALIDACIONES_TEMP_RRTT (DESCRIP,CANT_REGISTROS)
	SELECT v_ESPACIO_6||'MOTIVO_BAJA de POLIZAS: ' || COALESCE(MOTIVO_BAJA,'NULL'),COUNT(*) 
    FROM  EXT.POLIZAS
	WHERE FILE_NAME = :v_FILE_NAME
	GROUP BY MOTIVO_BAJA;
	
	--PRIMA_NETA_ANUALIZADA
	INSERT INTO EXT.VALIDACIONES_TEMP_RRTT (DESCRIP,CANT_REGISTROS)
	SELECT v_ESPACIO_6||'PRIMA_NETA_ANUALIZADA de GARANTIAS_RECIBO: ' ,SUM(COALESCE(PRIMA_NETA_ANUALIZADA,0)) 
    FROM  EXT.GARANTIAS_RECIBO
	WHERE FILE_NAME = :v_FILE_NAME;
	
	--PORC_COMISION_NP
	INSERT INTO EXT.VALIDACIONES_TEMP_RRTT (DESCRIP,CANT_REGISTROS)
	SELECT v_ESPACIO_6||'PORC_COMISION_NP de GARANTIAS_RECIBO: ' ,SUM(COALESCE(PORC_COMISION_NP,0)) 
    FROM  EXT.GARANTIAS_RECIBO
	WHERE FILE_NAME = :v_FILE_NAME;
	
	--PORC_COMISION_CONSERVACION
	INSERT INTO EXT.VALIDACIONES_TEMP_RRTT (DESCRIP,CANT_REGISTROS)
	SELECT v_ESPACIO_6||'PORC_COMISION_CONSERVACION de GARANTIAS_RECIBO: ' ,SUM(COALESCE(PORC_COMISION_CONSERVACION,0)) 
    FROM  EXT.GARANTIAS_RECIBO
	WHERE FILE_NAME = :v_FILE_NAME;
	
	--PRIMA_COMISIONABLE GARANTIAS_RECIBO
	INSERT INTO EXT.VALIDACIONES_TEMP_RRTT (DESCRIP,CANT_REGISTROS)
	SELECT v_ESPACIO_6||'PRIMA_COMISIONABLE de GARANTIAS_RECIBO: ' ,SUM(COALESCE(PRIMA_COMISIONABLE,0)) 
    FROM  EXT.GARANTIAS_RECIBO
	WHERE FILE_NAME = :v_FILE_NAME;
	
	--CONTO_COMO_NUEVO
	INSERT INTO EXT.VALIDACIONES_TEMP_RRTT (DESCRIP,CANT_REGISTROS)
	SELECT v_ESPACIO_6||'CONTO_COMO_NUEVO de ASEGURADOS: ' || CONTO_COMO_NUEVO,COUNT(*)
    FROM  EXT.ASEGURADOS
	WHERE FILE_NAME = :v_FILE_NAME
	GROUP BY CONTO_COMO_NUEVO;
	
	--PRIMA_COMISIONABLE GARANTIAS_ASEGURADO
	INSERT INTO EXT.VALIDACIONES_TEMP_RRTT (DESCRIP,CANT_REGISTROS)
	SELECT v_ESPACIO_6||'PRIMA_COMISIONABLE de GARANTIAS_ASEGURADO: ' ,SUM(COALESCE(PRIMA_COMISIONABLE,0)) 
    FROM  EXT.GARANTIAS_ASEGURADO
	WHERE FILE_NAME = :v_FILE_NAME;
	
	--PORCENTAJE_PARTICIPACION GARANTIAS_ASEGURADO
	INSERT INTO EXT.VALIDACIONES_TEMP_RRTT (DESCRIP,CANT_REGISTROS)
	SELECT v_ESPACIO_6||'PORCENTAJE_PARTICIPACION de GARANTIAS_ASEGURADO: ' ,SUM(COALESCE(PORCENTAJE_PARTICIPACION,0)) 
    FROM  EXT.GARANTIAS_ASEGURADO
	WHERE FILE_NAME = :v_FILE_NAME;
	
	--PC_PERIODO GARANTIAS_ASEGURADO
	INSERT INTO EXT.VALIDACIONES_TEMP_RRTT (DESCRIP,CANT_REGISTROS)
	SELECT v_ESPACIO_6||'PC_PERIODO de GARANTIAS_ASEGURADO: ' ,SUM(COALESCE(PC_PERIODO,0)) 
    FROM  EXT.GARANTIAS_ASEGURADO
	WHERE FILE_NAME = :v_FILE_NAME;
	
	--NUM_PERIODOS GARANTIAS_ASEGURADO
	INSERT INTO EXT.VALIDACIONES_TEMP_RRTT (DESCRIP,CANT_REGISTROS)
	SELECT v_ESPACIO_6||'NUM_PERIODOS de GARANTIAS_ASEGURADO: ' ,SUM(COALESCE(NUM_PERIODOS,0)) 
    FROM  EXT.GARANTIAS_ASEGURADO
	WHERE FILE_NAME = :v_FILE_NAME;
	
	
	
	
	
	
	
	
	
	
	--ASEGURADOS_NETOS
	INSERT INTO EXT.VALIDACIONES_TEMP_RRTT (DESCRIP,CANT_REGISTROS)
	SELECT v_ESPACIO_6||'Validacion de cantidad de registros ASEGURADOS_NETOS: ' || '                       ¡¡¡PENDIENTE!!!',NULL 
	FROM DUMMY;
	
	--AUMENTO_ASEGURADOS
	INSERT INTO EXT.VALIDACIONES_TEMP_RRTT (DESCRIP,CANT_REGISTROS)
	SELECT v_ESPACIO_6||'Validacion de cantidad de registros AUMENTO_ASEGURADOS: ' || '                       ¡¡¡PENDIENTE!!!',NULL 
	FROM DUMMY;
	
	
	
	--AGENTE CARTERA
	INSERT INTO EXT.VALIDACIONES_TEMP_RRTT (DESCRIP,CANT_REGISTROS)
	SELECT v_ESPACIO_6||'Validacion de cantidad de registros AGENTE_CARTERA: ' || '                       ¡¡¡PENDIENTE!!!',NULL 
	FROM DUMMY;
	
	
	
	
	--FECHA_FIN_COMISION_CARTERA
	INSERT INTO EXT.VALIDACIONES_TEMP_RRTT (DESCRIP,CANT_REGISTROS)
	SELECT v_ESPACIO_6||'Validacion de cantidad de registros FECHA_FIN_COMISION_CARTERA: ' || '                       ¡¡¡PENDIENTE!!!',NULL 
	FROM DUMMY;
	
	
	
	
	
	
	
	-- --INDICADOR_COMISION_CALCULADA
	-- INSERT INTO EXT.VALIDACIONES_TEMP_RRTT (DESCRIP,CANT_REGISTROS)
	-- SELECT v_ESPACIO_6||'INDICADOR_COMISION_CALCULADA de GARANTIAS_RECIBO: ' || INDICADOR_COMISION_CALCULADA, COUNT(*) 
 --   FROM  EXT.GARANTIAS_RECIBO
	-- WHERE FILE_NAME = :v_FILE_NAME
	-- GROUP BY INDICADOR_COMISION_CALCULADA;
	
	-- --INDICADOR_PORCENTAJE_CALCULA
	-- INSERT INTO EXT.VALIDACIONES_TEMP_RRTT (DESCRIP,CANT_REGISTROS)
	-- SELECT v_ESPACIO_6||'INDICADOR_PORCENTAJE_CALCULA de GARANTIAS_RECIBO: ' || INDICADOR_PORCENTAJE_CALCULA, COUNT(*) 
 --   FROM  EXT.GARANTIAS_RECIBO
	-- WHERE FILE_NAME = :v_FILE_NAME
	-- GROUP BY INDICADOR_PORCENTAJE_CALCULA;
	
	-- --PERIODO_EXTORNABLE
	-- INSERT INTO EXT.VALIDACIONES_TEMP_RRTT (DESCRIP,CANT_REGISTROS)
	-- SELECT v_ESPACIO_6||'PERIODO_EXTORNABLE de GARANTIAS_RECIBO:            ¡¡¡REVISAR!!!' || PERIODO_EXTORNABLE, COUNT(*) 
 --   FROM  EXT.GARANTIAS_RECIBO
	-- WHERE FILE_NAME = :v_FILE_NAME
	-- GROUP BY PERIODO_EXTORNABLE;
	
	-- --MESES_COBRADOS
	-- INSERT INTO EXT.VALIDACIONES_TEMP_RRTT (DESCRIP,CANT_REGISTROS)
	-- SELECT v_ESPACIO_6||'Validacion de cantidad de registros MESES_COBRADOS: ' || '                       ¡¡¡PENDIENTE!!!',NULL 
	-- FROM DUMMY;
	
	-- --INCREMENTO_PRIMA_ANUAL
	-- INSERT INTO EXT.VALIDACIONES_TEMP_RRTT (DESCRIP,CANT_REGISTROS)
	-- SELECT v_ESPACIO_6||'INCREMENTO_PRIMA_ANUAL de GARANTIAS_RECIBO: ' ,SUM(COALESCE(INCREMENTO_PRIMA_ANUAL,0)) 
 --   FROM  EXT.GARANTIAS_RECIBO
	-- WHERE FILE_NAME = :v_FILE_NAME;
	
	
	
	
    
    --VER RESULTADOS
    -- SELECT DESCRIP
    -- 	,CASE
    -- 		WHEN CANT_REGISTROS IS NULL
    -- 			THEN TO_VARCHAR('') 
    -- 			ELSE TO_VARCHAR(CANT_REGISTROS) 
    -- 	END CANT_REGISTROS 
    -- FROM EXT.VALIDACIONES_TEMP_RRTT;
    
END;
